// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package service_test

import (
	"context"
	"github.com/ethereum/go-ethereum/common"
	keyspb "github.com/raylsnetwork/rayls-sovereign-relayer/cts/gen/proto/keys"
	"github.com/raylsnetwork/rayls-sovereign-relayer/dvp"
	"github.com/raylsnetwork/rayls-sovereign-relayer/enygma"
	"github.com/raylsnetwork/rayls-sovereign-relayer/types"
	"go.opentelemetry.io/otel/trace"
	"google.golang.org/grpc"
	"math/big"
	"sync"
)

// executorTracerMock is a mock implementation of service.executorTracer.
//
//	func TestSomethingThatUsesexecutorTracer(t *testing.T) {
//
//		// make and configure a mocked service.executorTracer
//		mockedexecutorTracer := &executorTracerMock{
//			StartFunc: func(ctx context.Context, spanName string, opts ...trace.SpanStartOption) (context.Context, trace.Span) {
//				panic("mock out the Start method")
//			},
//		}
//
//		// use mockedexecutorTracer in code that requires service.executorTracer
//		// and then make assertions.
//
//	}
type executorTracerMock struct {
	// StartFunc mocks the Start method.
	StartFunc func(ctx context.Context, spanName string, opts ...trace.SpanStartOption) (context.Context, trace.Span)

	// calls tracks calls to the methods.
	calls struct {
		// Start holds details about calls to the Start method.
		Start []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// SpanName is the spanName argument value.
			SpanName string
			// Opts is the opts argument value.
			Opts []trace.SpanStartOption
		}
	}
	lockStart sync.RWMutex
}

// Start calls StartFunc.
func (mock *executorTracerMock) Start(ctx context.Context, spanName string, opts ...trace.SpanStartOption) (context.Context, trace.Span) {
	if mock.StartFunc == nil {
		panic("executorTracerMock.StartFunc: method is nil but executorTracer.Start was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		SpanName string
		Opts     []trace.SpanStartOption
	}{
		Ctx:      ctx,
		SpanName: spanName,
		Opts:     opts,
	}
	mock.lockStart.Lock()
	mock.calls.Start = append(mock.calls.Start, callInfo)
	mock.lockStart.Unlock()
	return mock.StartFunc(ctx, spanName, opts...)
}

// StartCalls gets all the calls that were made to Start.
// Check the length with:
//
//	len(mockedexecutorTracer.StartCalls())
func (mock *executorTracerMock) StartCalls() []struct {
	Ctx      context.Context
	SpanName string
	Opts     []trace.SpanStartOption
} {
	var calls []struct {
		Ctx      context.Context
		SpanName string
		Opts     []trace.SpanStartOption
	}
	mock.lockStart.RLock()
	calls = mock.calls.Start
	mock.lockStart.RUnlock()
	return calls
}

// executorEnygmaBatcherMock is a mock implementation of service.executorEnygmaBatcher.
//
//	func TestSomethingThatUsesexecutorEnygmaBatcher(t *testing.T) {
//
//		// make and configure a mocked service.executorEnygmaBatcher
//		mockedexecutorEnygmaBatcher := &executorEnygmaBatcherMock{
//			CreateBatchesWithAnonimityFunc: func(ctx context.Context, resourceId string, blockNumber *big.Int, txsByChainID map[string][]*types.EnygmaTransferBatchTx) ([]*types.EnygmaTransferBatch, error) {
//				panic("mock out the CreateBatchesWithAnonimity method")
//			},
//		}
//
//		// use mockedexecutorEnygmaBatcher in code that requires service.executorEnygmaBatcher
//		// and then make assertions.
//
//	}
type executorEnygmaBatcherMock struct {
	// CreateBatchesWithAnonimityFunc mocks the CreateBatchesWithAnonimity method.
	CreateBatchesWithAnonimityFunc func(ctx context.Context, resourceId string, blockNumber *big.Int, txsByChainID map[string][]*types.EnygmaTransferBatchTx) ([]*types.EnygmaTransferBatch, error)

	// calls tracks calls to the methods.
	calls struct {
		// CreateBatchesWithAnonimity holds details about calls to the CreateBatchesWithAnonimity method.
		CreateBatchesWithAnonimity []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ResourceId is the resourceId argument value.
			ResourceId string
			// BlockNumber is the blockNumber argument value.
			BlockNumber *big.Int
			// TxsByChainID is the txsByChainID argument value.
			TxsByChainID map[string][]*types.EnygmaTransferBatchTx
		}
	}
	lockCreateBatchesWithAnonimity sync.RWMutex
}

// CreateBatchesWithAnonimity calls CreateBatchesWithAnonimityFunc.
func (mock *executorEnygmaBatcherMock) CreateBatchesWithAnonimity(ctx context.Context, resourceId string, blockNumber *big.Int, txsByChainID map[string][]*types.EnygmaTransferBatchTx) ([]*types.EnygmaTransferBatch, error) {
	if mock.CreateBatchesWithAnonimityFunc == nil {
		panic("executorEnygmaBatcherMock.CreateBatchesWithAnonimityFunc: method is nil but executorEnygmaBatcher.CreateBatchesWithAnonimity was just called")
	}
	callInfo := struct {
		Ctx          context.Context
		ResourceId   string
		BlockNumber  *big.Int
		TxsByChainID map[string][]*types.EnygmaTransferBatchTx
	}{
		Ctx:          ctx,
		ResourceId:   resourceId,
		BlockNumber:  blockNumber,
		TxsByChainID: txsByChainID,
	}
	mock.lockCreateBatchesWithAnonimity.Lock()
	mock.calls.CreateBatchesWithAnonimity = append(mock.calls.CreateBatchesWithAnonimity, callInfo)
	mock.lockCreateBatchesWithAnonimity.Unlock()
	return mock.CreateBatchesWithAnonimityFunc(ctx, resourceId, blockNumber, txsByChainID)
}

// CreateBatchesWithAnonimityCalls gets all the calls that were made to CreateBatchesWithAnonimity.
// Check the length with:
//
//	len(mockedexecutorEnygmaBatcher.CreateBatchesWithAnonimityCalls())
func (mock *executorEnygmaBatcherMock) CreateBatchesWithAnonimityCalls() []struct {
	Ctx          context.Context
	ResourceId   string
	BlockNumber  *big.Int
	TxsByChainID map[string][]*types.EnygmaTransferBatchTx
} {
	var calls []struct {
		Ctx          context.Context
		ResourceId   string
		BlockNumber  *big.Int
		TxsByChainID map[string][]*types.EnygmaTransferBatchTx
	}
	mock.lockCreateBatchesWithAnonimity.RLock()
	calls = mock.calls.CreateBatchesWithAnonimity
	mock.lockCreateBatchesWithAnonimity.RUnlock()
	return calls
}

// executorProofGeneratorMock is a mock implementation of service.executorProofGenerator.
//
//	func TestSomethingThatUsesexecutorProofGenerator(t *testing.T) {
//
//		// make and configure a mocked service.executorProofGenerator
//		mockedexecutorProofGenerator := &executorProofGeneratorMock{
//			GenerateDepositProofFunc: func(ctx context.Context, params enygma.DepositProofParams) (*types.EnygmaProofResponse, []*types.Point, []*big.Int, []*big.Int, error) {
//				panic("mock out the GenerateDepositProof method")
//			},
//			GenerateTransferProofFunc: func(ctx context.Context, params enygma.TransferProofParams) (*types.EnygmaProofResponse, []*types.Point, []*big.Int, []*big.Int, error) {
//				panic("mock out the GenerateTransferProof method")
//			},
//			GenerateWithdrawProofFunc: func(ctx context.Context, params enygma.WithdrawProofParams) (*types.EnygmaProofResponse, []*types.Point, []*big.Int, []*big.Int, error) {
//				panic("mock out the GenerateWithdrawProof method")
//			},
//		}
//
//		// use mockedexecutorProofGenerator in code that requires service.executorProofGenerator
//		// and then make assertions.
//
//	}
type executorProofGeneratorMock struct {
	// GenerateDepositProofFunc mocks the GenerateDepositProof method.
	GenerateDepositProofFunc func(ctx context.Context, params enygma.DepositProofParams) (*types.EnygmaProofResponse, []*types.Point, []*big.Int, []*big.Int, error)

	// GenerateTransferProofFunc mocks the GenerateTransferProof method.
	GenerateTransferProofFunc func(ctx context.Context, params enygma.TransferProofParams) (*types.EnygmaProofResponse, []*types.Point, []*big.Int, []*big.Int, error)

	// GenerateWithdrawProofFunc mocks the GenerateWithdrawProof method.
	GenerateWithdrawProofFunc func(ctx context.Context, params enygma.WithdrawProofParams) (*types.EnygmaProofResponse, []*types.Point, []*big.Int, []*big.Int, error)

	// calls tracks calls to the methods.
	calls struct {
		// GenerateDepositProof holds details about calls to the GenerateDepositProof method.
		GenerateDepositProof []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Params is the params argument value.
			Params enygma.DepositProofParams
		}
		// GenerateTransferProof holds details about calls to the GenerateTransferProof method.
		GenerateTransferProof []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Params is the params argument value.
			Params enygma.TransferProofParams
		}
		// GenerateWithdrawProof holds details about calls to the GenerateWithdrawProof method.
		GenerateWithdrawProof []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Params is the params argument value.
			Params enygma.WithdrawProofParams
		}
	}
	lockGenerateDepositProof  sync.RWMutex
	lockGenerateTransferProof sync.RWMutex
	lockGenerateWithdrawProof sync.RWMutex
}

// GenerateDepositProof calls GenerateDepositProofFunc.
func (mock *executorProofGeneratorMock) GenerateDepositProof(ctx context.Context, params enygma.DepositProofParams) (*types.EnygmaProofResponse, []*types.Point, []*big.Int, []*big.Int, error) {
	if mock.GenerateDepositProofFunc == nil {
		panic("executorProofGeneratorMock.GenerateDepositProofFunc: method is nil but executorProofGenerator.GenerateDepositProof was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Params enygma.DepositProofParams
	}{
		Ctx:    ctx,
		Params: params,
	}
	mock.lockGenerateDepositProof.Lock()
	mock.calls.GenerateDepositProof = append(mock.calls.GenerateDepositProof, callInfo)
	mock.lockGenerateDepositProof.Unlock()
	return mock.GenerateDepositProofFunc(ctx, params)
}

// GenerateDepositProofCalls gets all the calls that were made to GenerateDepositProof.
// Check the length with:
//
//	len(mockedexecutorProofGenerator.GenerateDepositProofCalls())
func (mock *executorProofGeneratorMock) GenerateDepositProofCalls() []struct {
	Ctx    context.Context
	Params enygma.DepositProofParams
} {
	var calls []struct {
		Ctx    context.Context
		Params enygma.DepositProofParams
	}
	mock.lockGenerateDepositProof.RLock()
	calls = mock.calls.GenerateDepositProof
	mock.lockGenerateDepositProof.RUnlock()
	return calls
}

// GenerateTransferProof calls GenerateTransferProofFunc.
func (mock *executorProofGeneratorMock) GenerateTransferProof(ctx context.Context, params enygma.TransferProofParams) (*types.EnygmaProofResponse, []*types.Point, []*big.Int, []*big.Int, error) {
	if mock.GenerateTransferProofFunc == nil {
		panic("executorProofGeneratorMock.GenerateTransferProofFunc: method is nil but executorProofGenerator.GenerateTransferProof was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Params enygma.TransferProofParams
	}{
		Ctx:    ctx,
		Params: params,
	}
	mock.lockGenerateTransferProof.Lock()
	mock.calls.GenerateTransferProof = append(mock.calls.GenerateTransferProof, callInfo)
	mock.lockGenerateTransferProof.Unlock()
	return mock.GenerateTransferProofFunc(ctx, params)
}

// GenerateTransferProofCalls gets all the calls that were made to GenerateTransferProof.
// Check the length with:
//
//	len(mockedexecutorProofGenerator.GenerateTransferProofCalls())
func (mock *executorProofGeneratorMock) GenerateTransferProofCalls() []struct {
	Ctx    context.Context
	Params enygma.TransferProofParams
} {
	var calls []struct {
		Ctx    context.Context
		Params enygma.TransferProofParams
	}
	mock.lockGenerateTransferProof.RLock()
	calls = mock.calls.GenerateTransferProof
	mock.lockGenerateTransferProof.RUnlock()
	return calls
}

// GenerateWithdrawProof calls GenerateWithdrawProofFunc.
func (mock *executorProofGeneratorMock) GenerateWithdrawProof(ctx context.Context, params enygma.WithdrawProofParams) (*types.EnygmaProofResponse, []*types.Point, []*big.Int, []*big.Int, error) {
	if mock.GenerateWithdrawProofFunc == nil {
		panic("executorProofGeneratorMock.GenerateWithdrawProofFunc: method is nil but executorProofGenerator.GenerateWithdrawProof was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Params enygma.WithdrawProofParams
	}{
		Ctx:    ctx,
		Params: params,
	}
	mock.lockGenerateWithdrawProof.Lock()
	mock.calls.GenerateWithdrawProof = append(mock.calls.GenerateWithdrawProof, callInfo)
	mock.lockGenerateWithdrawProof.Unlock()
	return mock.GenerateWithdrawProofFunc(ctx, params)
}

// GenerateWithdrawProofCalls gets all the calls that were made to GenerateWithdrawProof.
// Check the length with:
//
//	len(mockedexecutorProofGenerator.GenerateWithdrawProofCalls())
func (mock *executorProofGeneratorMock) GenerateWithdrawProofCalls() []struct {
	Ctx    context.Context
	Params enygma.WithdrawProofParams
} {
	var calls []struct {
		Ctx    context.Context
		Params enygma.WithdrawProofParams
	}
	mock.lockGenerateWithdrawProof.RLock()
	calls = mock.calls.GenerateWithdrawProof
	mock.lockGenerateWithdrawProof.RUnlock()
	return calls
}

// executorEnygmaHistoryRepositoryMock is a mock implementation of service.executorEnygmaHistoryRepository.
//
//	func TestSomethingThatUsesexecutorEnygmaHistoryRepository(t *testing.T) {
//
//		// make and configure a mocked service.executorEnygmaHistoryRepository
//		mockedexecutorEnygmaHistoryRepository := &executorEnygmaHistoryRepositoryMock{
//			InsertEnygmaHistoryFunc: func(ctx context.Context, history types.EnygmaHistory) error {
//				panic("mock out the InsertEnygmaHistory method")
//			},
//		}
//
//		// use mockedexecutorEnygmaHistoryRepository in code that requires service.executorEnygmaHistoryRepository
//		// and then make assertions.
//
//	}
type executorEnygmaHistoryRepositoryMock struct {
	// InsertEnygmaHistoryFunc mocks the InsertEnygmaHistory method.
	InsertEnygmaHistoryFunc func(ctx context.Context, history types.EnygmaHistory) error

	// calls tracks calls to the methods.
	calls struct {
		// InsertEnygmaHistory holds details about calls to the InsertEnygmaHistory method.
		InsertEnygmaHistory []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// History is the history argument value.
			History types.EnygmaHistory
		}
	}
	lockInsertEnygmaHistory sync.RWMutex
}

// InsertEnygmaHistory calls InsertEnygmaHistoryFunc.
func (mock *executorEnygmaHistoryRepositoryMock) InsertEnygmaHistory(ctx context.Context, history types.EnygmaHistory) error {
	if mock.InsertEnygmaHistoryFunc == nil {
		panic("executorEnygmaHistoryRepositoryMock.InsertEnygmaHistoryFunc: method is nil but executorEnygmaHistoryRepository.InsertEnygmaHistory was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		History types.EnygmaHistory
	}{
		Ctx:     ctx,
		History: history,
	}
	mock.lockInsertEnygmaHistory.Lock()
	mock.calls.InsertEnygmaHistory = append(mock.calls.InsertEnygmaHistory, callInfo)
	mock.lockInsertEnygmaHistory.Unlock()
	return mock.InsertEnygmaHistoryFunc(ctx, history)
}

// InsertEnygmaHistoryCalls gets all the calls that were made to InsertEnygmaHistory.
// Check the length with:
//
//	len(mockedexecutorEnygmaHistoryRepository.InsertEnygmaHistoryCalls())
func (mock *executorEnygmaHistoryRepositoryMock) InsertEnygmaHistoryCalls() []struct {
	Ctx     context.Context
	History types.EnygmaHistory
} {
	var calls []struct {
		Ctx     context.Context
		History types.EnygmaHistory
	}
	mock.lockInsertEnygmaHistory.RLock()
	calls = mock.calls.InsertEnygmaHistory
	mock.lockInsertEnygmaHistory.RUnlock()
	return calls
}

// executorEnygmaClientMock is a mock implementation of service.executorEnygmaClient.
//
//	func TestSomethingThatUsesexecutorEnygmaClient(t *testing.T) {
//
//		// make and configure a mocked service.executorEnygmaClient
//		mockedexecutorEnygmaClient := &executorEnygmaClientMock{
//			GetDvpIntegrationContractAddressFunc: func(ctx context.Context, tokenAddress common.Address) (common.Address, error) {
//				panic("mock out the GetDvpIntegrationContractAddress method")
//			},
//			SupplyUpdateFunc: func(ctx context.Context, batchID string, tokenAddress common.Address, senderChainId *big.Int, blockNumber *big.Int, update types.EnygmaSupplyUpdate) error {
//				panic("mock out the SupplyUpdate method")
//			},
//			TransferBatchFunc: func(ctx context.Context, batchID string, tokenAddress common.Address, batches []*types.EnygmaTransferBatch, proof *types.EnygmaProofResponse, blockNumber *big.Int) error {
//				panic("mock out the TransferBatch method")
//			},
//		}
//
//		// use mockedexecutorEnygmaClient in code that requires service.executorEnygmaClient
//		// and then make assertions.
//
//	}
type executorEnygmaClientMock struct {
	// GetDvpIntegrationContractAddressFunc mocks the GetDvpIntegrationContractAddress method.
	GetDvpIntegrationContractAddressFunc func(ctx context.Context, tokenAddress common.Address) (common.Address, error)

	// SupplyUpdateFunc mocks the SupplyUpdate method.
	SupplyUpdateFunc func(ctx context.Context, batchID string, tokenAddress common.Address, senderChainId *big.Int, blockNumber *big.Int, update types.EnygmaSupplyUpdate) error

	// TransferBatchFunc mocks the TransferBatch method.
	TransferBatchFunc func(ctx context.Context, batchID string, tokenAddress common.Address, batches []*types.EnygmaTransferBatch, proof *types.EnygmaProofResponse, blockNumber *big.Int) error

	// calls tracks calls to the methods.
	calls struct {
		// GetDvpIntegrationContractAddress holds details about calls to the GetDvpIntegrationContractAddress method.
		GetDvpIntegrationContractAddress []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// TokenAddress is the tokenAddress argument value.
			TokenAddress common.Address
		}
		// SupplyUpdate holds details about calls to the SupplyUpdate method.
		SupplyUpdate []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// BatchID is the batchID argument value.
			BatchID string
			// TokenAddress is the tokenAddress argument value.
			TokenAddress common.Address
			// SenderChainId is the senderChainId argument value.
			SenderChainId *big.Int
			// BlockNumber is the blockNumber argument value.
			BlockNumber *big.Int
			// Update is the update argument value.
			Update types.EnygmaSupplyUpdate
		}
		// TransferBatch holds details about calls to the TransferBatch method.
		TransferBatch []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// BatchID is the batchID argument value.
			BatchID string
			// TokenAddress is the tokenAddress argument value.
			TokenAddress common.Address
			// Batches is the batches argument value.
			Batches []*types.EnygmaTransferBatch
			// Proof is the proof argument value.
			Proof *types.EnygmaProofResponse
			// BlockNumber is the blockNumber argument value.
			BlockNumber *big.Int
		}
	}
	lockGetDvpIntegrationContractAddress sync.RWMutex
	lockSupplyUpdate                     sync.RWMutex
	lockTransferBatch                    sync.RWMutex
}

// GetDvpIntegrationContractAddress calls GetDvpIntegrationContractAddressFunc.
func (mock *executorEnygmaClientMock) GetDvpIntegrationContractAddress(ctx context.Context, tokenAddress common.Address) (common.Address, error) {
	if mock.GetDvpIntegrationContractAddressFunc == nil {
		panic("executorEnygmaClientMock.GetDvpIntegrationContractAddressFunc: method is nil but executorEnygmaClient.GetDvpIntegrationContractAddress was just called")
	}
	callInfo := struct {
		Ctx          context.Context
		TokenAddress common.Address
	}{
		Ctx:          ctx,
		TokenAddress: tokenAddress,
	}
	mock.lockGetDvpIntegrationContractAddress.Lock()
	mock.calls.GetDvpIntegrationContractAddress = append(mock.calls.GetDvpIntegrationContractAddress, callInfo)
	mock.lockGetDvpIntegrationContractAddress.Unlock()
	return mock.GetDvpIntegrationContractAddressFunc(ctx, tokenAddress)
}

// GetDvpIntegrationContractAddressCalls gets all the calls that were made to GetDvpIntegrationContractAddress.
// Check the length with:
//
//	len(mockedexecutorEnygmaClient.GetDvpIntegrationContractAddressCalls())
func (mock *executorEnygmaClientMock) GetDvpIntegrationContractAddressCalls() []struct {
	Ctx          context.Context
	TokenAddress common.Address
} {
	var calls []struct {
		Ctx          context.Context
		TokenAddress common.Address
	}
	mock.lockGetDvpIntegrationContractAddress.RLock()
	calls = mock.calls.GetDvpIntegrationContractAddress
	mock.lockGetDvpIntegrationContractAddress.RUnlock()
	return calls
}

// SupplyUpdate calls SupplyUpdateFunc.
func (mock *executorEnygmaClientMock) SupplyUpdate(ctx context.Context, batchID string, tokenAddress common.Address, senderChainId *big.Int, blockNumber *big.Int, update types.EnygmaSupplyUpdate) error {
	if mock.SupplyUpdateFunc == nil {
		panic("executorEnygmaClientMock.SupplyUpdateFunc: method is nil but executorEnygmaClient.SupplyUpdate was just called")
	}
	callInfo := struct {
		Ctx           context.Context
		BatchID       string
		TokenAddress  common.Address
		SenderChainId *big.Int
		BlockNumber   *big.Int
		Update        types.EnygmaSupplyUpdate
	}{
		Ctx:           ctx,
		BatchID:       batchID,
		TokenAddress:  tokenAddress,
		SenderChainId: senderChainId,
		BlockNumber:   blockNumber,
		Update:        update,
	}
	mock.lockSupplyUpdate.Lock()
	mock.calls.SupplyUpdate = append(mock.calls.SupplyUpdate, callInfo)
	mock.lockSupplyUpdate.Unlock()
	return mock.SupplyUpdateFunc(ctx, batchID, tokenAddress, senderChainId, blockNumber, update)
}

// SupplyUpdateCalls gets all the calls that were made to SupplyUpdate.
// Check the length with:
//
//	len(mockedexecutorEnygmaClient.SupplyUpdateCalls())
func (mock *executorEnygmaClientMock) SupplyUpdateCalls() []struct {
	Ctx           context.Context
	BatchID       string
	TokenAddress  common.Address
	SenderChainId *big.Int
	BlockNumber   *big.Int
	Update        types.EnygmaSupplyUpdate
} {
	var calls []struct {
		Ctx           context.Context
		BatchID       string
		TokenAddress  common.Address
		SenderChainId *big.Int
		BlockNumber   *big.Int
		Update        types.EnygmaSupplyUpdate
	}
	mock.lockSupplyUpdate.RLock()
	calls = mock.calls.SupplyUpdate
	mock.lockSupplyUpdate.RUnlock()
	return calls
}

// TransferBatch calls TransferBatchFunc.
func (mock *executorEnygmaClientMock) TransferBatch(ctx context.Context, batchID string, tokenAddress common.Address, batches []*types.EnygmaTransferBatch, proof *types.EnygmaProofResponse, blockNumber *big.Int) error {
	if mock.TransferBatchFunc == nil {
		panic("executorEnygmaClientMock.TransferBatchFunc: method is nil but executorEnygmaClient.TransferBatch was just called")
	}
	callInfo := struct {
		Ctx          context.Context
		BatchID      string
		TokenAddress common.Address
		Batches      []*types.EnygmaTransferBatch
		Proof        *types.EnygmaProofResponse
		BlockNumber  *big.Int
	}{
		Ctx:          ctx,
		BatchID:      batchID,
		TokenAddress: tokenAddress,
		Batches:      batches,
		Proof:        proof,
		BlockNumber:  blockNumber,
	}
	mock.lockTransferBatch.Lock()
	mock.calls.TransferBatch = append(mock.calls.TransferBatch, callInfo)
	mock.lockTransferBatch.Unlock()
	return mock.TransferBatchFunc(ctx, batchID, tokenAddress, batches, proof, blockNumber)
}

// TransferBatchCalls gets all the calls that were made to TransferBatch.
// Check the length with:
//
//	len(mockedexecutorEnygmaClient.TransferBatchCalls())
func (mock *executorEnygmaClientMock) TransferBatchCalls() []struct {
	Ctx          context.Context
	BatchID      string
	TokenAddress common.Address
	Batches      []*types.EnygmaTransferBatch
	Proof        *types.EnygmaProofResponse
	BlockNumber  *big.Int
} {
	var calls []struct {
		Ctx          context.Context
		BatchID      string
		TokenAddress common.Address
		Batches      []*types.EnygmaTransferBatch
		Proof        *types.EnygmaProofResponse
		BlockNumber  *big.Int
	}
	mock.lockTransferBatch.RLock()
	calls = mock.calls.TransferBatch
	mock.lockTransferBatch.RUnlock()
	return calls
}

// ExecutorDvpIntegrationClientMock is a mock implementation of service.ExecutorDvpIntegrationClient.
//
//	func TestSomethingThatUsesExecutorDvpIntegrationClient(t *testing.T) {
//
//		// make and configure a mocked service.ExecutorDvpIntegrationClient
//		mockedExecutorDvpIntegrationClient := &ExecutorDvpIntegrationClientMock{
//			DepositFunc: func(ctx context.Context, chainEventID string, batches []*types.EnygmaTransferBatch, proof *types.EnygmaProofResponse, blockNumber *big.Int, chainId *big.Int, resourceId string, amount *big.Int, from common.Address, sourceTxHash common.Hash, dvpIntegrationAddress common.Address) error {
//				panic("mock out the Deposit method")
//			},
//			WithdrawFunc: func(ctx context.Context, chainEventID string, batches []*types.EnygmaTransferBatch, proof *types.EnygmaProofResponse, blockNumber *big.Int, jsProof *dvp.ProofReceipt, chainId *big.Int, resourceId string, amount *big.Int, from common.Address, sourceTxHash common.Hash, dvpIntegrationAddress common.Address) error {
//				panic("mock out the Withdraw method")
//			},
//		}
//
//		// use mockedExecutorDvpIntegrationClient in code that requires service.ExecutorDvpIntegrationClient
//		// and then make assertions.
//
//	}
type ExecutorDvpIntegrationClientMock struct {
	// DepositFunc mocks the Deposit method.
	DepositFunc func(ctx context.Context, chainEventID string, batches []*types.EnygmaTransferBatch, proof *types.EnygmaProofResponse, blockNumber *big.Int, chainId *big.Int, resourceId string, amount *big.Int, from common.Address, sourceTxHash common.Hash, dvpIntegrationAddress common.Address) error

	// WithdrawFunc mocks the Withdraw method.
	WithdrawFunc func(ctx context.Context, chainEventID string, batches []*types.EnygmaTransferBatch, proof *types.EnygmaProofResponse, blockNumber *big.Int, jsProof *dvp.ProofReceipt, chainId *big.Int, resourceId string, amount *big.Int, from common.Address, sourceTxHash common.Hash, dvpIntegrationAddress common.Address) error

	// calls tracks calls to the methods.
	calls struct {
		// Deposit holds details about calls to the Deposit method.
		Deposit []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ChainEventID is the chainEventID argument value.
			ChainEventID string
			// Batches is the batches argument value.
			Batches []*types.EnygmaTransferBatch
			// Proof is the proof argument value.
			Proof *types.EnygmaProofResponse
			// BlockNumber is the blockNumber argument value.
			BlockNumber *big.Int
			// ChainId is the chainId argument value.
			ChainId *big.Int
			// ResourceId is the resourceId argument value.
			ResourceId string
			// Amount is the amount argument value.
			Amount *big.Int
			// From is the from argument value.
			From common.Address
			// SourceTxHash is the sourceTxHash argument value.
			SourceTxHash common.Hash
			// DvpIntegrationAddress is the dvpIntegrationAddress argument value.
			DvpIntegrationAddress common.Address
		}
		// Withdraw holds details about calls to the Withdraw method.
		Withdraw []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ChainEventID is the chainEventID argument value.
			ChainEventID string
			// Batches is the batches argument value.
			Batches []*types.EnygmaTransferBatch
			// Proof is the proof argument value.
			Proof *types.EnygmaProofResponse
			// BlockNumber is the blockNumber argument value.
			BlockNumber *big.Int
			// JsProof is the jsProof argument value.
			JsProof *dvp.ProofReceipt
			// ChainId is the chainId argument value.
			ChainId *big.Int
			// ResourceId is the resourceId argument value.
			ResourceId string
			// Amount is the amount argument value.
			Amount *big.Int
			// From is the from argument value.
			From common.Address
			// SourceTxHash is the sourceTxHash argument value.
			SourceTxHash common.Hash
			// DvpIntegrationAddress is the dvpIntegrationAddress argument value.
			DvpIntegrationAddress common.Address
		}
	}
	lockDeposit  sync.RWMutex
	lockWithdraw sync.RWMutex
}

// Deposit calls DepositFunc.
func (mock *ExecutorDvpIntegrationClientMock) Deposit(ctx context.Context, chainEventID string, batches []*types.EnygmaTransferBatch, proof *types.EnygmaProofResponse, blockNumber *big.Int, chainId *big.Int, resourceId string, amount *big.Int, from common.Address, sourceTxHash common.Hash, dvpIntegrationAddress common.Address) error {
	if mock.DepositFunc == nil {
		panic("ExecutorDvpIntegrationClientMock.DepositFunc: method is nil but ExecutorDvpIntegrationClient.Deposit was just called")
	}
	callInfo := struct {
		Ctx                   context.Context
		ChainEventID          string
		Batches               []*types.EnygmaTransferBatch
		Proof                 *types.EnygmaProofResponse
		BlockNumber           *big.Int
		ChainId               *big.Int
		ResourceId            string
		Amount                *big.Int
		From                  common.Address
		SourceTxHash          common.Hash
		DvpIntegrationAddress common.Address
	}{
		Ctx:                   ctx,
		ChainEventID:          chainEventID,
		Batches:               batches,
		Proof:                 proof,
		BlockNumber:           blockNumber,
		ChainId:               chainId,
		ResourceId:            resourceId,
		Amount:                amount,
		From:                  from,
		SourceTxHash:          sourceTxHash,
		DvpIntegrationAddress: dvpIntegrationAddress,
	}
	mock.lockDeposit.Lock()
	mock.calls.Deposit = append(mock.calls.Deposit, callInfo)
	mock.lockDeposit.Unlock()
	return mock.DepositFunc(ctx, chainEventID, batches, proof, blockNumber, chainId, resourceId, amount, from, sourceTxHash, dvpIntegrationAddress)
}

// DepositCalls gets all the calls that were made to Deposit.
// Check the length with:
//
//	len(mockedExecutorDvpIntegrationClient.DepositCalls())
func (mock *ExecutorDvpIntegrationClientMock) DepositCalls() []struct {
	Ctx                   context.Context
	ChainEventID          string
	Batches               []*types.EnygmaTransferBatch
	Proof                 *types.EnygmaProofResponse
	BlockNumber           *big.Int
	ChainId               *big.Int
	ResourceId            string
	Amount                *big.Int
	From                  common.Address
	SourceTxHash          common.Hash
	DvpIntegrationAddress common.Address
} {
	var calls []struct {
		Ctx                   context.Context
		ChainEventID          string
		Batches               []*types.EnygmaTransferBatch
		Proof                 *types.EnygmaProofResponse
		BlockNumber           *big.Int
		ChainId               *big.Int
		ResourceId            string
		Amount                *big.Int
		From                  common.Address
		SourceTxHash          common.Hash
		DvpIntegrationAddress common.Address
	}
	mock.lockDeposit.RLock()
	calls = mock.calls.Deposit
	mock.lockDeposit.RUnlock()
	return calls
}

// Withdraw calls WithdrawFunc.
func (mock *ExecutorDvpIntegrationClientMock) Withdraw(ctx context.Context, chainEventID string, batches []*types.EnygmaTransferBatch, proof *types.EnygmaProofResponse, blockNumber *big.Int, jsProof *dvp.ProofReceipt, chainId *big.Int, resourceId string, amount *big.Int, from common.Address, sourceTxHash common.Hash, dvpIntegrationAddress common.Address) error {
	if mock.WithdrawFunc == nil {
		panic("ExecutorDvpIntegrationClientMock.WithdrawFunc: method is nil but ExecutorDvpIntegrationClient.Withdraw was just called")
	}
	callInfo := struct {
		Ctx                   context.Context
		ChainEventID          string
		Batches               []*types.EnygmaTransferBatch
		Proof                 *types.EnygmaProofResponse
		BlockNumber           *big.Int
		JsProof               *dvp.ProofReceipt
		ChainId               *big.Int
		ResourceId            string
		Amount                *big.Int
		From                  common.Address
		SourceTxHash          common.Hash
		DvpIntegrationAddress common.Address
	}{
		Ctx:                   ctx,
		ChainEventID:          chainEventID,
		Batches:               batches,
		Proof:                 proof,
		BlockNumber:           blockNumber,
		JsProof:               jsProof,
		ChainId:               chainId,
		ResourceId:            resourceId,
		Amount:                amount,
		From:                  from,
		SourceTxHash:          sourceTxHash,
		DvpIntegrationAddress: dvpIntegrationAddress,
	}
	mock.lockWithdraw.Lock()
	mock.calls.Withdraw = append(mock.calls.Withdraw, callInfo)
	mock.lockWithdraw.Unlock()
	return mock.WithdrawFunc(ctx, chainEventID, batches, proof, blockNumber, jsProof, chainId, resourceId, amount, from, sourceTxHash, dvpIntegrationAddress)
}

// WithdrawCalls gets all the calls that were made to Withdraw.
// Check the length with:
//
//	len(mockedExecutorDvpIntegrationClient.WithdrawCalls())
func (mock *ExecutorDvpIntegrationClientMock) WithdrawCalls() []struct {
	Ctx                   context.Context
	ChainEventID          string
	Batches               []*types.EnygmaTransferBatch
	Proof                 *types.EnygmaProofResponse
	BlockNumber           *big.Int
	JsProof               *dvp.ProofReceipt
	ChainId               *big.Int
	ResourceId            string
	Amount                *big.Int
	From                  common.Address
	SourceTxHash          common.Hash
	DvpIntegrationAddress common.Address
} {
	var calls []struct {
		Ctx                   context.Context
		ChainEventID          string
		Batches               []*types.EnygmaTransferBatch
		Proof                 *types.EnygmaProofResponse
		BlockNumber           *big.Int
		JsProof               *dvp.ProofReceipt
		ChainId               *big.Int
		ResourceId            string
		Amount                *big.Int
		From                  common.Address
		SourceTxHash          common.Hash
		DvpIntegrationAddress common.Address
	}
	mock.lockWithdraw.RLock()
	calls = mock.calls.Withdraw
	mock.lockWithdraw.RUnlock()
	return calls
}

// executorKeysClientMock is a mock implementation of service.executorKeysClient.
//
//	func TestSomethingThatUsesexecutorKeysClient(t *testing.T) {
//
//		// make and configure a mocked service.executorKeysClient
//		mockedexecutorKeysClient := &executorKeysClientMock{
//			GetPaymentSpendKeyFunc: func(ctx context.Context, in *keyspb.GetPaymentSpendKeyRequest, opts ...grpc.CallOption) (*keyspb.PaymentSpendKeyResponse, error) {
//				panic("mock out the GetPaymentSpendKey method")
//			},
//		}
//
//		// use mockedexecutorKeysClient in code that requires service.executorKeysClient
//		// and then make assertions.
//
//	}
type executorKeysClientMock struct {
	// GetPaymentSpendKeyFunc mocks the GetPaymentSpendKey method.
	GetPaymentSpendKeyFunc func(ctx context.Context, in *keyspb.GetPaymentSpendKeyRequest, opts ...grpc.CallOption) (*keyspb.PaymentSpendKeyResponse, error)

	// calls tracks calls to the methods.
	calls struct {
		// GetPaymentSpendKey holds details about calls to the GetPaymentSpendKey method.
		GetPaymentSpendKey []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// In is the in argument value.
			In *keyspb.GetPaymentSpendKeyRequest
			// Opts is the opts argument value.
			Opts []grpc.CallOption
		}
	}
	lockGetPaymentSpendKey sync.RWMutex
}

// GetPaymentSpendKey calls GetPaymentSpendKeyFunc.
func (mock *executorKeysClientMock) GetPaymentSpendKey(ctx context.Context, in *keyspb.GetPaymentSpendKeyRequest, opts ...grpc.CallOption) (*keyspb.PaymentSpendKeyResponse, error) {
	if mock.GetPaymentSpendKeyFunc == nil {
		panic("executorKeysClientMock.GetPaymentSpendKeyFunc: method is nil but executorKeysClient.GetPaymentSpendKey was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		In   *keyspb.GetPaymentSpendKeyRequest
		Opts []grpc.CallOption
	}{
		Ctx:  ctx,
		In:   in,
		Opts: opts,
	}
	mock.lockGetPaymentSpendKey.Lock()
	mock.calls.GetPaymentSpendKey = append(mock.calls.GetPaymentSpendKey, callInfo)
	mock.lockGetPaymentSpendKey.Unlock()
	return mock.GetPaymentSpendKeyFunc(ctx, in, opts...)
}

// GetPaymentSpendKeyCalls gets all the calls that were made to GetPaymentSpendKey.
// Check the length with:
//
//	len(mockedexecutorKeysClient.GetPaymentSpendKeyCalls())
func (mock *executorKeysClientMock) GetPaymentSpendKeyCalls() []struct {
	Ctx  context.Context
	In   *keyspb.GetPaymentSpendKeyRequest
	Opts []grpc.CallOption
} {
	var calls []struct {
		Ctx  context.Context
		In   *keyspb.GetPaymentSpendKeyRequest
		Opts []grpc.CallOption
	}
	mock.lockGetPaymentSpendKey.RLock()
	calls = mock.calls.GetPaymentSpendKey
	mock.lockGetPaymentSpendKey.RUnlock()
	return calls
}

// executorCommitmentCalculatorMock is a mock implementation of service.executorCommitmentCalculator.
//
//	func TestSomethingThatUsesexecutorCommitmentCalculator(t *testing.T) {
//
//		// make and configure a mocked service.executorCommitmentCalculator
//		mockedexecutorCommitmentCalculator := &executorCommitmentCalculatorMock{
//			CalculatePaymentCommitmentFunc: func(spendPK *big.Int, salt *big.Int, paymentAmount *big.Int, tokenAddress string) (*big.Int, error) {
//				panic("mock out the CalculatePaymentCommitment method")
//			},
//		}
//
//		// use mockedexecutorCommitmentCalculator in code that requires service.executorCommitmentCalculator
//		// and then make assertions.
//
//	}
type executorCommitmentCalculatorMock struct {
	// CalculatePaymentCommitmentFunc mocks the CalculatePaymentCommitment method.
	CalculatePaymentCommitmentFunc func(spendPK *big.Int, salt *big.Int, paymentAmount *big.Int, tokenAddress string) (*big.Int, error)

	// calls tracks calls to the methods.
	calls struct {
		// CalculatePaymentCommitment holds details about calls to the CalculatePaymentCommitment method.
		CalculatePaymentCommitment []struct {
			// SpendPK is the spendPK argument value.
			SpendPK *big.Int
			// Salt is the salt argument value.
			Salt *big.Int
			// PaymentAmount is the paymentAmount argument value.
			PaymentAmount *big.Int
			// TokenAddress is the tokenAddress argument value.
			TokenAddress string
		}
	}
	lockCalculatePaymentCommitment sync.RWMutex
}

// CalculatePaymentCommitment calls CalculatePaymentCommitmentFunc.
func (mock *executorCommitmentCalculatorMock) CalculatePaymentCommitment(spendPK *big.Int, salt *big.Int, paymentAmount *big.Int, tokenAddress string) (*big.Int, error) {
	if mock.CalculatePaymentCommitmentFunc == nil {
		panic("executorCommitmentCalculatorMock.CalculatePaymentCommitmentFunc: method is nil but executorCommitmentCalculator.CalculatePaymentCommitment was just called")
	}
	callInfo := struct {
		SpendPK       *big.Int
		Salt          *big.Int
		PaymentAmount *big.Int
		TokenAddress  string
	}{
		SpendPK:       spendPK,
		Salt:          salt,
		PaymentAmount: paymentAmount,
		TokenAddress:  tokenAddress,
	}
	mock.lockCalculatePaymentCommitment.Lock()
	mock.calls.CalculatePaymentCommitment = append(mock.calls.CalculatePaymentCommitment, callInfo)
	mock.lockCalculatePaymentCommitment.Unlock()
	return mock.CalculatePaymentCommitmentFunc(spendPK, salt, paymentAmount, tokenAddress)
}

// CalculatePaymentCommitmentCalls gets all the calls that were made to CalculatePaymentCommitment.
// Check the length with:
//
//	len(mockedexecutorCommitmentCalculator.CalculatePaymentCommitmentCalls())
func (mock *executorCommitmentCalculatorMock) CalculatePaymentCommitmentCalls() []struct {
	SpendPK       *big.Int
	Salt          *big.Int
	PaymentAmount *big.Int
	TokenAddress  string
} {
	var calls []struct {
		SpendPK       *big.Int
		Salt          *big.Int
		PaymentAmount *big.Int
		TokenAddress  string
	}
	mock.lockCalculatePaymentCommitment.RLock()
	calls = mock.calls.CalculatePaymentCommitment
	mock.lockCalculatePaymentCommitment.RUnlock()
	return calls
}
