// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package logrouter_test

import (
	"context"
	"github.com/raylsnetwork/rayls-privacy-relayer-api/private-relayer/dest/logrouter"
	"sync"
)

// Ensure, that RouterMQMock does implement logrouter.RouterMQ.
// If this is not the case, regenerate this file with moq.
var _ logrouter.RouterMQ = &RouterMQMock{}

// RouterMQMock is a mock implementation of logrouter.RouterMQ.
//
//	func TestSomethingThatUsesRouterMQ(t *testing.T) {
//
//		// make and configure a mocked logrouter.RouterMQ
//		mockedRouterMQ := &RouterMQMock{
//			PushFunc: func(contextMoqParam context.Context, block logrouter.Block) error {
//				panic("mock out the Push method")
//			},
//		}
//
//		// use mockedRouterMQ in code that requires logrouter.RouterMQ
//		// and then make assertions.
//
//	}
type RouterMQMock struct {
	// PushFunc mocks the Push method.
	PushFunc func(contextMoqParam context.Context, block logrouter.Block) error

	// calls tracks calls to the methods.
	calls struct {
		// Push holds details about calls to the Push method.
		Push []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// Block is the block argument value.
			Block logrouter.Block
		}
	}
	lockPush sync.RWMutex
}

// Push calls PushFunc.
func (mock *RouterMQMock) Push(contextMoqParam context.Context, block logrouter.Block) error {
	if mock.PushFunc == nil {
		panic("RouterMQMock.PushFunc: method is nil but RouterMQ.Push was just called")
	}
	callInfo := struct {
		ContextMoqParam context.Context
		Block           logrouter.Block
	}{
		ContextMoqParam: contextMoqParam,
		Block:           block,
	}
	mock.lockPush.Lock()
	mock.calls.Push = append(mock.calls.Push, callInfo)
	mock.lockPush.Unlock()
	return mock.PushFunc(contextMoqParam, block)
}

// PushCalls gets all the calls that were made to Push.
// Check the length with:
//
//	len(mockedRouterMQ.PushCalls())
func (mock *RouterMQMock) PushCalls() []struct {
	ContextMoqParam context.Context
	Block           logrouter.Block
} {
	var calls []struct {
		ContextMoqParam context.Context
		Block           logrouter.Block
	}
	mock.lockPush.RLock()
	calls = mock.calls.Push
	mock.lockPush.RUnlock()
	return calls
}
