// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package ethrpc_test

import (
	"context"
	"crypto/ecdsa"
	"github.com/ethereum/go-ethereum"
	"github.com/ethereum/go-ethereum/common"
	"github.com/ethereum/go-ethereum/core/types"
	"github.com/ethereum/go-ethereum/rpc"
	"github.com/raylsnetwork/rayls-privacy-relayer-api/cts/ethrpc"
	"math/big"
	"sync"
)

// Ensure, that EthereumClientMock does implement ethrpc.EthereumClient.
// If this is not the case, regenerate this file with moq.
var _ ethrpc.EthereumClient = &EthereumClientMock{}

// EthereumClientMock is a mock implementation of ethrpc.EthereumClient.
//
//	func TestSomethingThatUsesEthereumClient(t *testing.T) {
//
//		// make and configure a mocked ethrpc.EthereumClient
//		mockedEthereumClient := &EthereumClientMock{
//			CallContractFunc: func(ctx context.Context, msg ethereum.CallMsg, blockNumber *big.Int) ([]byte, error) {
//				panic("mock out the CallContract method")
//			},
//			ChainIDFunc: func(contextMoqParam context.Context) (*big.Int, error) {
//				panic("mock out the ChainID method")
//			},
//			EstimateGasFunc: func(ctx context.Context, msg ethereum.CallMsg) (uint64, error) {
//				panic("mock out the EstimateGas method")
//			},
//			PendingNonceAtFunc: func(contextMoqParam context.Context, address common.Address) (uint64, error) {
//				panic("mock out the PendingNonceAt method")
//			},
//			SuggestGasPriceFunc: func(contextMoqParam context.Context) (*big.Int, error) {
//				panic("mock out the SuggestGasPrice method")
//			},
//			TransactionByHashFunc: func(ctx context.Context, hash common.Hash) (*types.Transaction, bool, error) {
//				panic("mock out the TransactionByHash method")
//			},
//		}
//
//		// use mockedEthereumClient in code that requires ethrpc.EthereumClient
//		// and then make assertions.
//
//	}
type EthereumClientMock struct {
	// CallContractFunc mocks the CallContract method.
	CallContractFunc func(ctx context.Context, msg ethereum.CallMsg, blockNumber *big.Int) ([]byte, error)

	// ChainIDFunc mocks the ChainID method.
	ChainIDFunc func(contextMoqParam context.Context) (*big.Int, error)

	// EstimateGasFunc mocks the EstimateGas method.
	EstimateGasFunc func(ctx context.Context, msg ethereum.CallMsg) (uint64, error)

	// PendingNonceAtFunc mocks the PendingNonceAt method.
	PendingNonceAtFunc func(contextMoqParam context.Context, address common.Address) (uint64, error)

	// SuggestGasPriceFunc mocks the SuggestGasPrice method.
	SuggestGasPriceFunc func(contextMoqParam context.Context) (*big.Int, error)

	// TransactionByHashFunc mocks the TransactionByHash method.
	TransactionByHashFunc func(ctx context.Context, hash common.Hash) (*types.Transaction, bool, error)

	// calls tracks calls to the methods.
	calls struct {
		// CallContract holds details about calls to the CallContract method.
		CallContract []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Msg is the msg argument value.
			Msg ethereum.CallMsg
			// BlockNumber is the blockNumber argument value.
			BlockNumber *big.Int
		}
		// ChainID holds details about calls to the ChainID method.
		ChainID []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
		}
		// EstimateGas holds details about calls to the EstimateGas method.
		EstimateGas []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Msg is the msg argument value.
			Msg ethereum.CallMsg
		}
		// PendingNonceAt holds details about calls to the PendingNonceAt method.
		PendingNonceAt []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// Address is the address argument value.
			Address common.Address
		}
		// SuggestGasPrice holds details about calls to the SuggestGasPrice method.
		SuggestGasPrice []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
		}
		// TransactionByHash holds details about calls to the TransactionByHash method.
		TransactionByHash []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Hash is the hash argument value.
			Hash common.Hash
		}
	}
	lockCallContract      sync.RWMutex
	lockChainID           sync.RWMutex
	lockEstimateGas       sync.RWMutex
	lockPendingNonceAt    sync.RWMutex
	lockSuggestGasPrice   sync.RWMutex
	lockTransactionByHash sync.RWMutex
}

// CallContract calls CallContractFunc.
func (mock *EthereumClientMock) CallContract(ctx context.Context, msg ethereum.CallMsg, blockNumber *big.Int) ([]byte, error) {
	if mock.CallContractFunc == nil {
		panic("EthereumClientMock.CallContractFunc: method is nil but EthereumClient.CallContract was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		Msg         ethereum.CallMsg
		BlockNumber *big.Int
	}{
		Ctx:         ctx,
		Msg:         msg,
		BlockNumber: blockNumber,
	}
	mock.lockCallContract.Lock()
	mock.calls.CallContract = append(mock.calls.CallContract, callInfo)
	mock.lockCallContract.Unlock()
	return mock.CallContractFunc(ctx, msg, blockNumber)
}

// CallContractCalls gets all the calls that were made to CallContract.
// Check the length with:
//
//	len(mockedEthereumClient.CallContractCalls())
func (mock *EthereumClientMock) CallContractCalls() []struct {
	Ctx         context.Context
	Msg         ethereum.CallMsg
	BlockNumber *big.Int
} {
	var calls []struct {
		Ctx         context.Context
		Msg         ethereum.CallMsg
		BlockNumber *big.Int
	}
	mock.lockCallContract.RLock()
	calls = mock.calls.CallContract
	mock.lockCallContract.RUnlock()
	return calls
}

// ChainID calls ChainIDFunc.
func (mock *EthereumClientMock) ChainID(contextMoqParam context.Context) (*big.Int, error) {
	if mock.ChainIDFunc == nil {
		panic("EthereumClientMock.ChainIDFunc: method is nil but EthereumClient.ChainID was just called")
	}
	callInfo := struct {
		ContextMoqParam context.Context
	}{
		ContextMoqParam: contextMoqParam,
	}
	mock.lockChainID.Lock()
	mock.calls.ChainID = append(mock.calls.ChainID, callInfo)
	mock.lockChainID.Unlock()
	return mock.ChainIDFunc(contextMoqParam)
}

// ChainIDCalls gets all the calls that were made to ChainID.
// Check the length with:
//
//	len(mockedEthereumClient.ChainIDCalls())
func (mock *EthereumClientMock) ChainIDCalls() []struct {
	ContextMoqParam context.Context
} {
	var calls []struct {
		ContextMoqParam context.Context
	}
	mock.lockChainID.RLock()
	calls = mock.calls.ChainID
	mock.lockChainID.RUnlock()
	return calls
}

// EstimateGas calls EstimateGasFunc.
func (mock *EthereumClientMock) EstimateGas(ctx context.Context, msg ethereum.CallMsg) (uint64, error) {
	if mock.EstimateGasFunc == nil {
		panic("EthereumClientMock.EstimateGasFunc: method is nil but EthereumClient.EstimateGas was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Msg ethereum.CallMsg
	}{
		Ctx: ctx,
		Msg: msg,
	}
	mock.lockEstimateGas.Lock()
	mock.calls.EstimateGas = append(mock.calls.EstimateGas, callInfo)
	mock.lockEstimateGas.Unlock()
	return mock.EstimateGasFunc(ctx, msg)
}

// EstimateGasCalls gets all the calls that were made to EstimateGas.
// Check the length with:
//
//	len(mockedEthereumClient.EstimateGasCalls())
func (mock *EthereumClientMock) EstimateGasCalls() []struct {
	Ctx context.Context
	Msg ethereum.CallMsg
} {
	var calls []struct {
		Ctx context.Context
		Msg ethereum.CallMsg
	}
	mock.lockEstimateGas.RLock()
	calls = mock.calls.EstimateGas
	mock.lockEstimateGas.RUnlock()
	return calls
}

// PendingNonceAt calls PendingNonceAtFunc.
func (mock *EthereumClientMock) PendingNonceAt(contextMoqParam context.Context, address common.Address) (uint64, error) {
	if mock.PendingNonceAtFunc == nil {
		panic("EthereumClientMock.PendingNonceAtFunc: method is nil but EthereumClient.PendingNonceAt was just called")
	}
	callInfo := struct {
		ContextMoqParam context.Context
		Address         common.Address
	}{
		ContextMoqParam: contextMoqParam,
		Address:         address,
	}
	mock.lockPendingNonceAt.Lock()
	mock.calls.PendingNonceAt = append(mock.calls.PendingNonceAt, callInfo)
	mock.lockPendingNonceAt.Unlock()
	return mock.PendingNonceAtFunc(contextMoqParam, address)
}

// PendingNonceAtCalls gets all the calls that were made to PendingNonceAt.
// Check the length with:
//
//	len(mockedEthereumClient.PendingNonceAtCalls())
func (mock *EthereumClientMock) PendingNonceAtCalls() []struct {
	ContextMoqParam context.Context
	Address         common.Address
} {
	var calls []struct {
		ContextMoqParam context.Context
		Address         common.Address
	}
	mock.lockPendingNonceAt.RLock()
	calls = mock.calls.PendingNonceAt
	mock.lockPendingNonceAt.RUnlock()
	return calls
}

// SuggestGasPrice calls SuggestGasPriceFunc.
func (mock *EthereumClientMock) SuggestGasPrice(contextMoqParam context.Context) (*big.Int, error) {
	if mock.SuggestGasPriceFunc == nil {
		panic("EthereumClientMock.SuggestGasPriceFunc: method is nil but EthereumClient.SuggestGasPrice was just called")
	}
	callInfo := struct {
		ContextMoqParam context.Context
	}{
		ContextMoqParam: contextMoqParam,
	}
	mock.lockSuggestGasPrice.Lock()
	mock.calls.SuggestGasPrice = append(mock.calls.SuggestGasPrice, callInfo)
	mock.lockSuggestGasPrice.Unlock()
	return mock.SuggestGasPriceFunc(contextMoqParam)
}

// SuggestGasPriceCalls gets all the calls that were made to SuggestGasPrice.
// Check the length with:
//
//	len(mockedEthereumClient.SuggestGasPriceCalls())
func (mock *EthereumClientMock) SuggestGasPriceCalls() []struct {
	ContextMoqParam context.Context
} {
	var calls []struct {
		ContextMoqParam context.Context
	}
	mock.lockSuggestGasPrice.RLock()
	calls = mock.calls.SuggestGasPrice
	mock.lockSuggestGasPrice.RUnlock()
	return calls
}

// TransactionByHash calls TransactionByHashFunc.
func (mock *EthereumClientMock) TransactionByHash(ctx context.Context, hash common.Hash) (*types.Transaction, bool, error) {
	if mock.TransactionByHashFunc == nil {
		panic("EthereumClientMock.TransactionByHashFunc: method is nil but EthereumClient.TransactionByHash was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Hash common.Hash
	}{
		Ctx:  ctx,
		Hash: hash,
	}
	mock.lockTransactionByHash.Lock()
	mock.calls.TransactionByHash = append(mock.calls.TransactionByHash, callInfo)
	mock.lockTransactionByHash.Unlock()
	return mock.TransactionByHashFunc(ctx, hash)
}

// TransactionByHashCalls gets all the calls that were made to TransactionByHash.
// Check the length with:
//
//	len(mockedEthereumClient.TransactionByHashCalls())
func (mock *EthereumClientMock) TransactionByHashCalls() []struct {
	Ctx  context.Context
	Hash common.Hash
} {
	var calls []struct {
		Ctx  context.Context
		Hash common.Hash
	}
	mock.lockTransactionByHash.RLock()
	calls = mock.calls.TransactionByHash
	mock.lockTransactionByHash.RUnlock()
	return calls
}

// Ensure, that RPCClientMock does implement ethrpc.RPCClient.
// If this is not the case, regenerate this file with moq.
var _ ethrpc.RPCClient = &RPCClientMock{}

// RPCClientMock is a mock implementation of ethrpc.RPCClient.
//
//	func TestSomethingThatUsesRPCClient(t *testing.T) {
//
//		// make and configure a mocked ethrpc.RPCClient
//		mockedRPCClient := &RPCClientMock{
//			BatchCallContextFunc: func(contextMoqParam context.Context, batchElems []rpc.BatchElem) error {
//				panic("mock out the BatchCallContext method")
//			},
//		}
//
//		// use mockedRPCClient in code that requires ethrpc.RPCClient
//		// and then make assertions.
//
//	}
type RPCClientMock struct {
	// BatchCallContextFunc mocks the BatchCallContext method.
	BatchCallContextFunc func(contextMoqParam context.Context, batchElems []rpc.BatchElem) error

	// calls tracks calls to the methods.
	calls struct {
		// BatchCallContext holds details about calls to the BatchCallContext method.
		BatchCallContext []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// BatchElems is the batchElems argument value.
			BatchElems []rpc.BatchElem
		}
	}
	lockBatchCallContext sync.RWMutex
}

// BatchCallContext calls BatchCallContextFunc.
func (mock *RPCClientMock) BatchCallContext(contextMoqParam context.Context, batchElems []rpc.BatchElem) error {
	if mock.BatchCallContextFunc == nil {
		panic("RPCClientMock.BatchCallContextFunc: method is nil but RPCClient.BatchCallContext was just called")
	}
	callInfo := struct {
		ContextMoqParam context.Context
		BatchElems      []rpc.BatchElem
	}{
		ContextMoqParam: contextMoqParam,
		BatchElems:      batchElems,
	}
	mock.lockBatchCallContext.Lock()
	mock.calls.BatchCallContext = append(mock.calls.BatchCallContext, callInfo)
	mock.lockBatchCallContext.Unlock()
	return mock.BatchCallContextFunc(contextMoqParam, batchElems)
}

// BatchCallContextCalls gets all the calls that were made to BatchCallContext.
// Check the length with:
//
//	len(mockedRPCClient.BatchCallContextCalls())
func (mock *RPCClientMock) BatchCallContextCalls() []struct {
	ContextMoqParam context.Context
	BatchElems      []rpc.BatchElem
} {
	var calls []struct {
		ContextMoqParam context.Context
		BatchElems      []rpc.BatchElem
	}
	mock.lockBatchCallContext.RLock()
	calls = mock.calls.BatchCallContext
	mock.lockBatchCallContext.RUnlock()
	return calls
}

// Ensure, that KeyQueueMock does implement ethrpc.KeyQueue.
// If this is not the case, regenerate this file with moq.
var _ ethrpc.KeyQueue = &KeyQueueMock{}

// KeyQueueMock is a mock implementation of ethrpc.KeyQueue.
//
//	func TestSomethingThatUsesKeyQueue(t *testing.T) {
//
//		// make and configure a mocked ethrpc.KeyQueue
//		mockedKeyQueue := &KeyQueueMock{
//			DequeueFunc: func(contextMoqParam context.Context) (*ecdsa.PrivateKey, error) {
//				panic("mock out the Dequeue method")
//			},
//			EnqueueFunc: func(privateKey *ecdsa.PrivateKey)  {
//				panic("mock out the Enqueue method")
//			},
//		}
//
//		// use mockedKeyQueue in code that requires ethrpc.KeyQueue
//		// and then make assertions.
//
//	}
type KeyQueueMock struct {
	// DequeueFunc mocks the Dequeue method.
	DequeueFunc func(contextMoqParam context.Context) (*ecdsa.PrivateKey, error)

	// EnqueueFunc mocks the Enqueue method.
	EnqueueFunc func(privateKey *ecdsa.PrivateKey)

	// calls tracks calls to the methods.
	calls struct {
		// Dequeue holds details about calls to the Dequeue method.
		Dequeue []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
		}
		// Enqueue holds details about calls to the Enqueue method.
		Enqueue []struct {
			// PrivateKey is the privateKey argument value.
			PrivateKey *ecdsa.PrivateKey
		}
	}
	lockDequeue sync.RWMutex
	lockEnqueue sync.RWMutex
}

// Dequeue calls DequeueFunc.
func (mock *KeyQueueMock) Dequeue(contextMoqParam context.Context) (*ecdsa.PrivateKey, error) {
	if mock.DequeueFunc == nil {
		panic("KeyQueueMock.DequeueFunc: method is nil but KeyQueue.Dequeue was just called")
	}
	callInfo := struct {
		ContextMoqParam context.Context
	}{
		ContextMoqParam: contextMoqParam,
	}
	mock.lockDequeue.Lock()
	mock.calls.Dequeue = append(mock.calls.Dequeue, callInfo)
	mock.lockDequeue.Unlock()
	return mock.DequeueFunc(contextMoqParam)
}

// DequeueCalls gets all the calls that were made to Dequeue.
// Check the length with:
//
//	len(mockedKeyQueue.DequeueCalls())
func (mock *KeyQueueMock) DequeueCalls() []struct {
	ContextMoqParam context.Context
} {
	var calls []struct {
		ContextMoqParam context.Context
	}
	mock.lockDequeue.RLock()
	calls = mock.calls.Dequeue
	mock.lockDequeue.RUnlock()
	return calls
}

// Enqueue calls EnqueueFunc.
func (mock *KeyQueueMock) Enqueue(privateKey *ecdsa.PrivateKey) {
	if mock.EnqueueFunc == nil {
		panic("KeyQueueMock.EnqueueFunc: method is nil but KeyQueue.Enqueue was just called")
	}
	callInfo := struct {
		PrivateKey *ecdsa.PrivateKey
	}{
		PrivateKey: privateKey,
	}
	mock.lockEnqueue.Lock()
	mock.calls.Enqueue = append(mock.calls.Enqueue, callInfo)
	mock.lockEnqueue.Unlock()
	mock.EnqueueFunc(privateKey)
}

// EnqueueCalls gets all the calls that were made to Enqueue.
// Check the length with:
//
//	len(mockedKeyQueue.EnqueueCalls())
func (mock *KeyQueueMock) EnqueueCalls() []struct {
	PrivateKey *ecdsa.PrivateKey
} {
	var calls []struct {
		PrivateKey *ecdsa.PrivateKey
	}
	mock.lockEnqueue.RLock()
	calls = mock.calls.Enqueue
	mock.lockEnqueue.RUnlock()
	return calls
}
