// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package proofgen_test

import (
	"context"
	"github.com/ethereum/go-ethereum/common"
	"github.com/ethereum/go-ethereum/core/types"
	"github.com/raylsnetwork/rayls-sovereign-relayer/private-relayer/proofgen"
	"sync"
)

// Ensure, that EthereumClientMock does implement proofgen.EthereumClient.
// If this is not the case, regenerate this file with moq.
var _ proofgen.EthereumClient = &EthereumClientMock{}

// EthereumClientMock is a mock implementation of proofgen.EthereumClient.
//
//	func TestSomethingThatUsesEthereumClient(t *testing.T) {
//
//		// make and configure a mocked proofgen.EthereumClient
//		mockedEthereumClient := &EthereumClientMock{
//			BlockByHashFunc: func(contextMoqParam context.Context, hash common.Hash) (*types.Block, error) {
//				panic("mock out the BlockByHash method")
//			},
//			TransactionReceiptFunc: func(contextMoqParam context.Context, hash common.Hash) (*types.Receipt, error) {
//				panic("mock out the TransactionReceipt method")
//			},
//		}
//
//		// use mockedEthereumClient in code that requires proofgen.EthereumClient
//		// and then make assertions.
//
//	}
type EthereumClientMock struct {
	// BlockByHashFunc mocks the BlockByHash method.
	BlockByHashFunc func(contextMoqParam context.Context, hash common.Hash) (*types.Block, error)

	// TransactionReceiptFunc mocks the TransactionReceipt method.
	TransactionReceiptFunc func(contextMoqParam context.Context, hash common.Hash) (*types.Receipt, error)

	// calls tracks calls to the methods.
	calls struct {
		// BlockByHash holds details about calls to the BlockByHash method.
		BlockByHash []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// Hash is the hash argument value.
			Hash common.Hash
		}
		// TransactionReceipt holds details about calls to the TransactionReceipt method.
		TransactionReceipt []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// Hash is the hash argument value.
			Hash common.Hash
		}
	}
	lockBlockByHash        sync.RWMutex
	lockTransactionReceipt sync.RWMutex
}

// BlockByHash calls BlockByHashFunc.
func (mock *EthereumClientMock) BlockByHash(contextMoqParam context.Context, hash common.Hash) (*types.Block, error) {
	if mock.BlockByHashFunc == nil {
		panic("EthereumClientMock.BlockByHashFunc: method is nil but EthereumClient.BlockByHash was just called")
	}
	callInfo := struct {
		ContextMoqParam context.Context
		Hash            common.Hash
	}{
		ContextMoqParam: contextMoqParam,
		Hash:            hash,
	}
	mock.lockBlockByHash.Lock()
	mock.calls.BlockByHash = append(mock.calls.BlockByHash, callInfo)
	mock.lockBlockByHash.Unlock()
	return mock.BlockByHashFunc(contextMoqParam, hash)
}

// BlockByHashCalls gets all the calls that were made to BlockByHash.
// Check the length with:
//
//	len(mockedEthereumClient.BlockByHashCalls())
func (mock *EthereumClientMock) BlockByHashCalls() []struct {
	ContextMoqParam context.Context
	Hash            common.Hash
} {
	var calls []struct {
		ContextMoqParam context.Context
		Hash            common.Hash
	}
	mock.lockBlockByHash.RLock()
	calls = mock.calls.BlockByHash
	mock.lockBlockByHash.RUnlock()
	return calls
}

// TransactionReceipt calls TransactionReceiptFunc.
func (mock *EthereumClientMock) TransactionReceipt(contextMoqParam context.Context, hash common.Hash) (*types.Receipt, error) {
	if mock.TransactionReceiptFunc == nil {
		panic("EthereumClientMock.TransactionReceiptFunc: method is nil but EthereumClient.TransactionReceipt was just called")
	}
	callInfo := struct {
		ContextMoqParam context.Context
		Hash            common.Hash
	}{
		ContextMoqParam: contextMoqParam,
		Hash:            hash,
	}
	mock.lockTransactionReceipt.Lock()
	mock.calls.TransactionReceipt = append(mock.calls.TransactionReceipt, callInfo)
	mock.lockTransactionReceipt.Unlock()
	return mock.TransactionReceiptFunc(contextMoqParam, hash)
}

// TransactionReceiptCalls gets all the calls that were made to TransactionReceipt.
// Check the length with:
//
//	len(mockedEthereumClient.TransactionReceiptCalls())
func (mock *EthereumClientMock) TransactionReceiptCalls() []struct {
	ContextMoqParam context.Context
	Hash            common.Hash
} {
	var calls []struct {
		ContextMoqParam context.Context
		Hash            common.Hash
	}
	mock.lockTransactionReceipt.RLock()
	calls = mock.calls.TransactionReceipt
	mock.lockTransactionReceipt.RUnlock()
	return calls
}
