// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package service_test

import (
	"context"
	keyspb "github.com/raylsnetwork/rayls-sovereign-relayer/cts/gen/proto/keys"
	"github.com/raylsnetwork/rayls-sovereign-relayer/dvp"
	merkle "github.com/raylsnetwork/rayls-sovereign-relayer/merkle-service"
	"github.com/raylsnetwork/rayls-sovereign-relayer/types"
	"google.golang.org/grpc"
	"math/big"
	"sync"
)

// proofMerkleClientMock is a mock implementation of service.proofMerkleClient.
//
//	func TestSomethingThatUsesproofMerkleClient(t *testing.T) {
//
//		// make and configure a mocked service.proofMerkleClient
//		mockedproofMerkleClient := &proofMerkleClientMock{
//			GenerateMerkleProofFunc: func(ctx context.Context, commitment *big.Int, treeNumber int, tokenAddress string) (*merkle.MerkleProof, error) {
//				panic("mock out the GenerateMerkleProof method")
//			},
//		}
//
//		// use mockedproofMerkleClient in code that requires service.proofMerkleClient
//		// and then make assertions.
//
//	}
type proofMerkleClientMock struct {
	// GenerateMerkleProofFunc mocks the GenerateMerkleProof method.
	GenerateMerkleProofFunc func(ctx context.Context, commitment *big.Int, treeNumber int, tokenAddress string) (*merkle.MerkleProof, error)

	// calls tracks calls to the methods.
	calls struct {
		// GenerateMerkleProof holds details about calls to the GenerateMerkleProof method.
		GenerateMerkleProof []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Commitment is the commitment argument value.
			Commitment *big.Int
			// TreeNumber is the treeNumber argument value.
			TreeNumber int
			// TokenAddress is the tokenAddress argument value.
			TokenAddress string
		}
	}
	lockGenerateMerkleProof sync.RWMutex
}

// GenerateMerkleProof calls GenerateMerkleProofFunc.
func (mock *proofMerkleClientMock) GenerateMerkleProof(ctx context.Context, commitment *big.Int, treeNumber int, tokenAddress string) (*merkle.MerkleProof, error) {
	if mock.GenerateMerkleProofFunc == nil {
		panic("proofMerkleClientMock.GenerateMerkleProofFunc: method is nil but proofMerkleClient.GenerateMerkleProof was just called")
	}
	callInfo := struct {
		Ctx          context.Context
		Commitment   *big.Int
		TreeNumber   int
		TokenAddress string
	}{
		Ctx:          ctx,
		Commitment:   commitment,
		TreeNumber:   treeNumber,
		TokenAddress: tokenAddress,
	}
	mock.lockGenerateMerkleProof.Lock()
	mock.calls.GenerateMerkleProof = append(mock.calls.GenerateMerkleProof, callInfo)
	mock.lockGenerateMerkleProof.Unlock()
	return mock.GenerateMerkleProofFunc(ctx, commitment, treeNumber, tokenAddress)
}

// GenerateMerkleProofCalls gets all the calls that were made to GenerateMerkleProof.
// Check the length with:
//
//	len(mockedproofMerkleClient.GenerateMerkleProofCalls())
func (mock *proofMerkleClientMock) GenerateMerkleProofCalls() []struct {
	Ctx          context.Context
	Commitment   *big.Int
	TreeNumber   int
	TokenAddress string
} {
	var calls []struct {
		Ctx          context.Context
		Commitment   *big.Int
		TreeNumber   int
		TokenAddress string
	}
	mock.lockGenerateMerkleProof.RLock()
	calls = mock.calls.GenerateMerkleProof
	mock.lockGenerateMerkleProof.RUnlock()
	return calls
}

// proofKeysClientMock is a mock implementation of service.proofKeysClient.
//
//	func TestSomethingThatUsesproofKeysClient(t *testing.T) {
//
//		// make and configure a mocked service.proofKeysClient
//		mockedproofKeysClient := &proofKeysClientMock{
//			GetPaymentSpendKeyFunc: func(ctx context.Context, in *keyspb.GetPaymentSpendKeyRequest, opts ...grpc.CallOption) (*keyspb.PaymentSpendKeyResponse, error) {
//				panic("mock out the GetPaymentSpendKey method")
//			},
//		}
//
//		// use mockedproofKeysClient in code that requires service.proofKeysClient
//		// and then make assertions.
//
//	}
type proofKeysClientMock struct {
	// GetPaymentSpendKeyFunc mocks the GetPaymentSpendKey method.
	GetPaymentSpendKeyFunc func(ctx context.Context, in *keyspb.GetPaymentSpendKeyRequest, opts ...grpc.CallOption) (*keyspb.PaymentSpendKeyResponse, error)

	// calls tracks calls to the methods.
	calls struct {
		// GetPaymentSpendKey holds details about calls to the GetPaymentSpendKey method.
		GetPaymentSpendKey []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// In is the in argument value.
			In *keyspb.GetPaymentSpendKeyRequest
			// Opts is the opts argument value.
			Opts []grpc.CallOption
		}
	}
	lockGetPaymentSpendKey sync.RWMutex
}

// GetPaymentSpendKey calls GetPaymentSpendKeyFunc.
func (mock *proofKeysClientMock) GetPaymentSpendKey(ctx context.Context, in *keyspb.GetPaymentSpendKeyRequest, opts ...grpc.CallOption) (*keyspb.PaymentSpendKeyResponse, error) {
	if mock.GetPaymentSpendKeyFunc == nil {
		panic("proofKeysClientMock.GetPaymentSpendKeyFunc: method is nil but proofKeysClient.GetPaymentSpendKey was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		In   *keyspb.GetPaymentSpendKeyRequest
		Opts []grpc.CallOption
	}{
		Ctx:  ctx,
		In:   in,
		Opts: opts,
	}
	mock.lockGetPaymentSpendKey.Lock()
	mock.calls.GetPaymentSpendKey = append(mock.calls.GetPaymentSpendKey, callInfo)
	mock.lockGetPaymentSpendKey.Unlock()
	return mock.GetPaymentSpendKeyFunc(ctx, in, opts...)
}

// GetPaymentSpendKeyCalls gets all the calls that were made to GetPaymentSpendKey.
// Check the length with:
//
//	len(mockedproofKeysClient.GetPaymentSpendKeyCalls())
func (mock *proofKeysClientMock) GetPaymentSpendKeyCalls() []struct {
	Ctx  context.Context
	In   *keyspb.GetPaymentSpendKeyRequest
	Opts []grpc.CallOption
} {
	var calls []struct {
		Ctx  context.Context
		In   *keyspb.GetPaymentSpendKeyRequest
		Opts []grpc.CallOption
	}
	mock.lockGetPaymentSpendKey.RLock()
	calls = mock.calls.GetPaymentSpendKey
	mock.lockGetPaymentSpendKey.RUnlock()
	return calls
}

// proofAPIClientMock is a mock implementation of service.proofAPIClient.
//
//	func TestSomethingThatUsesproofAPIClient(t *testing.T) {
//
//		// make and configure a mocked service.proofAPIClient
//		mockedproofAPIClient := &proofAPIClientMock{
//			CreateEnygmaJSProofFunc: func(req *dvp.EnygmaJoinSplitProofRequest) (dvp.Proof, error) {
//				panic("mock out the CreateEnygmaJSProof method")
//			},
//			CreateErc1155JSProofFunc: func(req *dvp.ERC1155JoinSplitProofRequest) (dvp.Proof, error) {
//				panic("mock out the CreateErc1155JSProof method")
//			},
//			CreateErc721OwnershipProofFunc: func(req *dvp.ERC721OwnershipProofRequest) (dvp.Proof, error) {
//				panic("mock out the CreateErc721OwnershipProof method")
//			},
//		}
//
//		// use mockedproofAPIClient in code that requires service.proofAPIClient
//		// and then make assertions.
//
//	}
type proofAPIClientMock struct {
	// CreateEnygmaJSProofFunc mocks the CreateEnygmaJSProof method.
	CreateEnygmaJSProofFunc func(req *dvp.EnygmaJoinSplitProofRequest) (dvp.Proof, error)

	// CreateErc1155JSProofFunc mocks the CreateErc1155JSProof method.
	CreateErc1155JSProofFunc func(req *dvp.ERC1155JoinSplitProofRequest) (dvp.Proof, error)

	// CreateErc721OwnershipProofFunc mocks the CreateErc721OwnershipProof method.
	CreateErc721OwnershipProofFunc func(req *dvp.ERC721OwnershipProofRequest) (dvp.Proof, error)

	// calls tracks calls to the methods.
	calls struct {
		// CreateEnygmaJSProof holds details about calls to the CreateEnygmaJSProof method.
		CreateEnygmaJSProof []struct {
			// Req is the req argument value.
			Req *dvp.EnygmaJoinSplitProofRequest
		}
		// CreateErc1155JSProof holds details about calls to the CreateErc1155JSProof method.
		CreateErc1155JSProof []struct {
			// Req is the req argument value.
			Req *dvp.ERC1155JoinSplitProofRequest
		}
		// CreateErc721OwnershipProof holds details about calls to the CreateErc721OwnershipProof method.
		CreateErc721OwnershipProof []struct {
			// Req is the req argument value.
			Req *dvp.ERC721OwnershipProofRequest
		}
	}
	lockCreateEnygmaJSProof        sync.RWMutex
	lockCreateErc1155JSProof       sync.RWMutex
	lockCreateErc721OwnershipProof sync.RWMutex
}

// CreateEnygmaJSProof calls CreateEnygmaJSProofFunc.
func (mock *proofAPIClientMock) CreateEnygmaJSProof(req *dvp.EnygmaJoinSplitProofRequest) (dvp.Proof, error) {
	if mock.CreateEnygmaJSProofFunc == nil {
		panic("proofAPIClientMock.CreateEnygmaJSProofFunc: method is nil but proofAPIClient.CreateEnygmaJSProof was just called")
	}
	callInfo := struct {
		Req *dvp.EnygmaJoinSplitProofRequest
	}{
		Req: req,
	}
	mock.lockCreateEnygmaJSProof.Lock()
	mock.calls.CreateEnygmaJSProof = append(mock.calls.CreateEnygmaJSProof, callInfo)
	mock.lockCreateEnygmaJSProof.Unlock()
	return mock.CreateEnygmaJSProofFunc(req)
}

// CreateEnygmaJSProofCalls gets all the calls that were made to CreateEnygmaJSProof.
// Check the length with:
//
//	len(mockedproofAPIClient.CreateEnygmaJSProofCalls())
func (mock *proofAPIClientMock) CreateEnygmaJSProofCalls() []struct {
	Req *dvp.EnygmaJoinSplitProofRequest
} {
	var calls []struct {
		Req *dvp.EnygmaJoinSplitProofRequest
	}
	mock.lockCreateEnygmaJSProof.RLock()
	calls = mock.calls.CreateEnygmaJSProof
	mock.lockCreateEnygmaJSProof.RUnlock()
	return calls
}

// CreateErc1155JSProof calls CreateErc1155JSProofFunc.
func (mock *proofAPIClientMock) CreateErc1155JSProof(req *dvp.ERC1155JoinSplitProofRequest) (dvp.Proof, error) {
	if mock.CreateErc1155JSProofFunc == nil {
		panic("proofAPIClientMock.CreateErc1155JSProofFunc: method is nil but proofAPIClient.CreateErc1155JSProof was just called")
	}
	callInfo := struct {
		Req *dvp.ERC1155JoinSplitProofRequest
	}{
		Req: req,
	}
	mock.lockCreateErc1155JSProof.Lock()
	mock.calls.CreateErc1155JSProof = append(mock.calls.CreateErc1155JSProof, callInfo)
	mock.lockCreateErc1155JSProof.Unlock()
	return mock.CreateErc1155JSProofFunc(req)
}

// CreateErc1155JSProofCalls gets all the calls that were made to CreateErc1155JSProof.
// Check the length with:
//
//	len(mockedproofAPIClient.CreateErc1155JSProofCalls())
func (mock *proofAPIClientMock) CreateErc1155JSProofCalls() []struct {
	Req *dvp.ERC1155JoinSplitProofRequest
} {
	var calls []struct {
		Req *dvp.ERC1155JoinSplitProofRequest
	}
	mock.lockCreateErc1155JSProof.RLock()
	calls = mock.calls.CreateErc1155JSProof
	mock.lockCreateErc1155JSProof.RUnlock()
	return calls
}

// CreateErc721OwnershipProof calls CreateErc721OwnershipProofFunc.
func (mock *proofAPIClientMock) CreateErc721OwnershipProof(req *dvp.ERC721OwnershipProofRequest) (dvp.Proof, error) {
	if mock.CreateErc721OwnershipProofFunc == nil {
		panic("proofAPIClientMock.CreateErc721OwnershipProofFunc: method is nil but proofAPIClient.CreateErc721OwnershipProof was just called")
	}
	callInfo := struct {
		Req *dvp.ERC721OwnershipProofRequest
	}{
		Req: req,
	}
	mock.lockCreateErc721OwnershipProof.Lock()
	mock.calls.CreateErc721OwnershipProof = append(mock.calls.CreateErc721OwnershipProof, callInfo)
	mock.lockCreateErc721OwnershipProof.Unlock()
	return mock.CreateErc721OwnershipProofFunc(req)
}

// CreateErc721OwnershipProofCalls gets all the calls that were made to CreateErc721OwnershipProof.
// Check the length with:
//
//	len(mockedproofAPIClient.CreateErc721OwnershipProofCalls())
func (mock *proofAPIClientMock) CreateErc721OwnershipProofCalls() []struct {
	Req *dvp.ERC721OwnershipProofRequest
} {
	var calls []struct {
		Req *dvp.ERC721OwnershipProofRequest
	}
	mock.lockCreateErc721OwnershipProof.RLock()
	calls = mock.calls.CreateErc721OwnershipProof
	mock.lockCreateErc721OwnershipProof.RUnlock()
	return calls
}

// proofDepositRepositoryMock is a mock implementation of service.proofDepositRepository.
//
//	func TestSomethingThatUsesproofDepositRepository(t *testing.T) {
//
//		// make and configure a mocked service.proofDepositRepository
//		mockedproofDepositRepository := &proofDepositRepositoryMock{
//			BatchUpsertNullifiersFunc: func(ctx context.Context, commitmentNullifierMap map[string]string) error {
//				panic("mock out the BatchUpsertNullifiers method")
//			},
//			CreateDepositFunc: func(ctx context.Context, deposit *types.DvpDeposit) error {
//				panic("mock out the CreateDeposit method")
//			},
//			GetDepositsByTokenFunc: func(ctx context.Context, tokenAddress string, tokenId string, tokenType types.DvpTokenType, userAddress string, status types.DvpDepositStatus) ([]types.DvpDeposit, error) {
//				panic("mock out the GetDepositsByToken method")
//			},
//			GetFungibleDepositsFunc: func(ctx context.Context, tokenAddress string, userAddress string, tokenType types.DvpTokenType, status types.DvpDepositStatus) ([]types.DvpDeposit, error) {
//				panic("mock out the GetFungibleDeposits method")
//			},
//			UpsertDepositNullifierFunc: func(ctx context.Context, commitment *big.Int, nullifier *big.Int) error {
//				panic("mock out the UpsertDepositNullifier method")
//			},
//		}
//
//		// use mockedproofDepositRepository in code that requires service.proofDepositRepository
//		// and then make assertions.
//
//	}
type proofDepositRepositoryMock struct {
	// BatchUpsertNullifiersFunc mocks the BatchUpsertNullifiers method.
	BatchUpsertNullifiersFunc func(ctx context.Context, commitmentNullifierMap map[string]string) error

	// CreateDepositFunc mocks the CreateDeposit method.
	CreateDepositFunc func(ctx context.Context, deposit *types.DvpDeposit) error

	// GetDepositsByTokenFunc mocks the GetDepositsByToken method.
	GetDepositsByTokenFunc func(ctx context.Context, tokenAddress string, tokenId string, tokenType types.DvpTokenType, userAddress string, status types.DvpDepositStatus) ([]types.DvpDeposit, error)

	// GetFungibleDepositsFunc mocks the GetFungibleDeposits method.
	GetFungibleDepositsFunc func(ctx context.Context, tokenAddress string, userAddress string, tokenType types.DvpTokenType, status types.DvpDepositStatus) ([]types.DvpDeposit, error)

	// UpsertDepositNullifierFunc mocks the UpsertDepositNullifier method.
	UpsertDepositNullifierFunc func(ctx context.Context, commitment *big.Int, nullifier *big.Int) error

	// calls tracks calls to the methods.
	calls struct {
		// BatchUpsertNullifiers holds details about calls to the BatchUpsertNullifiers method.
		BatchUpsertNullifiers []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// CommitmentNullifierMap is the commitmentNullifierMap argument value.
			CommitmentNullifierMap map[string]string
		}
		// CreateDeposit holds details about calls to the CreateDeposit method.
		CreateDeposit []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Deposit is the deposit argument value.
			Deposit *types.DvpDeposit
		}
		// GetDepositsByToken holds details about calls to the GetDepositsByToken method.
		GetDepositsByToken []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// TokenAddress is the tokenAddress argument value.
			TokenAddress string
			// TokenId is the tokenId argument value.
			TokenId string
			// TokenType is the tokenType argument value.
			TokenType types.DvpTokenType
			// UserAddress is the userAddress argument value.
			UserAddress string
			// Status is the status argument value.
			Status types.DvpDepositStatus
		}
		// GetFungibleDeposits holds details about calls to the GetFungibleDeposits method.
		GetFungibleDeposits []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// TokenAddress is the tokenAddress argument value.
			TokenAddress string
			// UserAddress is the userAddress argument value.
			UserAddress string
			// TokenType is the tokenType argument value.
			TokenType types.DvpTokenType
			// Status is the status argument value.
			Status types.DvpDepositStatus
		}
		// UpsertDepositNullifier holds details about calls to the UpsertDepositNullifier method.
		UpsertDepositNullifier []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Commitment is the commitment argument value.
			Commitment *big.Int
			// Nullifier is the nullifier argument value.
			Nullifier *big.Int
		}
	}
	lockBatchUpsertNullifiers  sync.RWMutex
	lockCreateDeposit          sync.RWMutex
	lockGetDepositsByToken     sync.RWMutex
	lockGetFungibleDeposits    sync.RWMutex
	lockUpsertDepositNullifier sync.RWMutex
}

// BatchUpsertNullifiers calls BatchUpsertNullifiersFunc.
func (mock *proofDepositRepositoryMock) BatchUpsertNullifiers(ctx context.Context, commitmentNullifierMap map[string]string) error {
	if mock.BatchUpsertNullifiersFunc == nil {
		panic("proofDepositRepositoryMock.BatchUpsertNullifiersFunc: method is nil but proofDepositRepository.BatchUpsertNullifiers was just called")
	}
	callInfo := struct {
		Ctx                    context.Context
		CommitmentNullifierMap map[string]string
	}{
		Ctx:                    ctx,
		CommitmentNullifierMap: commitmentNullifierMap,
	}
	mock.lockBatchUpsertNullifiers.Lock()
	mock.calls.BatchUpsertNullifiers = append(mock.calls.BatchUpsertNullifiers, callInfo)
	mock.lockBatchUpsertNullifiers.Unlock()
	return mock.BatchUpsertNullifiersFunc(ctx, commitmentNullifierMap)
}

// BatchUpsertNullifiersCalls gets all the calls that were made to BatchUpsertNullifiers.
// Check the length with:
//
//	len(mockedproofDepositRepository.BatchUpsertNullifiersCalls())
func (mock *proofDepositRepositoryMock) BatchUpsertNullifiersCalls() []struct {
	Ctx                    context.Context
	CommitmentNullifierMap map[string]string
} {
	var calls []struct {
		Ctx                    context.Context
		CommitmentNullifierMap map[string]string
	}
	mock.lockBatchUpsertNullifiers.RLock()
	calls = mock.calls.BatchUpsertNullifiers
	mock.lockBatchUpsertNullifiers.RUnlock()
	return calls
}

// CreateDeposit calls CreateDepositFunc.
func (mock *proofDepositRepositoryMock) CreateDeposit(ctx context.Context, deposit *types.DvpDeposit) error {
	if mock.CreateDepositFunc == nil {
		panic("proofDepositRepositoryMock.CreateDepositFunc: method is nil but proofDepositRepository.CreateDeposit was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		Deposit *types.DvpDeposit
	}{
		Ctx:     ctx,
		Deposit: deposit,
	}
	mock.lockCreateDeposit.Lock()
	mock.calls.CreateDeposit = append(mock.calls.CreateDeposit, callInfo)
	mock.lockCreateDeposit.Unlock()
	return mock.CreateDepositFunc(ctx, deposit)
}

// CreateDepositCalls gets all the calls that were made to CreateDeposit.
// Check the length with:
//
//	len(mockedproofDepositRepository.CreateDepositCalls())
func (mock *proofDepositRepositoryMock) CreateDepositCalls() []struct {
	Ctx     context.Context
	Deposit *types.DvpDeposit
} {
	var calls []struct {
		Ctx     context.Context
		Deposit *types.DvpDeposit
	}
	mock.lockCreateDeposit.RLock()
	calls = mock.calls.CreateDeposit
	mock.lockCreateDeposit.RUnlock()
	return calls
}

// GetDepositsByToken calls GetDepositsByTokenFunc.
func (mock *proofDepositRepositoryMock) GetDepositsByToken(ctx context.Context, tokenAddress string, tokenId string, tokenType types.DvpTokenType, userAddress string, status types.DvpDepositStatus) ([]types.DvpDeposit, error) {
	if mock.GetDepositsByTokenFunc == nil {
		panic("proofDepositRepositoryMock.GetDepositsByTokenFunc: method is nil but proofDepositRepository.GetDepositsByToken was just called")
	}
	callInfo := struct {
		Ctx          context.Context
		TokenAddress string
		TokenId      string
		TokenType    types.DvpTokenType
		UserAddress  string
		Status       types.DvpDepositStatus
	}{
		Ctx:          ctx,
		TokenAddress: tokenAddress,
		TokenId:      tokenId,
		TokenType:    tokenType,
		UserAddress:  userAddress,
		Status:       status,
	}
	mock.lockGetDepositsByToken.Lock()
	mock.calls.GetDepositsByToken = append(mock.calls.GetDepositsByToken, callInfo)
	mock.lockGetDepositsByToken.Unlock()
	return mock.GetDepositsByTokenFunc(ctx, tokenAddress, tokenId, tokenType, userAddress, status)
}

// GetDepositsByTokenCalls gets all the calls that were made to GetDepositsByToken.
// Check the length with:
//
//	len(mockedproofDepositRepository.GetDepositsByTokenCalls())
func (mock *proofDepositRepositoryMock) GetDepositsByTokenCalls() []struct {
	Ctx          context.Context
	TokenAddress string
	TokenId      string
	TokenType    types.DvpTokenType
	UserAddress  string
	Status       types.DvpDepositStatus
} {
	var calls []struct {
		Ctx          context.Context
		TokenAddress string
		TokenId      string
		TokenType    types.DvpTokenType
		UserAddress  string
		Status       types.DvpDepositStatus
	}
	mock.lockGetDepositsByToken.RLock()
	calls = mock.calls.GetDepositsByToken
	mock.lockGetDepositsByToken.RUnlock()
	return calls
}

// GetFungibleDeposits calls GetFungibleDepositsFunc.
func (mock *proofDepositRepositoryMock) GetFungibleDeposits(ctx context.Context, tokenAddress string, userAddress string, tokenType types.DvpTokenType, status types.DvpDepositStatus) ([]types.DvpDeposit, error) {
	if mock.GetFungibleDepositsFunc == nil {
		panic("proofDepositRepositoryMock.GetFungibleDepositsFunc: method is nil but proofDepositRepository.GetFungibleDeposits was just called")
	}
	callInfo := struct {
		Ctx          context.Context
		TokenAddress string
		UserAddress  string
		TokenType    types.DvpTokenType
		Status       types.DvpDepositStatus
	}{
		Ctx:          ctx,
		TokenAddress: tokenAddress,
		UserAddress:  userAddress,
		TokenType:    tokenType,
		Status:       status,
	}
	mock.lockGetFungibleDeposits.Lock()
	mock.calls.GetFungibleDeposits = append(mock.calls.GetFungibleDeposits, callInfo)
	mock.lockGetFungibleDeposits.Unlock()
	return mock.GetFungibleDepositsFunc(ctx, tokenAddress, userAddress, tokenType, status)
}

// GetFungibleDepositsCalls gets all the calls that were made to GetFungibleDeposits.
// Check the length with:
//
//	len(mockedproofDepositRepository.GetFungibleDepositsCalls())
func (mock *proofDepositRepositoryMock) GetFungibleDepositsCalls() []struct {
	Ctx          context.Context
	TokenAddress string
	UserAddress  string
	TokenType    types.DvpTokenType
	Status       types.DvpDepositStatus
} {
	var calls []struct {
		Ctx          context.Context
		TokenAddress string
		UserAddress  string
		TokenType    types.DvpTokenType
		Status       types.DvpDepositStatus
	}
	mock.lockGetFungibleDeposits.RLock()
	calls = mock.calls.GetFungibleDeposits
	mock.lockGetFungibleDeposits.RUnlock()
	return calls
}

// UpsertDepositNullifier calls UpsertDepositNullifierFunc.
func (mock *proofDepositRepositoryMock) UpsertDepositNullifier(ctx context.Context, commitment *big.Int, nullifier *big.Int) error {
	if mock.UpsertDepositNullifierFunc == nil {
		panic("proofDepositRepositoryMock.UpsertDepositNullifierFunc: method is nil but proofDepositRepository.UpsertDepositNullifier was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		Commitment *big.Int
		Nullifier  *big.Int
	}{
		Ctx:        ctx,
		Commitment: commitment,
		Nullifier:  nullifier,
	}
	mock.lockUpsertDepositNullifier.Lock()
	mock.calls.UpsertDepositNullifier = append(mock.calls.UpsertDepositNullifier, callInfo)
	mock.lockUpsertDepositNullifier.Unlock()
	return mock.UpsertDepositNullifierFunc(ctx, commitment, nullifier)
}

// UpsertDepositNullifierCalls gets all the calls that were made to UpsertDepositNullifier.
// Check the length with:
//
//	len(mockedproofDepositRepository.UpsertDepositNullifierCalls())
func (mock *proofDepositRepositoryMock) UpsertDepositNullifierCalls() []struct {
	Ctx        context.Context
	Commitment *big.Int
	Nullifier  *big.Int
} {
	var calls []struct {
		Ctx        context.Context
		Commitment *big.Int
		Nullifier  *big.Int
	}
	mock.lockUpsertDepositNullifier.RLock()
	calls = mock.calls.UpsertDepositNullifier
	mock.lockUpsertDepositNullifier.RUnlock()
	return calls
}

// proofCommitmentCalculatorMock is a mock implementation of service.proofCommitmentCalculator.
//
//	func TestSomethingThatUsesproofCommitmentCalculator(t *testing.T) {
//
//		// make and configure a mocked service.proofCommitmentCalculator
//		mockedproofCommitmentCalculator := &proofCommitmentCalculatorMock{
//			CalculateERC1155CommitmentFunc: func(spendPK *big.Int, salt *big.Int, tokenAddress string, tokenID string, tokenAmount *big.Int) (*big.Int, error) {
//				panic("mock out the CalculateERC1155Commitment method")
//			},
//			CalculateNFTCommitmentFunc: func(spendPK *big.Int, salt *big.Int, nftID string, nftAddress string) (*big.Int, error) {
//				panic("mock out the CalculateNFTCommitment method")
//			},
//			CalculatePaymentCommitmentFunc: func(spendPK *big.Int, salt *big.Int, paymentAmount *big.Int, tokenAddress string) (*big.Int, error) {
//				panic("mock out the CalculatePaymentCommitment method")
//			},
//			GetNFTUniqueIDFunc: func(nftAddress string, nftID string) (*big.Int, error) {
//				panic("mock out the GetNFTUniqueID method")
//			},
//		}
//
//		// use mockedproofCommitmentCalculator in code that requires service.proofCommitmentCalculator
//		// and then make assertions.
//
//	}
type proofCommitmentCalculatorMock struct {
	// CalculateERC1155CommitmentFunc mocks the CalculateERC1155Commitment method.
	CalculateERC1155CommitmentFunc func(spendPK *big.Int, salt *big.Int, tokenAddress string, tokenID string, tokenAmount *big.Int) (*big.Int, error)

	// CalculateNFTCommitmentFunc mocks the CalculateNFTCommitment method.
	CalculateNFTCommitmentFunc func(spendPK *big.Int, salt *big.Int, nftID string, nftAddress string) (*big.Int, error)

	// CalculatePaymentCommitmentFunc mocks the CalculatePaymentCommitment method.
	CalculatePaymentCommitmentFunc func(spendPK *big.Int, salt *big.Int, paymentAmount *big.Int, tokenAddress string) (*big.Int, error)

	// GetNFTUniqueIDFunc mocks the GetNFTUniqueID method.
	GetNFTUniqueIDFunc func(nftAddress string, nftID string) (*big.Int, error)

	// calls tracks calls to the methods.
	calls struct {
		// CalculateERC1155Commitment holds details about calls to the CalculateERC1155Commitment method.
		CalculateERC1155Commitment []struct {
			// SpendPK is the spendPK argument value.
			SpendPK *big.Int
			// Salt is the salt argument value.
			Salt *big.Int
			// TokenAddress is the tokenAddress argument value.
			TokenAddress string
			// TokenID is the tokenID argument value.
			TokenID string
			// TokenAmount is the tokenAmount argument value.
			TokenAmount *big.Int
		}
		// CalculateNFTCommitment holds details about calls to the CalculateNFTCommitment method.
		CalculateNFTCommitment []struct {
			// SpendPK is the spendPK argument value.
			SpendPK *big.Int
			// Salt is the salt argument value.
			Salt *big.Int
			// NftID is the nftID argument value.
			NftID string
			// NftAddress is the nftAddress argument value.
			NftAddress string
		}
		// CalculatePaymentCommitment holds details about calls to the CalculatePaymentCommitment method.
		CalculatePaymentCommitment []struct {
			// SpendPK is the spendPK argument value.
			SpendPK *big.Int
			// Salt is the salt argument value.
			Salt *big.Int
			// PaymentAmount is the paymentAmount argument value.
			PaymentAmount *big.Int
			// TokenAddress is the tokenAddress argument value.
			TokenAddress string
		}
		// GetNFTUniqueID holds details about calls to the GetNFTUniqueID method.
		GetNFTUniqueID []struct {
			// NftAddress is the nftAddress argument value.
			NftAddress string
			// NftID is the nftID argument value.
			NftID string
		}
	}
	lockCalculateERC1155Commitment sync.RWMutex
	lockCalculateNFTCommitment     sync.RWMutex
	lockCalculatePaymentCommitment sync.RWMutex
	lockGetNFTUniqueID             sync.RWMutex
}

// CalculateERC1155Commitment calls CalculateERC1155CommitmentFunc.
func (mock *proofCommitmentCalculatorMock) CalculateERC1155Commitment(spendPK *big.Int, salt *big.Int, tokenAddress string, tokenID string, tokenAmount *big.Int) (*big.Int, error) {
	if mock.CalculateERC1155CommitmentFunc == nil {
		panic("proofCommitmentCalculatorMock.CalculateERC1155CommitmentFunc: method is nil but proofCommitmentCalculator.CalculateERC1155Commitment was just called")
	}
	callInfo := struct {
		SpendPK      *big.Int
		Salt         *big.Int
		TokenAddress string
		TokenID      string
		TokenAmount  *big.Int
	}{
		SpendPK:      spendPK,
		Salt:         salt,
		TokenAddress: tokenAddress,
		TokenID:      tokenID,
		TokenAmount:  tokenAmount,
	}
	mock.lockCalculateERC1155Commitment.Lock()
	mock.calls.CalculateERC1155Commitment = append(mock.calls.CalculateERC1155Commitment, callInfo)
	mock.lockCalculateERC1155Commitment.Unlock()
	return mock.CalculateERC1155CommitmentFunc(spendPK, salt, tokenAddress, tokenID, tokenAmount)
}

// CalculateERC1155CommitmentCalls gets all the calls that were made to CalculateERC1155Commitment.
// Check the length with:
//
//	len(mockedproofCommitmentCalculator.CalculateERC1155CommitmentCalls())
func (mock *proofCommitmentCalculatorMock) CalculateERC1155CommitmentCalls() []struct {
	SpendPK      *big.Int
	Salt         *big.Int
	TokenAddress string
	TokenID      string
	TokenAmount  *big.Int
} {
	var calls []struct {
		SpendPK      *big.Int
		Salt         *big.Int
		TokenAddress string
		TokenID      string
		TokenAmount  *big.Int
	}
	mock.lockCalculateERC1155Commitment.RLock()
	calls = mock.calls.CalculateERC1155Commitment
	mock.lockCalculateERC1155Commitment.RUnlock()
	return calls
}

// CalculateNFTCommitment calls CalculateNFTCommitmentFunc.
func (mock *proofCommitmentCalculatorMock) CalculateNFTCommitment(spendPK *big.Int, salt *big.Int, nftID string, nftAddress string) (*big.Int, error) {
	if mock.CalculateNFTCommitmentFunc == nil {
		panic("proofCommitmentCalculatorMock.CalculateNFTCommitmentFunc: method is nil but proofCommitmentCalculator.CalculateNFTCommitment was just called")
	}
	callInfo := struct {
		SpendPK    *big.Int
		Salt       *big.Int
		NftID      string
		NftAddress string
	}{
		SpendPK:    spendPK,
		Salt:       salt,
		NftID:      nftID,
		NftAddress: nftAddress,
	}
	mock.lockCalculateNFTCommitment.Lock()
	mock.calls.CalculateNFTCommitment = append(mock.calls.CalculateNFTCommitment, callInfo)
	mock.lockCalculateNFTCommitment.Unlock()
	return mock.CalculateNFTCommitmentFunc(spendPK, salt, nftID, nftAddress)
}

// CalculateNFTCommitmentCalls gets all the calls that were made to CalculateNFTCommitment.
// Check the length with:
//
//	len(mockedproofCommitmentCalculator.CalculateNFTCommitmentCalls())
func (mock *proofCommitmentCalculatorMock) CalculateNFTCommitmentCalls() []struct {
	SpendPK    *big.Int
	Salt       *big.Int
	NftID      string
	NftAddress string
} {
	var calls []struct {
		SpendPK    *big.Int
		Salt       *big.Int
		NftID      string
		NftAddress string
	}
	mock.lockCalculateNFTCommitment.RLock()
	calls = mock.calls.CalculateNFTCommitment
	mock.lockCalculateNFTCommitment.RUnlock()
	return calls
}

// CalculatePaymentCommitment calls CalculatePaymentCommitmentFunc.
func (mock *proofCommitmentCalculatorMock) CalculatePaymentCommitment(spendPK *big.Int, salt *big.Int, paymentAmount *big.Int, tokenAddress string) (*big.Int, error) {
	if mock.CalculatePaymentCommitmentFunc == nil {
		panic("proofCommitmentCalculatorMock.CalculatePaymentCommitmentFunc: method is nil but proofCommitmentCalculator.CalculatePaymentCommitment was just called")
	}
	callInfo := struct {
		SpendPK       *big.Int
		Salt          *big.Int
		PaymentAmount *big.Int
		TokenAddress  string
	}{
		SpendPK:       spendPK,
		Salt:          salt,
		PaymentAmount: paymentAmount,
		TokenAddress:  tokenAddress,
	}
	mock.lockCalculatePaymentCommitment.Lock()
	mock.calls.CalculatePaymentCommitment = append(mock.calls.CalculatePaymentCommitment, callInfo)
	mock.lockCalculatePaymentCommitment.Unlock()
	return mock.CalculatePaymentCommitmentFunc(spendPK, salt, paymentAmount, tokenAddress)
}

// CalculatePaymentCommitmentCalls gets all the calls that were made to CalculatePaymentCommitment.
// Check the length with:
//
//	len(mockedproofCommitmentCalculator.CalculatePaymentCommitmentCalls())
func (mock *proofCommitmentCalculatorMock) CalculatePaymentCommitmentCalls() []struct {
	SpendPK       *big.Int
	Salt          *big.Int
	PaymentAmount *big.Int
	TokenAddress  string
} {
	var calls []struct {
		SpendPK       *big.Int
		Salt          *big.Int
		PaymentAmount *big.Int
		TokenAddress  string
	}
	mock.lockCalculatePaymentCommitment.RLock()
	calls = mock.calls.CalculatePaymentCommitment
	mock.lockCalculatePaymentCommitment.RUnlock()
	return calls
}

// GetNFTUniqueID calls GetNFTUniqueIDFunc.
func (mock *proofCommitmentCalculatorMock) GetNFTUniqueID(nftAddress string, nftID string) (*big.Int, error) {
	if mock.GetNFTUniqueIDFunc == nil {
		panic("proofCommitmentCalculatorMock.GetNFTUniqueIDFunc: method is nil but proofCommitmentCalculator.GetNFTUniqueID was just called")
	}
	callInfo := struct {
		NftAddress string
		NftID      string
	}{
		NftAddress: nftAddress,
		NftID:      nftID,
	}
	mock.lockGetNFTUniqueID.Lock()
	mock.calls.GetNFTUniqueID = append(mock.calls.GetNFTUniqueID, callInfo)
	mock.lockGetNFTUniqueID.Unlock()
	return mock.GetNFTUniqueIDFunc(nftAddress, nftID)
}

// GetNFTUniqueIDCalls gets all the calls that were made to GetNFTUniqueID.
// Check the length with:
//
//	len(mockedproofCommitmentCalculator.GetNFTUniqueIDCalls())
func (mock *proofCommitmentCalculatorMock) GetNFTUniqueIDCalls() []struct {
	NftAddress string
	NftID      string
} {
	var calls []struct {
		NftAddress string
		NftID      string
	}
	mock.lockGetNFTUniqueID.RLock()
	calls = mock.calls.GetNFTUniqueID
	mock.lockGetNFTUniqueID.RUnlock()
	return calls
}

// proofTxManagerMock is a mock implementation of service.proofTxManager.
//
//	func TestSomethingThatUsesproofTxManager(t *testing.T) {
//
//		// make and configure a mocked service.proofTxManager
//		mockedproofTxManager := &proofTxManagerMock{
//			WithTransactionFunc: func(ctx context.Context, fn func(ctx context.Context) error) error {
//				panic("mock out the WithTransaction method")
//			},
//		}
//
//		// use mockedproofTxManager in code that requires service.proofTxManager
//		// and then make assertions.
//
//	}
type proofTxManagerMock struct {
	// WithTransactionFunc mocks the WithTransaction method.
	WithTransactionFunc func(ctx context.Context, fn func(ctx context.Context) error) error

	// calls tracks calls to the methods.
	calls struct {
		// WithTransaction holds details about calls to the WithTransaction method.
		WithTransaction []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Fn is the fn argument value.
			Fn func(ctx context.Context) error
		}
	}
	lockWithTransaction sync.RWMutex
}

// WithTransaction calls WithTransactionFunc.
func (mock *proofTxManagerMock) WithTransaction(ctx context.Context, fn func(ctx context.Context) error) error {
	if mock.WithTransactionFunc == nil {
		panic("proofTxManagerMock.WithTransactionFunc: method is nil but proofTxManager.WithTransaction was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Fn  func(ctx context.Context) error
	}{
		Ctx: ctx,
		Fn:  fn,
	}
	mock.lockWithTransaction.Lock()
	mock.calls.WithTransaction = append(mock.calls.WithTransaction, callInfo)
	mock.lockWithTransaction.Unlock()
	return mock.WithTransactionFunc(ctx, fn)
}

// WithTransactionCalls gets all the calls that were made to WithTransaction.
// Check the length with:
//
//	len(mockedproofTxManager.WithTransactionCalls())
func (mock *proofTxManagerMock) WithTransactionCalls() []struct {
	Ctx context.Context
	Fn  func(ctx context.Context) error
} {
	var calls []struct {
		Ctx context.Context
		Fn  func(ctx context.Context) error
	}
	mock.lockWithTransaction.RLock()
	calls = mock.calls.WithTransaction
	mock.lockWithTransaction.RUnlock()
	return calls
}
