// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package resultrouter_test

import (
	"context"
	"github.com/raylsnetwork/rayls-sovereign-relayer/msgqueue"
	"github.com/raylsnetwork/rayls-sovereign-relayer/resultrouter"
	"github.com/raylsnetwork/rayls-sovereign-relayer/types"
	"sync"
)

// Ensure, that ConsumerMock does implement resultrouter.Consumer.
// If this is not the case, regenerate this file with moq.
var _ resultrouter.Consumer = &ConsumerMock{}

// ConsumerMock is a mock implementation of resultrouter.Consumer.
//
//	func TestSomethingThatUsesConsumer(t *testing.T) {
//
//		// make and configure a mocked resultrouter.Consumer
//		mockedConsumer := &ConsumerMock{
//			FetchFunc: func(ctx context.Context, count int) ([]msgqueue.Message[types.TxResult], error) {
//				panic("mock out the Fetch method")
//			},
//		}
//
//		// use mockedConsumer in code that requires resultrouter.Consumer
//		// and then make assertions.
//
//	}
type ConsumerMock struct {
	// FetchFunc mocks the Fetch method.
	FetchFunc func(ctx context.Context, count int) ([]msgqueue.Message[types.TxResult], error)

	// calls tracks calls to the methods.
	calls struct {
		// Fetch holds details about calls to the Fetch method.
		Fetch []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Count is the count argument value.
			Count int
		}
	}
	lockFetch sync.RWMutex
}

// Fetch calls FetchFunc.
func (mock *ConsumerMock) Fetch(ctx context.Context, count int) ([]msgqueue.Message[types.TxResult], error) {
	if mock.FetchFunc == nil {
		panic("ConsumerMock.FetchFunc: method is nil but Consumer.Fetch was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Count int
	}{
		Ctx:   ctx,
		Count: count,
	}
	mock.lockFetch.Lock()
	mock.calls.Fetch = append(mock.calls.Fetch, callInfo)
	mock.lockFetch.Unlock()
	return mock.FetchFunc(ctx, count)
}

// FetchCalls gets all the calls that were made to Fetch.
// Check the length with:
//
//	len(mockedConsumer.FetchCalls())
func (mock *ConsumerMock) FetchCalls() []struct {
	Ctx   context.Context
	Count int
} {
	var calls []struct {
		Ctx   context.Context
		Count int
	}
	mock.lockFetch.RLock()
	calls = mock.calls.Fetch
	mock.lockFetch.RUnlock()
	return calls
}

// Ensure, that HandlerMock does implement resultrouter.Handler.
// If this is not the case, regenerate this file with moq.
var _ resultrouter.Handler = &HandlerMock{}

// HandlerMock is a mock implementation of resultrouter.Handler.
//
//	func TestSomethingThatUsesHandler(t *testing.T) {
//
//		// make and configure a mocked resultrouter.Handler
//		mockedHandler := &HandlerMock{
//			HandleFunc: func(ctx context.Context, results []types.TxResult) error {
//				panic("mock out the Handle method")
//			},
//		}
//
//		// use mockedHandler in code that requires resultrouter.Handler
//		// and then make assertions.
//
//	}
type HandlerMock struct {
	// HandleFunc mocks the Handle method.
	HandleFunc func(ctx context.Context, results []types.TxResult) error

	// calls tracks calls to the methods.
	calls struct {
		// Handle holds details about calls to the Handle method.
		Handle []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Results is the results argument value.
			Results []types.TxResult
		}
	}
	lockHandle sync.RWMutex
}

// Handle calls HandleFunc.
func (mock *HandlerMock) Handle(ctx context.Context, results []types.TxResult) error {
	if mock.HandleFunc == nil {
		panic("HandlerMock.HandleFunc: method is nil but Handler.Handle was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		Results []types.TxResult
	}{
		Ctx:     ctx,
		Results: results,
	}
	mock.lockHandle.Lock()
	mock.calls.Handle = append(mock.calls.Handle, callInfo)
	mock.lockHandle.Unlock()
	return mock.HandleFunc(ctx, results)
}

// HandleCalls gets all the calls that were made to Handle.
// Check the length with:
//
//	len(mockedHandler.HandleCalls())
func (mock *HandlerMock) HandleCalls() []struct {
	Ctx     context.Context
	Results []types.TxResult
} {
	var calls []struct {
		Ctx     context.Context
		Results []types.TxResult
	}
	mock.lockHandle.RLock()
	calls = mock.calls.Handle
	mock.lockHandle.RUnlock()
	return calls
}
