// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package resync

import (
	"context"
	"github.com/ethereum/go-ethereum"
	ethTypes "github.com/ethereum/go-ethereum/core/types"
	"github.com/raylsnetwork/rayls-privacy-relayer-api/cts/gen/proto/encrypt"
	"github.com/raylsnetwork/rayls-privacy-relayer-api/types"
	"go.opentelemetry.io/otel/trace"
	"google.golang.org/grpc"
	"math/big"
	"sync"
)

// Ensure, that resourceLockRepositoryMock does implement resourceLockRepository.
// If this is not the case, regenerate this file with moq.
var _ resourceLockRepository = &resourceLockRepositoryMock{}

// resourceLockRepositoryMock is a mock implementation of resourceLockRepository.
//
//	func TestSomethingThatUsesresourceLockRepository(t *testing.T) {
//
//		// make and configure a mocked resourceLockRepository
//		mockedresourceLockRepository := &resourceLockRepositoryMock{
//			InsertNewLockFunc: func(ctx context.Context, resourceId string) error {
//				panic("mock out the InsertNewLock method")
//			},
//			RemoveLockFunc: func(ctx context.Context, resourceId string) error {
//				panic("mock out the RemoveLock method")
//			},
//		}
//
//		// use mockedresourceLockRepository in code that requires resourceLockRepository
//		// and then make assertions.
//
//	}
type resourceLockRepositoryMock struct {
	// InsertNewLockFunc mocks the InsertNewLock method.
	InsertNewLockFunc func(ctx context.Context, resourceId string) error

	// RemoveLockFunc mocks the RemoveLock method.
	RemoveLockFunc func(ctx context.Context, resourceId string) error

	// calls tracks calls to the methods.
	calls struct {
		// InsertNewLock holds details about calls to the InsertNewLock method.
		InsertNewLock []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ResourceId is the resourceId argument value.
			ResourceId string
		}
		// RemoveLock holds details about calls to the RemoveLock method.
		RemoveLock []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ResourceId is the resourceId argument value.
			ResourceId string
		}
	}
	lockInsertNewLock sync.RWMutex
	lockRemoveLock    sync.RWMutex
}

// InsertNewLock calls InsertNewLockFunc.
func (mock *resourceLockRepositoryMock) InsertNewLock(ctx context.Context, resourceId string) error {
	if mock.InsertNewLockFunc == nil {
		panic("resourceLockRepositoryMock.InsertNewLockFunc: method is nil but resourceLockRepository.InsertNewLock was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		ResourceId string
	}{
		Ctx:        ctx,
		ResourceId: resourceId,
	}
	mock.lockInsertNewLock.Lock()
	mock.calls.InsertNewLock = append(mock.calls.InsertNewLock, callInfo)
	mock.lockInsertNewLock.Unlock()
	return mock.InsertNewLockFunc(ctx, resourceId)
}

// InsertNewLockCalls gets all the calls that were made to InsertNewLock.
// Check the length with:
//
//	len(mockedresourceLockRepository.InsertNewLockCalls())
func (mock *resourceLockRepositoryMock) InsertNewLockCalls() []struct {
	Ctx        context.Context
	ResourceId string
} {
	var calls []struct {
		Ctx        context.Context
		ResourceId string
	}
	mock.lockInsertNewLock.RLock()
	calls = mock.calls.InsertNewLock
	mock.lockInsertNewLock.RUnlock()
	return calls
}

// RemoveLock calls RemoveLockFunc.
func (mock *resourceLockRepositoryMock) RemoveLock(ctx context.Context, resourceId string) error {
	if mock.RemoveLockFunc == nil {
		panic("resourceLockRepositoryMock.RemoveLockFunc: method is nil but resourceLockRepository.RemoveLock was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		ResourceId string
	}{
		Ctx:        ctx,
		ResourceId: resourceId,
	}
	mock.lockRemoveLock.Lock()
	mock.calls.RemoveLock = append(mock.calls.RemoveLock, callInfo)
	mock.lockRemoveLock.Unlock()
	return mock.RemoveLockFunc(ctx, resourceId)
}

// RemoveLockCalls gets all the calls that were made to RemoveLock.
// Check the length with:
//
//	len(mockedresourceLockRepository.RemoveLockCalls())
func (mock *resourceLockRepositoryMock) RemoveLockCalls() []struct {
	Ctx        context.Context
	ResourceId string
} {
	var calls []struct {
		Ctx        context.Context
		ResourceId string
	}
	mock.lockRemoveLock.RLock()
	calls = mock.calls.RemoveLock
	mock.lockRemoveLock.RUnlock()
	return calls
}

// Ensure, that checkpointRepositoryMock does implement checkpointRepository.
// If this is not the case, regenerate this file with moq.
var _ checkpointRepository = &checkpointRepositoryMock{}

// checkpointRepositoryMock is a mock implementation of checkpointRepository.
//
//	func TestSomethingThatUsescheckpointRepository(t *testing.T) {
//
//		// make and configure a mocked checkpointRepository
//		mockedcheckpointRepository := &checkpointRepositoryMock{
//			CreateEnygmaCheckpointFunc: func(ctx context.Context, checkpoint types.EnygmaCheckpoint) error {
//				panic("mock out the CreateEnygmaCheckpoint method")
//			},
//			GetLatestCheckpointByFiltersFunc: func(ctx context.Context, resourceId string, status *types.EnygmaCheckpointStatus, finalizedBlockNumber *big.Int, pendingBlockNumber *big.Int) (*types.EnygmaCheckpoint, error) {
//				panic("mock out the GetLatestCheckpointByFilters method")
//			},
//			GetValidationCandidatesFunc: func(ctx context.Context) ([]types.EnygmaCheckpoint, error) {
//				panic("mock out the GetValidationCandidates method")
//			},
//			MarkAsFinalizedFunc: func(ctx context.Context, resourceId string, finalizedBlockNumber *big.Int) error {
//				panic("mock out the MarkAsFinalized method")
//			},
//		}
//
//		// use mockedcheckpointRepository in code that requires checkpointRepository
//		// and then make assertions.
//
//	}
type checkpointRepositoryMock struct {
	// CreateEnygmaCheckpointFunc mocks the CreateEnygmaCheckpoint method.
	CreateEnygmaCheckpointFunc func(ctx context.Context, checkpoint types.EnygmaCheckpoint) error

	// GetLatestCheckpointByFiltersFunc mocks the GetLatestCheckpointByFilters method.
	GetLatestCheckpointByFiltersFunc func(ctx context.Context, resourceId string, status *types.EnygmaCheckpointStatus, finalizedBlockNumber *big.Int, pendingBlockNumber *big.Int) (*types.EnygmaCheckpoint, error)

	// GetValidationCandidatesFunc mocks the GetValidationCandidates method.
	GetValidationCandidatesFunc func(ctx context.Context) ([]types.EnygmaCheckpoint, error)

	// MarkAsFinalizedFunc mocks the MarkAsFinalized method.
	MarkAsFinalizedFunc func(ctx context.Context, resourceId string, finalizedBlockNumber *big.Int) error

	// calls tracks calls to the methods.
	calls struct {
		// CreateEnygmaCheckpoint holds details about calls to the CreateEnygmaCheckpoint method.
		CreateEnygmaCheckpoint []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Checkpoint is the checkpoint argument value.
			Checkpoint types.EnygmaCheckpoint
		}
		// GetLatestCheckpointByFilters holds details about calls to the GetLatestCheckpointByFilters method.
		GetLatestCheckpointByFilters []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ResourceId is the resourceId argument value.
			ResourceId string
			// Status is the status argument value.
			Status *types.EnygmaCheckpointStatus
			// FinalizedBlockNumber is the finalizedBlockNumber argument value.
			FinalizedBlockNumber *big.Int
			// PendingBlockNumber is the pendingBlockNumber argument value.
			PendingBlockNumber *big.Int
		}
		// GetValidationCandidates holds details about calls to the GetValidationCandidates method.
		GetValidationCandidates []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// MarkAsFinalized holds details about calls to the MarkAsFinalized method.
		MarkAsFinalized []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ResourceId is the resourceId argument value.
			ResourceId string
			// FinalizedBlockNumber is the finalizedBlockNumber argument value.
			FinalizedBlockNumber *big.Int
		}
	}
	lockCreateEnygmaCheckpoint       sync.RWMutex
	lockGetLatestCheckpointByFilters sync.RWMutex
	lockGetValidationCandidates      sync.RWMutex
	lockMarkAsFinalized              sync.RWMutex
}

// CreateEnygmaCheckpoint calls CreateEnygmaCheckpointFunc.
func (mock *checkpointRepositoryMock) CreateEnygmaCheckpoint(ctx context.Context, checkpoint types.EnygmaCheckpoint) error {
	if mock.CreateEnygmaCheckpointFunc == nil {
		panic("checkpointRepositoryMock.CreateEnygmaCheckpointFunc: method is nil but checkpointRepository.CreateEnygmaCheckpoint was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		Checkpoint types.EnygmaCheckpoint
	}{
		Ctx:        ctx,
		Checkpoint: checkpoint,
	}
	mock.lockCreateEnygmaCheckpoint.Lock()
	mock.calls.CreateEnygmaCheckpoint = append(mock.calls.CreateEnygmaCheckpoint, callInfo)
	mock.lockCreateEnygmaCheckpoint.Unlock()
	return mock.CreateEnygmaCheckpointFunc(ctx, checkpoint)
}

// CreateEnygmaCheckpointCalls gets all the calls that were made to CreateEnygmaCheckpoint.
// Check the length with:
//
//	len(mockedcheckpointRepository.CreateEnygmaCheckpointCalls())
func (mock *checkpointRepositoryMock) CreateEnygmaCheckpointCalls() []struct {
	Ctx        context.Context
	Checkpoint types.EnygmaCheckpoint
} {
	var calls []struct {
		Ctx        context.Context
		Checkpoint types.EnygmaCheckpoint
	}
	mock.lockCreateEnygmaCheckpoint.RLock()
	calls = mock.calls.CreateEnygmaCheckpoint
	mock.lockCreateEnygmaCheckpoint.RUnlock()
	return calls
}

// GetLatestCheckpointByFilters calls GetLatestCheckpointByFiltersFunc.
func (mock *checkpointRepositoryMock) GetLatestCheckpointByFilters(ctx context.Context, resourceId string, status *types.EnygmaCheckpointStatus, finalizedBlockNumber *big.Int, pendingBlockNumber *big.Int) (*types.EnygmaCheckpoint, error) {
	if mock.GetLatestCheckpointByFiltersFunc == nil {
		panic("checkpointRepositoryMock.GetLatestCheckpointByFiltersFunc: method is nil but checkpointRepository.GetLatestCheckpointByFilters was just called")
	}
	callInfo := struct {
		Ctx                  context.Context
		ResourceId           string
		Status               *types.EnygmaCheckpointStatus
		FinalizedBlockNumber *big.Int
		PendingBlockNumber   *big.Int
	}{
		Ctx:                  ctx,
		ResourceId:           resourceId,
		Status:               status,
		FinalizedBlockNumber: finalizedBlockNumber,
		PendingBlockNumber:   pendingBlockNumber,
	}
	mock.lockGetLatestCheckpointByFilters.Lock()
	mock.calls.GetLatestCheckpointByFilters = append(mock.calls.GetLatestCheckpointByFilters, callInfo)
	mock.lockGetLatestCheckpointByFilters.Unlock()
	return mock.GetLatestCheckpointByFiltersFunc(ctx, resourceId, status, finalizedBlockNumber, pendingBlockNumber)
}

// GetLatestCheckpointByFiltersCalls gets all the calls that were made to GetLatestCheckpointByFilters.
// Check the length with:
//
//	len(mockedcheckpointRepository.GetLatestCheckpointByFiltersCalls())
func (mock *checkpointRepositoryMock) GetLatestCheckpointByFiltersCalls() []struct {
	Ctx                  context.Context
	ResourceId           string
	Status               *types.EnygmaCheckpointStatus
	FinalizedBlockNumber *big.Int
	PendingBlockNumber   *big.Int
} {
	var calls []struct {
		Ctx                  context.Context
		ResourceId           string
		Status               *types.EnygmaCheckpointStatus
		FinalizedBlockNumber *big.Int
		PendingBlockNumber   *big.Int
	}
	mock.lockGetLatestCheckpointByFilters.RLock()
	calls = mock.calls.GetLatestCheckpointByFilters
	mock.lockGetLatestCheckpointByFilters.RUnlock()
	return calls
}

// GetValidationCandidates calls GetValidationCandidatesFunc.
func (mock *checkpointRepositoryMock) GetValidationCandidates(ctx context.Context) ([]types.EnygmaCheckpoint, error) {
	if mock.GetValidationCandidatesFunc == nil {
		panic("checkpointRepositoryMock.GetValidationCandidatesFunc: method is nil but checkpointRepository.GetValidationCandidates was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockGetValidationCandidates.Lock()
	mock.calls.GetValidationCandidates = append(mock.calls.GetValidationCandidates, callInfo)
	mock.lockGetValidationCandidates.Unlock()
	return mock.GetValidationCandidatesFunc(ctx)
}

// GetValidationCandidatesCalls gets all the calls that were made to GetValidationCandidates.
// Check the length with:
//
//	len(mockedcheckpointRepository.GetValidationCandidatesCalls())
func (mock *checkpointRepositoryMock) GetValidationCandidatesCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockGetValidationCandidates.RLock()
	calls = mock.calls.GetValidationCandidates
	mock.lockGetValidationCandidates.RUnlock()
	return calls
}

// MarkAsFinalized calls MarkAsFinalizedFunc.
func (mock *checkpointRepositoryMock) MarkAsFinalized(ctx context.Context, resourceId string, finalizedBlockNumber *big.Int) error {
	if mock.MarkAsFinalizedFunc == nil {
		panic("checkpointRepositoryMock.MarkAsFinalizedFunc: method is nil but checkpointRepository.MarkAsFinalized was just called")
	}
	callInfo := struct {
		Ctx                  context.Context
		ResourceId           string
		FinalizedBlockNumber *big.Int
	}{
		Ctx:                  ctx,
		ResourceId:           resourceId,
		FinalizedBlockNumber: finalizedBlockNumber,
	}
	mock.lockMarkAsFinalized.Lock()
	mock.calls.MarkAsFinalized = append(mock.calls.MarkAsFinalized, callInfo)
	mock.lockMarkAsFinalized.Unlock()
	return mock.MarkAsFinalizedFunc(ctx, resourceId, finalizedBlockNumber)
}

// MarkAsFinalizedCalls gets all the calls that were made to MarkAsFinalized.
// Check the length with:
//
//	len(mockedcheckpointRepository.MarkAsFinalizedCalls())
func (mock *checkpointRepositoryMock) MarkAsFinalizedCalls() []struct {
	Ctx                  context.Context
	ResourceId           string
	FinalizedBlockNumber *big.Int
} {
	var calls []struct {
		Ctx                  context.Context
		ResourceId           string
		FinalizedBlockNumber *big.Int
	}
	mock.lockMarkAsFinalized.RLock()
	calls = mock.calls.MarkAsFinalized
	mock.lockMarkAsFinalized.RUnlock()
	return calls
}

// Ensure, that ethClientMock does implement ethClient.
// If this is not the case, regenerate this file with moq.
var _ ethClient = &ethClientMock{}

// ethClientMock is a mock implementation of ethClient.
//
//	func TestSomethingThatUsesethClient(t *testing.T) {
//
//		// make and configure a mocked ethClient
//		mockedethClient := &ethClientMock{
//			FilterLogsFunc: func(ctx context.Context, query ethereum.FilterQuery) ([]ethTypes.Log, error) {
//				panic("mock out the FilterLogs method")
//			},
//		}
//
//		// use mockedethClient in code that requires ethClient
//		// and then make assertions.
//
//	}
type ethClientMock struct {
	// FilterLogsFunc mocks the FilterLogs method.
	FilterLogsFunc func(ctx context.Context, query ethereum.FilterQuery) ([]ethTypes.Log, error)

	// calls tracks calls to the methods.
	calls struct {
		// FilterLogs holds details about calls to the FilterLogs method.
		FilterLogs []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Query is the query argument value.
			Query ethereum.FilterQuery
		}
	}
	lockFilterLogs sync.RWMutex
}

// FilterLogs calls FilterLogsFunc.
func (mock *ethClientMock) FilterLogs(ctx context.Context, query ethereum.FilterQuery) ([]ethTypes.Log, error) {
	if mock.FilterLogsFunc == nil {
		panic("ethClientMock.FilterLogsFunc: method is nil but ethClient.FilterLogs was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Query ethereum.FilterQuery
	}{
		Ctx:   ctx,
		Query: query,
	}
	mock.lockFilterLogs.Lock()
	mock.calls.FilterLogs = append(mock.calls.FilterLogs, callInfo)
	mock.lockFilterLogs.Unlock()
	return mock.FilterLogsFunc(ctx, query)
}

// FilterLogsCalls gets all the calls that were made to FilterLogs.
// Check the length with:
//
//	len(mockedethClient.FilterLogsCalls())
func (mock *ethClientMock) FilterLogsCalls() []struct {
	Ctx   context.Context
	Query ethereum.FilterQuery
} {
	var calls []struct {
		Ctx   context.Context
		Query ethereum.FilterQuery
	}
	mock.lockFilterLogs.RLock()
	calls = mock.calls.FilterLogs
	mock.lockFilterLogs.RUnlock()
	return calls
}

// Ensure, that kosDecryptorMock does implement kosDecryptor.
// If this is not the case, regenerate this file with moq.
var _ kosDecryptor = &kosDecryptorMock{}

// kosDecryptorMock is a mock implementation of kosDecryptor.
//
//	func TestSomethingThatUseskosDecryptor(t *testing.T) {
//
//		// make and configure a mocked kosDecryptor
//		mockedkosDecryptor := &kosDecryptorMock{
//			DecryptEnygmaTransferBatchFunc: func(ctx context.Context, in *encrypt.DecryptEnygmaTransferBatchRequest, opts ...grpc.CallOption) (*encrypt.DecryptEnygmaTransferBatchResponse, error) {
//				panic("mock out the DecryptEnygmaTransferBatch method")
//			},
//		}
//
//		// use mockedkosDecryptor in code that requires kosDecryptor
//		// and then make assertions.
//
//	}
type kosDecryptorMock struct {
	// DecryptEnygmaTransferBatchFunc mocks the DecryptEnygmaTransferBatch method.
	DecryptEnygmaTransferBatchFunc func(ctx context.Context, in *encrypt.DecryptEnygmaTransferBatchRequest, opts ...grpc.CallOption) (*encrypt.DecryptEnygmaTransferBatchResponse, error)

	// calls tracks calls to the methods.
	calls struct {
		// DecryptEnygmaTransferBatch holds details about calls to the DecryptEnygmaTransferBatch method.
		DecryptEnygmaTransferBatch []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// In is the in argument value.
			In *encrypt.DecryptEnygmaTransferBatchRequest
			// Opts is the opts argument value.
			Opts []grpc.CallOption
		}
	}
	lockDecryptEnygmaTransferBatch sync.RWMutex
}

// DecryptEnygmaTransferBatch calls DecryptEnygmaTransferBatchFunc.
func (mock *kosDecryptorMock) DecryptEnygmaTransferBatch(ctx context.Context, in *encrypt.DecryptEnygmaTransferBatchRequest, opts ...grpc.CallOption) (*encrypt.DecryptEnygmaTransferBatchResponse, error) {
	if mock.DecryptEnygmaTransferBatchFunc == nil {
		panic("kosDecryptorMock.DecryptEnygmaTransferBatchFunc: method is nil but kosDecryptor.DecryptEnygmaTransferBatch was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		In   *encrypt.DecryptEnygmaTransferBatchRequest
		Opts []grpc.CallOption
	}{
		Ctx:  ctx,
		In:   in,
		Opts: opts,
	}
	mock.lockDecryptEnygmaTransferBatch.Lock()
	mock.calls.DecryptEnygmaTransferBatch = append(mock.calls.DecryptEnygmaTransferBatch, callInfo)
	mock.lockDecryptEnygmaTransferBatch.Unlock()
	return mock.DecryptEnygmaTransferBatchFunc(ctx, in, opts...)
}

// DecryptEnygmaTransferBatchCalls gets all the calls that were made to DecryptEnygmaTransferBatch.
// Check the length with:
//
//	len(mockedkosDecryptor.DecryptEnygmaTransferBatchCalls())
func (mock *kosDecryptorMock) DecryptEnygmaTransferBatchCalls() []struct {
	Ctx  context.Context
	In   *encrypt.DecryptEnygmaTransferBatchRequest
	Opts []grpc.CallOption
} {
	var calls []struct {
		Ctx  context.Context
		In   *encrypt.DecryptEnygmaTransferBatchRequest
		Opts []grpc.CallOption
	}
	mock.lockDecryptEnygmaTransferBatch.RLock()
	calls = mock.calls.DecryptEnygmaTransferBatch
	mock.lockDecryptEnygmaTransferBatch.RUnlock()
	return calls
}

// Ensure, that enygmaReceiverMock does implement enygmaReceiver.
// If this is not the case, regenerate this file with moq.
var _ enygmaReceiver = &enygmaReceiverMock{}

// enygmaReceiverMock is a mock implementation of enygmaReceiver.
//
//	func TestSomethingThatUsesenygmaReceiver(t *testing.T) {
//
//		// make and configure a mocked enygmaReceiver
//		mockedenygmaReceiver := &enygmaReceiverMock{
//			HandleEnygmaCrossTransferFunc: func(ctx context.Context, batch *types.EnygmaTransferBatch) error {
//				panic("mock out the HandleEnygmaCrossTransfer method")
//			},
//		}
//
//		// use mockedenygmaReceiver in code that requires enygmaReceiver
//		// and then make assertions.
//
//	}
type enygmaReceiverMock struct {
	// HandleEnygmaCrossTransferFunc mocks the HandleEnygmaCrossTransfer method.
	HandleEnygmaCrossTransferFunc func(ctx context.Context, batch *types.EnygmaTransferBatch) error

	// calls tracks calls to the methods.
	calls struct {
		// HandleEnygmaCrossTransfer holds details about calls to the HandleEnygmaCrossTransfer method.
		HandleEnygmaCrossTransfer []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Batch is the batch argument value.
			Batch *types.EnygmaTransferBatch
		}
	}
	lockHandleEnygmaCrossTransfer sync.RWMutex
}

// HandleEnygmaCrossTransfer calls HandleEnygmaCrossTransferFunc.
func (mock *enygmaReceiverMock) HandleEnygmaCrossTransfer(ctx context.Context, batch *types.EnygmaTransferBatch) error {
	if mock.HandleEnygmaCrossTransferFunc == nil {
		panic("enygmaReceiverMock.HandleEnygmaCrossTransferFunc: method is nil but enygmaReceiver.HandleEnygmaCrossTransfer was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Batch *types.EnygmaTransferBatch
	}{
		Ctx:   ctx,
		Batch: batch,
	}
	mock.lockHandleEnygmaCrossTransfer.Lock()
	mock.calls.HandleEnygmaCrossTransfer = append(mock.calls.HandleEnygmaCrossTransfer, callInfo)
	mock.lockHandleEnygmaCrossTransfer.Unlock()
	return mock.HandleEnygmaCrossTransferFunc(ctx, batch)
}

// HandleEnygmaCrossTransferCalls gets all the calls that were made to HandleEnygmaCrossTransfer.
// Check the length with:
//
//	len(mockedenygmaReceiver.HandleEnygmaCrossTransferCalls())
func (mock *enygmaReceiverMock) HandleEnygmaCrossTransferCalls() []struct {
	Ctx   context.Context
	Batch *types.EnygmaTransferBatch
} {
	var calls []struct {
		Ctx   context.Context
		Batch *types.EnygmaTransferBatch
	}
	mock.lockHandleEnygmaCrossTransfer.RLock()
	calls = mock.calls.HandleEnygmaCrossTransfer
	mock.lockHandleEnygmaCrossTransfer.RUnlock()
	return calls
}

// Ensure, that tracerMock does implement tracer.
// If this is not the case, regenerate this file with moq.
var _ tracer = &tracerMock{}

// tracerMock is a mock implementation of tracer.
//
//	func TestSomethingThatUsestracer(t *testing.T) {
//
//		// make and configure a mocked tracer
//		mockedtracer := &tracerMock{
//			StartFunc: func(ctx context.Context, spanName string, opts ...trace.SpanStartOption) (context.Context, trace.Span) {
//				panic("mock out the Start method")
//			},
//		}
//
//		// use mockedtracer in code that requires tracer
//		// and then make assertions.
//
//	}
type tracerMock struct {
	// StartFunc mocks the Start method.
	StartFunc func(ctx context.Context, spanName string, opts ...trace.SpanStartOption) (context.Context, trace.Span)

	// calls tracks calls to the methods.
	calls struct {
		// Start holds details about calls to the Start method.
		Start []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// SpanName is the spanName argument value.
			SpanName string
			// Opts is the opts argument value.
			Opts []trace.SpanStartOption
		}
	}
	lockStart sync.RWMutex
}

// Start calls StartFunc.
func (mock *tracerMock) Start(ctx context.Context, spanName string, opts ...trace.SpanStartOption) (context.Context, trace.Span) {
	if mock.StartFunc == nil {
		panic("tracerMock.StartFunc: method is nil but tracer.Start was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		SpanName string
		Opts     []trace.SpanStartOption
	}{
		Ctx:      ctx,
		SpanName: spanName,
		Opts:     opts,
	}
	mock.lockStart.Lock()
	mock.calls.Start = append(mock.calls.Start, callInfo)
	mock.lockStart.Unlock()
	return mock.StartFunc(ctx, spanName, opts...)
}

// StartCalls gets all the calls that were made to Start.
// Check the length with:
//
//	len(mockedtracer.StartCalls())
func (mock *tracerMock) StartCalls() []struct {
	Ctx      context.Context
	SpanName string
	Opts     []trace.SpanStartOption
} {
	var calls []struct {
		Ctx      context.Context
		SpanName string
		Opts     []trace.SpanStartOption
	}
	mock.lockStart.RLock()
	calls = mock.calls.Start
	mock.lockStart.RUnlock()
	return calls
}
