// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package handler_test

import (
	"context"
	"github.com/ethereum/go-ethereum/common"
	"github.com/raylsnetwork/rayls-privacy-relayer-api/contracts/EndpointV1"
	keyspb "github.com/raylsnetwork/rayls-privacy-relayer-api/cts/gen/proto/keys"
	"github.com/raylsnetwork/rayls-privacy-relayer-api/dvp"
	"github.com/raylsnetwork/rayls-privacy-relayer-api/types"
	"go.opentelemetry.io/otel/trace"
	"google.golang.org/grpc"
	"math/big"
	"sync"
)

// initiatorEnygmaHistoryRepositoryMock is a mock implementation of handler.initiatorEnygmaHistoryRepository.
//
//	func TestSomethingThatUsesinitiatorEnygmaHistoryRepository(t *testing.T) {
//
//		// make and configure a mocked handler.initiatorEnygmaHistoryRepository
//		mockedinitiatorEnygmaHistoryRepository := &initiatorEnygmaHistoryRepositoryMock{
//			InsertEnygmaHistoryFunc: func(ctx context.Context, history types.EnygmaHistory) error {
//				panic("mock out the InsertEnygmaHistory method")
//			},
//		}
//
//		// use mockedinitiatorEnygmaHistoryRepository in code that requires handler.initiatorEnygmaHistoryRepository
//		// and then make assertions.
//
//	}
type initiatorEnygmaHistoryRepositoryMock struct {
	// InsertEnygmaHistoryFunc mocks the InsertEnygmaHistory method.
	InsertEnygmaHistoryFunc func(ctx context.Context, history types.EnygmaHistory) error

	// calls tracks calls to the methods.
	calls struct {
		// InsertEnygmaHistory holds details about calls to the InsertEnygmaHistory method.
		InsertEnygmaHistory []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// History is the history argument value.
			History types.EnygmaHistory
		}
	}
	lockInsertEnygmaHistory sync.RWMutex
}

// InsertEnygmaHistory calls InsertEnygmaHistoryFunc.
func (mock *initiatorEnygmaHistoryRepositoryMock) InsertEnygmaHistory(ctx context.Context, history types.EnygmaHistory) error {
	if mock.InsertEnygmaHistoryFunc == nil {
		panic("initiatorEnygmaHistoryRepositoryMock.InsertEnygmaHistoryFunc: method is nil but initiatorEnygmaHistoryRepository.InsertEnygmaHistory was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		History types.EnygmaHistory
	}{
		Ctx:     ctx,
		History: history,
	}
	mock.lockInsertEnygmaHistory.Lock()
	mock.calls.InsertEnygmaHistory = append(mock.calls.InsertEnygmaHistory, callInfo)
	mock.lockInsertEnygmaHistory.Unlock()
	return mock.InsertEnygmaHistoryFunc(ctx, history)
}

// InsertEnygmaHistoryCalls gets all the calls that were made to InsertEnygmaHistory.
// Check the length with:
//
//	len(mockedinitiatorEnygmaHistoryRepository.InsertEnygmaHistoryCalls())
func (mock *initiatorEnygmaHistoryRepositoryMock) InsertEnygmaHistoryCalls() []struct {
	Ctx     context.Context
	History types.EnygmaHistory
} {
	var calls []struct {
		Ctx     context.Context
		History types.EnygmaHistory
	}
	mock.lockInsertEnygmaHistory.RLock()
	calls = mock.calls.InsertEnygmaHistory
	mock.lockInsertEnygmaHistory.RUnlock()
	return calls
}

// initiatorDvpDepositRepositoryMock is a mock implementation of handler.initiatorDvpDepositRepository.
//
//	func TestSomethingThatUsesinitiatorDvpDepositRepository(t *testing.T) {
//
//		// make and configure a mocked handler.initiatorDvpDepositRepository
//		mockedinitiatorDvpDepositRepository := &initiatorDvpDepositRepositoryMock{
//			BatchUpdateStatusForCommitmentsFunc: func(ctx context.Context, commitments []string, status types.DvpDepositStatus) error {
//				panic("mock out the BatchUpdateStatusForCommitments method")
//			},
//			BatchUpsertNullifiersFunc: func(ctx context.Context, commitmentNullifierMap map[string]string) error {
//				panic("mock out the BatchUpsertNullifiers method")
//			},
//			CreateDepositFunc: func(ctx context.Context, deposit *types.DvpDeposit) error {
//				panic("mock out the CreateDeposit method")
//			},
//		}
//
//		// use mockedinitiatorDvpDepositRepository in code that requires handler.initiatorDvpDepositRepository
//		// and then make assertions.
//
//	}
type initiatorDvpDepositRepositoryMock struct {
	// BatchUpdateStatusForCommitmentsFunc mocks the BatchUpdateStatusForCommitments method.
	BatchUpdateStatusForCommitmentsFunc func(ctx context.Context, commitments []string, status types.DvpDepositStatus) error

	// BatchUpsertNullifiersFunc mocks the BatchUpsertNullifiers method.
	BatchUpsertNullifiersFunc func(ctx context.Context, commitmentNullifierMap map[string]string) error

	// CreateDepositFunc mocks the CreateDeposit method.
	CreateDepositFunc func(ctx context.Context, deposit *types.DvpDeposit) error

	// calls tracks calls to the methods.
	calls struct {
		// BatchUpdateStatusForCommitments holds details about calls to the BatchUpdateStatusForCommitments method.
		BatchUpdateStatusForCommitments []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Commitments is the commitments argument value.
			Commitments []string
			// Status is the status argument value.
			Status types.DvpDepositStatus
		}
		// BatchUpsertNullifiers holds details about calls to the BatchUpsertNullifiers method.
		BatchUpsertNullifiers []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// CommitmentNullifierMap is the commitmentNullifierMap argument value.
			CommitmentNullifierMap map[string]string
		}
		// CreateDeposit holds details about calls to the CreateDeposit method.
		CreateDeposit []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Deposit is the deposit argument value.
			Deposit *types.DvpDeposit
		}
	}
	lockBatchUpdateStatusForCommitments sync.RWMutex
	lockBatchUpsertNullifiers           sync.RWMutex
	lockCreateDeposit                   sync.RWMutex
}

// BatchUpdateStatusForCommitments calls BatchUpdateStatusForCommitmentsFunc.
func (mock *initiatorDvpDepositRepositoryMock) BatchUpdateStatusForCommitments(ctx context.Context, commitments []string, status types.DvpDepositStatus) error {
	if mock.BatchUpdateStatusForCommitmentsFunc == nil {
		panic("initiatorDvpDepositRepositoryMock.BatchUpdateStatusForCommitmentsFunc: method is nil but initiatorDvpDepositRepository.BatchUpdateStatusForCommitments was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		Commitments []string
		Status      types.DvpDepositStatus
	}{
		Ctx:         ctx,
		Commitments: commitments,
		Status:      status,
	}
	mock.lockBatchUpdateStatusForCommitments.Lock()
	mock.calls.BatchUpdateStatusForCommitments = append(mock.calls.BatchUpdateStatusForCommitments, callInfo)
	mock.lockBatchUpdateStatusForCommitments.Unlock()
	return mock.BatchUpdateStatusForCommitmentsFunc(ctx, commitments, status)
}

// BatchUpdateStatusForCommitmentsCalls gets all the calls that were made to BatchUpdateStatusForCommitments.
// Check the length with:
//
//	len(mockedinitiatorDvpDepositRepository.BatchUpdateStatusForCommitmentsCalls())
func (mock *initiatorDvpDepositRepositoryMock) BatchUpdateStatusForCommitmentsCalls() []struct {
	Ctx         context.Context
	Commitments []string
	Status      types.DvpDepositStatus
} {
	var calls []struct {
		Ctx         context.Context
		Commitments []string
		Status      types.DvpDepositStatus
	}
	mock.lockBatchUpdateStatusForCommitments.RLock()
	calls = mock.calls.BatchUpdateStatusForCommitments
	mock.lockBatchUpdateStatusForCommitments.RUnlock()
	return calls
}

// BatchUpsertNullifiers calls BatchUpsertNullifiersFunc.
func (mock *initiatorDvpDepositRepositoryMock) BatchUpsertNullifiers(ctx context.Context, commitmentNullifierMap map[string]string) error {
	if mock.BatchUpsertNullifiersFunc == nil {
		panic("initiatorDvpDepositRepositoryMock.BatchUpsertNullifiersFunc: method is nil but initiatorDvpDepositRepository.BatchUpsertNullifiers was just called")
	}
	callInfo := struct {
		Ctx                    context.Context
		CommitmentNullifierMap map[string]string
	}{
		Ctx:                    ctx,
		CommitmentNullifierMap: commitmentNullifierMap,
	}
	mock.lockBatchUpsertNullifiers.Lock()
	mock.calls.BatchUpsertNullifiers = append(mock.calls.BatchUpsertNullifiers, callInfo)
	mock.lockBatchUpsertNullifiers.Unlock()
	return mock.BatchUpsertNullifiersFunc(ctx, commitmentNullifierMap)
}

// BatchUpsertNullifiersCalls gets all the calls that were made to BatchUpsertNullifiers.
// Check the length with:
//
//	len(mockedinitiatorDvpDepositRepository.BatchUpsertNullifiersCalls())
func (mock *initiatorDvpDepositRepositoryMock) BatchUpsertNullifiersCalls() []struct {
	Ctx                    context.Context
	CommitmentNullifierMap map[string]string
} {
	var calls []struct {
		Ctx                    context.Context
		CommitmentNullifierMap map[string]string
	}
	mock.lockBatchUpsertNullifiers.RLock()
	calls = mock.calls.BatchUpsertNullifiers
	mock.lockBatchUpsertNullifiers.RUnlock()
	return calls
}

// CreateDeposit calls CreateDepositFunc.
func (mock *initiatorDvpDepositRepositoryMock) CreateDeposit(ctx context.Context, deposit *types.DvpDeposit) error {
	if mock.CreateDepositFunc == nil {
		panic("initiatorDvpDepositRepositoryMock.CreateDepositFunc: method is nil but initiatorDvpDepositRepository.CreateDeposit was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		Deposit *types.DvpDeposit
	}{
		Ctx:     ctx,
		Deposit: deposit,
	}
	mock.lockCreateDeposit.Lock()
	mock.calls.CreateDeposit = append(mock.calls.CreateDeposit, callInfo)
	mock.lockCreateDeposit.Unlock()
	return mock.CreateDepositFunc(ctx, deposit)
}

// CreateDepositCalls gets all the calls that were made to CreateDeposit.
// Check the length with:
//
//	len(mockedinitiatorDvpDepositRepository.CreateDepositCalls())
func (mock *initiatorDvpDepositRepositoryMock) CreateDepositCalls() []struct {
	Ctx     context.Context
	Deposit *types.DvpDeposit
} {
	var calls []struct {
		Ctx     context.Context
		Deposit *types.DvpDeposit
	}
	mock.lockCreateDeposit.RLock()
	calls = mock.calls.CreateDeposit
	mock.lockCreateDeposit.RUnlock()
	return calls
}

// initiatorTxManagerMock is a mock implementation of handler.initiatorTxManager.
//
//	func TestSomethingThatUsesinitiatorTxManager(t *testing.T) {
//
//		// make and configure a mocked handler.initiatorTxManager
//		mockedinitiatorTxManager := &initiatorTxManagerMock{
//			WithTransactionFunc: func(ctx context.Context, fn func(ctx context.Context) error) error {
//				panic("mock out the WithTransaction method")
//			},
//		}
//
//		// use mockedinitiatorTxManager in code that requires handler.initiatorTxManager
//		// and then make assertions.
//
//	}
type initiatorTxManagerMock struct {
	// WithTransactionFunc mocks the WithTransaction method.
	WithTransactionFunc func(ctx context.Context, fn func(ctx context.Context) error) error

	// calls tracks calls to the methods.
	calls struct {
		// WithTransaction holds details about calls to the WithTransaction method.
		WithTransaction []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Fn is the fn argument value.
			Fn func(ctx context.Context) error
		}
	}
	lockWithTransaction sync.RWMutex
}

// WithTransaction calls WithTransactionFunc.
func (mock *initiatorTxManagerMock) WithTransaction(ctx context.Context, fn func(ctx context.Context) error) error {
	if mock.WithTransactionFunc == nil {
		panic("initiatorTxManagerMock.WithTransactionFunc: method is nil but initiatorTxManager.WithTransaction was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Fn  func(ctx context.Context) error
	}{
		Ctx: ctx,
		Fn:  fn,
	}
	mock.lockWithTransaction.Lock()
	mock.calls.WithTransaction = append(mock.calls.WithTransaction, callInfo)
	mock.lockWithTransaction.Unlock()
	return mock.WithTransactionFunc(ctx, fn)
}

// WithTransactionCalls gets all the calls that were made to WithTransaction.
// Check the length with:
//
//	len(mockedinitiatorTxManager.WithTransactionCalls())
func (mock *initiatorTxManagerMock) WithTransactionCalls() []struct {
	Ctx context.Context
	Fn  func(ctx context.Context) error
} {
	var calls []struct {
		Ctx context.Context
		Fn  func(ctx context.Context) error
	}
	mock.lockWithTransaction.RLock()
	calls = mock.calls.WithTransaction
	mock.lockWithTransaction.RUnlock()
	return calls
}

// initiatorKeysClientMock is a mock implementation of handler.initiatorKeysClient.
//
//	func TestSomethingThatUsesinitiatorKeysClient(t *testing.T) {
//
//		// make and configure a mocked handler.initiatorKeysClient
//		mockedinitiatorKeysClient := &initiatorKeysClientMock{
//			GetPaymentSpendKeyFunc: func(ctx context.Context, in *keyspb.GetPaymentSpendKeyRequest, opts ...grpc.CallOption) (*keyspb.PaymentSpendKeyResponse, error) {
//				panic("mock out the GetPaymentSpendKey method")
//			},
//			GetViewPublicKeyFunc: func(ctx context.Context, in *keyspb.GetViewPublicKeyRequest, opts ...grpc.CallOption) (*keyspb.GetViewPublicKeyResponse, error) {
//				panic("mock out the GetViewPublicKey method")
//			},
//		}
//
//		// use mockedinitiatorKeysClient in code that requires handler.initiatorKeysClient
//		// and then make assertions.
//
//	}
type initiatorKeysClientMock struct {
	// GetPaymentSpendKeyFunc mocks the GetPaymentSpendKey method.
	GetPaymentSpendKeyFunc func(ctx context.Context, in *keyspb.GetPaymentSpendKeyRequest, opts ...grpc.CallOption) (*keyspb.PaymentSpendKeyResponse, error)

	// GetViewPublicKeyFunc mocks the GetViewPublicKey method.
	GetViewPublicKeyFunc func(ctx context.Context, in *keyspb.GetViewPublicKeyRequest, opts ...grpc.CallOption) (*keyspb.GetViewPublicKeyResponse, error)

	// calls tracks calls to the methods.
	calls struct {
		// GetPaymentSpendKey holds details about calls to the GetPaymentSpendKey method.
		GetPaymentSpendKey []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// In is the in argument value.
			In *keyspb.GetPaymentSpendKeyRequest
			// Opts is the opts argument value.
			Opts []grpc.CallOption
		}
		// GetViewPublicKey holds details about calls to the GetViewPublicKey method.
		GetViewPublicKey []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// In is the in argument value.
			In *keyspb.GetViewPublicKeyRequest
			// Opts is the opts argument value.
			Opts []grpc.CallOption
		}
	}
	lockGetPaymentSpendKey sync.RWMutex
	lockGetViewPublicKey   sync.RWMutex
}

// GetPaymentSpendKey calls GetPaymentSpendKeyFunc.
func (mock *initiatorKeysClientMock) GetPaymentSpendKey(ctx context.Context, in *keyspb.GetPaymentSpendKeyRequest, opts ...grpc.CallOption) (*keyspb.PaymentSpendKeyResponse, error) {
	if mock.GetPaymentSpendKeyFunc == nil {
		panic("initiatorKeysClientMock.GetPaymentSpendKeyFunc: method is nil but initiatorKeysClient.GetPaymentSpendKey was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		In   *keyspb.GetPaymentSpendKeyRequest
		Opts []grpc.CallOption
	}{
		Ctx:  ctx,
		In:   in,
		Opts: opts,
	}
	mock.lockGetPaymentSpendKey.Lock()
	mock.calls.GetPaymentSpendKey = append(mock.calls.GetPaymentSpendKey, callInfo)
	mock.lockGetPaymentSpendKey.Unlock()
	return mock.GetPaymentSpendKeyFunc(ctx, in, opts...)
}

// GetPaymentSpendKeyCalls gets all the calls that were made to GetPaymentSpendKey.
// Check the length with:
//
//	len(mockedinitiatorKeysClient.GetPaymentSpendKeyCalls())
func (mock *initiatorKeysClientMock) GetPaymentSpendKeyCalls() []struct {
	Ctx  context.Context
	In   *keyspb.GetPaymentSpendKeyRequest
	Opts []grpc.CallOption
} {
	var calls []struct {
		Ctx  context.Context
		In   *keyspb.GetPaymentSpendKeyRequest
		Opts []grpc.CallOption
	}
	mock.lockGetPaymentSpendKey.RLock()
	calls = mock.calls.GetPaymentSpendKey
	mock.lockGetPaymentSpendKey.RUnlock()
	return calls
}

// GetViewPublicKey calls GetViewPublicKeyFunc.
func (mock *initiatorKeysClientMock) GetViewPublicKey(ctx context.Context, in *keyspb.GetViewPublicKeyRequest, opts ...grpc.CallOption) (*keyspb.GetViewPublicKeyResponse, error) {
	if mock.GetViewPublicKeyFunc == nil {
		panic("initiatorKeysClientMock.GetViewPublicKeyFunc: method is nil but initiatorKeysClient.GetViewPublicKey was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		In   *keyspb.GetViewPublicKeyRequest
		Opts []grpc.CallOption
	}{
		Ctx:  ctx,
		In:   in,
		Opts: opts,
	}
	mock.lockGetViewPublicKey.Lock()
	mock.calls.GetViewPublicKey = append(mock.calls.GetViewPublicKey, callInfo)
	mock.lockGetViewPublicKey.Unlock()
	return mock.GetViewPublicKeyFunc(ctx, in, opts...)
}

// GetViewPublicKeyCalls gets all the calls that were made to GetViewPublicKey.
// Check the length with:
//
//	len(mockedinitiatorKeysClient.GetViewPublicKeyCalls())
func (mock *initiatorKeysClientMock) GetViewPublicKeyCalls() []struct {
	Ctx  context.Context
	In   *keyspb.GetViewPublicKeyRequest
	Opts []grpc.CallOption
} {
	var calls []struct {
		Ctx  context.Context
		In   *keyspb.GetViewPublicKeyRequest
		Opts []grpc.CallOption
	}
	mock.lockGetViewPublicKey.RLock()
	calls = mock.calls.GetViewPublicKey
	mock.lockGetViewPublicKey.RUnlock()
	return calls
}

// initiatorEndpointClientMock is a mock implementation of handler.initiatorEndpointClient.
//
//	func TestSomethingThatUsesinitiatorEndpointClient(t *testing.T) {
//
//		// make and configure a mocked handler.initiatorEndpointClient
//		mockedinitiatorEndpointClient := &initiatorEndpointClientMock{
//			GetResourceAddressFunc: func(ctx context.Context, resourceId string) (common.Address, error) {
//				panic("mock out the GetResourceAddress method")
//			},
//			ReceivePayloadFunc: func(ctx context.Context, fromChainId *big.Int, from common.Address, to common.Address, data EndpointV1.RaylsMessage, messageId [32]byte) (common.Hash, error) {
//				panic("mock out the ReceivePayload method")
//			},
//		}
//
//		// use mockedinitiatorEndpointClient in code that requires handler.initiatorEndpointClient
//		// and then make assertions.
//
//	}
type initiatorEndpointClientMock struct {
	// GetResourceAddressFunc mocks the GetResourceAddress method.
	GetResourceAddressFunc func(ctx context.Context, resourceId string) (common.Address, error)

	// ReceivePayloadFunc mocks the ReceivePayload method.
	ReceivePayloadFunc func(ctx context.Context, fromChainId *big.Int, from common.Address, to common.Address, data EndpointV1.RaylsMessage, messageId [32]byte) (common.Hash, error)

	// calls tracks calls to the methods.
	calls struct {
		// GetResourceAddress holds details about calls to the GetResourceAddress method.
		GetResourceAddress []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ResourceId is the resourceId argument value.
			ResourceId string
		}
		// ReceivePayload holds details about calls to the ReceivePayload method.
		ReceivePayload []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// FromChainId is the fromChainId argument value.
			FromChainId *big.Int
			// From is the from argument value.
			From common.Address
			// To is the to argument value.
			To common.Address
			// Data is the data argument value.
			Data EndpointV1.RaylsMessage
			// MessageId is the messageId argument value.
			MessageId [32]byte
		}
	}
	lockGetResourceAddress sync.RWMutex
	lockReceivePayload     sync.RWMutex
}

// GetResourceAddress calls GetResourceAddressFunc.
func (mock *initiatorEndpointClientMock) GetResourceAddress(ctx context.Context, resourceId string) (common.Address, error) {
	if mock.GetResourceAddressFunc == nil {
		panic("initiatorEndpointClientMock.GetResourceAddressFunc: method is nil but initiatorEndpointClient.GetResourceAddress was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		ResourceId string
	}{
		Ctx:        ctx,
		ResourceId: resourceId,
	}
	mock.lockGetResourceAddress.Lock()
	mock.calls.GetResourceAddress = append(mock.calls.GetResourceAddress, callInfo)
	mock.lockGetResourceAddress.Unlock()
	return mock.GetResourceAddressFunc(ctx, resourceId)
}

// GetResourceAddressCalls gets all the calls that were made to GetResourceAddress.
// Check the length with:
//
//	len(mockedinitiatorEndpointClient.GetResourceAddressCalls())
func (mock *initiatorEndpointClientMock) GetResourceAddressCalls() []struct {
	Ctx        context.Context
	ResourceId string
} {
	var calls []struct {
		Ctx        context.Context
		ResourceId string
	}
	mock.lockGetResourceAddress.RLock()
	calls = mock.calls.GetResourceAddress
	mock.lockGetResourceAddress.RUnlock()
	return calls
}

// ReceivePayload calls ReceivePayloadFunc.
func (mock *initiatorEndpointClientMock) ReceivePayload(ctx context.Context, fromChainId *big.Int, from common.Address, to common.Address, data EndpointV1.RaylsMessage, messageId [32]byte) (common.Hash, error) {
	if mock.ReceivePayloadFunc == nil {
		panic("initiatorEndpointClientMock.ReceivePayloadFunc: method is nil but initiatorEndpointClient.ReceivePayload was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		FromChainId *big.Int
		From        common.Address
		To          common.Address
		Data        EndpointV1.RaylsMessage
		MessageId   [32]byte
	}{
		Ctx:         ctx,
		FromChainId: fromChainId,
		From:        from,
		To:          to,
		Data:        data,
		MessageId:   messageId,
	}
	mock.lockReceivePayload.Lock()
	mock.calls.ReceivePayload = append(mock.calls.ReceivePayload, callInfo)
	mock.lockReceivePayload.Unlock()
	return mock.ReceivePayloadFunc(ctx, fromChainId, from, to, data, messageId)
}

// ReceivePayloadCalls gets all the calls that were made to ReceivePayload.
// Check the length with:
//
//	len(mockedinitiatorEndpointClient.ReceivePayloadCalls())
func (mock *initiatorEndpointClientMock) ReceivePayloadCalls() []struct {
	Ctx         context.Context
	FromChainId *big.Int
	From        common.Address
	To          common.Address
	Data        EndpointV1.RaylsMessage
	MessageId   [32]byte
} {
	var calls []struct {
		Ctx         context.Context
		FromChainId *big.Int
		From        common.Address
		To          common.Address
		Data        EndpointV1.RaylsMessage
		MessageId   [32]byte
	}
	mock.lockReceivePayload.RLock()
	calls = mock.calls.ReceivePayload
	mock.lockReceivePayload.RUnlock()
	return calls
}

// initiatorEnygmaHandlerClientMock is a mock implementation of handler.initiatorEnygmaHandlerClient.
//
//	func TestSomethingThatUsesinitiatorEnygmaHandlerClient(t *testing.T) {
//
//		// make and configure a mocked handler.initiatorEnygmaHandlerClient
//		mockedinitiatorEnygmaHandlerClient := &initiatorEnygmaHandlerClientMock{
//			ReceiveWithdrawFunc: func(ctx context.Context, chainEventID string, tokenAddress common.Address, to common.Address, value *big.Int, referenceId [32]byte) error {
//				panic("mock out the ReceiveWithdraw method")
//			},
//		}
//
//		// use mockedinitiatorEnygmaHandlerClient in code that requires handler.initiatorEnygmaHandlerClient
//		// and then make assertions.
//
//	}
type initiatorEnygmaHandlerClientMock struct {
	// ReceiveWithdrawFunc mocks the ReceiveWithdraw method.
	ReceiveWithdrawFunc func(ctx context.Context, chainEventID string, tokenAddress common.Address, to common.Address, value *big.Int, referenceId [32]byte) error

	// calls tracks calls to the methods.
	calls struct {
		// ReceiveWithdraw holds details about calls to the ReceiveWithdraw method.
		ReceiveWithdraw []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ChainEventID is the chainEventID argument value.
			ChainEventID string
			// TokenAddress is the tokenAddress argument value.
			TokenAddress common.Address
			// To is the to argument value.
			To common.Address
			// Value is the value argument value.
			Value *big.Int
			// ReferenceId is the referenceId argument value.
			ReferenceId [32]byte
		}
	}
	lockReceiveWithdraw sync.RWMutex
}

// ReceiveWithdraw calls ReceiveWithdrawFunc.
func (mock *initiatorEnygmaHandlerClientMock) ReceiveWithdraw(ctx context.Context, chainEventID string, tokenAddress common.Address, to common.Address, value *big.Int, referenceId [32]byte) error {
	if mock.ReceiveWithdrawFunc == nil {
		panic("initiatorEnygmaHandlerClientMock.ReceiveWithdrawFunc: method is nil but initiatorEnygmaHandlerClient.ReceiveWithdraw was just called")
	}
	callInfo := struct {
		Ctx          context.Context
		ChainEventID string
		TokenAddress common.Address
		To           common.Address
		Value        *big.Int
		ReferenceId  [32]byte
	}{
		Ctx:          ctx,
		ChainEventID: chainEventID,
		TokenAddress: tokenAddress,
		To:           to,
		Value:        value,
		ReferenceId:  referenceId,
	}
	mock.lockReceiveWithdraw.Lock()
	mock.calls.ReceiveWithdraw = append(mock.calls.ReceiveWithdraw, callInfo)
	mock.lockReceiveWithdraw.Unlock()
	return mock.ReceiveWithdrawFunc(ctx, chainEventID, tokenAddress, to, value, referenceId)
}

// ReceiveWithdrawCalls gets all the calls that were made to ReceiveWithdraw.
// Check the length with:
//
//	len(mockedinitiatorEnygmaHandlerClient.ReceiveWithdrawCalls())
func (mock *initiatorEnygmaHandlerClientMock) ReceiveWithdrawCalls() []struct {
	Ctx          context.Context
	ChainEventID string
	TokenAddress common.Address
	To           common.Address
	Value        *big.Int
	ReferenceId  [32]byte
} {
	var calls []struct {
		Ctx          context.Context
		ChainEventID string
		TokenAddress common.Address
		To           common.Address
		Value        *big.Int
		ReferenceId  [32]byte
	}
	mock.lockReceiveWithdraw.RLock()
	calls = mock.calls.ReceiveWithdraw
	mock.lockReceiveWithdraw.RUnlock()
	return calls
}

// initiatorCommitmentCalculatorMock is a mock implementation of handler.initiatorCommitmentCalculator.
//
//	func TestSomethingThatUsesinitiatorCommitmentCalculator(t *testing.T) {
//
//		// make and configure a mocked handler.initiatorCommitmentCalculator
//		mockedinitiatorCommitmentCalculator := &initiatorCommitmentCalculatorMock{
//			CalculatePaymentCommitmentFunc: func(spendPK *big.Int, salt *big.Int, paymentAmount *big.Int, tokenAddress string) (*big.Int, error) {
//				panic("mock out the CalculatePaymentCommitment method")
//			},
//		}
//
//		// use mockedinitiatorCommitmentCalculator in code that requires handler.initiatorCommitmentCalculator
//		// and then make assertions.
//
//	}
type initiatorCommitmentCalculatorMock struct {
	// CalculatePaymentCommitmentFunc mocks the CalculatePaymentCommitment method.
	CalculatePaymentCommitmentFunc func(spendPK *big.Int, salt *big.Int, paymentAmount *big.Int, tokenAddress string) (*big.Int, error)

	// calls tracks calls to the methods.
	calls struct {
		// CalculatePaymentCommitment holds details about calls to the CalculatePaymentCommitment method.
		CalculatePaymentCommitment []struct {
			// SpendPK is the spendPK argument value.
			SpendPK *big.Int
			// Salt is the salt argument value.
			Salt *big.Int
			// PaymentAmount is the paymentAmount argument value.
			PaymentAmount *big.Int
			// TokenAddress is the tokenAddress argument value.
			TokenAddress string
		}
	}
	lockCalculatePaymentCommitment sync.RWMutex
}

// CalculatePaymentCommitment calls CalculatePaymentCommitmentFunc.
func (mock *initiatorCommitmentCalculatorMock) CalculatePaymentCommitment(spendPK *big.Int, salt *big.Int, paymentAmount *big.Int, tokenAddress string) (*big.Int, error) {
	if mock.CalculatePaymentCommitmentFunc == nil {
		panic("initiatorCommitmentCalculatorMock.CalculatePaymentCommitmentFunc: method is nil but initiatorCommitmentCalculator.CalculatePaymentCommitment was just called")
	}
	callInfo := struct {
		SpendPK       *big.Int
		Salt          *big.Int
		PaymentAmount *big.Int
		TokenAddress  string
	}{
		SpendPK:       spendPK,
		Salt:          salt,
		PaymentAmount: paymentAmount,
		TokenAddress:  tokenAddress,
	}
	mock.lockCalculatePaymentCommitment.Lock()
	mock.calls.CalculatePaymentCommitment = append(mock.calls.CalculatePaymentCommitment, callInfo)
	mock.lockCalculatePaymentCommitment.Unlock()
	return mock.CalculatePaymentCommitmentFunc(spendPK, salt, paymentAmount, tokenAddress)
}

// CalculatePaymentCommitmentCalls gets all the calls that were made to CalculatePaymentCommitment.
// Check the length with:
//
//	len(mockedinitiatorCommitmentCalculator.CalculatePaymentCommitmentCalls())
func (mock *initiatorCommitmentCalculatorMock) CalculatePaymentCommitmentCalls() []struct {
	SpendPK       *big.Int
	Salt          *big.Int
	PaymentAmount *big.Int
	TokenAddress  string
} {
	var calls []struct {
		SpendPK       *big.Int
		Salt          *big.Int
		PaymentAmount *big.Int
		TokenAddress  string
	}
	mock.lockCalculatePaymentCommitment.RLock()
	calls = mock.calls.CalculatePaymentCommitment
	mock.lockCalculatePaymentCommitment.RUnlock()
	return calls
}

// initiatorDepositFinderMock is a mock implementation of handler.initiatorDepositFinder.
//
//	func TestSomethingThatUsesinitiatorDepositFinder(t *testing.T) {
//
//		// make and configure a mocked handler.initiatorDepositFinder
//		mockedinitiatorDepositFinder := &initiatorDepositFinderMock{
//			FindEnygmaDepositsFunc: func(ctx context.Context, userAddress string, tokenAddress string, paymentAmount *big.Int) ([]*types.DvpDeposit, error) {
//				panic("mock out the FindEnygmaDeposits method")
//			},
//		}
//
//		// use mockedinitiatorDepositFinder in code that requires handler.initiatorDepositFinder
//		// and then make assertions.
//
//	}
type initiatorDepositFinderMock struct {
	// FindEnygmaDepositsFunc mocks the FindEnygmaDeposits method.
	FindEnygmaDepositsFunc func(ctx context.Context, userAddress string, tokenAddress string, paymentAmount *big.Int) ([]*types.DvpDeposit, error)

	// calls tracks calls to the methods.
	calls struct {
		// FindEnygmaDeposits holds details about calls to the FindEnygmaDeposits method.
		FindEnygmaDeposits []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserAddress is the userAddress argument value.
			UserAddress string
			// TokenAddress is the tokenAddress argument value.
			TokenAddress string
			// PaymentAmount is the paymentAmount argument value.
			PaymentAmount *big.Int
		}
	}
	lockFindEnygmaDeposits sync.RWMutex
}

// FindEnygmaDeposits calls FindEnygmaDepositsFunc.
func (mock *initiatorDepositFinderMock) FindEnygmaDeposits(ctx context.Context, userAddress string, tokenAddress string, paymentAmount *big.Int) ([]*types.DvpDeposit, error) {
	if mock.FindEnygmaDepositsFunc == nil {
		panic("initiatorDepositFinderMock.FindEnygmaDepositsFunc: method is nil but initiatorDepositFinder.FindEnygmaDeposits was just called")
	}
	callInfo := struct {
		Ctx           context.Context
		UserAddress   string
		TokenAddress  string
		PaymentAmount *big.Int
	}{
		Ctx:           ctx,
		UserAddress:   userAddress,
		TokenAddress:  tokenAddress,
		PaymentAmount: paymentAmount,
	}
	mock.lockFindEnygmaDeposits.Lock()
	mock.calls.FindEnygmaDeposits = append(mock.calls.FindEnygmaDeposits, callInfo)
	mock.lockFindEnygmaDeposits.Unlock()
	return mock.FindEnygmaDepositsFunc(ctx, userAddress, tokenAddress, paymentAmount)
}

// FindEnygmaDepositsCalls gets all the calls that were made to FindEnygmaDeposits.
// Check the length with:
//
//	len(mockedinitiatorDepositFinder.FindEnygmaDepositsCalls())
func (mock *initiatorDepositFinderMock) FindEnygmaDepositsCalls() []struct {
	Ctx           context.Context
	UserAddress   string
	TokenAddress  string
	PaymentAmount *big.Int
} {
	var calls []struct {
		Ctx           context.Context
		UserAddress   string
		TokenAddress  string
		PaymentAmount *big.Int
	}
	mock.lockFindEnygmaDeposits.RLock()
	calls = mock.calls.FindEnygmaDeposits
	mock.lockFindEnygmaDeposits.RUnlock()
	return calls
}

// initiatorDepositConsolidatorMock is a mock implementation of handler.initiatorDepositConsolidator.
//
//	func TestSomethingThatUsesinitiatorDepositConsolidator(t *testing.T) {
//
//		// make and configure a mocked handler.initiatorDepositConsolidator
//		mockedinitiatorDepositConsolidator := &initiatorDepositConsolidatorMock{
//			ConsolidateEnygmaDepositsFunc: func(ctx context.Context, id string, sourceViewPublicKey []byte, depositsToConsolidate []*types.DvpDeposit, consolidationAmount *big.Int) ([]*types.DvpDeposit, error) {
//				panic("mock out the ConsolidateEnygmaDeposits method")
//			},
//			PrepareDepositsForJSProofFunc: func(ctx context.Context, id string, sourceViewPublicKey []byte, deposits []*types.DvpDeposit) ([]*types.DvpDeposit, error) {
//				panic("mock out the PrepareDepositsForJSProof method")
//			},
//		}
//
//		// use mockedinitiatorDepositConsolidator in code that requires handler.initiatorDepositConsolidator
//		// and then make assertions.
//
//	}
type initiatorDepositConsolidatorMock struct {
	// ConsolidateEnygmaDepositsFunc mocks the ConsolidateEnygmaDeposits method.
	ConsolidateEnygmaDepositsFunc func(ctx context.Context, id string, sourceViewPublicKey []byte, depositsToConsolidate []*types.DvpDeposit, consolidationAmount *big.Int) ([]*types.DvpDeposit, error)

	// PrepareDepositsForJSProofFunc mocks the PrepareDepositsForJSProof method.
	PrepareDepositsForJSProofFunc func(ctx context.Context, id string, sourceViewPublicKey []byte, deposits []*types.DvpDeposit) ([]*types.DvpDeposit, error)

	// calls tracks calls to the methods.
	calls struct {
		// ConsolidateEnygmaDeposits holds details about calls to the ConsolidateEnygmaDeposits method.
		ConsolidateEnygmaDeposits []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID string
			// SourceViewPublicKey is the sourceViewPublicKey argument value.
			SourceViewPublicKey []byte
			// DepositsToConsolidate is the depositsToConsolidate argument value.
			DepositsToConsolidate []*types.DvpDeposit
			// ConsolidationAmount is the consolidationAmount argument value.
			ConsolidationAmount *big.Int
		}
		// PrepareDepositsForJSProof holds details about calls to the PrepareDepositsForJSProof method.
		PrepareDepositsForJSProof []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID string
			// SourceViewPublicKey is the sourceViewPublicKey argument value.
			SourceViewPublicKey []byte
			// Deposits is the deposits argument value.
			Deposits []*types.DvpDeposit
		}
	}
	lockConsolidateEnygmaDeposits sync.RWMutex
	lockPrepareDepositsForJSProof sync.RWMutex
}

// ConsolidateEnygmaDeposits calls ConsolidateEnygmaDepositsFunc.
func (mock *initiatorDepositConsolidatorMock) ConsolidateEnygmaDeposits(ctx context.Context, id string, sourceViewPublicKey []byte, depositsToConsolidate []*types.DvpDeposit, consolidationAmount *big.Int) ([]*types.DvpDeposit, error) {
	if mock.ConsolidateEnygmaDepositsFunc == nil {
		panic("initiatorDepositConsolidatorMock.ConsolidateEnygmaDepositsFunc: method is nil but initiatorDepositConsolidator.ConsolidateEnygmaDeposits was just called")
	}
	callInfo := struct {
		Ctx                   context.Context
		ID                    string
		SourceViewPublicKey   []byte
		DepositsToConsolidate []*types.DvpDeposit
		ConsolidationAmount   *big.Int
	}{
		Ctx:                   ctx,
		ID:                    id,
		SourceViewPublicKey:   sourceViewPublicKey,
		DepositsToConsolidate: depositsToConsolidate,
		ConsolidationAmount:   consolidationAmount,
	}
	mock.lockConsolidateEnygmaDeposits.Lock()
	mock.calls.ConsolidateEnygmaDeposits = append(mock.calls.ConsolidateEnygmaDeposits, callInfo)
	mock.lockConsolidateEnygmaDeposits.Unlock()
	return mock.ConsolidateEnygmaDepositsFunc(ctx, id, sourceViewPublicKey, depositsToConsolidate, consolidationAmount)
}

// ConsolidateEnygmaDepositsCalls gets all the calls that were made to ConsolidateEnygmaDeposits.
// Check the length with:
//
//	len(mockedinitiatorDepositConsolidator.ConsolidateEnygmaDepositsCalls())
func (mock *initiatorDepositConsolidatorMock) ConsolidateEnygmaDepositsCalls() []struct {
	Ctx                   context.Context
	ID                    string
	SourceViewPublicKey   []byte
	DepositsToConsolidate []*types.DvpDeposit
	ConsolidationAmount   *big.Int
} {
	var calls []struct {
		Ctx                   context.Context
		ID                    string
		SourceViewPublicKey   []byte
		DepositsToConsolidate []*types.DvpDeposit
		ConsolidationAmount   *big.Int
	}
	mock.lockConsolidateEnygmaDeposits.RLock()
	calls = mock.calls.ConsolidateEnygmaDeposits
	mock.lockConsolidateEnygmaDeposits.RUnlock()
	return calls
}

// PrepareDepositsForJSProof calls PrepareDepositsForJSProofFunc.
func (mock *initiatorDepositConsolidatorMock) PrepareDepositsForJSProof(ctx context.Context, id string, sourceViewPublicKey []byte, deposits []*types.DvpDeposit) ([]*types.DvpDeposit, error) {
	if mock.PrepareDepositsForJSProofFunc == nil {
		panic("initiatorDepositConsolidatorMock.PrepareDepositsForJSProofFunc: method is nil but initiatorDepositConsolidator.PrepareDepositsForJSProof was just called")
	}
	callInfo := struct {
		Ctx                 context.Context
		ID                  string
		SourceViewPublicKey []byte
		Deposits            []*types.DvpDeposit
	}{
		Ctx:                 ctx,
		ID:                  id,
		SourceViewPublicKey: sourceViewPublicKey,
		Deposits:            deposits,
	}
	mock.lockPrepareDepositsForJSProof.Lock()
	mock.calls.PrepareDepositsForJSProof = append(mock.calls.PrepareDepositsForJSProof, callInfo)
	mock.lockPrepareDepositsForJSProof.Unlock()
	return mock.PrepareDepositsForJSProofFunc(ctx, id, sourceViewPublicKey, deposits)
}

// PrepareDepositsForJSProofCalls gets all the calls that were made to PrepareDepositsForJSProof.
// Check the length with:
//
//	len(mockedinitiatorDepositConsolidator.PrepareDepositsForJSProofCalls())
func (mock *initiatorDepositConsolidatorMock) PrepareDepositsForJSProofCalls() []struct {
	Ctx                 context.Context
	ID                  string
	SourceViewPublicKey []byte
	Deposits            []*types.DvpDeposit
} {
	var calls []struct {
		Ctx                 context.Context
		ID                  string
		SourceViewPublicKey []byte
		Deposits            []*types.DvpDeposit
	}
	mock.lockPrepareDepositsForJSProof.RLock()
	calls = mock.calls.PrepareDepositsForJSProof
	mock.lockPrepareDepositsForJSProof.RUnlock()
	return calls
}

// initiatorDvpProofGeneratorMock is a mock implementation of handler.initiatorDvpProofGenerator.
//
//	func TestSomethingThatUsesinitiatorDvpProofGenerator(t *testing.T) {
//
//		// make and configure a mocked handler.initiatorDvpProofGenerator
//		mockedinitiatorDvpProofGenerator := &initiatorDvpProofGeneratorMock{
//			GenerateEnygmaJSProofFunc: func(ctx context.Context, sourceViewPublicKey []byte, nftCommitment *big.Int, destinationPaymentPublicKey *big.Int, destinationSalt *big.Int, paymentAmount *big.Int, tokenAddress string, deposits []*types.DvpDeposit) (*dvp.ProofReceipt, error) {
//				panic("mock out the GenerateEnygmaJSProof method")
//			},
//		}
//
//		// use mockedinitiatorDvpProofGenerator in code that requires handler.initiatorDvpProofGenerator
//		// and then make assertions.
//
//	}
type initiatorDvpProofGeneratorMock struct {
	// GenerateEnygmaJSProofFunc mocks the GenerateEnygmaJSProof method.
	GenerateEnygmaJSProofFunc func(ctx context.Context, sourceViewPublicKey []byte, nftCommitment *big.Int, destinationPaymentPublicKey *big.Int, destinationSalt *big.Int, paymentAmount *big.Int, tokenAddress string, deposits []*types.DvpDeposit) (*dvp.ProofReceipt, error)

	// calls tracks calls to the methods.
	calls struct {
		// GenerateEnygmaJSProof holds details about calls to the GenerateEnygmaJSProof method.
		GenerateEnygmaJSProof []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// SourceViewPublicKey is the sourceViewPublicKey argument value.
			SourceViewPublicKey []byte
			// NftCommitment is the nftCommitment argument value.
			NftCommitment *big.Int
			// DestinationPaymentPublicKey is the destinationPaymentPublicKey argument value.
			DestinationPaymentPublicKey *big.Int
			// DestinationSalt is the destinationSalt argument value.
			DestinationSalt *big.Int
			// PaymentAmount is the paymentAmount argument value.
			PaymentAmount *big.Int
			// TokenAddress is the tokenAddress argument value.
			TokenAddress string
			// Deposits is the deposits argument value.
			Deposits []*types.DvpDeposit
		}
	}
	lockGenerateEnygmaJSProof sync.RWMutex
}

// GenerateEnygmaJSProof calls GenerateEnygmaJSProofFunc.
func (mock *initiatorDvpProofGeneratorMock) GenerateEnygmaJSProof(ctx context.Context, sourceViewPublicKey []byte, nftCommitment *big.Int, destinationPaymentPublicKey *big.Int, destinationSalt *big.Int, paymentAmount *big.Int, tokenAddress string, deposits []*types.DvpDeposit) (*dvp.ProofReceipt, error) {
	if mock.GenerateEnygmaJSProofFunc == nil {
		panic("initiatorDvpProofGeneratorMock.GenerateEnygmaJSProofFunc: method is nil but initiatorDvpProofGenerator.GenerateEnygmaJSProof was just called")
	}
	callInfo := struct {
		Ctx                         context.Context
		SourceViewPublicKey         []byte
		NftCommitment               *big.Int
		DestinationPaymentPublicKey *big.Int
		DestinationSalt             *big.Int
		PaymentAmount               *big.Int
		TokenAddress                string
		Deposits                    []*types.DvpDeposit
	}{
		Ctx:                         ctx,
		SourceViewPublicKey:         sourceViewPublicKey,
		NftCommitment:               nftCommitment,
		DestinationPaymentPublicKey: destinationPaymentPublicKey,
		DestinationSalt:             destinationSalt,
		PaymentAmount:               paymentAmount,
		TokenAddress:                tokenAddress,
		Deposits:                    deposits,
	}
	mock.lockGenerateEnygmaJSProof.Lock()
	mock.calls.GenerateEnygmaJSProof = append(mock.calls.GenerateEnygmaJSProof, callInfo)
	mock.lockGenerateEnygmaJSProof.Unlock()
	return mock.GenerateEnygmaJSProofFunc(ctx, sourceViewPublicKey, nftCommitment, destinationPaymentPublicKey, destinationSalt, paymentAmount, tokenAddress, deposits)
}

// GenerateEnygmaJSProofCalls gets all the calls that were made to GenerateEnygmaJSProof.
// Check the length with:
//
//	len(mockedinitiatorDvpProofGenerator.GenerateEnygmaJSProofCalls())
func (mock *initiatorDvpProofGeneratorMock) GenerateEnygmaJSProofCalls() []struct {
	Ctx                         context.Context
	SourceViewPublicKey         []byte
	NftCommitment               *big.Int
	DestinationPaymentPublicKey *big.Int
	DestinationSalt             *big.Int
	PaymentAmount               *big.Int
	TokenAddress                string
	Deposits                    []*types.DvpDeposit
} {
	var calls []struct {
		Ctx                         context.Context
		SourceViewPublicKey         []byte
		NftCommitment               *big.Int
		DestinationPaymentPublicKey *big.Int
		DestinationSalt             *big.Int
		PaymentAmount               *big.Int
		TokenAddress                string
		Deposits                    []*types.DvpDeposit
	}
	mock.lockGenerateEnygmaJSProof.RLock()
	calls = mock.calls.GenerateEnygmaJSProof
	mock.lockGenerateEnygmaJSProof.RUnlock()
	return calls
}

// initiatorTracerMock is a mock implementation of handler.initiatorTracer.
//
//	func TestSomethingThatUsesinitiatorTracer(t *testing.T) {
//
//		// make and configure a mocked handler.initiatorTracer
//		mockedinitiatorTracer := &initiatorTracerMock{
//			StartFunc: func(ctx context.Context, spanName string, opts ...trace.SpanStartOption) (context.Context, trace.Span) {
//				panic("mock out the Start method")
//			},
//		}
//
//		// use mockedinitiatorTracer in code that requires handler.initiatorTracer
//		// and then make assertions.
//
//	}
type initiatorTracerMock struct {
	// StartFunc mocks the Start method.
	StartFunc func(ctx context.Context, spanName string, opts ...trace.SpanStartOption) (context.Context, trace.Span)

	// calls tracks calls to the methods.
	calls struct {
		// Start holds details about calls to the Start method.
		Start []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// SpanName is the spanName argument value.
			SpanName string
			// Opts is the opts argument value.
			Opts []trace.SpanStartOption
		}
	}
	lockStart sync.RWMutex
}

// Start calls StartFunc.
func (mock *initiatorTracerMock) Start(ctx context.Context, spanName string, opts ...trace.SpanStartOption) (context.Context, trace.Span) {
	if mock.StartFunc == nil {
		panic("initiatorTracerMock.StartFunc: method is nil but initiatorTracer.Start was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		SpanName string
		Opts     []trace.SpanStartOption
	}{
		Ctx:      ctx,
		SpanName: spanName,
		Opts:     opts,
	}
	mock.lockStart.Lock()
	mock.calls.Start = append(mock.calls.Start, callInfo)
	mock.lockStart.Unlock()
	return mock.StartFunc(ctx, spanName, opts...)
}

// StartCalls gets all the calls that were made to Start.
// Check the length with:
//
//	len(mockedinitiatorTracer.StartCalls())
func (mock *initiatorTracerMock) StartCalls() []struct {
	Ctx      context.Context
	SpanName string
	Opts     []trace.SpanStartOption
} {
	var calls []struct {
		Ctx      context.Context
		SpanName string
		Opts     []trace.SpanStartOption
	}
	mock.lockStart.RLock()
	calls = mock.calls.Start
	mock.lockStart.RUnlock()
	return calls
}

// initiatorRetryServiceMock is a mock implementation of handler.initiatorRetryService.
//
//	func TestSomethingThatUsesinitiatorRetryService(t *testing.T) {
//
//		// make and configure a mocked handler.initiatorRetryService
//		mockedinitiatorRetryService := &initiatorRetryServiceMock{
//			RetryOperationFunc: func(ctx context.Context, operationName string, maxRetries int, blockNumber uint64, executeOperation func(ctx context.Context, nextBlockNumber uint64) error) (uint64, error) {
//				panic("mock out the RetryOperation method")
//			},
//		}
//
//		// use mockedinitiatorRetryService in code that requires handler.initiatorRetryService
//		// and then make assertions.
//
//	}
type initiatorRetryServiceMock struct {
	// RetryOperationFunc mocks the RetryOperation method.
	RetryOperationFunc func(ctx context.Context, operationName string, maxRetries int, blockNumber uint64, executeOperation func(ctx context.Context, nextBlockNumber uint64) error) (uint64, error)

	// calls tracks calls to the methods.
	calls struct {
		// RetryOperation holds details about calls to the RetryOperation method.
		RetryOperation []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OperationName is the operationName argument value.
			OperationName string
			// MaxRetries is the maxRetries argument value.
			MaxRetries int
			// BlockNumber is the blockNumber argument value.
			BlockNumber uint64
			// ExecuteOperation is the executeOperation argument value.
			ExecuteOperation func(ctx context.Context, nextBlockNumber uint64) error
		}
	}
	lockRetryOperation sync.RWMutex
}

// RetryOperation calls RetryOperationFunc.
func (mock *initiatorRetryServiceMock) RetryOperation(ctx context.Context, operationName string, maxRetries int, blockNumber uint64, executeOperation func(ctx context.Context, nextBlockNumber uint64) error) (uint64, error) {
	if mock.RetryOperationFunc == nil {
		panic("initiatorRetryServiceMock.RetryOperationFunc: method is nil but initiatorRetryService.RetryOperation was just called")
	}
	callInfo := struct {
		Ctx              context.Context
		OperationName    string
		MaxRetries       int
		BlockNumber      uint64
		ExecuteOperation func(ctx context.Context, nextBlockNumber uint64) error
	}{
		Ctx:              ctx,
		OperationName:    operationName,
		MaxRetries:       maxRetries,
		BlockNumber:      blockNumber,
		ExecuteOperation: executeOperation,
	}
	mock.lockRetryOperation.Lock()
	mock.calls.RetryOperation = append(mock.calls.RetryOperation, callInfo)
	mock.lockRetryOperation.Unlock()
	return mock.RetryOperationFunc(ctx, operationName, maxRetries, blockNumber, executeOperation)
}

// RetryOperationCalls gets all the calls that were made to RetryOperation.
// Check the length with:
//
//	len(mockedinitiatorRetryService.RetryOperationCalls())
func (mock *initiatorRetryServiceMock) RetryOperationCalls() []struct {
	Ctx              context.Context
	OperationName    string
	MaxRetries       int
	BlockNumber      uint64
	ExecuteOperation func(ctx context.Context, nextBlockNumber uint64) error
} {
	var calls []struct {
		Ctx              context.Context
		OperationName    string
		MaxRetries       int
		BlockNumber      uint64
		ExecuteOperation func(ctx context.Context, nextBlockNumber uint64) error
	}
	mock.lockRetryOperation.RLock()
	calls = mock.calls.RetryOperation
	mock.lockRetryOperation.RUnlock()
	return calls
}

// initiatorEnygmaBatcherMock is a mock implementation of handler.initiatorEnygmaBatcher.
//
//	func TestSomethingThatUsesinitiatorEnygmaBatcher(t *testing.T) {
//
//		// make and configure a mocked handler.initiatorEnygmaBatcher
//		mockedinitiatorEnygmaBatcher := &initiatorEnygmaBatcherMock{
//			CreateBatchesWithAnonimityFunc: func(ctx context.Context, resourceId string, blockNumber *big.Int, txsByChainID map[string][]*types.EnygmaTransferBatchTx) ([]*types.EnygmaTransferBatch, error) {
//				panic("mock out the CreateBatchesWithAnonimity method")
//			},
//		}
//
//		// use mockedinitiatorEnygmaBatcher in code that requires handler.initiatorEnygmaBatcher
//		// and then make assertions.
//
//	}
type initiatorEnygmaBatcherMock struct {
	// CreateBatchesWithAnonimityFunc mocks the CreateBatchesWithAnonimity method.
	CreateBatchesWithAnonimityFunc func(ctx context.Context, resourceId string, blockNumber *big.Int, txsByChainID map[string][]*types.EnygmaTransferBatchTx) ([]*types.EnygmaTransferBatch, error)

	// calls tracks calls to the methods.
	calls struct {
		// CreateBatchesWithAnonimity holds details about calls to the CreateBatchesWithAnonimity method.
		CreateBatchesWithAnonimity []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ResourceId is the resourceId argument value.
			ResourceId string
			// BlockNumber is the blockNumber argument value.
			BlockNumber *big.Int
			// TxsByChainID is the txsByChainID argument value.
			TxsByChainID map[string][]*types.EnygmaTransferBatchTx
		}
	}
	lockCreateBatchesWithAnonimity sync.RWMutex
}

// CreateBatchesWithAnonimity calls CreateBatchesWithAnonimityFunc.
func (mock *initiatorEnygmaBatcherMock) CreateBatchesWithAnonimity(ctx context.Context, resourceId string, blockNumber *big.Int, txsByChainID map[string][]*types.EnygmaTransferBatchTx) ([]*types.EnygmaTransferBatch, error) {
	if mock.CreateBatchesWithAnonimityFunc == nil {
		panic("initiatorEnygmaBatcherMock.CreateBatchesWithAnonimityFunc: method is nil but initiatorEnygmaBatcher.CreateBatchesWithAnonimity was just called")
	}
	callInfo := struct {
		Ctx          context.Context
		ResourceId   string
		BlockNumber  *big.Int
		TxsByChainID map[string][]*types.EnygmaTransferBatchTx
	}{
		Ctx:          ctx,
		ResourceId:   resourceId,
		BlockNumber:  blockNumber,
		TxsByChainID: txsByChainID,
	}
	mock.lockCreateBatchesWithAnonimity.Lock()
	mock.calls.CreateBatchesWithAnonimity = append(mock.calls.CreateBatchesWithAnonimity, callInfo)
	mock.lockCreateBatchesWithAnonimity.Unlock()
	return mock.CreateBatchesWithAnonimityFunc(ctx, resourceId, blockNumber, txsByChainID)
}

// CreateBatchesWithAnonimityCalls gets all the calls that were made to CreateBatchesWithAnonimity.
// Check the length with:
//
//	len(mockedinitiatorEnygmaBatcher.CreateBatchesWithAnonimityCalls())
func (mock *initiatorEnygmaBatcherMock) CreateBatchesWithAnonimityCalls() []struct {
	Ctx          context.Context
	ResourceId   string
	BlockNumber  *big.Int
	TxsByChainID map[string][]*types.EnygmaTransferBatchTx
} {
	var calls []struct {
		Ctx          context.Context
		ResourceId   string
		BlockNumber  *big.Int
		TxsByChainID map[string][]*types.EnygmaTransferBatchTx
	}
	mock.lockCreateBatchesWithAnonimity.RLock()
	calls = mock.calls.CreateBatchesWithAnonimity
	mock.lockCreateBatchesWithAnonimity.RUnlock()
	return calls
}

// initiatorEnygmaExecutorMock is a mock implementation of handler.initiatorEnygmaExecutor.
//
//	func TestSomethingThatUsesinitiatorEnygmaExecutor(t *testing.T) {
//
//		// make and configure a mocked handler.initiatorEnygmaExecutor
//		mockedinitiatorEnygmaExecutor := &initiatorEnygmaExecutorMock{
//			ExecuteEnygmaCrossTransferFunc: func(ctx context.Context, batchID string, blockNumber uint64, resourceId string, batch map[string][]*types.EnygmaTransferBatchTx, enygmaAddress common.Address) error {
//				panic("mock out the ExecuteEnygmaCrossTransfer method")
//			},
//			ExecuteEnygmaDepositFunc: func(ctx context.Context, id string, resourceId string, amount *big.Int, blockNumber uint64, commitment *big.Int, salt *big.Int, from common.Address, txHash common.Hash, enygmaAddress common.Address) error {
//				panic("mock out the ExecuteEnygmaDeposit method")
//			},
//			ExecuteEnygmaSupplyUpdateFunc: func(ctx context.Context, batchID string, resourceId string, blockNumber uint64, batch types.EnygmaSupplyUpdate, enygmaAddress common.Address) error {
//				panic("mock out the ExecuteEnygmaSupplyUpdate method")
//			},
//			ExecuteEnygmaWithdrawalFunc: func(ctx context.Context, chainEventID string, resourceId string, amount *big.Int, deposits []*types.DvpDeposit, blockNumber uint64, enygmaAddress common.Address, proof *dvp.ProofReceipt, from common.Address, txHash common.Hash) error {
//				panic("mock out the ExecuteEnygmaWithdrawal method")
//			},
//		}
//
//		// use mockedinitiatorEnygmaExecutor in code that requires handler.initiatorEnygmaExecutor
//		// and then make assertions.
//
//	}
type initiatorEnygmaExecutorMock struct {
	// ExecuteEnygmaCrossTransferFunc mocks the ExecuteEnygmaCrossTransfer method.
	ExecuteEnygmaCrossTransferFunc func(ctx context.Context, batchID string, blockNumber uint64, resourceId string, batch map[string][]*types.EnygmaTransferBatchTx, enygmaAddress common.Address) error

	// ExecuteEnygmaDepositFunc mocks the ExecuteEnygmaDeposit method.
	ExecuteEnygmaDepositFunc func(ctx context.Context, id string, resourceId string, amount *big.Int, blockNumber uint64, commitment *big.Int, salt *big.Int, from common.Address, txHash common.Hash, enygmaAddress common.Address) error

	// ExecuteEnygmaSupplyUpdateFunc mocks the ExecuteEnygmaSupplyUpdate method.
	ExecuteEnygmaSupplyUpdateFunc func(ctx context.Context, batchID string, resourceId string, blockNumber uint64, batch types.EnygmaSupplyUpdate, enygmaAddress common.Address) error

	// ExecuteEnygmaWithdrawalFunc mocks the ExecuteEnygmaWithdrawal method.
	ExecuteEnygmaWithdrawalFunc func(ctx context.Context, chainEventID string, resourceId string, amount *big.Int, deposits []*types.DvpDeposit, blockNumber uint64, enygmaAddress common.Address, proof *dvp.ProofReceipt, from common.Address, txHash common.Hash) error

	// calls tracks calls to the methods.
	calls struct {
		// ExecuteEnygmaCrossTransfer holds details about calls to the ExecuteEnygmaCrossTransfer method.
		ExecuteEnygmaCrossTransfer []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// BatchID is the batchID argument value.
			BatchID string
			// BlockNumber is the blockNumber argument value.
			BlockNumber uint64
			// ResourceId is the resourceId argument value.
			ResourceId string
			// Batch is the batch argument value.
			Batch map[string][]*types.EnygmaTransferBatchTx
			// EnygmaAddress is the enygmaAddress argument value.
			EnygmaAddress common.Address
		}
		// ExecuteEnygmaDeposit holds details about calls to the ExecuteEnygmaDeposit method.
		ExecuteEnygmaDeposit []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID string
			// ResourceId is the resourceId argument value.
			ResourceId string
			// Amount is the amount argument value.
			Amount *big.Int
			// BlockNumber is the blockNumber argument value.
			BlockNumber uint64
			// Commitment is the commitment argument value.
			Commitment *big.Int
			// Salt is the salt argument value.
			Salt *big.Int
			// From is the from argument value.
			From common.Address
			// TxHash is the txHash argument value.
			TxHash common.Hash
			// EnygmaAddress is the enygmaAddress argument value.
			EnygmaAddress common.Address
		}
		// ExecuteEnygmaSupplyUpdate holds details about calls to the ExecuteEnygmaSupplyUpdate method.
		ExecuteEnygmaSupplyUpdate []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// BatchID is the batchID argument value.
			BatchID string
			// ResourceId is the resourceId argument value.
			ResourceId string
			// BlockNumber is the blockNumber argument value.
			BlockNumber uint64
			// Batch is the batch argument value.
			Batch types.EnygmaSupplyUpdate
			// EnygmaAddress is the enygmaAddress argument value.
			EnygmaAddress common.Address
		}
		// ExecuteEnygmaWithdrawal holds details about calls to the ExecuteEnygmaWithdrawal method.
		ExecuteEnygmaWithdrawal []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ChainEventID is the chainEventID argument value.
			ChainEventID string
			// ResourceId is the resourceId argument value.
			ResourceId string
			// Amount is the amount argument value.
			Amount *big.Int
			// Deposits is the deposits argument value.
			Deposits []*types.DvpDeposit
			// BlockNumber is the blockNumber argument value.
			BlockNumber uint64
			// EnygmaAddress is the enygmaAddress argument value.
			EnygmaAddress common.Address
			// Proof is the proof argument value.
			Proof *dvp.ProofReceipt
			// From is the from argument value.
			From common.Address
			// TxHash is the txHash argument value.
			TxHash common.Hash
		}
	}
	lockExecuteEnygmaCrossTransfer sync.RWMutex
	lockExecuteEnygmaDeposit       sync.RWMutex
	lockExecuteEnygmaSupplyUpdate  sync.RWMutex
	lockExecuteEnygmaWithdrawal    sync.RWMutex
}

// ExecuteEnygmaCrossTransfer calls ExecuteEnygmaCrossTransferFunc.
func (mock *initiatorEnygmaExecutorMock) ExecuteEnygmaCrossTransfer(ctx context.Context, batchID string, blockNumber uint64, resourceId string, batch map[string][]*types.EnygmaTransferBatchTx, enygmaAddress common.Address) error {
	if mock.ExecuteEnygmaCrossTransferFunc == nil {
		panic("initiatorEnygmaExecutorMock.ExecuteEnygmaCrossTransferFunc: method is nil but initiatorEnygmaExecutor.ExecuteEnygmaCrossTransfer was just called")
	}
	callInfo := struct {
		Ctx           context.Context
		BatchID       string
		BlockNumber   uint64
		ResourceId    string
		Batch         map[string][]*types.EnygmaTransferBatchTx
		EnygmaAddress common.Address
	}{
		Ctx:           ctx,
		BatchID:       batchID,
		BlockNumber:   blockNumber,
		ResourceId:    resourceId,
		Batch:         batch,
		EnygmaAddress: enygmaAddress,
	}
	mock.lockExecuteEnygmaCrossTransfer.Lock()
	mock.calls.ExecuteEnygmaCrossTransfer = append(mock.calls.ExecuteEnygmaCrossTransfer, callInfo)
	mock.lockExecuteEnygmaCrossTransfer.Unlock()
	return mock.ExecuteEnygmaCrossTransferFunc(ctx, batchID, blockNumber, resourceId, batch, enygmaAddress)
}

// ExecuteEnygmaCrossTransferCalls gets all the calls that were made to ExecuteEnygmaCrossTransfer.
// Check the length with:
//
//	len(mockedinitiatorEnygmaExecutor.ExecuteEnygmaCrossTransferCalls())
func (mock *initiatorEnygmaExecutorMock) ExecuteEnygmaCrossTransferCalls() []struct {
	Ctx           context.Context
	BatchID       string
	BlockNumber   uint64
	ResourceId    string
	Batch         map[string][]*types.EnygmaTransferBatchTx
	EnygmaAddress common.Address
} {
	var calls []struct {
		Ctx           context.Context
		BatchID       string
		BlockNumber   uint64
		ResourceId    string
		Batch         map[string][]*types.EnygmaTransferBatchTx
		EnygmaAddress common.Address
	}
	mock.lockExecuteEnygmaCrossTransfer.RLock()
	calls = mock.calls.ExecuteEnygmaCrossTransfer
	mock.lockExecuteEnygmaCrossTransfer.RUnlock()
	return calls
}

// ExecuteEnygmaDeposit calls ExecuteEnygmaDepositFunc.
func (mock *initiatorEnygmaExecutorMock) ExecuteEnygmaDeposit(ctx context.Context, id string, resourceId string, amount *big.Int, blockNumber uint64, commitment *big.Int, salt *big.Int, from common.Address, txHash common.Hash, enygmaAddress common.Address) error {
	if mock.ExecuteEnygmaDepositFunc == nil {
		panic("initiatorEnygmaExecutorMock.ExecuteEnygmaDepositFunc: method is nil but initiatorEnygmaExecutor.ExecuteEnygmaDeposit was just called")
	}
	callInfo := struct {
		Ctx           context.Context
		ID            string
		ResourceId    string
		Amount        *big.Int
		BlockNumber   uint64
		Commitment    *big.Int
		Salt          *big.Int
		From          common.Address
		TxHash        common.Hash
		EnygmaAddress common.Address
	}{
		Ctx:           ctx,
		ID:            id,
		ResourceId:    resourceId,
		Amount:        amount,
		BlockNumber:   blockNumber,
		Commitment:    commitment,
		Salt:          salt,
		From:          from,
		TxHash:        txHash,
		EnygmaAddress: enygmaAddress,
	}
	mock.lockExecuteEnygmaDeposit.Lock()
	mock.calls.ExecuteEnygmaDeposit = append(mock.calls.ExecuteEnygmaDeposit, callInfo)
	mock.lockExecuteEnygmaDeposit.Unlock()
	return mock.ExecuteEnygmaDepositFunc(ctx, id, resourceId, amount, blockNumber, commitment, salt, from, txHash, enygmaAddress)
}

// ExecuteEnygmaDepositCalls gets all the calls that were made to ExecuteEnygmaDeposit.
// Check the length with:
//
//	len(mockedinitiatorEnygmaExecutor.ExecuteEnygmaDepositCalls())
func (mock *initiatorEnygmaExecutorMock) ExecuteEnygmaDepositCalls() []struct {
	Ctx           context.Context
	ID            string
	ResourceId    string
	Amount        *big.Int
	BlockNumber   uint64
	Commitment    *big.Int
	Salt          *big.Int
	From          common.Address
	TxHash        common.Hash
	EnygmaAddress common.Address
} {
	var calls []struct {
		Ctx           context.Context
		ID            string
		ResourceId    string
		Amount        *big.Int
		BlockNumber   uint64
		Commitment    *big.Int
		Salt          *big.Int
		From          common.Address
		TxHash        common.Hash
		EnygmaAddress common.Address
	}
	mock.lockExecuteEnygmaDeposit.RLock()
	calls = mock.calls.ExecuteEnygmaDeposit
	mock.lockExecuteEnygmaDeposit.RUnlock()
	return calls
}

// ExecuteEnygmaSupplyUpdate calls ExecuteEnygmaSupplyUpdateFunc.
func (mock *initiatorEnygmaExecutorMock) ExecuteEnygmaSupplyUpdate(ctx context.Context, batchID string, resourceId string, blockNumber uint64, batch types.EnygmaSupplyUpdate, enygmaAddress common.Address) error {
	if mock.ExecuteEnygmaSupplyUpdateFunc == nil {
		panic("initiatorEnygmaExecutorMock.ExecuteEnygmaSupplyUpdateFunc: method is nil but initiatorEnygmaExecutor.ExecuteEnygmaSupplyUpdate was just called")
	}
	callInfo := struct {
		Ctx           context.Context
		BatchID       string
		ResourceId    string
		BlockNumber   uint64
		Batch         types.EnygmaSupplyUpdate
		EnygmaAddress common.Address
	}{
		Ctx:           ctx,
		BatchID:       batchID,
		ResourceId:    resourceId,
		BlockNumber:   blockNumber,
		Batch:         batch,
		EnygmaAddress: enygmaAddress,
	}
	mock.lockExecuteEnygmaSupplyUpdate.Lock()
	mock.calls.ExecuteEnygmaSupplyUpdate = append(mock.calls.ExecuteEnygmaSupplyUpdate, callInfo)
	mock.lockExecuteEnygmaSupplyUpdate.Unlock()
	return mock.ExecuteEnygmaSupplyUpdateFunc(ctx, batchID, resourceId, blockNumber, batch, enygmaAddress)
}

// ExecuteEnygmaSupplyUpdateCalls gets all the calls that were made to ExecuteEnygmaSupplyUpdate.
// Check the length with:
//
//	len(mockedinitiatorEnygmaExecutor.ExecuteEnygmaSupplyUpdateCalls())
func (mock *initiatorEnygmaExecutorMock) ExecuteEnygmaSupplyUpdateCalls() []struct {
	Ctx           context.Context
	BatchID       string
	ResourceId    string
	BlockNumber   uint64
	Batch         types.EnygmaSupplyUpdate
	EnygmaAddress common.Address
} {
	var calls []struct {
		Ctx           context.Context
		BatchID       string
		ResourceId    string
		BlockNumber   uint64
		Batch         types.EnygmaSupplyUpdate
		EnygmaAddress common.Address
	}
	mock.lockExecuteEnygmaSupplyUpdate.RLock()
	calls = mock.calls.ExecuteEnygmaSupplyUpdate
	mock.lockExecuteEnygmaSupplyUpdate.RUnlock()
	return calls
}

// ExecuteEnygmaWithdrawal calls ExecuteEnygmaWithdrawalFunc.
func (mock *initiatorEnygmaExecutorMock) ExecuteEnygmaWithdrawal(ctx context.Context, chainEventID string, resourceId string, amount *big.Int, deposits []*types.DvpDeposit, blockNumber uint64, enygmaAddress common.Address, proof *dvp.ProofReceipt, from common.Address, txHash common.Hash) error {
	if mock.ExecuteEnygmaWithdrawalFunc == nil {
		panic("initiatorEnygmaExecutorMock.ExecuteEnygmaWithdrawalFunc: method is nil but initiatorEnygmaExecutor.ExecuteEnygmaWithdrawal was just called")
	}
	callInfo := struct {
		Ctx           context.Context
		ChainEventID  string
		ResourceId    string
		Amount        *big.Int
		Deposits      []*types.DvpDeposit
		BlockNumber   uint64
		EnygmaAddress common.Address
		Proof         *dvp.ProofReceipt
		From          common.Address
		TxHash        common.Hash
	}{
		Ctx:           ctx,
		ChainEventID:  chainEventID,
		ResourceId:    resourceId,
		Amount:        amount,
		Deposits:      deposits,
		BlockNumber:   blockNumber,
		EnygmaAddress: enygmaAddress,
		Proof:         proof,
		From:          from,
		TxHash:        txHash,
	}
	mock.lockExecuteEnygmaWithdrawal.Lock()
	mock.calls.ExecuteEnygmaWithdrawal = append(mock.calls.ExecuteEnygmaWithdrawal, callInfo)
	mock.lockExecuteEnygmaWithdrawal.Unlock()
	return mock.ExecuteEnygmaWithdrawalFunc(ctx, chainEventID, resourceId, amount, deposits, blockNumber, enygmaAddress, proof, from, txHash)
}

// ExecuteEnygmaWithdrawalCalls gets all the calls that were made to ExecuteEnygmaWithdrawal.
// Check the length with:
//
//	len(mockedinitiatorEnygmaExecutor.ExecuteEnygmaWithdrawalCalls())
func (mock *initiatorEnygmaExecutorMock) ExecuteEnygmaWithdrawalCalls() []struct {
	Ctx           context.Context
	ChainEventID  string
	ResourceId    string
	Amount        *big.Int
	Deposits      []*types.DvpDeposit
	BlockNumber   uint64
	EnygmaAddress common.Address
	Proof         *dvp.ProofReceipt
	From          common.Address
	TxHash        common.Hash
} {
	var calls []struct {
		Ctx           context.Context
		ChainEventID  string
		ResourceId    string
		Amount        *big.Int
		Deposits      []*types.DvpDeposit
		BlockNumber   uint64
		EnygmaAddress common.Address
		Proof         *dvp.ProofReceipt
		From          common.Address
		TxHash        common.Hash
	}
	mock.lockExecuteEnygmaWithdrawal.RLock()
	calls = mock.calls.ExecuteEnygmaWithdrawal
	mock.lockExecuteEnygmaWithdrawal.RUnlock()
	return calls
}

// initiatorEnygmaFinalizationServiceMock is a mock implementation of handler.initiatorEnygmaFinalizationService.
//
//	func TestSomethingThatUsesinitiatorEnygmaFinalizationService(t *testing.T) {
//
//		// make and configure a mocked handler.initiatorEnygmaFinalizationService
//		mockedinitiatorEnygmaFinalizationService := &initiatorEnygmaFinalizationServiceMock{
//			ExecuteFinalizationFunc: func(ctx context.Context, id string, blockNumber uint64, resourceId string) error {
//				panic("mock out the ExecuteFinalization method")
//			},
//		}
//
//		// use mockedinitiatorEnygmaFinalizationService in code that requires handler.initiatorEnygmaFinalizationService
//		// and then make assertions.
//
//	}
type initiatorEnygmaFinalizationServiceMock struct {
	// ExecuteFinalizationFunc mocks the ExecuteFinalization method.
	ExecuteFinalizationFunc func(ctx context.Context, id string, blockNumber uint64, resourceId string) error

	// calls tracks calls to the methods.
	calls struct {
		// ExecuteFinalization holds details about calls to the ExecuteFinalization method.
		ExecuteFinalization []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID string
			// BlockNumber is the blockNumber argument value.
			BlockNumber uint64
			// ResourceId is the resourceId argument value.
			ResourceId string
		}
	}
	lockExecuteFinalization sync.RWMutex
}

// ExecuteFinalization calls ExecuteFinalizationFunc.
func (mock *initiatorEnygmaFinalizationServiceMock) ExecuteFinalization(ctx context.Context, id string, blockNumber uint64, resourceId string) error {
	if mock.ExecuteFinalizationFunc == nil {
		panic("initiatorEnygmaFinalizationServiceMock.ExecuteFinalizationFunc: method is nil but initiatorEnygmaFinalizationService.ExecuteFinalization was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		ID          string
		BlockNumber uint64
		ResourceId  string
	}{
		Ctx:         ctx,
		ID:          id,
		BlockNumber: blockNumber,
		ResourceId:  resourceId,
	}
	mock.lockExecuteFinalization.Lock()
	mock.calls.ExecuteFinalization = append(mock.calls.ExecuteFinalization, callInfo)
	mock.lockExecuteFinalization.Unlock()
	return mock.ExecuteFinalizationFunc(ctx, id, blockNumber, resourceId)
}

// ExecuteFinalizationCalls gets all the calls that were made to ExecuteFinalization.
// Check the length with:
//
//	len(mockedinitiatorEnygmaFinalizationService.ExecuteFinalizationCalls())
func (mock *initiatorEnygmaFinalizationServiceMock) ExecuteFinalizationCalls() []struct {
	Ctx         context.Context
	ID          string
	BlockNumber uint64
	ResourceId  string
} {
	var calls []struct {
		Ctx         context.Context
		ID          string
		BlockNumber uint64
		ResourceId  string
	}
	mock.lockExecuteFinalization.RLock()
	calls = mock.calls.ExecuteFinalization
	mock.lockExecuteFinalization.RUnlock()
	return calls
}

// initiatorEnygmaCreationServiceMock is a mock implementation of handler.initiatorEnygmaCreationService.
//
//	func TestSomethingThatUsesinitiatorEnygmaCreationService(t *testing.T) {
//
//		// make and configure a mocked handler.initiatorEnygmaCreationService
//		mockedinitiatorEnygmaCreationService := &initiatorEnygmaCreationServiceMock{
//			CreateEnygmaFunc: func(ctx context.Context, resourceId string, fromChainId *big.Int, blockNumberPrivateHub *big.Int) error {
//				panic("mock out the CreateEnygma method")
//			},
//		}
//
//		// use mockedinitiatorEnygmaCreationService in code that requires handler.initiatorEnygmaCreationService
//		// and then make assertions.
//
//	}
type initiatorEnygmaCreationServiceMock struct {
	// CreateEnygmaFunc mocks the CreateEnygma method.
	CreateEnygmaFunc func(ctx context.Context, resourceId string, fromChainId *big.Int, blockNumberPrivateHub *big.Int) error

	// calls tracks calls to the methods.
	calls struct {
		// CreateEnygma holds details about calls to the CreateEnygma method.
		CreateEnygma []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ResourceId is the resourceId argument value.
			ResourceId string
			// FromChainId is the fromChainId argument value.
			FromChainId *big.Int
			// BlockNumberPrivateHub is the blockNumberPrivateHub argument value.
			BlockNumberPrivateHub *big.Int
		}
	}
	lockCreateEnygma sync.RWMutex
}

// CreateEnygma calls CreateEnygmaFunc.
func (mock *initiatorEnygmaCreationServiceMock) CreateEnygma(ctx context.Context, resourceId string, fromChainId *big.Int, blockNumberPrivateHub *big.Int) error {
	if mock.CreateEnygmaFunc == nil {
		panic("initiatorEnygmaCreationServiceMock.CreateEnygmaFunc: method is nil but initiatorEnygmaCreationService.CreateEnygma was just called")
	}
	callInfo := struct {
		Ctx                   context.Context
		ResourceId            string
		FromChainId           *big.Int
		BlockNumberPrivateHub *big.Int
	}{
		Ctx:                   ctx,
		ResourceId:            resourceId,
		FromChainId:           fromChainId,
		BlockNumberPrivateHub: blockNumberPrivateHub,
	}
	mock.lockCreateEnygma.Lock()
	mock.calls.CreateEnygma = append(mock.calls.CreateEnygma, callInfo)
	mock.lockCreateEnygma.Unlock()
	return mock.CreateEnygmaFunc(ctx, resourceId, fromChainId, blockNumberPrivateHub)
}

// CreateEnygmaCalls gets all the calls that were made to CreateEnygma.
// Check the length with:
//
//	len(mockedinitiatorEnygmaCreationService.CreateEnygmaCalls())
func (mock *initiatorEnygmaCreationServiceMock) CreateEnygmaCalls() []struct {
	Ctx                   context.Context
	ResourceId            string
	FromChainId           *big.Int
	BlockNumberPrivateHub *big.Int
} {
	var calls []struct {
		Ctx                   context.Context
		ResourceId            string
		FromChainId           *big.Int
		BlockNumberPrivateHub *big.Int
	}
	mock.lockCreateEnygma.RLock()
	calls = mock.calls.CreateEnygma
	mock.lockCreateEnygma.RUnlock()
	return calls
}
