// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package logparser_test

import (
	"context"
	"github.com/raylsnetwork/rayls-sovereign-relayer/msgqueue"
	shrservice "github.com/raylsnetwork/rayls-sovereign-relayer/private-relayer/shared/service"
	"github.com/raylsnetwork/rayls-sovereign-relayer/private-relayer/source/logparser"
	"github.com/raylsnetwork/rayls-sovereign-relayer/private-relayer/source/logrouter"
	"github.com/raylsnetwork/rayls-sovereign-relayer/private-relayer/source/service"
	"math/big"
	"sync"
)

// Ensure, that EndpointMQMock does implement logparser.EndpointMQ.
// If this is not the case, regenerate this file with moq.
var _ logparser.EndpointMQ = &EndpointMQMock{}

// EndpointMQMock is a mock implementation of logparser.EndpointMQ.
//
//	func TestSomethingThatUsesEndpointMQ(t *testing.T) {
//
//		// make and configure a mocked logparser.EndpointMQ
//		mockedEndpointMQ := &EndpointMQMock{
//			NextFunc: func(ctx context.Context) (msgqueue.Message[logrouter.Block], error) {
//				panic("mock out the Next method")
//			},
//		}
//
//		// use mockedEndpointMQ in code that requires logparser.EndpointMQ
//		// and then make assertions.
//
//	}
type EndpointMQMock struct {
	// NextFunc mocks the Next method.
	NextFunc func(ctx context.Context) (msgqueue.Message[logrouter.Block], error)

	// calls tracks calls to the methods.
	calls struct {
		// Next holds details about calls to the Next method.
		Next []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
	}
	lockNext sync.RWMutex
}

// Next calls NextFunc.
func (mock *EndpointMQMock) Next(ctx context.Context) (msgqueue.Message[logrouter.Block], error) {
	if mock.NextFunc == nil {
		panic("EndpointMQMock.NextFunc: method is nil but EndpointMQ.Next was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockNext.Lock()
	mock.calls.Next = append(mock.calls.Next, callInfo)
	mock.lockNext.Unlock()
	return mock.NextFunc(ctx)
}

// NextCalls gets all the calls that were made to Next.
// Check the length with:
//
//	len(mockedEndpointMQ.NextCalls())
func (mock *EndpointMQMock) NextCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockNext.RLock()
	calls = mock.calls.Next
	mock.lockNext.RUnlock()
	return calls
}

// Ensure, that CrossChainMQMock does implement logparser.CrossChainMQ.
// If this is not the case, regenerate this file with moq.
var _ logparser.CrossChainMQ = &CrossChainMQMock{}

// CrossChainMQMock is a mock implementation of logparser.CrossChainMQ.
//
//	func TestSomethingThatUsesCrossChainMQ(t *testing.T) {
//
//		// make and configure a mocked logparser.CrossChainMQ
//		mockedCrossChainMQ := &CrossChainMQMock{
//			PushFunc: func(contextMoqParam context.Context, crossChainMessage service.CrossChainMessage) error {
//				panic("mock out the Push method")
//			},
//		}
//
//		// use mockedCrossChainMQ in code that requires logparser.CrossChainMQ
//		// and then make assertions.
//
//	}
type CrossChainMQMock struct {
	// PushFunc mocks the Push method.
	PushFunc func(contextMoqParam context.Context, crossChainMessage service.CrossChainMessage) error

	// calls tracks calls to the methods.
	calls struct {
		// Push holds details about calls to the Push method.
		Push []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// CrossChainMessage is the crossChainMessage argument value.
			CrossChainMessage service.CrossChainMessage
		}
	}
	lockPush sync.RWMutex
}

// Push calls PushFunc.
func (mock *CrossChainMQMock) Push(contextMoqParam context.Context, crossChainMessage service.CrossChainMessage) error {
	if mock.PushFunc == nil {
		panic("CrossChainMQMock.PushFunc: method is nil but CrossChainMQ.Push was just called")
	}
	callInfo := struct {
		ContextMoqParam   context.Context
		CrossChainMessage service.CrossChainMessage
	}{
		ContextMoqParam:   contextMoqParam,
		CrossChainMessage: crossChainMessage,
	}
	mock.lockPush.Lock()
	mock.calls.Push = append(mock.calls.Push, callInfo)
	mock.lockPush.Unlock()
	return mock.PushFunc(contextMoqParam, crossChainMessage)
}

// PushCalls gets all the calls that were made to Push.
// Check the length with:
//
//	len(mockedCrossChainMQ.PushCalls())
func (mock *CrossChainMQMock) PushCalls() []struct {
	ContextMoqParam   context.Context
	CrossChainMessage service.CrossChainMessage
} {
	var calls []struct {
		ContextMoqParam   context.Context
		CrossChainMessage service.CrossChainMessage
	}
	mock.lockPush.RLock()
	calls = mock.calls.Push
	mock.lockPush.RUnlock()
	return calls
}

// Ensure, that PrivateHubMQMock does implement logparser.PrivateHubMQ.
// If this is not the case, regenerate this file with moq.
var _ logparser.PrivateHubMQ = &PrivateHubMQMock{}

// PrivateHubMQMock is a mock implementation of logparser.PrivateHubMQ.
//
//	func TestSomethingThatUsesPrivateHubMQ(t *testing.T) {
//
//		// make and configure a mocked logparser.PrivateHubMQ
//		mockedPrivateHubMQ := &PrivateHubMQMock{
//			PushFunc: func(contextMoqParam context.Context, privateHubMessage shrservice.PrivateHubMessage) error {
//				panic("mock out the Push method")
//			},
//		}
//
//		// use mockedPrivateHubMQ in code that requires logparser.PrivateHubMQ
//		// and then make assertions.
//
//	}
type PrivateHubMQMock struct {
	// PushFunc mocks the Push method.
	PushFunc func(contextMoqParam context.Context, privateHubMessage shrservice.PrivateHubMessage) error

	// calls tracks calls to the methods.
	calls struct {
		// Push holds details about calls to the Push method.
		Push []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// PrivateHubMessage is the privateHubMessage argument value.
			PrivateHubMessage shrservice.PrivateHubMessage
		}
	}
	lockPush sync.RWMutex
}

// Push calls PushFunc.
func (mock *PrivateHubMQMock) Push(contextMoqParam context.Context, privateHubMessage shrservice.PrivateHubMessage) error {
	if mock.PushFunc == nil {
		panic("PrivateHubMQMock.PushFunc: method is nil but PrivateHubMQ.Push was just called")
	}
	callInfo := struct {
		ContextMoqParam   context.Context
		PrivateHubMessage shrservice.PrivateHubMessage
	}{
		ContextMoqParam:   contextMoqParam,
		PrivateHubMessage: privateHubMessage,
	}
	mock.lockPush.Lock()
	mock.calls.Push = append(mock.calls.Push, callInfo)
	mock.lockPush.Unlock()
	return mock.PushFunc(contextMoqParam, privateHubMessage)
}

// PushCalls gets all the calls that were made to Push.
// Check the length with:
//
//	len(mockedPrivateHubMQ.PushCalls())
func (mock *PrivateHubMQMock) PushCalls() []struct {
	ContextMoqParam   context.Context
	PrivateHubMessage shrservice.PrivateHubMessage
} {
	var calls []struct {
		ContextMoqParam   context.Context
		PrivateHubMessage shrservice.PrivateHubMessage
	}
	mock.lockPush.RLock()
	calls = mock.calls.Push
	mock.lockPush.RUnlock()
	return calls
}

// Ensure, that KeysServiceMock does implement logparser.KeysService.
// If this is not the case, regenerate this file with moq.
var _ logparser.KeysService = &KeysServiceMock{}

// KeysServiceMock is a mock implementation of logparser.KeysService.
//
//	func TestSomethingThatUsesKeysService(t *testing.T) {
//
//		// make and configure a mocked logparser.KeysService
//		mockedKeysService := &KeysServiceMock{
//			UpdateRaylsViewKeysFunc: func(contextMoqParam context.Context, intMoqParam *big.Int) error {
//				panic("mock out the UpdateRaylsViewKeys method")
//			},
//		}
//
//		// use mockedKeysService in code that requires logparser.KeysService
//		// and then make assertions.
//
//	}
type KeysServiceMock struct {
	// UpdateRaylsViewKeysFunc mocks the UpdateRaylsViewKeys method.
	UpdateRaylsViewKeysFunc func(contextMoqParam context.Context, intMoqParam *big.Int) error

	// calls tracks calls to the methods.
	calls struct {
		// UpdateRaylsViewKeys holds details about calls to the UpdateRaylsViewKeys method.
		UpdateRaylsViewKeys []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// IntMoqParam is the intMoqParam argument value.
			IntMoqParam *big.Int
		}
	}
	lockUpdateRaylsViewKeys sync.RWMutex
}

// UpdateRaylsViewKeys calls UpdateRaylsViewKeysFunc.
func (mock *KeysServiceMock) UpdateRaylsViewKeys(contextMoqParam context.Context, intMoqParam *big.Int) error {
	if mock.UpdateRaylsViewKeysFunc == nil {
		panic("KeysServiceMock.UpdateRaylsViewKeysFunc: method is nil but KeysService.UpdateRaylsViewKeys was just called")
	}
	callInfo := struct {
		ContextMoqParam context.Context
		IntMoqParam     *big.Int
	}{
		ContextMoqParam: contextMoqParam,
		IntMoqParam:     intMoqParam,
	}
	mock.lockUpdateRaylsViewKeys.Lock()
	mock.calls.UpdateRaylsViewKeys = append(mock.calls.UpdateRaylsViewKeys, callInfo)
	mock.lockUpdateRaylsViewKeys.Unlock()
	return mock.UpdateRaylsViewKeysFunc(contextMoqParam, intMoqParam)
}

// UpdateRaylsViewKeysCalls gets all the calls that were made to UpdateRaylsViewKeys.
// Check the length with:
//
//	len(mockedKeysService.UpdateRaylsViewKeysCalls())
func (mock *KeysServiceMock) UpdateRaylsViewKeysCalls() []struct {
	ContextMoqParam context.Context
	IntMoqParam     *big.Int
} {
	var calls []struct {
		ContextMoqParam context.Context
		IntMoqParam     *big.Int
	}
	mock.lockUpdateRaylsViewKeys.RLock()
	calls = mock.calls.UpdateRaylsViewKeys
	mock.lockUpdateRaylsViewKeys.RUnlock()
	return calls
}
