// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package logparser_test

import (
	"context"
	"github.com/raylsnetwork/rayls-sovereign-relayer/msgqueue"
	"github.com/raylsnetwork/rayls-sovereign-relayer/private-relayer/source/logparser"
	"github.com/raylsnetwork/rayls-sovereign-relayer/private-relayer/source/logrouter"
	"github.com/raylsnetwork/rayls-sovereign-relayer/private-relayer/source/service"
	"sync"
)

// Ensure, that EnygmaBlockMQMock does implement logparser.EnygmaBlockMQ.
// If this is not the case, regenerate this file with moq.
var _ logparser.EnygmaBlockMQ = &EnygmaBlockMQMock{}

// EnygmaBlockMQMock is a mock implementation of logparser.EnygmaBlockMQ.
//
//	func TestSomethingThatUsesEnygmaBlockMQ(t *testing.T) {
//
//		// make and configure a mocked logparser.EnygmaBlockMQ
//		mockedEnygmaBlockMQ := &EnygmaBlockMQMock{
//			NextFunc: func(ctx context.Context) (msgqueue.Message[logrouter.Block], error) {
//				panic("mock out the Next method")
//			},
//		}
//
//		// use mockedEnygmaBlockMQ in code that requires logparser.EnygmaBlockMQ
//		// and then make assertions.
//
//	}
type EnygmaBlockMQMock struct {
	// NextFunc mocks the Next method.
	NextFunc func(ctx context.Context) (msgqueue.Message[logrouter.Block], error)

	// calls tracks calls to the methods.
	calls struct {
		// Next holds details about calls to the Next method.
		Next []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
	}
	lockNext sync.RWMutex
}

// Next calls NextFunc.
func (mock *EnygmaBlockMQMock) Next(ctx context.Context) (msgqueue.Message[logrouter.Block], error) {
	if mock.NextFunc == nil {
		panic("EnygmaBlockMQMock.NextFunc: method is nil but EnygmaBlockMQ.Next was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockNext.Lock()
	mock.calls.Next = append(mock.calls.Next, callInfo)
	mock.lockNext.Unlock()
	return mock.NextFunc(ctx)
}

// NextCalls gets all the calls that were made to Next.
// Check the length with:
//
//	len(mockedEnygmaBlockMQ.NextCalls())
func (mock *EnygmaBlockMQMock) NextCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockNext.RLock()
	calls = mock.calls.Next
	mock.lockNext.RUnlock()
	return calls
}

// Ensure, that EnygmaEventMQMock does implement logparser.EnygmaEventMQ.
// If this is not the case, regenerate this file with moq.
var _ logparser.EnygmaEventMQ = &EnygmaEventMQMock{}

// EnygmaEventMQMock is a mock implementation of logparser.EnygmaEventMQ.
//
//	func TestSomethingThatUsesEnygmaEventMQ(t *testing.T) {
//
//		// make and configure a mocked logparser.EnygmaEventMQ
//		mockedEnygmaEventMQ := &EnygmaEventMQMock{
//			PushFunc: func(contextMoqParam context.Context, enygmaSerializedEvent service.EnygmaSerializedEvent) error {
//				panic("mock out the Push method")
//			},
//			PushBatchChunkedFunc: func(contextMoqParam context.Context, enygmaSerializedEvents []service.EnygmaSerializedEvent) error {
//				panic("mock out the PushBatchChunked method")
//			},
//		}
//
//		// use mockedEnygmaEventMQ in code that requires logparser.EnygmaEventMQ
//		// and then make assertions.
//
//	}
type EnygmaEventMQMock struct {
	// PushFunc mocks the Push method.
	PushFunc func(contextMoqParam context.Context, enygmaSerializedEvent service.EnygmaSerializedEvent) error

	// PushBatchChunkedFunc mocks the PushBatchChunked method.
	PushBatchChunkedFunc func(contextMoqParam context.Context, enygmaSerializedEvents []service.EnygmaSerializedEvent) error

	// calls tracks calls to the methods.
	calls struct {
		// Push holds details about calls to the Push method.
		Push []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// EnygmaSerializedEvent is the enygmaSerializedEvent argument value.
			EnygmaSerializedEvent service.EnygmaSerializedEvent
		}
		// PushBatchChunked holds details about calls to the PushBatchChunked method.
		PushBatchChunked []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// EnygmaSerializedEvents is the enygmaSerializedEvents argument value.
			EnygmaSerializedEvents []service.EnygmaSerializedEvent
		}
	}
	lockPush      sync.RWMutex
	lockPushBatchChunked sync.RWMutex
}

// Push calls PushFunc.
func (mock *EnygmaEventMQMock) Push(contextMoqParam context.Context, enygmaSerializedEvent service.EnygmaSerializedEvent) error {
	if mock.PushFunc == nil {
		panic("EnygmaEventMQMock.PushFunc: method is nil but EnygmaEventMQ.Push was just called")
	}
	callInfo := struct {
		ContextMoqParam       context.Context
		EnygmaSerializedEvent service.EnygmaSerializedEvent
	}{
		ContextMoqParam:       contextMoqParam,
		EnygmaSerializedEvent: enygmaSerializedEvent,
	}
	mock.lockPush.Lock()
	mock.calls.Push = append(mock.calls.Push, callInfo)
	mock.lockPush.Unlock()
	return mock.PushFunc(contextMoqParam, enygmaSerializedEvent)
}

// PushCalls gets all the calls that were made to Push.
// Check the length with:
//
//	len(mockedEnygmaEventMQ.PushCalls())
func (mock *EnygmaEventMQMock) PushCalls() []struct {
	ContextMoqParam       context.Context
	EnygmaSerializedEvent service.EnygmaSerializedEvent
} {
	var calls []struct {
		ContextMoqParam       context.Context
		EnygmaSerializedEvent service.EnygmaSerializedEvent
	}
	mock.lockPush.RLock()
	calls = mock.calls.Push
	mock.lockPush.RUnlock()
	return calls
}

// PushBatchChunked calls PushBatchChunkedFunc.
func (mock *EnygmaEventMQMock) PushBatchChunked(contextMoqParam context.Context, enygmaSerializedEvents []service.EnygmaSerializedEvent) error {
	if mock.PushBatchChunkedFunc == nil {
		panic("EnygmaEventMQMock.PushBatchChunkedFunc: method is nil but EnygmaEventMQ.PushBatchChunked was just called")
	}
	callInfo := struct {
		ContextMoqParam        context.Context
		EnygmaSerializedEvents []service.EnygmaSerializedEvent
	}{
		ContextMoqParam:        contextMoqParam,
		EnygmaSerializedEvents: enygmaSerializedEvents,
	}
	mock.lockPushBatchChunked.Lock()
	mock.calls.PushBatchChunked = append(mock.calls.PushBatchChunked, callInfo)
	mock.lockPushBatchChunked.Unlock()
	return mock.PushBatchChunkedFunc(contextMoqParam, enygmaSerializedEvents)
}

// PushBatchChunkedCalls gets all the calls that were made to PushBatchChunked.
// Check the length with:
//
//	len(mockedEnygmaEventMQ.PushBatchChunkedCalls())
func (mock *EnygmaEventMQMock) PushBatchChunkedCalls() []struct {
	ContextMoqParam        context.Context
	EnygmaSerializedEvents []service.EnygmaSerializedEvent
} {
	var calls []struct {
		ContextMoqParam        context.Context
		EnygmaSerializedEvents []service.EnygmaSerializedEvent
	}
	mock.lockPushBatchChunked.RLock()
	calls = mock.calls.PushBatchChunked
	mock.lockPushBatchChunked.RUnlock()
	return calls
}

// Ensure, that DvpBatchMQMock does implement logparser.DvpBatchMQ.
// If this is not the case, regenerate this file with moq.
var _ logparser.DvpBatchMQ = &DvpBatchMQMock{}

// DvpBatchMQMock is a mock implementation of logparser.DvpBatchMQ.
//
//	func TestSomethingThatUsesDvpBatchMQ(t *testing.T) {
//
//		// make and configure a mocked logparser.DvpBatchMQ
//		mockedDvpBatchMQ := &DvpBatchMQMock{
//			PushFunc: func(contextMoqParam context.Context, dvpSerializedEventBatch service.DvpSerializedEventBatch) error {
//				panic("mock out the Push method")
//			},
//		}
//
//		// use mockedDvpBatchMQ in code that requires logparser.DvpBatchMQ
//		// and then make assertions.
//
//	}
type DvpBatchMQMock struct {
	// PushFunc mocks the Push method.
	PushFunc func(contextMoqParam context.Context, dvpSerializedEventBatch service.DvpSerializedEventBatch) error

	// calls tracks calls to the methods.
	calls struct {
		// Push holds details about calls to the Push method.
		Push []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// DvpSerializedEventBatch is the dvpSerializedEventBatch argument value.
			DvpSerializedEventBatch service.DvpSerializedEventBatch
		}
	}
	lockPush sync.RWMutex
}

// Push calls PushFunc.
func (mock *DvpBatchMQMock) Push(contextMoqParam context.Context, dvpSerializedEventBatch service.DvpSerializedEventBatch) error {
	if mock.PushFunc == nil {
		panic("DvpBatchMQMock.PushFunc: method is nil but DvpBatchMQ.Push was just called")
	}
	callInfo := struct {
		ContextMoqParam         context.Context
		DvpSerializedEventBatch service.DvpSerializedEventBatch
	}{
		ContextMoqParam:         contextMoqParam,
		DvpSerializedEventBatch: dvpSerializedEventBatch,
	}
	mock.lockPush.Lock()
	mock.calls.Push = append(mock.calls.Push, callInfo)
	mock.lockPush.Unlock()
	return mock.PushFunc(contextMoqParam, dvpSerializedEventBatch)
}

// PushCalls gets all the calls that were made to Push.
// Check the length with:
//
//	len(mockedDvpBatchMQ.PushCalls())
func (mock *DvpBatchMQMock) PushCalls() []struct {
	ContextMoqParam         context.Context
	DvpSerializedEventBatch service.DvpSerializedEventBatch
} {
	var calls []struct {
		ContextMoqParam         context.Context
		DvpSerializedEventBatch service.DvpSerializedEventBatch
	}
	mock.lockPush.RLock()
	calls = mock.calls.Push
	mock.lockPush.RUnlock()
	return calls
}
