package otel

// Spans
const (
	SPAN_EXECUTE_ENYGMA_TRANSFERS         = "execute_enygma_transfers"
	SPAN_HANDLE_ENYGMA_CROSS_TRANSFER     = "handle_enygma_cross_transfer"
	SPAN_INITIATE_ENYGMA_CROSS_TRANSFER   = "initiate_enygma_cross_transfer"
	SPAN_RETRY_ENYGMA_OPERATION           = "retry_enygma_operation"
	SPAN_WAIT_FOR_NEXT_BLOCK              = "wait_for_next_block"
	SPAN_CREATE_BATCHES_WITH_ANONYMITY    = "create_batches_with_anonymity"
	SPAN_GENERATE_TRANSFER_PROOF          = "generate_transfer_proof"
	SPAN_GET_ENYGMA_SHARED_SECRETS        = "get_enygma_shared_secrets"
	SPAN_GET_ENYGMA_KEY                   = "get_enygma_key"
	SPAN_GET_PUBLIC_VALUES_FINALISED      = "get_public_values_finalised"
	SPAN_CREATE_TRANSFER_PROOF            = "create_transfer_proof"
	SPAN_SEND_ENYGMA_TRANSFER_BATCH       = "send_enygma_transfer_batch"
	SPAN_ENCRYPT_ENYGMA_TRANSFER_BATCH    = "encrypt_enygma_transfer_batch"
	SPAN_TRANSFER_BATCH                   = "transfer_batch"
	SPAN_TRANSFER_BATCH_RECEIPT           = "transfer_batch_receipt"
	SPAN_EXECUTE_FINALIZATION             = "execute_enygma_finalization_transaction"
	SPAN_REVERT_ENYGMA_TRANSFER           = "revert_enygma_transfer"
	SPAN_REVERT_TRANSFERS_IN_PN           = "revert_transfers_in_pn"
	SPAN_EXECUTE_ENYGMA_CREATION          = "execute_enygma_creation"
	SPAN_HANDLE_ENYGMA_CREATION           = "handle_enygma_creation"
	SPAN_HANDLE_ENYGMA_SUPPLY_UPDATE      = "handle_enygma_supply_update"
	SPAN_EXECUTE_ENYGMA_SUPPLY_UDPATE     = "execute_enygma_supply_update"
	SPAN_INITIATE_ENYGMA_SUPPLY_UPDATE    = "initiate_enygma_supply_update"
	SPAN_REVERT_ENYGMA_SUPPLY_UPDATE      = "revert_enygma_supply_update"
	SPAN_CREATE_ENYGMA                    = "create_enygma"
	SPAN_FINISH_ENYGMA_CROSS_TRANSFER     = "finish_enygma_cross_transfer"
	SPAN_DEPLOY_ENYGMA_CONTRACT           = "deploy_enygma_contract"
	SPAN_PROCESS_ENYGMA_FINALIZED_BALANCE = "process_enygma_finalized_balance"
	SPAN_DECRYPT_ENYGMA_TRANSFER_EVENT    = "decrypt_enygma_transfer_event"
	SPAN_SEND_CROSS_MINT                  = "send_enygma_cross_mint"
	SPAN_TRANSFER_COMPLETED               = "enygma_transfer_completed"
	SPAN_TRANSFER_SENT                    = "enygma-transfer-sent"
	SPAN_TRANSFER_RECEIVED                = "enygma-transfer-received"
)

// Attribute keys
const (
	ATTR_RESOURCE_ID               = "resource_id"
	ATTR_BLOCK_NUMBER              = "block_number"
	ATTR_ANONYMITY_INDEX           = "anonymity_index"
	ATTR_SENDER_AMOUNT             = "sender_amount"
	ATTR_SENDER_CHAIN_ID           = "sender_chain_id"
	ATTR_BATCH_LENGTH              = "batch_length"
	ATTR_ENYGMA_ADDRESS            = "enygma_address"
	ATTR_SHOULD_FINALIZE           = "should_finalize"
	ATTR_REVERT_REASON             = "revert_reason"
	ATTR_ERROR_MESSAGE             = "error_message"
	ATTR_RETRY_COUNT               = "retry_count"
	ATTR_FINAL_BLOCK_NUMBER        = "final_block_number"
	ATTR_FINAL_RETRY_COUNT         = "final_retry_count"
	ATTR_TRANSFERS_LENGTH          = "transfers_length"
	ATTR_PN_CHAIN_ID               = "pn_chain_id"
	ATTR_REVERT_TXS_COUNT          = "revert_txs_count"
	ATTR_SUCCESS_TXS_COUNT         = "success_txs_count"
	ATTR_FAILED_TXS_COUNT          = "failed_txs_count"
	ATTR_INITIAL_SUPPLY            = "initial_supply"
	ATTR_ENYGMA_SUPPLY_UPDATE_TYPE = "enygma_supply_update_type"
	ATTR_AMOUNT                    = "amount"
	SPAN_UPDATE_ENYGMA_SUPPLY      = "update_enygma_supply"
	ATTR_MINTS                     = "mints"
	ATTR_BURNS                     = "burns"
	ATTR_BLOCK_NUMBER_PNH          = "block_number_pnh"
	ATTR_MESSAGE_ID                = "message_id"
	ATTR_REFERENCE_ID              = "reference_id"
	ATTR_SEND_TIMESTAMP            = "send_timestamp"
	ATTR_RECEIVE_TIMESTAMP         = "receive_timestamp"
	ATTR_SOFT_FINALITY_LATENCY = "soft_finality_latency"
	ATTR_HARD_FINALITY_LATENCY = "hard_finality_latency"
)

// Event names
const (
	EVENT_RETRYABLE_ERROR_ENCOUNTERED = "retryable_error_encountered"
	EVENT_BATCH_EXECUTION_FAILED      = "batch_execution_failed"
	EVENT_REVERT_TX_FAILED            = "revert_tx_failed"
	EVENT_REVERT_TX_SEND_FAILED       = "revert_tx_send_failed"
)

// Status messages - Success
const (
	STATUS_SUCCESS_TRANSFER_BATCH_SENT              = "transfer batch sent successfully"
	STATUS_SUCCESS_ENYGMA_CROSS_TRANSFER_INITIATED  = "enygma cross transfer initiated successfully"
	STATUS_SUCCESS_OPERATION_SUCCEEDED              = "operation succeeded"
	STATUS_SUCCESS_BATCHES_CREATED                  = "batches created successfully"
	STATUS_SUCCESS_TRANSFER_PROOF_GENERATED         = "transfer proof generated successfully"
	STATUS_SUCCESS_TRANSFERS_EXECUTED_AND_FINALIZED = "transfers executed and finalized successfully"
	STATUS_SUCCESS_TRANSFER_EXECUTED                = "cross transfer executed successfully"
	STATUS_SUCCESS_TRANSFERS_REVERTED               = "transfers reverted successfully"
	STATUS_SUCCESS_REVERTS_SENT_TO_PN               = "revert transactions sent to PN"
	STATUS_SUCCESS_MINT_SENT                        = "enygma cross mint sent successfully"
	STATUS_SUCCESS_TRANSFER_COMPLETED_SENT          = "enygma transfer completed sent successfully"
)

// Status messages - Error
const (
	STATUS_ERROR_FAILED_TO_EXECUTE_TRANSFER_BATCH    = "failed to execute transfer batch"
	STATUS_ERROR_RECEIPT_ERROR                       = "receipt error"
	STATUS_ERROR_TRANSFER_BATCH_REVERTED             = "transfer batch was reverted"
	STATUS_ERROR_FAILED_TO_SEND_TRANSFER_BATCH       = "failed to send transfer batch"
	STATUS_ERROR_MAX_RETRIES_EXCEEDED                = "max retries exceeded"
	STATUS_ERROR_ANONYMITY_INDEX_VALIDATION_FAILED   = "anonymity index validation failed"
	STATUS_ERROR_FAILED_TO_PREPARE_COMMON_PROOF_DATA = "failed to prepare common proof data"
	STATUS_ERROR_PROOF_CREATION_FAILED               = "proof creation failed"
	STATUS_ERROR_FAILED_TO_CREATE_TRANSFER_PROOF     = "failed to create transfer proof"
	STATUS_ERROR_FAILED_TO_GET_SHARED_SECRETS        = "failed to get shared secrets"
	STATUS_ERROR_FAILED_TO_GET_ENYGMA_KEY            = "failed to get enygma key"
	STATUS_ERROR_FAILED_TO_REVERT_TRANSFER_BATCH     = "failed to revert transfer batch"
	STATUS_ERROR_FAILED_TO_REVERT_ALL_TRANSFERS      = "failed to revert all transfers"
	STATUS_ERROR_FAILED_TO_EXECUTE_FINALIZATION_TX   = "failed to execute finalization transaction"
	STATUS_ERROR_ALL_TRANSFERS_FAILED                = "all transfers failed"
	STATUS_ERROR_FAILED_TO_GET_RESOURCE_ADDRESS      = "failed to get resource address"
	STATUS_ERROR_FAILED_TO_SEND_REVERT_BATCH         = "failed to send revert batch"
	STATUS_ERROR_FAILED_TO_DEPLOY_ENYGMA_CONTRACT    = "failed to deploy enygma contract"
	STATUS_ERROR_FAILED_TO_SEND_MINT                 = "failed to send enygma cross mint"
	STATUS_ERROR_FAILED_TO_SEND_TRANSFER_COMPLETED   = "failed to send enygma transfer completed"
	STATUS_ERROR_FAILED_TO_SEND_SUPPLY_UPDATE        = "failed to send enygma supply update"
)
