// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package service_test

import (
	"context"
	"github.com/ethereum/go-ethereum/common"
	"github.com/raylsnetwork/rayls-privacy-relayer-api/batcher"
	"github.com/raylsnetwork/rayls-privacy-relayer-api/contracts/EndpointV1"
	"github.com/raylsnetwork/rayls-privacy-relayer-api/msgqueue"
	"github.com/raylsnetwork/rayls-privacy-relayer-api/private-relayer/shared/service"
	"math/big"
	"sync"
)

// Ensure, that TransactionGeneratorMock does implement service.TransactionGenerator.
// If this is not the case, regenerate this file with moq.
var _ service.TransactionGenerator = &TransactionGeneratorMock{}

// TransactionGeneratorMock is a mock implementation of service.TransactionGenerator.
//
//	func TestSomethingThatUsesTransactionGenerator(t *testing.T) {
//
//		// make and configure a mocked service.TransactionGenerator
//		mockedTransactionGenerator := &TransactionGeneratorMock{
//			GenerateFunc: func(fromChainID *big.Int, fromAddress common.Address, toAddress common.Address, message EndpointV1.RaylsMessage, id common.Hash) ([]byte, error) {
//				panic("mock out the Generate method")
//			},
//		}
//
//		// use mockedTransactionGenerator in code that requires service.TransactionGenerator
//		// and then make assertions.
//
//	}
type TransactionGeneratorMock struct {
	// GenerateFunc mocks the Generate method.
	GenerateFunc func(fromChainID *big.Int, fromAddress common.Address, toAddress common.Address, message EndpointV1.RaylsMessage, id common.Hash) ([]byte, error)

	// calls tracks calls to the methods.
	calls struct {
		// Generate holds details about calls to the Generate method.
		Generate []struct {
			// FromChainID is the fromChainID argument value.
			FromChainID *big.Int
			// FromAddress is the fromAddress argument value.
			FromAddress common.Address
			// ToAddress is the toAddress argument value.
			ToAddress common.Address
			// Message is the message argument value.
			Message EndpointV1.RaylsMessage
			// ID is the id argument value.
			ID common.Hash
		}
	}
	lockGenerate sync.RWMutex
}

// Generate calls GenerateFunc.
func (mock *TransactionGeneratorMock) Generate(fromChainID *big.Int, fromAddress common.Address, toAddress common.Address, message EndpointV1.RaylsMessage, id common.Hash) ([]byte, error) {
	if mock.GenerateFunc == nil {
		panic("TransactionGeneratorMock.GenerateFunc: method is nil but TransactionGenerator.Generate was just called")
	}
	callInfo := struct {
		FromChainID *big.Int
		FromAddress common.Address
		ToAddress   common.Address
		Message     EndpointV1.RaylsMessage
		ID          common.Hash
	}{
		FromChainID: fromChainID,
		FromAddress: fromAddress,
		ToAddress:   toAddress,
		Message:     message,
		ID:          id,
	}
	mock.lockGenerate.Lock()
	mock.calls.Generate = append(mock.calls.Generate, callInfo)
	mock.lockGenerate.Unlock()
	return mock.GenerateFunc(fromChainID, fromAddress, toAddress, message, id)
}

// GenerateCalls gets all the calls that were made to Generate.
// Check the length with:
//
//	len(mockedTransactionGenerator.GenerateCalls())
func (mock *TransactionGeneratorMock) GenerateCalls() []struct {
	FromChainID *big.Int
	FromAddress common.Address
	ToAddress   common.Address
	Message     EndpointV1.RaylsMessage
	ID          common.Hash
} {
	var calls []struct {
		FromChainID *big.Int
		FromAddress common.Address
		ToAddress   common.Address
		Message     EndpointV1.RaylsMessage
		ID          common.Hash
	}
	mock.lockGenerate.RLock()
	calls = mock.calls.Generate
	mock.lockGenerate.RUnlock()
	return calls
}

// Ensure, that PrivateHubConsumerMock does implement service.PrivateHubConsumer.
// If this is not the case, regenerate this file with moq.
var _ service.PrivateHubConsumer = &PrivateHubConsumerMock{}

// PrivateHubConsumerMock is a mock implementation of service.PrivateHubConsumer.
//
//	func TestSomethingThatUsesPrivateHubConsumer(t *testing.T) {
//
//		// make and configure a mocked service.PrivateHubConsumer
//		mockedPrivateHubConsumer := &PrivateHubConsumerMock{
//			FetchFunc: func(ctx context.Context, count int) ([]msgqueue.Message[service.PrivateHubMessage], error) {
//				panic("mock out the Fetch method")
//			},
//		}
//
//		// use mockedPrivateHubConsumer in code that requires service.PrivateHubConsumer
//		// and then make assertions.
//
//	}
type PrivateHubConsumerMock struct {
	// FetchFunc mocks the Fetch method.
	FetchFunc func(ctx context.Context, count int) ([]msgqueue.Message[service.PrivateHubMessage], error)

	// calls tracks calls to the methods.
	calls struct {
		// Fetch holds details about calls to the Fetch method.
		Fetch []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Count is the count argument value.
			Count int
		}
	}
	lockFetch sync.RWMutex
}

// Fetch calls FetchFunc.
func (mock *PrivateHubConsumerMock) Fetch(ctx context.Context, count int) ([]msgqueue.Message[service.PrivateHubMessage], error) {
	if mock.FetchFunc == nil {
		panic("PrivateHubConsumerMock.FetchFunc: method is nil but PrivateHubConsumer.Fetch was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Count int
	}{
		Ctx:   ctx,
		Count: count,
	}
	mock.lockFetch.Lock()
	mock.calls.Fetch = append(mock.calls.Fetch, callInfo)
	mock.lockFetch.Unlock()
	return mock.FetchFunc(ctx, count)
}

// FetchCalls gets all the calls that were made to Fetch.
// Check the length with:
//
//	len(mockedPrivateHubConsumer.FetchCalls())
func (mock *PrivateHubConsumerMock) FetchCalls() []struct {
	Ctx   context.Context
	Count int
} {
	var calls []struct {
		Ctx   context.Context
		Count int
	}
	mock.lockFetch.RLock()
	calls = mock.calls.Fetch
	mock.lockFetch.RUnlock()
	return calls
}

// Ensure, that BatcherMock does implement service.Batcher.
// If this is not the case, regenerate this file with moq.
var _ service.Batcher = &BatcherMock{}

// BatcherMock is a mock implementation of service.Batcher.
//
//	func TestSomethingThatUsesBatcher(t *testing.T) {
//
//		// make and configure a mocked service.Batcher
//		mockedBatcher := &BatcherMock{
//			SendFunc: func(ctx context.Context, msgs []batcher.Message) error {
//				panic("mock out the Send method")
//			},
//		}
//
//		// use mockedBatcher in code that requires service.Batcher
//		// and then make assertions.
//
//	}
type BatcherMock struct {
	// SendFunc mocks the Send method.
	SendFunc func(ctx context.Context, msgs []batcher.Message) error

	// calls tracks calls to the methods.
	calls struct {
		// Send holds details about calls to the Send method.
		Send []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Msgs is the msgs argument value.
			Msgs []batcher.Message
		}
	}
	lockSend sync.RWMutex
}

// Send calls SendFunc.
func (mock *BatcherMock) Send(ctx context.Context, msgs []batcher.Message) error {
	if mock.SendFunc == nil {
		panic("BatcherMock.SendFunc: method is nil but Batcher.Send was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Msgs []batcher.Message
	}{
		Ctx:  ctx,
		Msgs: msgs,
	}
	mock.lockSend.Lock()
	mock.calls.Send = append(mock.calls.Send, callInfo)
	mock.lockSend.Unlock()
	return mock.SendFunc(ctx, msgs)
}

// SendCalls gets all the calls that were made to Send.
// Check the length with:
//
//	len(mockedBatcher.SendCalls())
func (mock *BatcherMock) SendCalls() []struct {
	Ctx  context.Context
	Msgs []batcher.Message
} {
	var calls []struct {
		Ctx  context.Context
		Msgs []batcher.Message
	}
	mock.lockSend.RLock()
	calls = mock.calls.Send
	mock.lockSend.RUnlock()
	return calls
}
