// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package logparser_test

import (
	"context"
	ethTypes "github.com/ethereum/go-ethereum/core/types"
	encryptpb "github.com/raylsnetwork/rayls-privacy-relayer-api/cts/gen/proto/encrypt"
	keyspb "github.com/raylsnetwork/rayls-privacy-relayer-api/cts/gen/proto/keys"
	"github.com/raylsnetwork/rayls-privacy-relayer-api/msgqueue"
	"github.com/raylsnetwork/rayls-privacy-relayer-api/private-relayer/dest/logparser"
	"github.com/raylsnetwork/rayls-privacy-relayer-api/private-relayer/dest/logrouter"
	"github.com/raylsnetwork/rayls-privacy-relayer-api/private-relayer/dest/service"
	"github.com/raylsnetwork/rayls-privacy-relayer-api/types"
	"google.golang.org/grpc"
	"math/big"
	"sync"
)

// Ensure, that DvpTeleportMQMock does implement logparser.DvpTeleportMQ.
// If this is not the case, regenerate this file with moq.
var _ logparser.DvpTeleportMQ = &DvpTeleportMQMock{}

// DvpTeleportMQMock is a mock implementation of logparser.DvpTeleportMQ.
//
//	func TestSomethingThatUsesDvpTeleportMQ(t *testing.T) {
//
//		// make and configure a mocked logparser.DvpTeleportMQ
//		mockedDvpTeleportMQ := &DvpTeleportMQMock{
//			NextFunc: func(ctx context.Context) (msgqueue.Message[logrouter.Block], error) {
//				panic("mock out the Next method")
//			},
//		}
//
//		// use mockedDvpTeleportMQ in code that requires logparser.DvpTeleportMQ
//		// and then make assertions.
//
//	}
type DvpTeleportMQMock struct {
	// NextFunc mocks the Next method.
	NextFunc func(ctx context.Context) (msgqueue.Message[logrouter.Block], error)

	// calls tracks calls to the methods.
	calls struct {
		// Next holds details about calls to the Next method.
		Next []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
	}
	lockNext sync.RWMutex
}

// Next calls NextFunc.
func (mock *DvpTeleportMQMock) Next(ctx context.Context) (msgqueue.Message[logrouter.Block], error) {
	if mock.NextFunc == nil {
		panic("DvpTeleportMQMock.NextFunc: method is nil but DvpTeleportMQ.Next was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockNext.Lock()
	mock.calls.Next = append(mock.calls.Next, callInfo)
	mock.lockNext.Unlock()
	return mock.NextFunc(ctx)
}

// NextCalls gets all the calls that were made to Next.
// Check the length with:
//
//	len(mockedDvpTeleportMQ.NextCalls())
func (mock *DvpTeleportMQMock) NextCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockNext.RLock()
	calls = mock.calls.Next
	mock.lockNext.RUnlock()
	return calls
}

// Ensure, that DvpOrchestratorMQMock does implement logparser.DvpOrchestratorMQ.
// If this is not the case, regenerate this file with moq.
var _ logparser.DvpOrchestratorMQ = &DvpOrchestratorMQMock{}

// DvpOrchestratorMQMock is a mock implementation of logparser.DvpOrchestratorMQ.
//
//	func TestSomethingThatUsesDvpOrchestratorMQ(t *testing.T) {
//
//		// make and configure a mocked logparser.DvpOrchestratorMQ
//		mockedDvpOrchestratorMQ := &DvpOrchestratorMQMock{
//			PushFunc: func(ctx context.Context, msg service.DvpDestMessage) error {
//				panic("mock out the Push method")
//			},
//		}
//
//		// use mockedDvpOrchestratorMQ in code that requires logparser.DvpOrchestratorMQ
//		// and then make assertions.
//
//	}
type DvpOrchestratorMQMock struct {
	// PushFunc mocks the Push method.
	PushFunc func(ctx context.Context, msg service.DvpDestMessage) error

	// calls tracks calls to the methods.
	calls struct {
		// Push holds details about calls to the Push method.
		Push []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Msg is the msg argument value.
			Msg service.DvpDestMessage
		}
	}
	lockPush sync.RWMutex
}

// Push calls PushFunc.
func (mock *DvpOrchestratorMQMock) Push(ctx context.Context, msg service.DvpDestMessage) error {
	if mock.PushFunc == nil {
		panic("DvpOrchestratorMQMock.PushFunc: method is nil but DvpOrchestratorMQ.Push was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Msg service.DvpDestMessage
	}{
		Ctx: ctx,
		Msg: msg,
	}
	mock.lockPush.Lock()
	mock.calls.Push = append(mock.calls.Push, callInfo)
	mock.lockPush.Unlock()
	return mock.PushFunc(ctx, msg)
}

// PushCalls gets all the calls that were made to Push.
// Check the length with:
//
//	len(mockedDvpOrchestratorMQ.PushCalls())
func (mock *DvpOrchestratorMQMock) PushCalls() []struct {
	Ctx context.Context
	Msg service.DvpDestMessage
} {
	var calls []struct {
		Ctx context.Context
		Msg service.DvpDestMessage
	}
	mock.lockPush.RLock()
	calls = mock.calls.Push
	mock.lockPush.RUnlock()
	return calls
}

// Ensure, that DvpCTSClientMock does implement logparser.DvpCTSClient.
// If this is not the case, regenerate this file with moq.
var _ logparser.DvpCTSClient = &DvpCTSClientMock{}

// DvpCTSClientMock is a mock implementation of logparser.DvpCTSClient.
//
//	func TestSomethingThatUsesDvpCTSClient(t *testing.T) {
//
//		// make and configure a mocked logparser.DvpCTSClient
//		mockedDvpCTSClient := &DvpCTSClientMock{
//			DecryptWithoutFPWithSSFunc: func(ctx context.Context, in *encryptpb.DecryptWithoutFPWithSSRequest, opts ...grpc.CallOption) (*encryptpb.DecryptWithoutFPWithSSResponse, error) {
//				panic("mock out the DecryptWithoutFPWithSS method")
//			},
//			RecoverViewSaltFunc: func(ctx context.Context, in *keyspb.RecoverViewSaltRequest, opts ...grpc.CallOption) (*keyspb.RecoverViewSaltResponse, error) {
//				panic("mock out the RecoverViewSalt method")
//			},
//		}
//
//		// use mockedDvpCTSClient in code that requires logparser.DvpCTSClient
//		// and then make assertions.
//
//	}
type DvpCTSClientMock struct {
	// DecryptWithoutFPWithSSFunc mocks the DecryptWithoutFPWithSS method.
	DecryptWithoutFPWithSSFunc func(ctx context.Context, in *encryptpb.DecryptWithoutFPWithSSRequest, opts ...grpc.CallOption) (*encryptpb.DecryptWithoutFPWithSSResponse, error)

	// RecoverViewSaltFunc mocks the RecoverViewSalt method.
	RecoverViewSaltFunc func(ctx context.Context, in *keyspb.RecoverViewSaltRequest, opts ...grpc.CallOption) (*keyspb.RecoverViewSaltResponse, error)

	// calls tracks calls to the methods.
	calls struct {
		// DecryptWithoutFPWithSS holds details about calls to the DecryptWithoutFPWithSS method.
		DecryptWithoutFPWithSS []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// In is the in argument value.
			In *encryptpb.DecryptWithoutFPWithSSRequest
			// Opts is the opts argument value.
			Opts []grpc.CallOption
		}
		// RecoverViewSalt holds details about calls to the RecoverViewSalt method.
		RecoverViewSalt []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// In is the in argument value.
			In *keyspb.RecoverViewSaltRequest
			// Opts is the opts argument value.
			Opts []grpc.CallOption
		}
	}
	lockDecryptWithoutFPWithSS sync.RWMutex
	lockRecoverViewSalt        sync.RWMutex
}

// DecryptWithoutFPWithSS calls DecryptWithoutFPWithSSFunc.
func (mock *DvpCTSClientMock) DecryptWithoutFPWithSS(ctx context.Context, in *encryptpb.DecryptWithoutFPWithSSRequest, opts ...grpc.CallOption) (*encryptpb.DecryptWithoutFPWithSSResponse, error) {
	if mock.DecryptWithoutFPWithSSFunc == nil {
		panic("DvpCTSClientMock.DecryptWithoutFPWithSSFunc: method is nil but DvpCTSClient.DecryptWithoutFPWithSS was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		In   *encryptpb.DecryptWithoutFPWithSSRequest
		Opts []grpc.CallOption
	}{
		Ctx:  ctx,
		In:   in,
		Opts: opts,
	}
	mock.lockDecryptWithoutFPWithSS.Lock()
	mock.calls.DecryptWithoutFPWithSS = append(mock.calls.DecryptWithoutFPWithSS, callInfo)
	mock.lockDecryptWithoutFPWithSS.Unlock()
	return mock.DecryptWithoutFPWithSSFunc(ctx, in, opts...)
}

// DecryptWithoutFPWithSSCalls gets all the calls that were made to DecryptWithoutFPWithSS.
// Check the length with:
//
//	len(mockedDvpCTSClient.DecryptWithoutFPWithSSCalls())
func (mock *DvpCTSClientMock) DecryptWithoutFPWithSSCalls() []struct {
	Ctx  context.Context
	In   *encryptpb.DecryptWithoutFPWithSSRequest
	Opts []grpc.CallOption
} {
	var calls []struct {
		Ctx  context.Context
		In   *encryptpb.DecryptWithoutFPWithSSRequest
		Opts []grpc.CallOption
	}
	mock.lockDecryptWithoutFPWithSS.RLock()
	calls = mock.calls.DecryptWithoutFPWithSS
	mock.lockDecryptWithoutFPWithSS.RUnlock()
	return calls
}

// RecoverViewSalt calls RecoverViewSaltFunc.
func (mock *DvpCTSClientMock) RecoverViewSalt(ctx context.Context, in *keyspb.RecoverViewSaltRequest, opts ...grpc.CallOption) (*keyspb.RecoverViewSaltResponse, error) {
	if mock.RecoverViewSaltFunc == nil {
		panic("DvpCTSClientMock.RecoverViewSaltFunc: method is nil but DvpCTSClient.RecoverViewSalt was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		In   *keyspb.RecoverViewSaltRequest
		Opts []grpc.CallOption
	}{
		Ctx:  ctx,
		In:   in,
		Opts: opts,
	}
	mock.lockRecoverViewSalt.Lock()
	mock.calls.RecoverViewSalt = append(mock.calls.RecoverViewSalt, callInfo)
	mock.lockRecoverViewSalt.Unlock()
	return mock.RecoverViewSaltFunc(ctx, in, opts...)
}

// RecoverViewSaltCalls gets all the calls that were made to RecoverViewSalt.
// Check the length with:
//
//	len(mockedDvpCTSClient.RecoverViewSaltCalls())
func (mock *DvpCTSClientMock) RecoverViewSaltCalls() []struct {
	Ctx  context.Context
	In   *keyspb.RecoverViewSaltRequest
	Opts []grpc.CallOption
} {
	var calls []struct {
		Ctx  context.Context
		In   *keyspb.RecoverViewSaltRequest
		Opts []grpc.CallOption
	}
	mock.lockRecoverViewSalt.RLock()
	calls = mock.calls.RecoverViewSalt
	mock.lockRecoverViewSalt.RUnlock()
	return calls
}

// Ensure, that DvpBackoffMock does implement logparser.DvpBackoff.
// If this is not the case, regenerate this file with moq.
var _ logparser.DvpBackoff = &DvpBackoffMock{}

// DvpBackoffMock is a mock implementation of logparser.DvpBackoff.
//
//	func TestSomethingThatUsesDvpBackoff(t *testing.T) {
//
//		// make and configure a mocked logparser.DvpBackoff
//		mockedDvpBackoff := &DvpBackoffMock{
//			DoFunc: func(ctx context.Context, maxAttempts int, fn func() error) error {
//				panic("mock out the Do method")
//			},
//		}
//
//		// use mockedDvpBackoff in code that requires logparser.DvpBackoff
//		// and then make assertions.
//
//	}
type DvpBackoffMock struct {
	// DoFunc mocks the Do method.
	DoFunc func(ctx context.Context, maxAttempts int, fn func() error) error

	// calls tracks calls to the methods.
	calls struct {
		// Do holds details about calls to the Do method.
		Do []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// MaxAttempts is the maxAttempts argument value.
			MaxAttempts int
			// Fn is the fn argument value.
			Fn func() error
		}
	}
	lockDo sync.RWMutex
}

// Do calls DoFunc.
func (mock *DvpBackoffMock) Do(ctx context.Context, maxAttempts int, fn func() error) error {
	if mock.DoFunc == nil {
		panic("DvpBackoffMock.DoFunc: method is nil but DvpBackoff.Do was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		MaxAttempts int
		Fn          func() error
	}{
		Ctx:         ctx,
		MaxAttempts: maxAttempts,
		Fn:          fn,
	}
	mock.lockDo.Lock()
	mock.calls.Do = append(mock.calls.Do, callInfo)
	mock.lockDo.Unlock()
	return mock.DoFunc(ctx, maxAttempts, fn)
}

// DoCalls gets all the calls that were made to Do.
// Check the length with:
//
//	len(mockedDvpBackoff.DoCalls())
func (mock *DvpBackoffMock) DoCalls() []struct {
	Ctx         context.Context
	MaxAttempts int
	Fn          func() error
} {
	var calls []struct {
		Ctx         context.Context
		MaxAttempts int
		Fn          func() error
	}
	mock.lockDo.RLock()
	calls = mock.calls.Do
	mock.lockDo.RUnlock()
	return calls
}

// Ensure, that DvpEthereumClientMock does implement logparser.DvpEthereumClient.
// If this is not the case, regenerate this file with moq.
var _ logparser.DvpEthereumClient = &DvpEthereumClientMock{}

// DvpEthereumClientMock is a mock implementation of logparser.DvpEthereumClient.
//
//	func TestSomethingThatUsesDvpEthereumClient(t *testing.T) {
//
//		// make and configure a mocked logparser.DvpEthereumClient
//		mockedDvpEthereumClient := &DvpEthereumClientMock{
//			BlockByNumberFunc: func(ctx context.Context, number *big.Int) (*ethTypes.Block, error) {
//				panic("mock out the BlockByNumber method")
//			},
//		}
//
//		// use mockedDvpEthereumClient in code that requires logparser.DvpEthereumClient
//		// and then make assertions.
//
//	}
type DvpEthereumClientMock struct {
	// BlockByNumberFunc mocks the BlockByNumber method.
	BlockByNumberFunc func(ctx context.Context, number *big.Int) (*ethTypes.Block, error)

	// calls tracks calls to the methods.
	calls struct {
		// BlockByNumber holds details about calls to the BlockByNumber method.
		BlockByNumber []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Number is the number argument value.
			Number *big.Int
		}
	}
	lockBlockByNumber sync.RWMutex
}

// BlockByNumber calls BlockByNumberFunc.
func (mock *DvpEthereumClientMock) BlockByNumber(ctx context.Context, number *big.Int) (*ethTypes.Block, error) {
	if mock.BlockByNumberFunc == nil {
		panic("DvpEthereumClientMock.BlockByNumberFunc: method is nil but DvpEthereumClient.BlockByNumber was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Number *big.Int
	}{
		Ctx:    ctx,
		Number: number,
	}
	mock.lockBlockByNumber.Lock()
	mock.calls.BlockByNumber = append(mock.calls.BlockByNumber, callInfo)
	mock.lockBlockByNumber.Unlock()
	return mock.BlockByNumberFunc(ctx, number)
}

// BlockByNumberCalls gets all the calls that were made to BlockByNumber.
// Check the length with:
//
//	len(mockedDvpEthereumClient.BlockByNumberCalls())
func (mock *DvpEthereumClientMock) BlockByNumberCalls() []struct {
	Ctx    context.Context
	Number *big.Int
} {
	var calls []struct {
		Ctx    context.Context
		Number *big.Int
	}
	mock.lockBlockByNumber.RLock()
	calls = mock.calls.BlockByNumber
	mock.lockBlockByNumber.RUnlock()
	return calls
}

// Ensure, that DvpSwapRepositoryMock does implement logparser.DvpSwapRepository.
// If this is not the case, regenerate this file with moq.
var _ logparser.DvpSwapRepository = &DvpSwapRepositoryMock{}

// DvpSwapRepositoryMock is a mock implementation of logparser.DvpSwapRepository.
//
//	func TestSomethingThatUsesDvpSwapRepository(t *testing.T) {
//
//		// make and configure a mocked logparser.DvpSwapRepository
//		mockedDvpSwapRepository := &DvpSwapRepositoryMock{
//			GetSwapBySharedIDFunc: func(ctx context.Context, sharedID string) (*types.DvpSwap, error) {
//				panic("mock out the GetSwapBySharedID method")
//			},
//			UpdateSwapToFunc: func(ctx context.Context, sharedID string, to string) error {
//				panic("mock out the UpdateSwapTo method")
//			},
//		}
//
//		// use mockedDvpSwapRepository in code that requires logparser.DvpSwapRepository
//		// and then make assertions.
//
//	}
type DvpSwapRepositoryMock struct {
	// GetSwapBySharedIDFunc mocks the GetSwapBySharedID method.
	GetSwapBySharedIDFunc func(ctx context.Context, sharedID string) (*types.DvpSwap, error)

	// UpdateSwapToFunc mocks the UpdateSwapTo method.
	UpdateSwapToFunc func(ctx context.Context, sharedID string, to string) error

	// calls tracks calls to the methods.
	calls struct {
		// GetSwapBySharedID holds details about calls to the GetSwapBySharedID method.
		GetSwapBySharedID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// SharedID is the sharedID argument value.
			SharedID string
		}
		// UpdateSwapTo holds details about calls to the UpdateSwapTo method.
		UpdateSwapTo []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// SharedID is the sharedID argument value.
			SharedID string
			// To is the to argument value.
			To string
		}
	}
	lockGetSwapBySharedID sync.RWMutex
	lockUpdateSwapTo      sync.RWMutex
}

// GetSwapBySharedID calls GetSwapBySharedIDFunc.
func (mock *DvpSwapRepositoryMock) GetSwapBySharedID(ctx context.Context, sharedID string) (*types.DvpSwap, error) {
	if mock.GetSwapBySharedIDFunc == nil {
		panic("DvpSwapRepositoryMock.GetSwapBySharedIDFunc: method is nil but DvpSwapRepository.GetSwapBySharedID was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		SharedID string
	}{
		Ctx:      ctx,
		SharedID: sharedID,
	}
	mock.lockGetSwapBySharedID.Lock()
	mock.calls.GetSwapBySharedID = append(mock.calls.GetSwapBySharedID, callInfo)
	mock.lockGetSwapBySharedID.Unlock()
	return mock.GetSwapBySharedIDFunc(ctx, sharedID)
}

// GetSwapBySharedIDCalls gets all the calls that were made to GetSwapBySharedID.
// Check the length with:
//
//	len(mockedDvpSwapRepository.GetSwapBySharedIDCalls())
func (mock *DvpSwapRepositoryMock) GetSwapBySharedIDCalls() []struct {
	Ctx      context.Context
	SharedID string
} {
	var calls []struct {
		Ctx      context.Context
		SharedID string
	}
	mock.lockGetSwapBySharedID.RLock()
	calls = mock.calls.GetSwapBySharedID
	mock.lockGetSwapBySharedID.RUnlock()
	return calls
}

// UpdateSwapTo calls UpdateSwapToFunc.
func (mock *DvpSwapRepositoryMock) UpdateSwapTo(ctx context.Context, sharedID string, to string) error {
	if mock.UpdateSwapToFunc == nil {
		panic("DvpSwapRepositoryMock.UpdateSwapToFunc: method is nil but DvpSwapRepository.UpdateSwapTo was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		SharedID string
		To       string
	}{
		Ctx:      ctx,
		SharedID: sharedID,
		To:       to,
	}
	mock.lockUpdateSwapTo.Lock()
	mock.calls.UpdateSwapTo = append(mock.calls.UpdateSwapTo, callInfo)
	mock.lockUpdateSwapTo.Unlock()
	return mock.UpdateSwapToFunc(ctx, sharedID, to)
}

// UpdateSwapToCalls gets all the calls that were made to UpdateSwapTo.
// Check the length with:
//
//	len(mockedDvpSwapRepository.UpdateSwapToCalls())
func (mock *DvpSwapRepositoryMock) UpdateSwapToCalls() []struct {
	Ctx      context.Context
	SharedID string
	To       string
} {
	var calls []struct {
		Ctx      context.Context
		SharedID string
		To       string
	}
	mock.lockUpdateSwapTo.RLock()
	calls = mock.calls.UpdateSwapTo
	mock.lockUpdateSwapTo.RUnlock()
	return calls
}
