// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package logparser_test

import (
	"context"
	"github.com/raylsnetwork/rayls-privacy-relayer-api/msgqueue"
	"github.com/raylsnetwork/rayls-privacy-relayer-api/private-relayer/dest/logparser"
	"github.com/raylsnetwork/rayls-privacy-relayer-api/private-relayer/dest/logrouter"
	"github.com/raylsnetwork/rayls-privacy-relayer-api/private-relayer/shared/service"
	"sync"
)

// Ensure, that EndpointMQMock does implement logparser.EndpointMQ.
// If this is not the case, regenerate this file with moq.
var _ logparser.EndpointMQ = &EndpointMQMock{}

// EndpointMQMock is a mock implementation of logparser.EndpointMQ.
//
//	func TestSomethingThatUsesEndpointMQ(t *testing.T) {
//
//		// make and configure a mocked logparser.EndpointMQ
//		mockedEndpointMQ := &EndpointMQMock{
//			NextFunc: func(ctx context.Context) (msgqueue.Message[logrouter.Block], error) {
//				panic("mock out the Next method")
//			},
//		}
//
//		// use mockedEndpointMQ in code that requires logparser.EndpointMQ
//		// and then make assertions.
//
//	}
type EndpointMQMock struct {
	// NextFunc mocks the Next method.
	NextFunc func(ctx context.Context) (msgqueue.Message[logrouter.Block], error)

	// calls tracks calls to the methods.
	calls struct {
		// Next holds details about calls to the Next method.
		Next []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
	}
	lockNext sync.RWMutex
}

// Next calls NextFunc.
func (mock *EndpointMQMock) Next(ctx context.Context) (msgqueue.Message[logrouter.Block], error) {
	if mock.NextFunc == nil {
		panic("EndpointMQMock.NextFunc: method is nil but EndpointMQ.Next was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockNext.Lock()
	mock.calls.Next = append(mock.calls.Next, callInfo)
	mock.lockNext.Unlock()
	return mock.NextFunc(ctx)
}

// NextCalls gets all the calls that were made to Next.
// Check the length with:
//
//	len(mockedEndpointMQ.NextCalls())
func (mock *EndpointMQMock) NextCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockNext.RLock()
	calls = mock.calls.Next
	mock.lockNext.RUnlock()
	return calls
}

// Ensure, that PrivateHubMQMock does implement logparser.PrivateHubMQ.
// If this is not the case, regenerate this file with moq.
var _ logparser.PrivateHubMQ = &PrivateHubMQMock{}

// PrivateHubMQMock is a mock implementation of logparser.PrivateHubMQ.
//
//	func TestSomethingThatUsesPrivateHubMQ(t *testing.T) {
//
//		// make and configure a mocked logparser.PrivateHubMQ
//		mockedPrivateHubMQ := &PrivateHubMQMock{
//			PushBatchFunc: func(contextMoqParam context.Context, privateHubMessages []service.PrivateHubMessage) error {
//				panic("mock out the PushBatch method")
//			},
//		}
//
//		// use mockedPrivateHubMQ in code that requires logparser.PrivateHubMQ
//		// and then make assertions.
//
//	}
type PrivateHubMQMock struct {
	// PushBatchFunc mocks the PushBatch method.
	PushBatchFunc func(contextMoqParam context.Context, privateHubMessages []service.PrivateHubMessage) error

	// calls tracks calls to the methods.
	calls struct {
		// PushBatch holds details about calls to the PushBatch method.
		PushBatch []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// PrivateHubMessages is the privateHubMessages argument value.
			PrivateHubMessages []service.PrivateHubMessage
		}
	}
	lockPushBatch sync.RWMutex
}

// PushBatch calls PushBatchFunc.
func (mock *PrivateHubMQMock) PushBatch(contextMoqParam context.Context, privateHubMessages []service.PrivateHubMessage) error {
	if mock.PushBatchFunc == nil {
		panic("PrivateHubMQMock.PushBatchFunc: method is nil but PrivateHubMQ.PushBatch was just called")
	}
	callInfo := struct {
		ContextMoqParam    context.Context
		PrivateHubMessages []service.PrivateHubMessage
	}{
		ContextMoqParam:    contextMoqParam,
		PrivateHubMessages: privateHubMessages,
	}
	mock.lockPushBatch.Lock()
	mock.calls.PushBatch = append(mock.calls.PushBatch, callInfo)
	mock.lockPushBatch.Unlock()
	return mock.PushBatchFunc(contextMoqParam, privateHubMessages)
}

// PushBatchCalls gets all the calls that were made to PushBatch.
// Check the length with:
//
//	len(mockedPrivateHubMQ.PushBatchCalls())
func (mock *PrivateHubMQMock) PushBatchCalls() []struct {
	ContextMoqParam    context.Context
	PrivateHubMessages []service.PrivateHubMessage
} {
	var calls []struct {
		ContextMoqParam    context.Context
		PrivateHubMessages []service.PrivateHubMessage
	}
	mock.lockPushBatch.RLock()
	calls = mock.calls.PushBatch
	mock.lockPushBatch.RUnlock()
	return calls
}

// Ensure, that EndpointBackoffMock does implement logparser.EndpointBackoff.
// If this is not the case, regenerate this file with moq.
var _ logparser.EndpointBackoff = &EndpointBackoffMock{}

// EndpointBackoffMock is a mock implementation of logparser.EndpointBackoff.
//
//	func TestSomethingThatUsesEndpointBackoff(t *testing.T) {
//
//		// make and configure a mocked logparser.EndpointBackoff
//		mockedEndpointBackoff := &EndpointBackoffMock{
//			DoFunc: func(ctx context.Context, maxAttempts int, fn func() error) error {
//				panic("mock out the Do method")
//			},
//		}
//
//		// use mockedEndpointBackoff in code that requires logparser.EndpointBackoff
//		// and then make assertions.
//
//	}
type EndpointBackoffMock struct {
	// DoFunc mocks the Do method.
	DoFunc func(ctx context.Context, maxAttempts int, fn func() error) error

	// calls tracks calls to the methods.
	calls struct {
		// Do holds details about calls to the Do method.
		Do []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// MaxAttempts is the maxAttempts argument value.
			MaxAttempts int
			// Fn is the fn argument value.
			Fn func() error
		}
	}
	lockDo sync.RWMutex
}

// Do calls DoFunc.
func (mock *EndpointBackoffMock) Do(ctx context.Context, maxAttempts int, fn func() error) error {
	if mock.DoFunc == nil {
		panic("EndpointBackoffMock.DoFunc: method is nil but EndpointBackoff.Do was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		MaxAttempts int
		Fn          func() error
	}{
		Ctx:         ctx,
		MaxAttempts: maxAttempts,
		Fn:          fn,
	}
	mock.lockDo.Lock()
	mock.calls.Do = append(mock.calls.Do, callInfo)
	mock.lockDo.Unlock()
	return mock.DoFunc(ctx, maxAttempts, fn)
}

// DoCalls gets all the calls that were made to Do.
// Check the length with:
//
//	len(mockedEndpointBackoff.DoCalls())
func (mock *EndpointBackoffMock) DoCalls() []struct {
	Ctx         context.Context
	MaxAttempts int
	Fn          func() error
} {
	var calls []struct {
		Ctx         context.Context
		MaxAttempts int
		Fn          func() error
	}
	mock.lockDo.RLock()
	calls = mock.calls.Do
	mock.lockDo.RUnlock()
	return calls
}
