// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package batcher_test

import (
	"context"
	"github.com/ethereum/go-ethereum/common"
	"github.com/raylsnetwork/rayls-sovereign-relayer/cts/batcher"
	"github.com/raylsnetwork/rayls-sovereign-relayer/cts/ethrpc"
	"github.com/raylsnetwork/rayls-sovereign-relayer/msgqueue"
	"github.com/raylsnetwork/rayls-sovereign-relayer/types"
	"sync"
	"time"
)

// Ensure, that MessageConsumerMock does implement batcher.MessageConsumer.
// If this is not the case, regenerate this file with moq.
var _ batcher.MessageConsumer = &MessageConsumerMock{}

// MessageConsumerMock is a mock implementation of batcher.MessageConsumer.
//
//	func TestSomethingThatUsesMessageConsumer(t *testing.T) {
//
//		// make and configure a mocked batcher.MessageConsumer
//		mockedMessageConsumer := &MessageConsumerMock{
//			FetchFunc: func(ctx context.Context, count int) ([]msgqueue.Message[types.TxRequest], error) {
//				panic("mock out the Fetch method")
//			},
//		}
//
//		// use mockedMessageConsumer in code that requires batcher.MessageConsumer
//		// and then make assertions.
//
//	}
type MessageConsumerMock struct {
	// FetchFunc mocks the Fetch method.
	FetchFunc func(ctx context.Context, count int) ([]msgqueue.Message[types.TxRequest], error)

	// calls tracks calls to the methods.
	calls struct {
		// Fetch holds details about calls to the Fetch method.
		Fetch []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Count is the count argument value.
			Count int
		}
	}
	lockFetch sync.RWMutex
}

// Fetch calls FetchFunc.
func (mock *MessageConsumerMock) Fetch(ctx context.Context, count int) ([]msgqueue.Message[types.TxRequest], error) {
	if mock.FetchFunc == nil {
		panic("MessageConsumerMock.FetchFunc: method is nil but MessageConsumer.Fetch was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Count int
	}{
		Ctx:   ctx,
		Count: count,
	}
	mock.lockFetch.Lock()
	mock.calls.Fetch = append(mock.calls.Fetch, callInfo)
	mock.lockFetch.Unlock()
	return mock.FetchFunc(ctx, count)
}

// FetchCalls gets all the calls that were made to Fetch.
// Check the length with:
//
//	len(mockedMessageConsumer.FetchCalls())
func (mock *MessageConsumerMock) FetchCalls() []struct {
	Ctx   context.Context
	Count int
} {
	var calls []struct {
		Ctx   context.Context
		Count int
	}
	mock.lockFetch.RLock()
	calls = mock.calls.Fetch
	mock.lockFetch.RUnlock()
	return calls
}

// Ensure, that ResultPublisherMock does implement batcher.ResultPublisher.
// If this is not the case, regenerate this file with moq.
var _ batcher.ResultPublisher = &ResultPublisherMock{}

// ResultPublisherMock is a mock implementation of batcher.ResultPublisher.
//
//	func TestSomethingThatUsesResultPublisher(t *testing.T) {
//
//		// make and configure a mocked batcher.ResultPublisher
//		mockedResultPublisher := &ResultPublisherMock{
//			PushFunc: func(ctx context.Context, r types.TxResult) error {
//				panic("mock out the Push method")
//			},
//		}
//
//		// use mockedResultPublisher in code that requires batcher.ResultPublisher
//		// and then make assertions.
//
//	}
type ResultPublisherMock struct {
	// PushFunc mocks the Push method.
	PushFunc func(ctx context.Context, r types.TxResult) error

	// calls tracks calls to the methods.
	calls struct {
		// Push holds details about calls to the Push method.
		Push []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// R is the r argument value.
			R types.TxResult
		}
	}
	lockPush sync.RWMutex
}

// Push calls PushFunc.
func (mock *ResultPublisherMock) Push(ctx context.Context, r types.TxResult) error {
	if mock.PushFunc == nil {
		panic("ResultPublisherMock.PushFunc: method is nil but ResultPublisher.Push was just called")
	}
	callInfo := struct {
		Ctx context.Context
		R   types.TxResult
	}{
		Ctx: ctx,
		R:   r,
	}
	mock.lockPush.Lock()
	mock.calls.Push = append(mock.calls.Push, callInfo)
	mock.lockPush.Unlock()
	return mock.PushFunc(ctx, r)
}

// PushCalls gets all the calls that were made to Push.
// Check the length with:
//
//	len(mockedResultPublisher.PushCalls())
func (mock *ResultPublisherMock) PushCalls() []struct {
	Ctx context.Context
	R   types.TxResult
} {
	var calls []struct {
		Ctx context.Context
		R   types.TxResult
	}
	mock.lockPush.RLock()
	calls = mock.calls.Push
	mock.lockPush.RUnlock()
	return calls
}

// Ensure, that BatcherMock does implement batcher.Batcher.
// If this is not the case, regenerate this file with moq.
var _ batcher.Batcher = &BatcherMock{}

// BatcherMock is a mock implementation of batcher.Batcher.
//
//	func TestSomethingThatUsesBatcher(t *testing.T) {
//
//		// make and configure a mocked batcher.Batcher
//		mockedBatcher := &BatcherMock{
//			GetReceiptsFunc: func(ctx context.Context, hashes []common.Hash) ([]ethrpc.ReceiptResult, error) {
//				panic("mock out the GetReceipts method")
//			},
//			SendFunc: func(ctx context.Context, inputs []ethrpc.TransactionInput) ([]ethrpc.SendResult, error) {
//				panic("mock out the Send method")
//			},
//		}
//
//		// use mockedBatcher in code that requires batcher.Batcher
//		// and then make assertions.
//
//	}
type BatcherMock struct {
	// GetReceiptsFunc mocks the GetReceipts method.
	GetReceiptsFunc func(ctx context.Context, hashes []common.Hash) ([]ethrpc.ReceiptResult, error)

	// SendFunc mocks the Send method.
	SendFunc func(ctx context.Context, inputs []ethrpc.TransactionInput) ([]ethrpc.SendResult, error)

	// calls tracks calls to the methods.
	calls struct {
		// GetReceipts holds details about calls to the GetReceipts method.
		GetReceipts []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Hashes is the hashes argument value.
			Hashes []common.Hash
		}
		// Send holds details about calls to the Send method.
		Send []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Inputs is the inputs argument value.
			Inputs []ethrpc.TransactionInput
		}
	}
	lockGetReceipts sync.RWMutex
	lockSend        sync.RWMutex
}

// GetReceipts calls GetReceiptsFunc.
func (mock *BatcherMock) GetReceipts(ctx context.Context, hashes []common.Hash) ([]ethrpc.ReceiptResult, error) {
	if mock.GetReceiptsFunc == nil {
		panic("BatcherMock.GetReceiptsFunc: method is nil but Batcher.GetReceipts was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Hashes []common.Hash
	}{
		Ctx:    ctx,
		Hashes: hashes,
	}
	mock.lockGetReceipts.Lock()
	mock.calls.GetReceipts = append(mock.calls.GetReceipts, callInfo)
	mock.lockGetReceipts.Unlock()
	return mock.GetReceiptsFunc(ctx, hashes)
}

// GetReceiptsCalls gets all the calls that were made to GetReceipts.
// Check the length with:
//
//	len(mockedBatcher.GetReceiptsCalls())
func (mock *BatcherMock) GetReceiptsCalls() []struct {
	Ctx    context.Context
	Hashes []common.Hash
} {
	var calls []struct {
		Ctx    context.Context
		Hashes []common.Hash
	}
	mock.lockGetReceipts.RLock()
	calls = mock.calls.GetReceipts
	mock.lockGetReceipts.RUnlock()
	return calls
}

// Send calls SendFunc.
func (mock *BatcherMock) Send(ctx context.Context, inputs []ethrpc.TransactionInput) ([]ethrpc.SendResult, error) {
	if mock.SendFunc == nil {
		panic("BatcherMock.SendFunc: method is nil but Batcher.Send was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Inputs []ethrpc.TransactionInput
	}{
		Ctx:    ctx,
		Inputs: inputs,
	}
	mock.lockSend.Lock()
	mock.calls.Send = append(mock.calls.Send, callInfo)
	mock.lockSend.Unlock()
	return mock.SendFunc(ctx, inputs)
}

// SendCalls gets all the calls that were made to Send.
// Check the length with:
//
//	len(mockedBatcher.SendCalls())
func (mock *BatcherMock) SendCalls() []struct {
	Ctx    context.Context
	Inputs []ethrpc.TransactionInput
} {
	var calls []struct {
		Ctx    context.Context
		Inputs []ethrpc.TransactionInput
	}
	mock.lockSend.RLock()
	calls = mock.calls.Send
	mock.lockSend.RUnlock()
	return calls
}

// Ensure, that RepositoryMock does implement batcher.Repository.
// If this is not the case, regenerate this file with moq.
var _ batcher.Repository = &RepositoryMock{}

// RepositoryMock is a mock implementation of batcher.Repository.
//
//	func TestSomethingThatUsesRepository(t *testing.T) {
//
//		// make and configure a mocked batcher.Repository
//		mockedRepository := &RepositoryMock{
//			ClaimPendingFunc: func(ctx context.Context, identity string, limit int) ([]batcher.CTSTransaction, error) {
//				panic("mock out the ClaimPending method")
//			},
//			ClaimSentFunc: func(ctx context.Context, identity string, limit int) ([]batcher.CTSTransaction, error) {
//				panic("mock out the ClaimSent method")
//			},
//			ClaimStuckFunc: func(ctx context.Context, identity string, olderThan time.Time, limit int) ([]batcher.CTSTransaction, error) {
//				panic("mock out the ClaimStuck method")
//			},
//			IncrementReceiptAttemptsFunc: func(ctx context.Context, keys []batcher.TxKey) error {
//				panic("mock out the IncrementReceiptAttempts method")
//			},
//			IncrementSendAttemptsFunc: func(ctx context.Context, keys []batcher.TxKey) error {
//				panic("mock out the IncrementSendAttempts method")
//			},
//			InsertFunc: func(ctx context.Context, req types.TxRequest) error {
//				panic("mock out the Insert method")
//			},
//			MarkFailedFunc: func(ctx context.Context, key batcher.TxKey, reason string) error {
//				panic("mock out the MarkFailed method")
//			},
//			MarkFinishedRevertFunc: func(ctx context.Context, key batcher.TxKey, revertData []byte) error {
//				panic("mock out the MarkFinishedRevert method")
//			},
//			MarkFinishedSuccessFunc: func(ctx context.Context, key batcher.TxKey, receiptStatus uint64) error {
//				panic("mock out the MarkFinishedSuccess method")
//			},
//			MarkResentFunc: func(ctx context.Context, key batcher.TxKey) error {
//				panic("mock out the MarkResent method")
//			},
//			MarkSentFunc: func(ctx context.Context, key batcher.TxKey, hash common.Hash) error {
//				panic("mock out the MarkSent method")
//			},
//		}
//
//		// use mockedRepository in code that requires batcher.Repository
//		// and then make assertions.
//
//	}
type RepositoryMock struct {
	// ClaimPendingFunc mocks the ClaimPending method.
	ClaimPendingFunc func(ctx context.Context, identity string, limit int) ([]batcher.CTSTransaction, error)

	// ClaimSentFunc mocks the ClaimSent method.
	ClaimSentFunc func(ctx context.Context, identity string, limit int) ([]batcher.CTSTransaction, error)

	// ClaimStuckFunc mocks the ClaimStuck method.
	ClaimStuckFunc func(ctx context.Context, identity string, olderThan time.Time, limit int) ([]batcher.CTSTransaction, error)

	// IncrementReceiptAttemptsFunc mocks the IncrementReceiptAttempts method.
	IncrementReceiptAttemptsFunc func(ctx context.Context, keys []batcher.TxKey) error

	// IncrementSendAttemptsFunc mocks the IncrementSendAttempts method.
	IncrementSendAttemptsFunc func(ctx context.Context, keys []batcher.TxKey) error

	// InsertFunc mocks the Insert method.
	InsertFunc func(ctx context.Context, req types.TxRequest) error

	// MarkFailedFunc mocks the MarkFailed method.
	MarkFailedFunc func(ctx context.Context, key batcher.TxKey, reason string) error

	// MarkFinishedRevertFunc mocks the MarkFinishedRevert method.
	MarkFinishedRevertFunc func(ctx context.Context, key batcher.TxKey, revertData []byte) error

	// MarkFinishedSuccessFunc mocks the MarkFinishedSuccess method.
	MarkFinishedSuccessFunc func(ctx context.Context, key batcher.TxKey, receiptStatus uint64) error

	// MarkResentFunc mocks the MarkResent method.
	MarkResentFunc func(ctx context.Context, key batcher.TxKey) error

	// MarkSentFunc mocks the MarkSent method.
	MarkSentFunc func(ctx context.Context, key batcher.TxKey, hash common.Hash) error

	// calls tracks calls to the methods.
	calls struct {
		// ClaimPending holds details about calls to the ClaimPending method.
		ClaimPending []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Identity is the identity argument value.
			Identity string
			// Limit is the limit argument value.
			Limit int
		}
		// ClaimSent holds details about calls to the ClaimSent method.
		ClaimSent []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Identity is the identity argument value.
			Identity string
			// Limit is the limit argument value.
			Limit int
		}
		// ClaimStuck holds details about calls to the ClaimStuck method.
		ClaimStuck []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Identity is the identity argument value.
			Identity string
			// OlderThan is the olderThan argument value.
			OlderThan time.Time
			// Limit is the limit argument value.
			Limit int
		}
		// IncrementReceiptAttempts holds details about calls to the IncrementReceiptAttempts method.
		IncrementReceiptAttempts []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Keys is the keys argument value.
			Keys []batcher.TxKey
		}
		// IncrementSendAttempts holds details about calls to the IncrementSendAttempts method.
		IncrementSendAttempts []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Keys is the keys argument value.
			Keys []batcher.TxKey
		}
		// Insert holds details about calls to the Insert method.
		Insert []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Req is the req argument value.
			Req types.TxRequest
		}
		// MarkFailed holds details about calls to the MarkFailed method.
		MarkFailed []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Key is the key argument value.
			Key batcher.TxKey
			// Reason is the reason argument value.
			Reason string
		}
		// MarkFinishedRevert holds details about calls to the MarkFinishedRevert method.
		MarkFinishedRevert []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Key is the key argument value.
			Key batcher.TxKey
			// RevertData is the revertData argument value.
			RevertData []byte
		}
		// MarkFinishedSuccess holds details about calls to the MarkFinishedSuccess method.
		MarkFinishedSuccess []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Key is the key argument value.
			Key batcher.TxKey
			// ReceiptStatus is the receiptStatus argument value.
			ReceiptStatus uint64
		}
		// MarkResent holds details about calls to the MarkResent method.
		MarkResent []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Key is the key argument value.
			Key batcher.TxKey
		}
		// MarkSent holds details about calls to the MarkSent method.
		MarkSent []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Key is the key argument value.
			Key batcher.TxKey
			// Hash is the hash argument value.
			Hash common.Hash
		}
	}
	lockClaimPending             sync.RWMutex
	lockClaimSent                sync.RWMutex
	lockClaimStuck               sync.RWMutex
	lockIncrementReceiptAttempts sync.RWMutex
	lockIncrementSendAttempts    sync.RWMutex
	lockInsert                   sync.RWMutex
	lockMarkFailed               sync.RWMutex
	lockMarkFinishedRevert       sync.RWMutex
	lockMarkFinishedSuccess      sync.RWMutex
	lockMarkResent               sync.RWMutex
	lockMarkSent                 sync.RWMutex
}

// ClaimPending calls ClaimPendingFunc.
func (mock *RepositoryMock) ClaimPending(ctx context.Context, identity string, limit int) ([]batcher.CTSTransaction, error) {
	if mock.ClaimPendingFunc == nil {
		panic("RepositoryMock.ClaimPendingFunc: method is nil but Repository.ClaimPending was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		Identity string
		Limit    int
	}{
		Ctx:      ctx,
		Identity: identity,
		Limit:    limit,
	}
	mock.lockClaimPending.Lock()
	mock.calls.ClaimPending = append(mock.calls.ClaimPending, callInfo)
	mock.lockClaimPending.Unlock()
	return mock.ClaimPendingFunc(ctx, identity, limit)
}

// ClaimPendingCalls gets all the calls that were made to ClaimPending.
// Check the length with:
//
//	len(mockedRepository.ClaimPendingCalls())
func (mock *RepositoryMock) ClaimPendingCalls() []struct {
	Ctx      context.Context
	Identity string
	Limit    int
} {
	var calls []struct {
		Ctx      context.Context
		Identity string
		Limit    int
	}
	mock.lockClaimPending.RLock()
	calls = mock.calls.ClaimPending
	mock.lockClaimPending.RUnlock()
	return calls
}

// ClaimSent calls ClaimSentFunc.
func (mock *RepositoryMock) ClaimSent(ctx context.Context, identity string, limit int) ([]batcher.CTSTransaction, error) {
	if mock.ClaimSentFunc == nil {
		panic("RepositoryMock.ClaimSentFunc: method is nil but Repository.ClaimSent was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		Identity string
		Limit    int
	}{
		Ctx:      ctx,
		Identity: identity,
		Limit:    limit,
	}
	mock.lockClaimSent.Lock()
	mock.calls.ClaimSent = append(mock.calls.ClaimSent, callInfo)
	mock.lockClaimSent.Unlock()
	return mock.ClaimSentFunc(ctx, identity, limit)
}

// ClaimSentCalls gets all the calls that were made to ClaimSent.
// Check the length with:
//
//	len(mockedRepository.ClaimSentCalls())
func (mock *RepositoryMock) ClaimSentCalls() []struct {
	Ctx      context.Context
	Identity string
	Limit    int
} {
	var calls []struct {
		Ctx      context.Context
		Identity string
		Limit    int
	}
	mock.lockClaimSent.RLock()
	calls = mock.calls.ClaimSent
	mock.lockClaimSent.RUnlock()
	return calls
}

// ClaimStuck calls ClaimStuckFunc.
func (mock *RepositoryMock) ClaimStuck(ctx context.Context, identity string, olderThan time.Time, limit int) ([]batcher.CTSTransaction, error) {
	if mock.ClaimStuckFunc == nil {
		panic("RepositoryMock.ClaimStuckFunc: method is nil but Repository.ClaimStuck was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		Identity  string
		OlderThan time.Time
		Limit     int
	}{
		Ctx:       ctx,
		Identity:  identity,
		OlderThan: olderThan,
		Limit:     limit,
	}
	mock.lockClaimStuck.Lock()
	mock.calls.ClaimStuck = append(mock.calls.ClaimStuck, callInfo)
	mock.lockClaimStuck.Unlock()
	return mock.ClaimStuckFunc(ctx, identity, olderThan, limit)
}

// ClaimStuckCalls gets all the calls that were made to ClaimStuck.
// Check the length with:
//
//	len(mockedRepository.ClaimStuckCalls())
func (mock *RepositoryMock) ClaimStuckCalls() []struct {
	Ctx       context.Context
	Identity  string
	OlderThan time.Time
	Limit     int
} {
	var calls []struct {
		Ctx       context.Context
		Identity  string
		OlderThan time.Time
		Limit     int
	}
	mock.lockClaimStuck.RLock()
	calls = mock.calls.ClaimStuck
	mock.lockClaimStuck.RUnlock()
	return calls
}

// IncrementReceiptAttempts calls IncrementReceiptAttemptsFunc.
func (mock *RepositoryMock) IncrementReceiptAttempts(ctx context.Context, keys []batcher.TxKey) error {
	if mock.IncrementReceiptAttemptsFunc == nil {
		panic("RepositoryMock.IncrementReceiptAttemptsFunc: method is nil but Repository.IncrementReceiptAttempts was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Keys []batcher.TxKey
	}{
		Ctx:  ctx,
		Keys: keys,
	}
	mock.lockIncrementReceiptAttempts.Lock()
	mock.calls.IncrementReceiptAttempts = append(mock.calls.IncrementReceiptAttempts, callInfo)
	mock.lockIncrementReceiptAttempts.Unlock()
	return mock.IncrementReceiptAttemptsFunc(ctx, keys)
}

// IncrementReceiptAttemptsCalls gets all the calls that were made to IncrementReceiptAttempts.
// Check the length with:
//
//	len(mockedRepository.IncrementReceiptAttemptsCalls())
func (mock *RepositoryMock) IncrementReceiptAttemptsCalls() []struct {
	Ctx  context.Context
	Keys []batcher.TxKey
} {
	var calls []struct {
		Ctx  context.Context
		Keys []batcher.TxKey
	}
	mock.lockIncrementReceiptAttempts.RLock()
	calls = mock.calls.IncrementReceiptAttempts
	mock.lockIncrementReceiptAttempts.RUnlock()
	return calls
}

// IncrementSendAttempts calls IncrementSendAttemptsFunc.
func (mock *RepositoryMock) IncrementSendAttempts(ctx context.Context, keys []batcher.TxKey) error {
	if mock.IncrementSendAttemptsFunc == nil {
		panic("RepositoryMock.IncrementSendAttemptsFunc: method is nil but Repository.IncrementSendAttempts was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Keys []batcher.TxKey
	}{
		Ctx:  ctx,
		Keys: keys,
	}
	mock.lockIncrementSendAttempts.Lock()
	mock.calls.IncrementSendAttempts = append(mock.calls.IncrementSendAttempts, callInfo)
	mock.lockIncrementSendAttempts.Unlock()
	return mock.IncrementSendAttemptsFunc(ctx, keys)
}

// IncrementSendAttemptsCalls gets all the calls that were made to IncrementSendAttempts.
// Check the length with:
//
//	len(mockedRepository.IncrementSendAttemptsCalls())
func (mock *RepositoryMock) IncrementSendAttemptsCalls() []struct {
	Ctx  context.Context
	Keys []batcher.TxKey
} {
	var calls []struct {
		Ctx  context.Context
		Keys []batcher.TxKey
	}
	mock.lockIncrementSendAttempts.RLock()
	calls = mock.calls.IncrementSendAttempts
	mock.lockIncrementSendAttempts.RUnlock()
	return calls
}

// Insert calls InsertFunc.
func (mock *RepositoryMock) Insert(ctx context.Context, req types.TxRequest) error {
	if mock.InsertFunc == nil {
		panic("RepositoryMock.InsertFunc: method is nil but Repository.Insert was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Req types.TxRequest
	}{
		Ctx: ctx,
		Req: req,
	}
	mock.lockInsert.Lock()
	mock.calls.Insert = append(mock.calls.Insert, callInfo)
	mock.lockInsert.Unlock()
	return mock.InsertFunc(ctx, req)
}

// InsertCalls gets all the calls that were made to Insert.
// Check the length with:
//
//	len(mockedRepository.InsertCalls())
func (mock *RepositoryMock) InsertCalls() []struct {
	Ctx context.Context
	Req types.TxRequest
} {
	var calls []struct {
		Ctx context.Context
		Req types.TxRequest
	}
	mock.lockInsert.RLock()
	calls = mock.calls.Insert
	mock.lockInsert.RUnlock()
	return calls
}

// MarkFailed calls MarkFailedFunc.
func (mock *RepositoryMock) MarkFailed(ctx context.Context, key batcher.TxKey, reason string) error {
	if mock.MarkFailedFunc == nil {
		panic("RepositoryMock.MarkFailedFunc: method is nil but Repository.MarkFailed was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Key    batcher.TxKey
		Reason string
	}{
		Ctx:    ctx,
		Key:    key,
		Reason: reason,
	}
	mock.lockMarkFailed.Lock()
	mock.calls.MarkFailed = append(mock.calls.MarkFailed, callInfo)
	mock.lockMarkFailed.Unlock()
	return mock.MarkFailedFunc(ctx, key, reason)
}

// MarkFailedCalls gets all the calls that were made to MarkFailed.
// Check the length with:
//
//	len(mockedRepository.MarkFailedCalls())
func (mock *RepositoryMock) MarkFailedCalls() []struct {
	Ctx    context.Context
	Key    batcher.TxKey
	Reason string
} {
	var calls []struct {
		Ctx    context.Context
		Key    batcher.TxKey
		Reason string
	}
	mock.lockMarkFailed.RLock()
	calls = mock.calls.MarkFailed
	mock.lockMarkFailed.RUnlock()
	return calls
}

// MarkFinishedRevert calls MarkFinishedRevertFunc.
func (mock *RepositoryMock) MarkFinishedRevert(ctx context.Context, key batcher.TxKey, revertData []byte) error {
	if mock.MarkFinishedRevertFunc == nil {
		panic("RepositoryMock.MarkFinishedRevertFunc: method is nil but Repository.MarkFinishedRevert was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		Key        batcher.TxKey
		RevertData []byte
	}{
		Ctx:        ctx,
		Key:        key,
		RevertData: revertData,
	}
	mock.lockMarkFinishedRevert.Lock()
	mock.calls.MarkFinishedRevert = append(mock.calls.MarkFinishedRevert, callInfo)
	mock.lockMarkFinishedRevert.Unlock()
	return mock.MarkFinishedRevertFunc(ctx, key, revertData)
}

// MarkFinishedRevertCalls gets all the calls that were made to MarkFinishedRevert.
// Check the length with:
//
//	len(mockedRepository.MarkFinishedRevertCalls())
func (mock *RepositoryMock) MarkFinishedRevertCalls() []struct {
	Ctx        context.Context
	Key        batcher.TxKey
	RevertData []byte
} {
	var calls []struct {
		Ctx        context.Context
		Key        batcher.TxKey
		RevertData []byte
	}
	mock.lockMarkFinishedRevert.RLock()
	calls = mock.calls.MarkFinishedRevert
	mock.lockMarkFinishedRevert.RUnlock()
	return calls
}

// MarkFinishedSuccess calls MarkFinishedSuccessFunc.
func (mock *RepositoryMock) MarkFinishedSuccess(ctx context.Context, key batcher.TxKey, receiptStatus uint64) error {
	if mock.MarkFinishedSuccessFunc == nil {
		panic("RepositoryMock.MarkFinishedSuccessFunc: method is nil but Repository.MarkFinishedSuccess was just called")
	}
	callInfo := struct {
		Ctx           context.Context
		Key           batcher.TxKey
		ReceiptStatus uint64
	}{
		Ctx:           ctx,
		Key:           key,
		ReceiptStatus: receiptStatus,
	}
	mock.lockMarkFinishedSuccess.Lock()
	mock.calls.MarkFinishedSuccess = append(mock.calls.MarkFinishedSuccess, callInfo)
	mock.lockMarkFinishedSuccess.Unlock()
	return mock.MarkFinishedSuccessFunc(ctx, key, receiptStatus)
}

// MarkFinishedSuccessCalls gets all the calls that were made to MarkFinishedSuccess.
// Check the length with:
//
//	len(mockedRepository.MarkFinishedSuccessCalls())
func (mock *RepositoryMock) MarkFinishedSuccessCalls() []struct {
	Ctx           context.Context
	Key           batcher.TxKey
	ReceiptStatus uint64
} {
	var calls []struct {
		Ctx           context.Context
		Key           batcher.TxKey
		ReceiptStatus uint64
	}
	mock.lockMarkFinishedSuccess.RLock()
	calls = mock.calls.MarkFinishedSuccess
	mock.lockMarkFinishedSuccess.RUnlock()
	return calls
}

// MarkResent calls MarkResentFunc.
func (mock *RepositoryMock) MarkResent(ctx context.Context, key batcher.TxKey) error {
	if mock.MarkResentFunc == nil {
		panic("RepositoryMock.MarkResentFunc: method is nil but Repository.MarkResent was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Key batcher.TxKey
	}{
		Ctx: ctx,
		Key: key,
	}
	mock.lockMarkResent.Lock()
	mock.calls.MarkResent = append(mock.calls.MarkResent, callInfo)
	mock.lockMarkResent.Unlock()
	return mock.MarkResentFunc(ctx, key)
}

// MarkResentCalls gets all the calls that were made to MarkResent.
// Check the length with:
//
//	len(mockedRepository.MarkResentCalls())
func (mock *RepositoryMock) MarkResentCalls() []struct {
	Ctx context.Context
	Key batcher.TxKey
} {
	var calls []struct {
		Ctx context.Context
		Key batcher.TxKey
	}
	mock.lockMarkResent.RLock()
	calls = mock.calls.MarkResent
	mock.lockMarkResent.RUnlock()
	return calls
}

// MarkSent calls MarkSentFunc.
func (mock *RepositoryMock) MarkSent(ctx context.Context, key batcher.TxKey, hash common.Hash) error {
	if mock.MarkSentFunc == nil {
		panic("RepositoryMock.MarkSentFunc: method is nil but Repository.MarkSent was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Key  batcher.TxKey
		Hash common.Hash
	}{
		Ctx:  ctx,
		Key:  key,
		Hash: hash,
	}
	mock.lockMarkSent.Lock()
	mock.calls.MarkSent = append(mock.calls.MarkSent, callInfo)
	mock.lockMarkSent.Unlock()
	return mock.MarkSentFunc(ctx, key, hash)
}

// MarkSentCalls gets all the calls that were made to MarkSent.
// Check the length with:
//
//	len(mockedRepository.MarkSentCalls())
func (mock *RepositoryMock) MarkSentCalls() []struct {
	Ctx  context.Context
	Key  batcher.TxKey
	Hash common.Hash
} {
	var calls []struct {
		Ctx  context.Context
		Key  batcher.TxKey
		Hash common.Hash
	}
	mock.lockMarkSent.RLock()
	calls = mock.calls.MarkSent
	mock.lockMarkSent.RUnlock()
	return calls
}
