// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package keymanager_test

import (
	"context"
	"github.com/raylsnetwork/rayls-privacy-relayer-api/cts/domain"
	"github.com/raylsnetwork/rayls-privacy-relayer-api/cts/keymanager"
	"sync"
)

// Ensure, that KeysServiceMock does implement keymanager.KeysService.
// If this is not the case, regenerate this file with moq.
var _ keymanager.KeysService = &KeysServiceMock{}

// KeysServiceMock is a mock implementation of keymanager.KeysService.
//
//	func TestSomethingThatUsesKeysService(t *testing.T) {
//
//		// make and configure a mocked keymanager.KeysService
//		mockedKeysService := &KeysServiceMock{
//			CreatePrivateRelayerRaylsSignKeysFunc: func(ctx context.Context) (domain.PrivateRelayerRaylsSignKeys, error) {
//				panic("mock out the CreatePrivateRelayerRaylsSignKeys method")
//			},
//			CreatePublicRelayerRaylsSignKeysFunc: func(ctx context.Context) (domain.PublicRelayerRaylsSignKeys, error) {
//				panic("mock out the CreatePublicRelayerRaylsSignKeys method")
//			},
//			GetPrivateRelayerRaylsSignKeysFunc: func(ctx context.Context) (domain.PrivateRelayerRaylsSignKeys, error) {
//				panic("mock out the GetPrivateRelayerRaylsSignKeys method")
//			},
//			GetPublicRelayerRaylsSignKeysFunc: func(ctx context.Context) (domain.PublicRelayerRaylsSignKeys, error) {
//				panic("mock out the GetPublicRelayerRaylsSignKeys method")
//			},
//		}
//
//		// use mockedKeysService in code that requires keymanager.KeysService
//		// and then make assertions.
//
//	}
type KeysServiceMock struct {
	// CreatePrivateRelayerRaylsSignKeysFunc mocks the CreatePrivateRelayerRaylsSignKeys method.
	CreatePrivateRelayerRaylsSignKeysFunc func(ctx context.Context) (domain.PrivateRelayerRaylsSignKeys, error)

	// CreatePublicRelayerRaylsSignKeysFunc mocks the CreatePublicRelayerRaylsSignKeys method.
	CreatePublicRelayerRaylsSignKeysFunc func(ctx context.Context) (domain.PublicRelayerRaylsSignKeys, error)

	// GetPrivateRelayerRaylsSignKeysFunc mocks the GetPrivateRelayerRaylsSignKeys method.
	GetPrivateRelayerRaylsSignKeysFunc func(ctx context.Context) (domain.PrivateRelayerRaylsSignKeys, error)

	// GetPublicRelayerRaylsSignKeysFunc mocks the GetPublicRelayerRaylsSignKeys method.
	GetPublicRelayerRaylsSignKeysFunc func(ctx context.Context) (domain.PublicRelayerRaylsSignKeys, error)

	// calls tracks calls to the methods.
	calls struct {
		// CreatePrivateRelayerRaylsSignKeys holds details about calls to the CreatePrivateRelayerRaylsSignKeys method.
		CreatePrivateRelayerRaylsSignKeys []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// CreatePublicRelayerRaylsSignKeys holds details about calls to the CreatePublicRelayerRaylsSignKeys method.
		CreatePublicRelayerRaylsSignKeys []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// GetPrivateRelayerRaylsSignKeys holds details about calls to the GetPrivateRelayerRaylsSignKeys method.
		GetPrivateRelayerRaylsSignKeys []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// GetPublicRelayerRaylsSignKeys holds details about calls to the GetPublicRelayerRaylsSignKeys method.
		GetPublicRelayerRaylsSignKeys []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
	}
	lockCreatePrivateRelayerRaylsSignKeys sync.RWMutex
	lockCreatePublicRelayerRaylsSignKeys  sync.RWMutex
	lockGetPrivateRelayerRaylsSignKeys    sync.RWMutex
	lockGetPublicRelayerRaylsSignKeys     sync.RWMutex
}

// CreatePrivateRelayerRaylsSignKeys calls CreatePrivateRelayerRaylsSignKeysFunc.
func (mock *KeysServiceMock) CreatePrivateRelayerRaylsSignKeys(ctx context.Context) (domain.PrivateRelayerRaylsSignKeys, error) {
	if mock.CreatePrivateRelayerRaylsSignKeysFunc == nil {
		panic("KeysServiceMock.CreatePrivateRelayerRaylsSignKeysFunc: method is nil but KeysService.CreatePrivateRelayerRaylsSignKeys was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockCreatePrivateRelayerRaylsSignKeys.Lock()
	mock.calls.CreatePrivateRelayerRaylsSignKeys = append(mock.calls.CreatePrivateRelayerRaylsSignKeys, callInfo)
	mock.lockCreatePrivateRelayerRaylsSignKeys.Unlock()
	return mock.CreatePrivateRelayerRaylsSignKeysFunc(ctx)
}

// CreatePrivateRelayerRaylsSignKeysCalls gets all the calls that were made to CreatePrivateRelayerRaylsSignKeys.
// Check the length with:
//
//	len(mockedKeysService.CreatePrivateRelayerRaylsSignKeysCalls())
func (mock *KeysServiceMock) CreatePrivateRelayerRaylsSignKeysCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockCreatePrivateRelayerRaylsSignKeys.RLock()
	calls = mock.calls.CreatePrivateRelayerRaylsSignKeys
	mock.lockCreatePrivateRelayerRaylsSignKeys.RUnlock()
	return calls
}

// CreatePublicRelayerRaylsSignKeys calls CreatePublicRelayerRaylsSignKeysFunc.
func (mock *KeysServiceMock) CreatePublicRelayerRaylsSignKeys(ctx context.Context) (domain.PublicRelayerRaylsSignKeys, error) {
	if mock.CreatePublicRelayerRaylsSignKeysFunc == nil {
		panic("KeysServiceMock.CreatePublicRelayerRaylsSignKeysFunc: method is nil but KeysService.CreatePublicRelayerRaylsSignKeys was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockCreatePublicRelayerRaylsSignKeys.Lock()
	mock.calls.CreatePublicRelayerRaylsSignKeys = append(mock.calls.CreatePublicRelayerRaylsSignKeys, callInfo)
	mock.lockCreatePublicRelayerRaylsSignKeys.Unlock()
	return mock.CreatePublicRelayerRaylsSignKeysFunc(ctx)
}

// CreatePublicRelayerRaylsSignKeysCalls gets all the calls that were made to CreatePublicRelayerRaylsSignKeys.
// Check the length with:
//
//	len(mockedKeysService.CreatePublicRelayerRaylsSignKeysCalls())
func (mock *KeysServiceMock) CreatePublicRelayerRaylsSignKeysCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockCreatePublicRelayerRaylsSignKeys.RLock()
	calls = mock.calls.CreatePublicRelayerRaylsSignKeys
	mock.lockCreatePublicRelayerRaylsSignKeys.RUnlock()
	return calls
}

// GetPrivateRelayerRaylsSignKeys calls GetPrivateRelayerRaylsSignKeysFunc.
func (mock *KeysServiceMock) GetPrivateRelayerRaylsSignKeys(ctx context.Context) (domain.PrivateRelayerRaylsSignKeys, error) {
	if mock.GetPrivateRelayerRaylsSignKeysFunc == nil {
		panic("KeysServiceMock.GetPrivateRelayerRaylsSignKeysFunc: method is nil but KeysService.GetPrivateRelayerRaylsSignKeys was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockGetPrivateRelayerRaylsSignKeys.Lock()
	mock.calls.GetPrivateRelayerRaylsSignKeys = append(mock.calls.GetPrivateRelayerRaylsSignKeys, callInfo)
	mock.lockGetPrivateRelayerRaylsSignKeys.Unlock()
	return mock.GetPrivateRelayerRaylsSignKeysFunc(ctx)
}

// GetPrivateRelayerRaylsSignKeysCalls gets all the calls that were made to GetPrivateRelayerRaylsSignKeys.
// Check the length with:
//
//	len(mockedKeysService.GetPrivateRelayerRaylsSignKeysCalls())
func (mock *KeysServiceMock) GetPrivateRelayerRaylsSignKeysCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockGetPrivateRelayerRaylsSignKeys.RLock()
	calls = mock.calls.GetPrivateRelayerRaylsSignKeys
	mock.lockGetPrivateRelayerRaylsSignKeys.RUnlock()
	return calls
}

// GetPublicRelayerRaylsSignKeys calls GetPublicRelayerRaylsSignKeysFunc.
func (mock *KeysServiceMock) GetPublicRelayerRaylsSignKeys(ctx context.Context) (domain.PublicRelayerRaylsSignKeys, error) {
	if mock.GetPublicRelayerRaylsSignKeysFunc == nil {
		panic("KeysServiceMock.GetPublicRelayerRaylsSignKeysFunc: method is nil but KeysService.GetPublicRelayerRaylsSignKeys was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockGetPublicRelayerRaylsSignKeys.Lock()
	mock.calls.GetPublicRelayerRaylsSignKeys = append(mock.calls.GetPublicRelayerRaylsSignKeys, callInfo)
	mock.lockGetPublicRelayerRaylsSignKeys.Unlock()
	return mock.GetPublicRelayerRaylsSignKeysFunc(ctx)
}

// GetPublicRelayerRaylsSignKeysCalls gets all the calls that were made to GetPublicRelayerRaylsSignKeys.
// Check the length with:
//
//	len(mockedKeysService.GetPublicRelayerRaylsSignKeysCalls())
func (mock *KeysServiceMock) GetPublicRelayerRaylsSignKeysCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockGetPublicRelayerRaylsSignKeys.RLock()
	calls = mock.calls.GetPublicRelayerRaylsSignKeys
	mock.lockGetPublicRelayerRaylsSignKeys.RUnlock()
	return calls
}

// Ensure, that AccessManagerMock does implement keymanager.AccessManager.
// If this is not the case, regenerate this file with moq.
var _ keymanager.AccessManager = &AccessManagerMock{}

// AccessManagerMock is a mock implementation of keymanager.AccessManager.
//
//	func TestSomethingThatUsesAccessManager(t *testing.T) {
//
//		// make and configure a mocked keymanager.AccessManager
//		mockedAccessManager := &AccessManagerMock{
//			WaitForAuthorizationFunc: func(ctx context.Context, component string, keys []string) error {
//				panic("mock out the WaitForAuthorization method")
//			},
//		}
//
//		// use mockedAccessManager in code that requires keymanager.AccessManager
//		// and then make assertions.
//
//	}
type AccessManagerMock struct {
	// WaitForAuthorizationFunc mocks the WaitForAuthorization method.
	WaitForAuthorizationFunc func(ctx context.Context, component string, keys []string) error

	// calls tracks calls to the methods.
	calls struct {
		// WaitForAuthorization holds details about calls to the WaitForAuthorization method.
		WaitForAuthorization []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Component is the component argument value.
			Component string
			// Keys is the keys argument value.
			Keys []string
		}
	}
	lockWaitForAuthorization sync.RWMutex
}

// WaitForAuthorization calls WaitForAuthorizationFunc.
func (mock *AccessManagerMock) WaitForAuthorization(ctx context.Context, component string, keys []string) error {
	if mock.WaitForAuthorizationFunc == nil {
		panic("AccessManagerMock.WaitForAuthorizationFunc: method is nil but AccessManager.WaitForAuthorization was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		Component string
		Keys      []string
	}{
		Ctx:       ctx,
		Component: component,
		Keys:      keys,
	}
	mock.lockWaitForAuthorization.Lock()
	mock.calls.WaitForAuthorization = append(mock.calls.WaitForAuthorization, callInfo)
	mock.lockWaitForAuthorization.Unlock()
	return mock.WaitForAuthorizationFunc(ctx, component, keys)
}

// WaitForAuthorizationCalls gets all the calls that were made to WaitForAuthorization.
// Check the length with:
//
//	len(mockedAccessManager.WaitForAuthorizationCalls())
func (mock *AccessManagerMock) WaitForAuthorizationCalls() []struct {
	Ctx       context.Context
	Component string
	Keys      []string
} {
	var calls []struct {
		Ctx       context.Context
		Component string
		Keys      []string
	}
	mock.lockWaitForAuthorization.RLock()
	calls = mock.calls.WaitForAuthorization
	mock.lockWaitForAuthorization.RUnlock()
	return calls
}
