// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package service_test

import (
	"context"
	"github.com/ethereum/go-ethereum/common"
	"github.com/raylsnetwork/rayls-sovereign-relayer/batcher"
	"github.com/raylsnetwork/rayls-sovereign-relayer/contracts/EndpointV1"
	"github.com/raylsnetwork/rayls-sovereign-relayer/msgqueue"
	"github.com/raylsnetwork/rayls-sovereign-relayer/private-relayer/dest/service"
	"github.com/raylsnetwork/rayls-sovereign-relayer/types"
	"math/big"
	"sync"
)

// Ensure, that CrossChainMQMock does implement service.CrossChainMQ.
// If this is not the case, regenerate this file with moq.
var _ service.CrossChainMQ = &CrossChainMQMock{}

// CrossChainMQMock is a mock implementation of service.CrossChainMQ.
//
//	func TestSomethingThatUsesCrossChainMQ(t *testing.T) {
//
//		// make and configure a mocked service.CrossChainMQ
//		mockedCrossChainMQ := &CrossChainMQMock{
//			FetchFunc: func(ctx context.Context, count int) ([]msgqueue.Message[types.DispatchedMessageToPrivateHub], error) {
//				panic("mock out the Fetch method")
//			},
//		}
//
//		// use mockedCrossChainMQ in code that requires service.CrossChainMQ
//		// and then make assertions.
//
//	}
type CrossChainMQMock struct {
	// FetchFunc mocks the Fetch method.
	FetchFunc func(ctx context.Context, count int) ([]msgqueue.Message[types.DispatchedMessageToPrivateHub], error)

	// calls tracks calls to the methods.
	calls struct {
		// Fetch holds details about calls to the Fetch method.
		Fetch []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Count is the count argument value.
			Count int
		}
	}
	lockFetch sync.RWMutex
}

// Fetch calls FetchFunc.
func (mock *CrossChainMQMock) Fetch(ctx context.Context, count int) ([]msgqueue.Message[types.DispatchedMessageToPrivateHub], error) {
	if mock.FetchFunc == nil {
		panic("CrossChainMQMock.FetchFunc: method is nil but CrossChainMQ.Fetch was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Count int
	}{
		Ctx:   ctx,
		Count: count,
	}
	mock.lockFetch.Lock()
	mock.calls.Fetch = append(mock.calls.Fetch, callInfo)
	mock.lockFetch.Unlock()
	return mock.FetchFunc(ctx, count)
}

// FetchCalls gets all the calls that were made to Fetch.
// Check the length with:
//
//	len(mockedCrossChainMQ.FetchCalls())
func (mock *CrossChainMQMock) FetchCalls() []struct {
	Ctx   context.Context
	Count int
} {
	var calls []struct {
		Ctx   context.Context
		Count int
	}
	mock.lockFetch.RLock()
	calls = mock.calls.Fetch
	mock.lockFetch.RUnlock()
	return calls
}

// Ensure, that TransactionRepositoryMock does implement service.TransactionRepository.
// If this is not the case, regenerate this file with moq.
var _ service.TransactionRepository = &TransactionRepositoryMock{}

// TransactionRepositoryMock is a mock implementation of service.TransactionRepository.
//
//	func TestSomethingThatUsesTransactionRepository(t *testing.T) {
//
//		// make and configure a mocked service.TransactionRepository
//		mockedTransactionRepository := &TransactionRepositoryMock{
//			BatchCreateFunc: func(ctx context.Context, txs []types.Transaction) error {
//				panic("mock out the BatchCreate method")
//			},
//			BatchUpdateDestinationHashForSharedIDsFunc: func(ctx context.Context, hashBySharedID map[string]common.Hash) error {
//				panic("mock out the BatchUpdateDestinationHashForSharedIDs method")
//			},
//		}
//
//		// use mockedTransactionRepository in code that requires service.TransactionRepository
//		// and then make assertions.
//
//	}
type TransactionRepositoryMock struct {
	// BatchCreateFunc mocks the BatchCreate method.
	BatchCreateFunc func(ctx context.Context, txs []types.Transaction) error

	// BatchUpdateDestinationHashForSharedIDsFunc mocks the BatchUpdateDestinationHashForSharedIDs method.
	BatchUpdateDestinationHashForSharedIDsFunc func(ctx context.Context, hashBySharedID map[string]common.Hash) error

	// calls tracks calls to the methods.
	calls struct {
		// BatchCreate holds details about calls to the BatchCreate method.
		BatchCreate []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Txs is the txs argument value.
			Txs []types.Transaction
		}
		// BatchUpdateDestinationHashForSharedIDs holds details about calls to the BatchUpdateDestinationHashForSharedIDs method.
		BatchUpdateDestinationHashForSharedIDs []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// HashBySharedID is the hashBySharedID argument value.
			HashBySharedID map[string]common.Hash
		}
	}
	lockBatchCreate                            sync.RWMutex
	lockBatchUpdateDestinationHashForSharedIDs sync.RWMutex
}

// BatchCreate calls BatchCreateFunc.
func (mock *TransactionRepositoryMock) BatchCreate(ctx context.Context, txs []types.Transaction) error {
	if mock.BatchCreateFunc == nil {
		panic("TransactionRepositoryMock.BatchCreateFunc: method is nil but TransactionRepository.BatchCreate was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Txs []types.Transaction
	}{
		Ctx: ctx,
		Txs: txs,
	}
	mock.lockBatchCreate.Lock()
	mock.calls.BatchCreate = append(mock.calls.BatchCreate, callInfo)
	mock.lockBatchCreate.Unlock()
	return mock.BatchCreateFunc(ctx, txs)
}

// BatchCreateCalls gets all the calls that were made to BatchCreate.
// Check the length with:
//
//	len(mockedTransactionRepository.BatchCreateCalls())
func (mock *TransactionRepositoryMock) BatchCreateCalls() []struct {
	Ctx context.Context
	Txs []types.Transaction
} {
	var calls []struct {
		Ctx context.Context
		Txs []types.Transaction
	}
	mock.lockBatchCreate.RLock()
	calls = mock.calls.BatchCreate
	mock.lockBatchCreate.RUnlock()
	return calls
}

// BatchUpdateDestinationHashForSharedIDs calls BatchUpdateDestinationHashForSharedIDsFunc.
func (mock *TransactionRepositoryMock) BatchUpdateDestinationHashForSharedIDs(ctx context.Context, hashBySharedID map[string]common.Hash) error {
	if mock.BatchUpdateDestinationHashForSharedIDsFunc == nil {
		panic("TransactionRepositoryMock.BatchUpdateDestinationHashForSharedIDsFunc: method is nil but TransactionRepository.BatchUpdateDestinationHashForSharedIDs was just called")
	}
	callInfo := struct {
		Ctx            context.Context
		HashBySharedID map[string]common.Hash
	}{
		Ctx:            ctx,
		HashBySharedID: hashBySharedID,
	}
	mock.lockBatchUpdateDestinationHashForSharedIDs.Lock()
	mock.calls.BatchUpdateDestinationHashForSharedIDs = append(mock.calls.BatchUpdateDestinationHashForSharedIDs, callInfo)
	mock.lockBatchUpdateDestinationHashForSharedIDs.Unlock()
	return mock.BatchUpdateDestinationHashForSharedIDsFunc(ctx, hashBySharedID)
}

// BatchUpdateDestinationHashForSharedIDsCalls gets all the calls that were made to BatchUpdateDestinationHashForSharedIDs.
// Check the length with:
//
//	len(mockedTransactionRepository.BatchUpdateDestinationHashForSharedIDsCalls())
func (mock *TransactionRepositoryMock) BatchUpdateDestinationHashForSharedIDsCalls() []struct {
	Ctx            context.Context
	HashBySharedID map[string]common.Hash
} {
	var calls []struct {
		Ctx            context.Context
		HashBySharedID map[string]common.Hash
	}
	mock.lockBatchUpdateDestinationHashForSharedIDs.RLock()
	calls = mock.calls.BatchUpdateDestinationHashForSharedIDs
	mock.lockBatchUpdateDestinationHashForSharedIDs.RUnlock()
	return calls
}

// Ensure, that SignatureRepositoryMock does implement service.SignatureRepository.
// If this is not the case, regenerate this file with moq.
var _ service.SignatureRepository = &SignatureRepositoryMock{}

// SignatureRepositoryMock is a mock implementation of service.SignatureRepository.
//
//	func TestSomethingThatUsesSignatureRepository(t *testing.T) {
//
//		// make and configure a mocked service.SignatureRepository
//		mockedSignatureRepository := &SignatureRepositoryMock{
//			BatchCreateFunc: func(ctx context.Context, signatures []types.CalldataSignature) error {
//				panic("mock out the BatchCreate method")
//			},
//		}
//
//		// use mockedSignatureRepository in code that requires service.SignatureRepository
//		// and then make assertions.
//
//	}
type SignatureRepositoryMock struct {
	// BatchCreateFunc mocks the BatchCreate method.
	BatchCreateFunc func(ctx context.Context, signatures []types.CalldataSignature) error

	// calls tracks calls to the methods.
	calls struct {
		// BatchCreate holds details about calls to the BatchCreate method.
		BatchCreate []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Signatures is the signatures argument value.
			Signatures []types.CalldataSignature
		}
	}
	lockBatchCreate sync.RWMutex
}

// BatchCreate calls BatchCreateFunc.
func (mock *SignatureRepositoryMock) BatchCreate(ctx context.Context, signatures []types.CalldataSignature) error {
	if mock.BatchCreateFunc == nil {
		panic("SignatureRepositoryMock.BatchCreateFunc: method is nil but SignatureRepository.BatchCreate was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		Signatures []types.CalldataSignature
	}{
		Ctx:        ctx,
		Signatures: signatures,
	}
	mock.lockBatchCreate.Lock()
	mock.calls.BatchCreate = append(mock.calls.BatchCreate, callInfo)
	mock.lockBatchCreate.Unlock()
	return mock.BatchCreateFunc(ctx, signatures)
}

// BatchCreateCalls gets all the calls that were made to BatchCreate.
// Check the length with:
//
//	len(mockedSignatureRepository.BatchCreateCalls())
func (mock *SignatureRepositoryMock) BatchCreateCalls() []struct {
	Ctx        context.Context
	Signatures []types.CalldataSignature
} {
	var calls []struct {
		Ctx        context.Context
		Signatures []types.CalldataSignature
	}
	mock.lockBatchCreate.RLock()
	calls = mock.calls.BatchCreate
	mock.lockBatchCreate.RUnlock()
	return calls
}

// Ensure, that TransactionGeneratorMock does implement service.TransactionGenerator.
// If this is not the case, regenerate this file with moq.
var _ service.TransactionGenerator = &TransactionGeneratorMock{}

// TransactionGeneratorMock is a mock implementation of service.TransactionGenerator.
//
//	func TestSomethingThatUsesTransactionGenerator(t *testing.T) {
//
//		// make and configure a mocked service.TransactionGenerator
//		mockedTransactionGenerator := &TransactionGeneratorMock{
//			GenerateFunc: func(fromChainID *big.Int, fromAddress common.Address, toAddress common.Address, message EndpointV1.RaylsMessage, id common.Hash) ([]byte, error) {
//				panic("mock out the Generate method")
//			},
//		}
//
//		// use mockedTransactionGenerator in code that requires service.TransactionGenerator
//		// and then make assertions.
//
//	}
type TransactionGeneratorMock struct {
	// GenerateFunc mocks the Generate method.
	GenerateFunc func(fromChainID *big.Int, fromAddress common.Address, toAddress common.Address, message EndpointV1.RaylsMessage, id common.Hash) ([]byte, error)

	// calls tracks calls to the methods.
	calls struct {
		// Generate holds details about calls to the Generate method.
		Generate []struct {
			// FromChainID is the fromChainID argument value.
			FromChainID *big.Int
			// FromAddress is the fromAddress argument value.
			FromAddress common.Address
			// ToAddress is the toAddress argument value.
			ToAddress common.Address
			// Message is the message argument value.
			Message EndpointV1.RaylsMessage
			// ID is the id argument value.
			ID common.Hash
		}
	}
	lockGenerate sync.RWMutex
}

// Generate calls GenerateFunc.
func (mock *TransactionGeneratorMock) Generate(fromChainID *big.Int, fromAddress common.Address, toAddress common.Address, message EndpointV1.RaylsMessage, id common.Hash) ([]byte, error) {
	if mock.GenerateFunc == nil {
		panic("TransactionGeneratorMock.GenerateFunc: method is nil but TransactionGenerator.Generate was just called")
	}
	callInfo := struct {
		FromChainID *big.Int
		FromAddress common.Address
		ToAddress   common.Address
		Message     EndpointV1.RaylsMessage
		ID          common.Hash
	}{
		FromChainID: fromChainID,
		FromAddress: fromAddress,
		ToAddress:   toAddress,
		Message:     message,
		ID:          id,
	}
	mock.lockGenerate.Lock()
	mock.calls.Generate = append(mock.calls.Generate, callInfo)
	mock.lockGenerate.Unlock()
	return mock.GenerateFunc(fromChainID, fromAddress, toAddress, message, id)
}

// GenerateCalls gets all the calls that were made to Generate.
// Check the length with:
//
//	len(mockedTransactionGenerator.GenerateCalls())
func (mock *TransactionGeneratorMock) GenerateCalls() []struct {
	FromChainID *big.Int
	FromAddress common.Address
	ToAddress   common.Address
	Message     EndpointV1.RaylsMessage
	ID          common.Hash
} {
	var calls []struct {
		FromChainID *big.Int
		FromAddress common.Address
		ToAddress   common.Address
		Message     EndpointV1.RaylsMessage
		ID          common.Hash
	}
	mock.lockGenerate.RLock()
	calls = mock.calls.Generate
	mock.lockGenerate.RUnlock()
	return calls
}

// Ensure, that BatcherMock does implement service.Batcher.
// If this is not the case, regenerate this file with moq.
var _ service.Batcher = &BatcherMock{}

// BatcherMock is a mock implementation of service.Batcher.
//
//	func TestSomethingThatUsesBatcher(t *testing.T) {
//
//		// make and configure a mocked service.Batcher
//		mockedBatcher := &BatcherMock{
//			SendFunc: func(ctx context.Context, msgs []batcher.Message) error {
//				panic("mock out the Send method")
//			},
//		}
//
//		// use mockedBatcher in code that requires service.Batcher
//		// and then make assertions.
//
//	}
type BatcherMock struct {
	// SendFunc mocks the Send method.
	SendFunc func(ctx context.Context, msgs []batcher.Message) error

	// calls tracks calls to the methods.
	calls struct {
		// Send holds details about calls to the Send method.
		Send []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Msgs is the msgs argument value.
			Msgs []batcher.Message
		}
	}
	lockSend sync.RWMutex
}

// Send calls SendFunc.
func (mock *BatcherMock) Send(ctx context.Context, msgs []batcher.Message) error {
	if mock.SendFunc == nil {
		panic("BatcherMock.SendFunc: method is nil but Batcher.Send was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Msgs []batcher.Message
	}{
		Ctx:  ctx,
		Msgs: msgs,
	}
	mock.lockSend.Lock()
	mock.calls.Send = append(mock.calls.Send, callInfo)
	mock.lockSend.Unlock()
	return mock.SendFunc(ctx, msgs)
}

// SendCalls gets all the calls that were made to Send.
// Check the length with:
//
//	len(mockedBatcher.SendCalls())
func (mock *BatcherMock) SendCalls() []struct {
	Ctx  context.Context
	Msgs []batcher.Message
} {
	var calls []struct {
		Ctx  context.Context
		Msgs []batcher.Message
	}
	mock.lockSend.RLock()
	calls = mock.calls.Send
	mock.lockSend.RUnlock()
	return calls
}

// Ensure, that ReceiptHandlerMock does implement service.ReceiptHandler.
// If this is not the case, regenerate this file with moq.
var _ service.ReceiptHandler = &ReceiptHandlerMock{}

// ReceiptHandlerMock is a mock implementation of service.ReceiptHandler.
//
//	func TestSomethingThatUsesReceiptHandler(t *testing.T) {
//
//		// make and configure a mocked service.ReceiptHandler
//		mockedReceiptHandler := &ReceiptHandlerMock{
//			HandleFailedMinedFunc: func(ctx context.Context, sharedIDs []string) error {
//				panic("mock out the HandleFailedMined method")
//			},
//			HandleSuccessfullyMinedFunc: func(ctx context.Context, sharedIDs []string) error {
//				panic("mock out the HandleSuccessfullyMined method")
//			},
//		}
//
//		// use mockedReceiptHandler in code that requires service.ReceiptHandler
//		// and then make assertions.
//
//	}
type ReceiptHandlerMock struct {
	// HandleFailedMinedFunc mocks the HandleFailedMined method.
	HandleFailedMinedFunc func(ctx context.Context, sharedIDs []string) error

	// HandleSuccessfullyMinedFunc mocks the HandleSuccessfullyMined method.
	HandleSuccessfullyMinedFunc func(ctx context.Context, sharedIDs []string) error

	// calls tracks calls to the methods.
	calls struct {
		// HandleFailedMined holds details about calls to the HandleFailedMined method.
		HandleFailedMined []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// SharedIDs is the sharedIDs argument value.
			SharedIDs []string
		}
		// HandleSuccessfullyMined holds details about calls to the HandleSuccessfullyMined method.
		HandleSuccessfullyMined []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// SharedIDs is the sharedIDs argument value.
			SharedIDs []string
		}
	}
	lockHandleFailedMined       sync.RWMutex
	lockHandleSuccessfullyMined sync.RWMutex
}

// HandleFailedMined calls HandleFailedMinedFunc.
func (mock *ReceiptHandlerMock) HandleFailedMined(ctx context.Context, sharedIDs []string) error {
	if mock.HandleFailedMinedFunc == nil {
		panic("ReceiptHandlerMock.HandleFailedMinedFunc: method is nil but ReceiptHandler.HandleFailedMined was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		SharedIDs []string
	}{
		Ctx:       ctx,
		SharedIDs: sharedIDs,
	}
	mock.lockHandleFailedMined.Lock()
	mock.calls.HandleFailedMined = append(mock.calls.HandleFailedMined, callInfo)
	mock.lockHandleFailedMined.Unlock()
	return mock.HandleFailedMinedFunc(ctx, sharedIDs)
}

// HandleFailedMinedCalls gets all the calls that were made to HandleFailedMined.
// Check the length with:
//
//	len(mockedReceiptHandler.HandleFailedMinedCalls())
func (mock *ReceiptHandlerMock) HandleFailedMinedCalls() []struct {
	Ctx       context.Context
	SharedIDs []string
} {
	var calls []struct {
		Ctx       context.Context
		SharedIDs []string
	}
	mock.lockHandleFailedMined.RLock()
	calls = mock.calls.HandleFailedMined
	mock.lockHandleFailedMined.RUnlock()
	return calls
}

// HandleSuccessfullyMined calls HandleSuccessfullyMinedFunc.
func (mock *ReceiptHandlerMock) HandleSuccessfullyMined(ctx context.Context, sharedIDs []string) error {
	if mock.HandleSuccessfullyMinedFunc == nil {
		panic("ReceiptHandlerMock.HandleSuccessfullyMinedFunc: method is nil but ReceiptHandler.HandleSuccessfullyMined was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		SharedIDs []string
	}{
		Ctx:       ctx,
		SharedIDs: sharedIDs,
	}
	mock.lockHandleSuccessfullyMined.Lock()
	mock.calls.HandleSuccessfullyMined = append(mock.calls.HandleSuccessfullyMined, callInfo)
	mock.lockHandleSuccessfullyMined.Unlock()
	return mock.HandleSuccessfullyMinedFunc(ctx, sharedIDs)
}

// HandleSuccessfullyMinedCalls gets all the calls that were made to HandleSuccessfullyMined.
// Check the length with:
//
//	len(mockedReceiptHandler.HandleSuccessfullyMinedCalls())
func (mock *ReceiptHandlerMock) HandleSuccessfullyMinedCalls() []struct {
	Ctx       context.Context
	SharedIDs []string
} {
	var calls []struct {
		Ctx       context.Context
		SharedIDs []string
	}
	mock.lockHandleSuccessfullyMined.RLock()
	calls = mock.calls.HandleSuccessfullyMined
	mock.lockHandleSuccessfullyMined.RUnlock()
	return calls
}

// Ensure, that EndpointClientMock does implement service.EndpointClient.
// If this is not the case, regenerate this file with moq.
var _ service.EndpointClient = &EndpointClientMock{}

// EndpointClientMock is a mock implementation of service.EndpointClient.
//
//	func TestSomethingThatUsesEndpointClient(t *testing.T) {
//
//		// make and configure a mocked service.EndpointClient
//		mockedEndpointClient := &EndpointClientMock{
//			GetResourceAddressFunc: func(ctx context.Context, resourceId string) (common.Address, error) {
//				panic("mock out the GetResourceAddress method")
//			},
//		}
//
//		// use mockedEndpointClient in code that requires service.EndpointClient
//		// and then make assertions.
//
//	}
type EndpointClientMock struct {
	// GetResourceAddressFunc mocks the GetResourceAddress method.
	GetResourceAddressFunc func(ctx context.Context, resourceId string) (common.Address, error)

	// calls tracks calls to the methods.
	calls struct {
		// GetResourceAddress holds details about calls to the GetResourceAddress method.
		GetResourceAddress []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ResourceId is the resourceId argument value.
			ResourceId string
		}
	}
	lockGetResourceAddress sync.RWMutex
}

// GetResourceAddress calls GetResourceAddressFunc.
func (mock *EndpointClientMock) GetResourceAddress(ctx context.Context, resourceId string) (common.Address, error) {
	if mock.GetResourceAddressFunc == nil {
		panic("EndpointClientMock.GetResourceAddressFunc: method is nil but EndpointClient.GetResourceAddress was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		ResourceId string
	}{
		Ctx:        ctx,
		ResourceId: resourceId,
	}
	mock.lockGetResourceAddress.Lock()
	mock.calls.GetResourceAddress = append(mock.calls.GetResourceAddress, callInfo)
	mock.lockGetResourceAddress.Unlock()
	return mock.GetResourceAddressFunc(ctx, resourceId)
}

// GetResourceAddressCalls gets all the calls that were made to GetResourceAddress.
// Check the length with:
//
//	len(mockedEndpointClient.GetResourceAddressCalls())
func (mock *EndpointClientMock) GetResourceAddressCalls() []struct {
	Ctx        context.Context
	ResourceId string
} {
	var calls []struct {
		Ctx        context.Context
		ResourceId string
	}
	mock.lockGetResourceAddress.RLock()
	calls = mock.calls.GetResourceAddress
	mock.lockGetResourceAddress.RUnlock()
	return calls
}

// Ensure, that DeployerClientMock does implement service.DeployerClient.
// If this is not the case, regenerate this file with moq.
var _ service.DeployerClient = &DeployerClientMock{}

// DeployerClientMock is a mock implementation of service.DeployerClient.
//
//	func TestSomethingThatUsesDeployerClient(t *testing.T) {
//
//		// make and configure a mocked service.DeployerClient
//		mockedDeployerClient := &DeployerClientMock{
//			DeployResourceAndExecuteFunc: func(ctx context.Context, resourceId [32]byte, message *types.DispatchedMessageToPrivateHub) (common.Hash, error) {
//				panic("mock out the DeployResourceAndExecute method")
//			},
//		}
//
//		// use mockedDeployerClient in code that requires service.DeployerClient
//		// and then make assertions.
//
//	}
type DeployerClientMock struct {
	// DeployResourceAndExecuteFunc mocks the DeployResourceAndExecute method.
	DeployResourceAndExecuteFunc func(ctx context.Context, resourceId [32]byte, message *types.DispatchedMessageToPrivateHub) (common.Hash, error)

	// calls tracks calls to the methods.
	calls struct {
		// DeployResourceAndExecute holds details about calls to the DeployResourceAndExecute method.
		DeployResourceAndExecute []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ResourceId is the resourceId argument value.
			ResourceId [32]byte
			// Message is the message argument value.
			Message *types.DispatchedMessageToPrivateHub
		}
	}
	lockDeployResourceAndExecute sync.RWMutex
}

// DeployResourceAndExecute calls DeployResourceAndExecuteFunc.
func (mock *DeployerClientMock) DeployResourceAndExecute(ctx context.Context, resourceId [32]byte, message *types.DispatchedMessageToPrivateHub) (common.Hash, error) {
	if mock.DeployResourceAndExecuteFunc == nil {
		panic("DeployerClientMock.DeployResourceAndExecuteFunc: method is nil but DeployerClient.DeployResourceAndExecute was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		ResourceId [32]byte
		Message    *types.DispatchedMessageToPrivateHub
	}{
		Ctx:        ctx,
		ResourceId: resourceId,
		Message:    message,
	}
	mock.lockDeployResourceAndExecute.Lock()
	mock.calls.DeployResourceAndExecute = append(mock.calls.DeployResourceAndExecute, callInfo)
	mock.lockDeployResourceAndExecute.Unlock()
	return mock.DeployResourceAndExecuteFunc(ctx, resourceId, message)
}

// DeployResourceAndExecuteCalls gets all the calls that were made to DeployResourceAndExecute.
// Check the length with:
//
//	len(mockedDeployerClient.DeployResourceAndExecuteCalls())
func (mock *DeployerClientMock) DeployResourceAndExecuteCalls() []struct {
	Ctx        context.Context
	ResourceId [32]byte
	Message    *types.DispatchedMessageToPrivateHub
} {
	var calls []struct {
		Ctx        context.Context
		ResourceId [32]byte
		Message    *types.DispatchedMessageToPrivateHub
	}
	mock.lockDeployResourceAndExecute.RLock()
	calls = mock.calls.DeployResourceAndExecute
	mock.lockDeployResourceAndExecute.RUnlock()
	return calls
}
