// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package service_test

import (
	"context"
	"github.com/raylsnetwork/rayls-privacy-relayer-api/msgqueue"
	"github.com/raylsnetwork/rayls-privacy-relayer-api/private-relayer/dest/service"
	"github.com/raylsnetwork/rayls-privacy-relayer-api/types"
	"math/big"
	"sync"
)

// Ensure, that DvpDestMQMock does implement service.DvpDestMQ.
// If this is not the case, regenerate this file with moq.
var _ service.DvpDestMQ = &DvpDestMQMock{}

// DvpDestMQMock is a mock implementation of service.DvpDestMQ.
//
//	func TestSomethingThatUsesDvpDestMQ(t *testing.T) {
//
//		// make and configure a mocked service.DvpDestMQ
//		mockedDvpDestMQ := &DvpDestMQMock{
//			NextFunc: func(ctx context.Context) (msgqueue.Message[service.DvpDestMessage], error) {
//				panic("mock out the Next method")
//			},
//		}
//
//		// use mockedDvpDestMQ in code that requires service.DvpDestMQ
//		// and then make assertions.
//
//	}
type DvpDestMQMock struct {
	// NextFunc mocks the Next method.
	NextFunc func(ctx context.Context) (msgqueue.Message[service.DvpDestMessage], error)

	// calls tracks calls to the methods.
	calls struct {
		// Next holds details about calls to the Next method.
		Next []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
	}
	lockNext sync.RWMutex
}

// Next calls NextFunc.
func (mock *DvpDestMQMock) Next(ctx context.Context) (msgqueue.Message[service.DvpDestMessage], error) {
	if mock.NextFunc == nil {
		panic("DvpDestMQMock.NextFunc: method is nil but DvpDestMQ.Next was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockNext.Lock()
	mock.calls.Next = append(mock.calls.Next, callInfo)
	mock.lockNext.Unlock()
	return mock.NextFunc(ctx)
}

// NextCalls gets all the calls that were made to Next.
// Check the length with:
//
//	len(mockedDvpDestMQ.NextCalls())
func (mock *DvpDestMQMock) NextCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockNext.RLock()
	calls = mock.calls.Next
	mock.lockNext.RUnlock()
	return calls
}

// Ensure, that DvpReceiverMock does implement service.DvpReceiver.
// If this is not the case, regenerate this file with moq.
var _ service.DvpReceiver = &DvpReceiverMock{}

// DvpReceiverMock is a mock implementation of service.DvpReceiver.
//
//	func TestSomethingThatUsesDvpReceiver(t *testing.T) {
//
//		// make and configure a mocked service.DvpReceiver
//		mockedDvpReceiver := &DvpReceiverMock{
//			HandleCommitmentsFunc: func(ctx context.Context, data *types.DvpCommitmentsData) error {
//				panic("mock out the HandleCommitments method")
//			},
//			HandleNullifiersFunc: func(ctx context.Context, tokenAddress string, nullifiers []*big.Int) error {
//				panic("mock out the HandleNullifiers method")
//			},
//			HandleSwapCompletedFunc: func(ctx context.Context, sharedID string) error {
//				panic("mock out the HandleSwapCompleted method")
//			},
//			HandleSwapInitiatedFunc: func(ctx context.Context, blockNum uint64, data *types.DvpSwapInitiatedData) error {
//				panic("mock out the HandleSwapInitiated method")
//			},
//			HandleSwapRevertFunc: func(ctx context.Context, sharedId string, status types.DvpSwapStatus) error {
//				panic("mock out the HandleSwapRevert method")
//			},
//		}
//
//		// use mockedDvpReceiver in code that requires service.DvpReceiver
//		// and then make assertions.
//
//	}
type DvpReceiverMock struct {
	// HandleCommitmentsFunc mocks the HandleCommitments method.
	HandleCommitmentsFunc func(ctx context.Context, data *types.DvpCommitmentsData) error

	// HandleNullifiersFunc mocks the HandleNullifiers method.
	HandleNullifiersFunc func(ctx context.Context, tokenAddress string, nullifiers []*big.Int) error

	// HandleSwapCompletedFunc mocks the HandleSwapCompleted method.
	HandleSwapCompletedFunc func(ctx context.Context, sharedID string) error

	// HandleSwapInitiatedFunc mocks the HandleSwapInitiated method.
	HandleSwapInitiatedFunc func(ctx context.Context, blockNum uint64, data *types.DvpSwapInitiatedData) error

	// HandleSwapRevertFunc mocks the HandleSwapRevert method.
	HandleSwapRevertFunc func(ctx context.Context, sharedId string, status types.DvpSwapStatus) error

	// calls tracks calls to the methods.
	calls struct {
		// HandleCommitments holds details about calls to the HandleCommitments method.
		HandleCommitments []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Data is the data argument value.
			Data *types.DvpCommitmentsData
		}
		// HandleNullifiers holds details about calls to the HandleNullifiers method.
		HandleNullifiers []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// TokenAddress is the tokenAddress argument value.
			TokenAddress string
			// Nullifiers is the nullifiers argument value.
			Nullifiers []*big.Int
		}
		// HandleSwapCompleted holds details about calls to the HandleSwapCompleted method.
		HandleSwapCompleted []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// SharedID is the sharedID argument value.
			SharedID string
		}
		// HandleSwapInitiated holds details about calls to the HandleSwapInitiated method.
		HandleSwapInitiated []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// BlockNum is the blockNum argument value.
			BlockNum uint64
			// Data is the data argument value.
			Data *types.DvpSwapInitiatedData
		}
		// HandleSwapRevert holds details about calls to the HandleSwapRevert method.
		HandleSwapRevert []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// SharedId is the sharedId argument value.
			SharedId string
			// Status is the status argument value.
			Status types.DvpSwapStatus
		}
	}
	lockHandleCommitments   sync.RWMutex
	lockHandleNullifiers    sync.RWMutex
	lockHandleSwapCompleted sync.RWMutex
	lockHandleSwapInitiated sync.RWMutex
	lockHandleSwapRevert    sync.RWMutex
}

// HandleCommitments calls HandleCommitmentsFunc.
func (mock *DvpReceiverMock) HandleCommitments(ctx context.Context, data *types.DvpCommitmentsData) error {
	if mock.HandleCommitmentsFunc == nil {
		panic("DvpReceiverMock.HandleCommitmentsFunc: method is nil but DvpReceiver.HandleCommitments was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Data *types.DvpCommitmentsData
	}{
		Ctx:  ctx,
		Data: data,
	}
	mock.lockHandleCommitments.Lock()
	mock.calls.HandleCommitments = append(mock.calls.HandleCommitments, callInfo)
	mock.lockHandleCommitments.Unlock()
	return mock.HandleCommitmentsFunc(ctx, data)
}

// HandleCommitmentsCalls gets all the calls that were made to HandleCommitments.
// Check the length with:
//
//	len(mockedDvpReceiver.HandleCommitmentsCalls())
func (mock *DvpReceiverMock) HandleCommitmentsCalls() []struct {
	Ctx  context.Context
	Data *types.DvpCommitmentsData
} {
	var calls []struct {
		Ctx  context.Context
		Data *types.DvpCommitmentsData
	}
	mock.lockHandleCommitments.RLock()
	calls = mock.calls.HandleCommitments
	mock.lockHandleCommitments.RUnlock()
	return calls
}

// HandleNullifiers calls HandleNullifiersFunc.
func (mock *DvpReceiverMock) HandleNullifiers(ctx context.Context, tokenAddress string, nullifiers []*big.Int) error {
	if mock.HandleNullifiersFunc == nil {
		panic("DvpReceiverMock.HandleNullifiersFunc: method is nil but DvpReceiver.HandleNullifiers was just called")
	}
	callInfo := struct {
		Ctx          context.Context
		TokenAddress string
		Nullifiers   []*big.Int
	}{
		Ctx:          ctx,
		TokenAddress: tokenAddress,
		Nullifiers:   nullifiers,
	}
	mock.lockHandleNullifiers.Lock()
	mock.calls.HandleNullifiers = append(mock.calls.HandleNullifiers, callInfo)
	mock.lockHandleNullifiers.Unlock()
	return mock.HandleNullifiersFunc(ctx, tokenAddress, nullifiers)
}

// HandleNullifiersCalls gets all the calls that were made to HandleNullifiers.
// Check the length with:
//
//	len(mockedDvpReceiver.HandleNullifiersCalls())
func (mock *DvpReceiverMock) HandleNullifiersCalls() []struct {
	Ctx          context.Context
	TokenAddress string
	Nullifiers   []*big.Int
} {
	var calls []struct {
		Ctx          context.Context
		TokenAddress string
		Nullifiers   []*big.Int
	}
	mock.lockHandleNullifiers.RLock()
	calls = mock.calls.HandleNullifiers
	mock.lockHandleNullifiers.RUnlock()
	return calls
}

// HandleSwapCompleted calls HandleSwapCompletedFunc.
func (mock *DvpReceiverMock) HandleSwapCompleted(ctx context.Context, sharedID string) error {
	if mock.HandleSwapCompletedFunc == nil {
		panic("DvpReceiverMock.HandleSwapCompletedFunc: method is nil but DvpReceiver.HandleSwapCompleted was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		SharedID string
	}{
		Ctx:      ctx,
		SharedID: sharedID,
	}
	mock.lockHandleSwapCompleted.Lock()
	mock.calls.HandleSwapCompleted = append(mock.calls.HandleSwapCompleted, callInfo)
	mock.lockHandleSwapCompleted.Unlock()
	return mock.HandleSwapCompletedFunc(ctx, sharedID)
}

// HandleSwapCompletedCalls gets all the calls that were made to HandleSwapCompleted.
// Check the length with:
//
//	len(mockedDvpReceiver.HandleSwapCompletedCalls())
func (mock *DvpReceiverMock) HandleSwapCompletedCalls() []struct {
	Ctx      context.Context
	SharedID string
} {
	var calls []struct {
		Ctx      context.Context
		SharedID string
	}
	mock.lockHandleSwapCompleted.RLock()
	calls = mock.calls.HandleSwapCompleted
	mock.lockHandleSwapCompleted.RUnlock()
	return calls
}

// HandleSwapInitiated calls HandleSwapInitiatedFunc.
func (mock *DvpReceiverMock) HandleSwapInitiated(ctx context.Context, blockNum uint64, data *types.DvpSwapInitiatedData) error {
	if mock.HandleSwapInitiatedFunc == nil {
		panic("DvpReceiverMock.HandleSwapInitiatedFunc: method is nil but DvpReceiver.HandleSwapInitiated was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		BlockNum uint64
		Data     *types.DvpSwapInitiatedData
	}{
		Ctx:      ctx,
		BlockNum: blockNum,
		Data:     data,
	}
	mock.lockHandleSwapInitiated.Lock()
	mock.calls.HandleSwapInitiated = append(mock.calls.HandleSwapInitiated, callInfo)
	mock.lockHandleSwapInitiated.Unlock()
	return mock.HandleSwapInitiatedFunc(ctx, blockNum, data)
}

// HandleSwapInitiatedCalls gets all the calls that were made to HandleSwapInitiated.
// Check the length with:
//
//	len(mockedDvpReceiver.HandleSwapInitiatedCalls())
func (mock *DvpReceiverMock) HandleSwapInitiatedCalls() []struct {
	Ctx      context.Context
	BlockNum uint64
	Data     *types.DvpSwapInitiatedData
} {
	var calls []struct {
		Ctx      context.Context
		BlockNum uint64
		Data     *types.DvpSwapInitiatedData
	}
	mock.lockHandleSwapInitiated.RLock()
	calls = mock.calls.HandleSwapInitiated
	mock.lockHandleSwapInitiated.RUnlock()
	return calls
}

// HandleSwapRevert calls HandleSwapRevertFunc.
func (mock *DvpReceiverMock) HandleSwapRevert(ctx context.Context, sharedId string, status types.DvpSwapStatus) error {
	if mock.HandleSwapRevertFunc == nil {
		panic("DvpReceiverMock.HandleSwapRevertFunc: method is nil but DvpReceiver.HandleSwapRevert was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		SharedId string
		Status   types.DvpSwapStatus
	}{
		Ctx:      ctx,
		SharedId: sharedId,
		Status:   status,
	}
	mock.lockHandleSwapRevert.Lock()
	mock.calls.HandleSwapRevert = append(mock.calls.HandleSwapRevert, callInfo)
	mock.lockHandleSwapRevert.Unlock()
	return mock.HandleSwapRevertFunc(ctx, sharedId, status)
}

// HandleSwapRevertCalls gets all the calls that were made to HandleSwapRevert.
// Check the length with:
//
//	len(mockedDvpReceiver.HandleSwapRevertCalls())
func (mock *DvpReceiverMock) HandleSwapRevertCalls() []struct {
	Ctx      context.Context
	SharedId string
	Status   types.DvpSwapStatus
} {
	var calls []struct {
		Ctx      context.Context
		SharedId string
		Status   types.DvpSwapStatus
	}
	mock.lockHandleSwapRevert.RLock()
	calls = mock.calls.HandleSwapRevert
	mock.lockHandleSwapRevert.RUnlock()
	return calls
}

// Ensure, that DvpBackoffMock does implement service.DvpBackoff.
// If this is not the case, regenerate this file with moq.
var _ service.DvpBackoff = &DvpBackoffMock{}

// DvpBackoffMock is a mock implementation of service.DvpBackoff.
//
//	func TestSomethingThatUsesDvpBackoff(t *testing.T) {
//
//		// make and configure a mocked service.DvpBackoff
//		mockedDvpBackoff := &DvpBackoffMock{
//			DoFunc: func(ctx context.Context, maxAttempts int, fn func() error) error {
//				panic("mock out the Do method")
//			},
//		}
//
//		// use mockedDvpBackoff in code that requires service.DvpBackoff
//		// and then make assertions.
//
//	}
type DvpBackoffMock struct {
	// DoFunc mocks the Do method.
	DoFunc func(ctx context.Context, maxAttempts int, fn func() error) error

	// calls tracks calls to the methods.
	calls struct {
		// Do holds details about calls to the Do method.
		Do []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// MaxAttempts is the maxAttempts argument value.
			MaxAttempts int
			// Fn is the fn argument value.
			Fn func() error
		}
	}
	lockDo sync.RWMutex
}

// Do calls DoFunc.
func (mock *DvpBackoffMock) Do(ctx context.Context, maxAttempts int, fn func() error) error {
	if mock.DoFunc == nil {
		panic("DvpBackoffMock.DoFunc: method is nil but DvpBackoff.Do was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		MaxAttempts int
		Fn          func() error
	}{
		Ctx:         ctx,
		MaxAttempts: maxAttempts,
		Fn:          fn,
	}
	mock.lockDo.Lock()
	mock.calls.Do = append(mock.calls.Do, callInfo)
	mock.lockDo.Unlock()
	return mock.DoFunc(ctx, maxAttempts, fn)
}

// DoCalls gets all the calls that were made to Do.
// Check the length with:
//
//	len(mockedDvpBackoff.DoCalls())
func (mock *DvpBackoffMock) DoCalls() []struct {
	Ctx         context.Context
	MaxAttempts int
	Fn          func() error
} {
	var calls []struct {
		Ctx         context.Context
		MaxAttempts int
		Fn          func() error
	}
	mock.lockDo.RLock()
	calls = mock.calls.Do
	mock.lockDo.RUnlock()
	return calls
}
