// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package service_test

import (
	"context"
	"github.com/raylsnetwork/rayls-sovereign-relayer/msgqueue"
	"github.com/raylsnetwork/rayls-sovereign-relayer/private-relayer/dest/service"
	"github.com/raylsnetwork/rayls-sovereign-relayer/types"
	"math/big"
	"sync"
)

// Ensure, that EnygmaDestMQMock does implement service.EnygmaDestMQ.
// If this is not the case, regenerate this file with moq.
var _ service.EnygmaDestMQ = &EnygmaDestMQMock{}

// EnygmaDestMQMock is a mock implementation of service.EnygmaDestMQ.
//
//	func TestSomethingThatUsesEnygmaDestMQ(t *testing.T) {
//
//		// make and configure a mocked service.EnygmaDestMQ
//		mockedEnygmaDestMQ := &EnygmaDestMQMock{
//			NextFunc: func(ctx context.Context) (msgqueue.Message[service.EnygmaDestMessage], error) {
//				panic("mock out the Next method")
//			},
//		}
//
//		// use mockedEnygmaDestMQ in code that requires service.EnygmaDestMQ
//		// and then make assertions.
//
//	}
type EnygmaDestMQMock struct {
	// NextFunc mocks the Next method.
	NextFunc func(ctx context.Context) (msgqueue.Message[service.EnygmaDestMessage], error)

	// calls tracks calls to the methods.
	calls struct {
		// Next holds details about calls to the Next method.
		Next []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
	}
	lockNext sync.RWMutex
}

// Next calls NextFunc.
func (mock *EnygmaDestMQMock) Next(ctx context.Context) (msgqueue.Message[service.EnygmaDestMessage], error) {
	if mock.NextFunc == nil {
		panic("EnygmaDestMQMock.NextFunc: method is nil but EnygmaDestMQ.Next was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockNext.Lock()
	mock.calls.Next = append(mock.calls.Next, callInfo)
	mock.lockNext.Unlock()
	return mock.NextFunc(ctx)
}

// NextCalls gets all the calls that were made to Next.
// Check the length with:
//
//	len(mockedEnygmaDestMQ.NextCalls())
func (mock *EnygmaDestMQMock) NextCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockNext.RLock()
	calls = mock.calls.Next
	mock.lockNext.RUnlock()
	return calls
}

// Ensure, that EnygmaReceiverMock does implement service.EnygmaReceiver.
// If this is not the case, regenerate this file with moq.
var _ service.EnygmaReceiver = &EnygmaReceiverMock{}

// EnygmaReceiverMock is a mock implementation of service.EnygmaReceiver.
//
//	func TestSomethingThatUsesEnygmaReceiver(t *testing.T) {
//
//		// make and configure a mocked service.EnygmaReceiver
//		mockedEnygmaReceiver := &EnygmaReceiverMock{
//			HandleEnygmaCrossTransferFunc: func(ctx context.Context, batch *types.EnygmaTransferBatch) error {
//				panic("mock out the HandleEnygmaCrossTransfer method")
//			},
//		}
//
//		// use mockedEnygmaReceiver in code that requires service.EnygmaReceiver
//		// and then make assertions.
//
//	}
type EnygmaReceiverMock struct {
	// HandleEnygmaCrossTransferFunc mocks the HandleEnygmaCrossTransfer method.
	HandleEnygmaCrossTransferFunc func(ctx context.Context, batch *types.EnygmaTransferBatch) error

	// calls tracks calls to the methods.
	calls struct {
		// HandleEnygmaCrossTransfer holds details about calls to the HandleEnygmaCrossTransfer method.
		HandleEnygmaCrossTransfer []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Batch is the batch argument value.
			Batch *types.EnygmaTransferBatch
		}
	}
	lockHandleEnygmaCrossTransfer sync.RWMutex
}

// HandleEnygmaCrossTransfer calls HandleEnygmaCrossTransferFunc.
func (mock *EnygmaReceiverMock) HandleEnygmaCrossTransfer(ctx context.Context, batch *types.EnygmaTransferBatch) error {
	if mock.HandleEnygmaCrossTransferFunc == nil {
		panic("EnygmaReceiverMock.HandleEnygmaCrossTransferFunc: method is nil but EnygmaReceiver.HandleEnygmaCrossTransfer was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Batch *types.EnygmaTransferBatch
	}{
		Ctx:   ctx,
		Batch: batch,
	}
	mock.lockHandleEnygmaCrossTransfer.Lock()
	mock.calls.HandleEnygmaCrossTransfer = append(mock.calls.HandleEnygmaCrossTransfer, callInfo)
	mock.lockHandleEnygmaCrossTransfer.Unlock()
	return mock.HandleEnygmaCrossTransferFunc(ctx, batch)
}

// HandleEnygmaCrossTransferCalls gets all the calls that were made to HandleEnygmaCrossTransfer.
// Check the length with:
//
//	len(mockedEnygmaReceiver.HandleEnygmaCrossTransferCalls())
func (mock *EnygmaReceiverMock) HandleEnygmaCrossTransferCalls() []struct {
	Ctx   context.Context
	Batch *types.EnygmaTransferBatch
} {
	var calls []struct {
		Ctx   context.Context
		Batch *types.EnygmaTransferBatch
	}
	mock.lockHandleEnygmaCrossTransfer.RLock()
	calls = mock.calls.HandleEnygmaCrossTransfer
	mock.lockHandleEnygmaCrossTransfer.RUnlock()
	return calls
}

// Ensure, that EnygmaCheckpointRepositoryMock does implement service.EnygmaCheckpointRepository.
// If this is not the case, regenerate this file with moq.
var _ service.EnygmaCheckpointRepository = &EnygmaCheckpointRepositoryMock{}

// EnygmaCheckpointRepositoryMock is a mock implementation of service.EnygmaCheckpointRepository.
//
//	func TestSomethingThatUsesEnygmaCheckpointRepository(t *testing.T) {
//
//		// make and configure a mocked service.EnygmaCheckpointRepository
//		mockedEnygmaCheckpointRepository := &EnygmaCheckpointRepositoryMock{
//			CreateEnygmaCheckpointFunc: func(ctx context.Context, checkpoint types.EnygmaCheckpoint) error {
//				panic("mock out the CreateEnygmaCheckpoint method")
//			},
//			GetLatestCheckpointByFiltersFunc: func(ctx context.Context, resourceId string, status *types.EnygmaCheckpointStatus, finalizedBlockNumber *big.Int, pendingBlockNumber *big.Int) (*types.EnygmaCheckpoint, error) {
//				panic("mock out the GetLatestCheckpointByFilters method")
//			},
//		}
//
//		// use mockedEnygmaCheckpointRepository in code that requires service.EnygmaCheckpointRepository
//		// and then make assertions.
//
//	}
type EnygmaCheckpointRepositoryMock struct {
	// CreateEnygmaCheckpointFunc mocks the CreateEnygmaCheckpoint method.
	CreateEnygmaCheckpointFunc func(ctx context.Context, checkpoint types.EnygmaCheckpoint) error

	// GetLatestCheckpointByFiltersFunc mocks the GetLatestCheckpointByFilters method.
	GetLatestCheckpointByFiltersFunc func(ctx context.Context, resourceId string, status *types.EnygmaCheckpointStatus, finalizedBlockNumber *big.Int, pendingBlockNumber *big.Int) (*types.EnygmaCheckpoint, error)

	// calls tracks calls to the methods.
	calls struct {
		// CreateEnygmaCheckpoint holds details about calls to the CreateEnygmaCheckpoint method.
		CreateEnygmaCheckpoint []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Checkpoint is the checkpoint argument value.
			Checkpoint types.EnygmaCheckpoint
		}
		// GetLatestCheckpointByFilters holds details about calls to the GetLatestCheckpointByFilters method.
		GetLatestCheckpointByFilters []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ResourceId is the resourceId argument value.
			ResourceId string
			// Status is the status argument value.
			Status *types.EnygmaCheckpointStatus
			// FinalizedBlockNumber is the finalizedBlockNumber argument value.
			FinalizedBlockNumber *big.Int
			// PendingBlockNumber is the pendingBlockNumber argument value.
			PendingBlockNumber *big.Int
		}
	}
	lockCreateEnygmaCheckpoint       sync.RWMutex
	lockGetLatestCheckpointByFilters sync.RWMutex
}

// CreateEnygmaCheckpoint calls CreateEnygmaCheckpointFunc.
func (mock *EnygmaCheckpointRepositoryMock) CreateEnygmaCheckpoint(ctx context.Context, checkpoint types.EnygmaCheckpoint) error {
	if mock.CreateEnygmaCheckpointFunc == nil {
		panic("EnygmaCheckpointRepositoryMock.CreateEnygmaCheckpointFunc: method is nil but EnygmaCheckpointRepository.CreateEnygmaCheckpoint was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		Checkpoint types.EnygmaCheckpoint
	}{
		Ctx:        ctx,
		Checkpoint: checkpoint,
	}
	mock.lockCreateEnygmaCheckpoint.Lock()
	mock.calls.CreateEnygmaCheckpoint = append(mock.calls.CreateEnygmaCheckpoint, callInfo)
	mock.lockCreateEnygmaCheckpoint.Unlock()
	return mock.CreateEnygmaCheckpointFunc(ctx, checkpoint)
}

// CreateEnygmaCheckpointCalls gets all the calls that were made to CreateEnygmaCheckpoint.
// Check the length with:
//
//	len(mockedEnygmaCheckpointRepository.CreateEnygmaCheckpointCalls())
func (mock *EnygmaCheckpointRepositoryMock) CreateEnygmaCheckpointCalls() []struct {
	Ctx        context.Context
	Checkpoint types.EnygmaCheckpoint
} {
	var calls []struct {
		Ctx        context.Context
		Checkpoint types.EnygmaCheckpoint
	}
	mock.lockCreateEnygmaCheckpoint.RLock()
	calls = mock.calls.CreateEnygmaCheckpoint
	mock.lockCreateEnygmaCheckpoint.RUnlock()
	return calls
}

// GetLatestCheckpointByFilters calls GetLatestCheckpointByFiltersFunc.
func (mock *EnygmaCheckpointRepositoryMock) GetLatestCheckpointByFilters(ctx context.Context, resourceId string, status *types.EnygmaCheckpointStatus, finalizedBlockNumber *big.Int, pendingBlockNumber *big.Int) (*types.EnygmaCheckpoint, error) {
	if mock.GetLatestCheckpointByFiltersFunc == nil {
		panic("EnygmaCheckpointRepositoryMock.GetLatestCheckpointByFiltersFunc: method is nil but EnygmaCheckpointRepository.GetLatestCheckpointByFilters was just called")
	}
	callInfo := struct {
		Ctx                  context.Context
		ResourceId           string
		Status               *types.EnygmaCheckpointStatus
		FinalizedBlockNumber *big.Int
		PendingBlockNumber   *big.Int
	}{
		Ctx:                  ctx,
		ResourceId:           resourceId,
		Status:               status,
		FinalizedBlockNumber: finalizedBlockNumber,
		PendingBlockNumber:   pendingBlockNumber,
	}
	mock.lockGetLatestCheckpointByFilters.Lock()
	mock.calls.GetLatestCheckpointByFilters = append(mock.calls.GetLatestCheckpointByFilters, callInfo)
	mock.lockGetLatestCheckpointByFilters.Unlock()
	return mock.GetLatestCheckpointByFiltersFunc(ctx, resourceId, status, finalizedBlockNumber, pendingBlockNumber)
}

// GetLatestCheckpointByFiltersCalls gets all the calls that were made to GetLatestCheckpointByFilters.
// Check the length with:
//
//	len(mockedEnygmaCheckpointRepository.GetLatestCheckpointByFiltersCalls())
func (mock *EnygmaCheckpointRepositoryMock) GetLatestCheckpointByFiltersCalls() []struct {
	Ctx                  context.Context
	ResourceId           string
	Status               *types.EnygmaCheckpointStatus
	FinalizedBlockNumber *big.Int
	PendingBlockNumber   *big.Int
} {
	var calls []struct {
		Ctx                  context.Context
		ResourceId           string
		Status               *types.EnygmaCheckpointStatus
		FinalizedBlockNumber *big.Int
		PendingBlockNumber   *big.Int
	}
	mock.lockGetLatestCheckpointByFilters.RLock()
	calls = mock.calls.GetLatestCheckpointByFilters
	mock.lockGetLatestCheckpointByFilters.RUnlock()
	return calls
}

// Ensure, that BackoffMock does implement service.Backoff.
// If this is not the case, regenerate this file with moq.
var _ service.Backoff = &BackoffMock{}

// BackoffMock is a mock implementation of service.Backoff.
//
//	func TestSomethingThatUsesBackoff(t *testing.T) {
//
//		// make and configure a mocked service.Backoff
//		mockedBackoff := &BackoffMock{
//			DoFunc: func(ctx context.Context, maxAttempts int, fn func() error) error {
//				panic("mock out the Do method")
//			},
//		}
//
//		// use mockedBackoff in code that requires service.Backoff
//		// and then make assertions.
//
//	}
type BackoffMock struct {
	// DoFunc mocks the Do method.
	DoFunc func(ctx context.Context, maxAttempts int, fn func() error) error

	// calls tracks calls to the methods.
	calls struct {
		// Do holds details about calls to the Do method.
		Do []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// MaxAttempts is the maxAttempts argument value.
			MaxAttempts int
			// Fn is the fn argument value.
			Fn func() error
		}
	}
	lockDo sync.RWMutex
}

// Do calls DoFunc.
func (mock *BackoffMock) Do(ctx context.Context, maxAttempts int, fn func() error) error {
	if mock.DoFunc == nil {
		panic("BackoffMock.DoFunc: method is nil but Backoff.Do was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		MaxAttempts int
		Fn          func() error
	}{
		Ctx:         ctx,
		MaxAttempts: maxAttempts,
		Fn:          fn,
	}
	mock.lockDo.Lock()
	mock.calls.Do = append(mock.calls.Do, callInfo)
	mock.lockDo.Unlock()
	return mock.DoFunc(ctx, maxAttempts, fn)
}

// DoCalls gets all the calls that were made to Do.
// Check the length with:
//
//	len(mockedBackoff.DoCalls())
func (mock *BackoffMock) DoCalls() []struct {
	Ctx         context.Context
	MaxAttempts int
	Fn          func() error
} {
	var calls []struct {
		Ctx         context.Context
		MaxAttempts int
		Fn          func() error
	}
	mock.lockDo.RLock()
	calls = mock.calls.Do
	mock.lockDo.RUnlock()
	return calls
}
