// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package service_test

import (
	"context"
	"github.com/ethereum/go-ethereum/common"
	"github.com/raylsnetwork/rayls-privacy-relayer-api/msgqueue"
	"github.com/raylsnetwork/rayls-privacy-relayer-api/private-relayer/source/service"
	"github.com/raylsnetwork/rayls-privacy-relayer-api/types"
	"math/big"
	"sync"
)

// Ensure, that EnygmaBatchMQMock does implement service.EnygmaBatchMQ.
// If this is not the case, regenerate this file with moq.
var _ service.EnygmaBatchMQ = &EnygmaBatchMQMock{}

// EnygmaBatchMQMock is a mock implementation of service.EnygmaBatchMQ.
//
//	func TestSomethingThatUsesEnygmaBatchMQ(t *testing.T) {
//
//		// make and configure a mocked service.EnygmaBatchMQ
//		mockedEnygmaBatchMQ := &EnygmaBatchMQMock{
//			FetchFunc: func(ctx context.Context, count int) ([]msgqueue.Message[service.EnygmaSerializedEvent], error) {
//				panic("mock out the Fetch method")
//			},
//		}
//
//		// use mockedEnygmaBatchMQ in code that requires service.EnygmaBatchMQ
//		// and then make assertions.
//
//	}
type EnygmaBatchMQMock struct {
	// FetchFunc mocks the Fetch method.
	FetchFunc func(ctx context.Context, count int) ([]msgqueue.Message[service.EnygmaSerializedEvent], error)

	// calls tracks calls to the methods.
	calls struct {
		// Fetch holds details about calls to the Fetch method.
		Fetch []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Count is the count argument value.
			Count int
		}
	}
	lockFetch sync.RWMutex
}

// Fetch calls FetchFunc.
func (mock *EnygmaBatchMQMock) Fetch(ctx context.Context, count int) ([]msgqueue.Message[service.EnygmaSerializedEvent], error) {
	if mock.FetchFunc == nil {
		panic("EnygmaBatchMQMock.FetchFunc: method is nil but EnygmaBatchMQ.Fetch was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Count int
	}{
		Ctx:   ctx,
		Count: count,
	}
	mock.lockFetch.Lock()
	mock.calls.Fetch = append(mock.calls.Fetch, callInfo)
	mock.lockFetch.Unlock()
	return mock.FetchFunc(ctx, count)
}

// FetchCalls gets all the calls that were made to Fetch.
// Check the length with:
//
//	len(mockedEnygmaBatchMQ.FetchCalls())
func (mock *EnygmaBatchMQMock) FetchCalls() []struct {
	Ctx   context.Context
	Count int
} {
	var calls []struct {
		Ctx   context.Context
		Count int
	}
	mock.lockFetch.RLock()
	calls = mock.calls.Fetch
	mock.lockFetch.RUnlock()
	return calls
}

// Ensure, that EnygmaInitiatorMock does implement service.EnygmaInitiator.
// If this is not the case, regenerate this file with moq.
var _ service.EnygmaInitiator = &EnygmaInitiatorMock{}

// EnygmaInitiatorMock is a mock implementation of service.EnygmaInitiator.
//
//	func TestSomethingThatUsesEnygmaInitiator(t *testing.T) {
//
//		// make and configure a mocked service.EnygmaInitiator
//		mockedEnygmaInitiator := &EnygmaInitiatorMock{
//			HandleEnygmaCreationFunc: func(ctx context.Context, chainEventID string, resourceId string, blockNumber uint64, initialSupply *big.Int) (uint64, error) {
//				panic("mock out the HandleEnygmaCreation method")
//			},
//			HandleEnygmaCrossTransferFunc: func(ctx context.Context, batchID string, resourceID string, blockNumber uint64, batch map[string][]*types.EnygmaTransferBatchTx) (uint64, error) {
//				panic("mock out the HandleEnygmaCrossTransfer method")
//			},
//			HandleEnygmaDepositFunc: func(ctx context.Context, chainEventID string, blockNumber uint64, resourceID string, referenceID [32]byte, from common.Address, amount *big.Int, txHash common.Hash) (uint64, error) {
//				panic("mock out the HandleEnygmaDeposit method")
//			},
//			HandleEnygmaSupplyUpdatesFunc: func(ctx context.Context, batchID string, resourceId string, blockNumber uint64, batch types.EnygmaSupplyUpdate) (uint64, error) {
//				panic("mock out the HandleEnygmaSupplyUpdates method")
//			},
//			HandleEnygmaWithdrawalFunc: func(ctx context.Context, chainEventID string, blockNumber uint64, resourceID string, referenceID [32]byte, to common.Address, amount *big.Int, txHash common.Hash) (uint64, error) {
//				panic("mock out the HandleEnygmaWithdrawal method")
//			},
//		}
//
//		// use mockedEnygmaInitiator in code that requires service.EnygmaInitiator
//		// and then make assertions.
//
//	}
type EnygmaInitiatorMock struct {
	// HandleEnygmaCreationFunc mocks the HandleEnygmaCreation method.
	HandleEnygmaCreationFunc func(ctx context.Context, chainEventID string, resourceId string, blockNumber uint64, initialSupply *big.Int) (uint64, error)

	// HandleEnygmaCrossTransferFunc mocks the HandleEnygmaCrossTransfer method.
	HandleEnygmaCrossTransferFunc func(ctx context.Context, batchID string, resourceID string, blockNumber uint64, batch map[string][]*types.EnygmaTransferBatchTx) (uint64, error)

	// HandleEnygmaDepositFunc mocks the HandleEnygmaDeposit method.
	HandleEnygmaDepositFunc func(ctx context.Context, chainEventID string, blockNumber uint64, resourceID string, referenceID [32]byte, from common.Address, amount *big.Int, txHash common.Hash) (uint64, error)

	// HandleEnygmaSupplyUpdatesFunc mocks the HandleEnygmaSupplyUpdates method.
	HandleEnygmaSupplyUpdatesFunc func(ctx context.Context, batchID string, resourceId string, blockNumber uint64, batch types.EnygmaSupplyUpdate) (uint64, error)

	// HandleEnygmaWithdrawalFunc mocks the HandleEnygmaWithdrawal method.
	HandleEnygmaWithdrawalFunc func(ctx context.Context, chainEventID string, blockNumber uint64, resourceID string, referenceID [32]byte, to common.Address, amount *big.Int, txHash common.Hash) (uint64, error)

	// calls tracks calls to the methods.
	calls struct {
		// HandleEnygmaCreation holds details about calls to the HandleEnygmaCreation method.
		HandleEnygmaCreation []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ChainEventID is the chainEventID argument value.
			ChainEventID string
			// ResourceId is the resourceId argument value.
			ResourceId string
			// BlockNumber is the blockNumber argument value.
			BlockNumber uint64
			// InitialSupply is the initialSupply argument value.
			InitialSupply *big.Int
		}
		// HandleEnygmaCrossTransfer holds details about calls to the HandleEnygmaCrossTransfer method.
		HandleEnygmaCrossTransfer []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// BatchID is the batchID argument value.
			BatchID string
			// ResourceID is the resourceID argument value.
			ResourceID string
			// BlockNumber is the blockNumber argument value.
			BlockNumber uint64
			// Batch is the batch argument value.
			Batch map[string][]*types.EnygmaTransferBatchTx
		}
		// HandleEnygmaDeposit holds details about calls to the HandleEnygmaDeposit method.
		HandleEnygmaDeposit []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ChainEventID is the chainEventID argument value.
			ChainEventID string
			// BlockNumber is the blockNumber argument value.
			BlockNumber uint64
			// ResourceID is the resourceID argument value.
			ResourceID string
			// ReferenceID is the referenceID argument value.
			ReferenceID [32]byte
			// From is the from argument value.
			From common.Address
			// Amount is the amount argument value.
			Amount *big.Int
			// TxHash is the txHash argument value.
			TxHash common.Hash
		}
		// HandleEnygmaSupplyUpdates holds details about calls to the HandleEnygmaSupplyUpdates method.
		HandleEnygmaSupplyUpdates []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// BatchID is the batchID argument value.
			BatchID string
			// ResourceId is the resourceId argument value.
			ResourceId string
			// BlockNumber is the blockNumber argument value.
			BlockNumber uint64
			// Batch is the batch argument value.
			Batch types.EnygmaSupplyUpdate
		}
		// HandleEnygmaWithdrawal holds details about calls to the HandleEnygmaWithdrawal method.
		HandleEnygmaWithdrawal []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ChainEventID is the chainEventID argument value.
			ChainEventID string
			// BlockNumber is the blockNumber argument value.
			BlockNumber uint64
			// ResourceID is the resourceID argument value.
			ResourceID string
			// ReferenceID is the referenceID argument value.
			ReferenceID [32]byte
			// To is the to argument value.
			To common.Address
			// Amount is the amount argument value.
			Amount *big.Int
			// TxHash is the txHash argument value.
			TxHash common.Hash
		}
	}
	lockHandleEnygmaCreation      sync.RWMutex
	lockHandleEnygmaCrossTransfer sync.RWMutex
	lockHandleEnygmaDeposit       sync.RWMutex
	lockHandleEnygmaSupplyUpdates sync.RWMutex
	lockHandleEnygmaWithdrawal    sync.RWMutex
}

// HandleEnygmaCreation calls HandleEnygmaCreationFunc.
func (mock *EnygmaInitiatorMock) HandleEnygmaCreation(ctx context.Context, chainEventID string, resourceId string, blockNumber uint64, initialSupply *big.Int) (uint64, error) {
	if mock.HandleEnygmaCreationFunc == nil {
		panic("EnygmaInitiatorMock.HandleEnygmaCreationFunc: method is nil but EnygmaInitiator.HandleEnygmaCreation was just called")
	}
	callInfo := struct {
		Ctx           context.Context
		ChainEventID  string
		ResourceId    string
		BlockNumber   uint64
		InitialSupply *big.Int
	}{
		Ctx:           ctx,
		ChainEventID:  chainEventID,
		ResourceId:    resourceId,
		BlockNumber:   blockNumber,
		InitialSupply: initialSupply,
	}
	mock.lockHandleEnygmaCreation.Lock()
	mock.calls.HandleEnygmaCreation = append(mock.calls.HandleEnygmaCreation, callInfo)
	mock.lockHandleEnygmaCreation.Unlock()
	return mock.HandleEnygmaCreationFunc(ctx, chainEventID, resourceId, blockNumber, initialSupply)
}

// HandleEnygmaCreationCalls gets all the calls that were made to HandleEnygmaCreation.
// Check the length with:
//
//	len(mockedEnygmaInitiator.HandleEnygmaCreationCalls())
func (mock *EnygmaInitiatorMock) HandleEnygmaCreationCalls() []struct {
	Ctx           context.Context
	ChainEventID  string
	ResourceId    string
	BlockNumber   uint64
	InitialSupply *big.Int
} {
	var calls []struct {
		Ctx           context.Context
		ChainEventID  string
		ResourceId    string
		BlockNumber   uint64
		InitialSupply *big.Int
	}
	mock.lockHandleEnygmaCreation.RLock()
	calls = mock.calls.HandleEnygmaCreation
	mock.lockHandleEnygmaCreation.RUnlock()
	return calls
}

// HandleEnygmaCrossTransfer calls HandleEnygmaCrossTransferFunc.
func (mock *EnygmaInitiatorMock) HandleEnygmaCrossTransfer(ctx context.Context, batchID string, resourceID string, blockNumber uint64, batch map[string][]*types.EnygmaTransferBatchTx) (uint64, error) {
	if mock.HandleEnygmaCrossTransferFunc == nil {
		panic("EnygmaInitiatorMock.HandleEnygmaCrossTransferFunc: method is nil but EnygmaInitiator.HandleEnygmaCrossTransfer was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		BatchID     string
		ResourceID  string
		BlockNumber uint64
		Batch       map[string][]*types.EnygmaTransferBatchTx
	}{
		Ctx:         ctx,
		BatchID:     batchID,
		ResourceID:  resourceID,
		BlockNumber: blockNumber,
		Batch:       batch,
	}
	mock.lockHandleEnygmaCrossTransfer.Lock()
	mock.calls.HandleEnygmaCrossTransfer = append(mock.calls.HandleEnygmaCrossTransfer, callInfo)
	mock.lockHandleEnygmaCrossTransfer.Unlock()
	return mock.HandleEnygmaCrossTransferFunc(ctx, batchID, resourceID, blockNumber, batch)
}

// HandleEnygmaCrossTransferCalls gets all the calls that were made to HandleEnygmaCrossTransfer.
// Check the length with:
//
//	len(mockedEnygmaInitiator.HandleEnygmaCrossTransferCalls())
func (mock *EnygmaInitiatorMock) HandleEnygmaCrossTransferCalls() []struct {
	Ctx         context.Context
	BatchID     string
	ResourceID  string
	BlockNumber uint64
	Batch       map[string][]*types.EnygmaTransferBatchTx
} {
	var calls []struct {
		Ctx         context.Context
		BatchID     string
		ResourceID  string
		BlockNumber uint64
		Batch       map[string][]*types.EnygmaTransferBatchTx
	}
	mock.lockHandleEnygmaCrossTransfer.RLock()
	calls = mock.calls.HandleEnygmaCrossTransfer
	mock.lockHandleEnygmaCrossTransfer.RUnlock()
	return calls
}

// HandleEnygmaDeposit calls HandleEnygmaDepositFunc.
func (mock *EnygmaInitiatorMock) HandleEnygmaDeposit(ctx context.Context, chainEventID string, blockNumber uint64, resourceID string, referenceID [32]byte, from common.Address, amount *big.Int, txHash common.Hash) (uint64, error) {
	if mock.HandleEnygmaDepositFunc == nil {
		panic("EnygmaInitiatorMock.HandleEnygmaDepositFunc: method is nil but EnygmaInitiator.HandleEnygmaDeposit was just called")
	}
	callInfo := struct {
		Ctx          context.Context
		ChainEventID string
		BlockNumber  uint64
		ResourceID   string
		ReferenceID  [32]byte
		From         common.Address
		Amount       *big.Int
		TxHash       common.Hash
	}{
		Ctx:          ctx,
		ChainEventID: chainEventID,
		BlockNumber:  blockNumber,
		ResourceID:   resourceID,
		ReferenceID:  referenceID,
		From:         from,
		Amount:       amount,
		TxHash:       txHash,
	}
	mock.lockHandleEnygmaDeposit.Lock()
	mock.calls.HandleEnygmaDeposit = append(mock.calls.HandleEnygmaDeposit, callInfo)
	mock.lockHandleEnygmaDeposit.Unlock()
	return mock.HandleEnygmaDepositFunc(ctx, chainEventID, blockNumber, resourceID, referenceID, from, amount, txHash)
}

// HandleEnygmaDepositCalls gets all the calls that were made to HandleEnygmaDeposit.
// Check the length with:
//
//	len(mockedEnygmaInitiator.HandleEnygmaDepositCalls())
func (mock *EnygmaInitiatorMock) HandleEnygmaDepositCalls() []struct {
	Ctx          context.Context
	ChainEventID string
	BlockNumber  uint64
	ResourceID   string
	ReferenceID  [32]byte
	From         common.Address
	Amount       *big.Int
	TxHash       common.Hash
} {
	var calls []struct {
		Ctx          context.Context
		ChainEventID string
		BlockNumber  uint64
		ResourceID   string
		ReferenceID  [32]byte
		From         common.Address
		Amount       *big.Int
		TxHash       common.Hash
	}
	mock.lockHandleEnygmaDeposit.RLock()
	calls = mock.calls.HandleEnygmaDeposit
	mock.lockHandleEnygmaDeposit.RUnlock()
	return calls
}

// HandleEnygmaSupplyUpdates calls HandleEnygmaSupplyUpdatesFunc.
func (mock *EnygmaInitiatorMock) HandleEnygmaSupplyUpdates(ctx context.Context, batchID string, resourceId string, blockNumber uint64, batch types.EnygmaSupplyUpdate) (uint64, error) {
	if mock.HandleEnygmaSupplyUpdatesFunc == nil {
		panic("EnygmaInitiatorMock.HandleEnygmaSupplyUpdatesFunc: method is nil but EnygmaInitiator.HandleEnygmaSupplyUpdates was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		BatchID     string
		ResourceId  string
		BlockNumber uint64
		Batch       types.EnygmaSupplyUpdate
	}{
		Ctx:         ctx,
		BatchID:     batchID,
		ResourceId:  resourceId,
		BlockNumber: blockNumber,
		Batch:       batch,
	}
	mock.lockHandleEnygmaSupplyUpdates.Lock()
	mock.calls.HandleEnygmaSupplyUpdates = append(mock.calls.HandleEnygmaSupplyUpdates, callInfo)
	mock.lockHandleEnygmaSupplyUpdates.Unlock()
	return mock.HandleEnygmaSupplyUpdatesFunc(ctx, batchID, resourceId, blockNumber, batch)
}

// HandleEnygmaSupplyUpdatesCalls gets all the calls that were made to HandleEnygmaSupplyUpdates.
// Check the length with:
//
//	len(mockedEnygmaInitiator.HandleEnygmaSupplyUpdatesCalls())
func (mock *EnygmaInitiatorMock) HandleEnygmaSupplyUpdatesCalls() []struct {
	Ctx         context.Context
	BatchID     string
	ResourceId  string
	BlockNumber uint64
	Batch       types.EnygmaSupplyUpdate
} {
	var calls []struct {
		Ctx         context.Context
		BatchID     string
		ResourceId  string
		BlockNumber uint64
		Batch       types.EnygmaSupplyUpdate
	}
	mock.lockHandleEnygmaSupplyUpdates.RLock()
	calls = mock.calls.HandleEnygmaSupplyUpdates
	mock.lockHandleEnygmaSupplyUpdates.RUnlock()
	return calls
}

// HandleEnygmaWithdrawal calls HandleEnygmaWithdrawalFunc.
func (mock *EnygmaInitiatorMock) HandleEnygmaWithdrawal(ctx context.Context, chainEventID string, blockNumber uint64, resourceID string, referenceID [32]byte, to common.Address, amount *big.Int, txHash common.Hash) (uint64, error) {
	if mock.HandleEnygmaWithdrawalFunc == nil {
		panic("EnygmaInitiatorMock.HandleEnygmaWithdrawalFunc: method is nil but EnygmaInitiator.HandleEnygmaWithdrawal was just called")
	}
	callInfo := struct {
		Ctx          context.Context
		ChainEventID string
		BlockNumber  uint64
		ResourceID   string
		ReferenceID  [32]byte
		To           common.Address
		Amount       *big.Int
		TxHash       common.Hash
	}{
		Ctx:          ctx,
		ChainEventID: chainEventID,
		BlockNumber:  blockNumber,
		ResourceID:   resourceID,
		ReferenceID:  referenceID,
		To:           to,
		Amount:       amount,
		TxHash:       txHash,
	}
	mock.lockHandleEnygmaWithdrawal.Lock()
	mock.calls.HandleEnygmaWithdrawal = append(mock.calls.HandleEnygmaWithdrawal, callInfo)
	mock.lockHandleEnygmaWithdrawal.Unlock()
	return mock.HandleEnygmaWithdrawalFunc(ctx, chainEventID, blockNumber, resourceID, referenceID, to, amount, txHash)
}

// HandleEnygmaWithdrawalCalls gets all the calls that were made to HandleEnygmaWithdrawal.
// Check the length with:
//
//	len(mockedEnygmaInitiator.HandleEnygmaWithdrawalCalls())
func (mock *EnygmaInitiatorMock) HandleEnygmaWithdrawalCalls() []struct {
	Ctx          context.Context
	ChainEventID string
	BlockNumber  uint64
	ResourceID   string
	ReferenceID  [32]byte
	To           common.Address
	Amount       *big.Int
	TxHash       common.Hash
} {
	var calls []struct {
		Ctx          context.Context
		ChainEventID string
		BlockNumber  uint64
		ResourceID   string
		ReferenceID  [32]byte
		To           common.Address
		Amount       *big.Int
		TxHash       common.Hash
	}
	mock.lockHandleEnygmaWithdrawal.RLock()
	calls = mock.calls.HandleEnygmaWithdrawal
	mock.lockHandleEnygmaWithdrawal.RUnlock()
	return calls
}

// Ensure, that EnygmaReverterMock does implement service.EnygmaReverter.
// If this is not the case, regenerate this file with moq.
var _ service.EnygmaReverter = &EnygmaReverterMock{}

// EnygmaReverterMock is a mock implementation of service.EnygmaReverter.
//
//	func TestSomethingThatUsesEnygmaReverter(t *testing.T) {
//
//		// make and configure a mocked service.EnygmaReverter
//		mockedEnygmaReverter := &EnygmaReverterMock{
//			RevertEnygmaDepositFunc: func(ctx context.Context, resourceId string, referenceId [32]byte, from common.Address, amount *big.Int) error {
//				panic("mock out the RevertEnygmaDeposit method")
//			},
//			RevertEnygmaSupplyUpdateFunc: func(ctx context.Context, resourceId string, supplyUpdateEvents []service.EnygmaSupplyUpdate) error {
//				panic("mock out the RevertEnygmaSupplyUpdate method")
//			},
//			RevertEnygmaTransferFunc: func(parentCtx context.Context, resourceId string, txsByChainID map[string][]*types.EnygmaTransferBatchTx) error {
//				panic("mock out the RevertEnygmaTransfer method")
//			},
//		}
//
//		// use mockedEnygmaReverter in code that requires service.EnygmaReverter
//		// and then make assertions.
//
//	}
type EnygmaReverterMock struct {
	// RevertEnygmaDepositFunc mocks the RevertEnygmaDeposit method.
	RevertEnygmaDepositFunc func(ctx context.Context, resourceId string, referenceId [32]byte, from common.Address, amount *big.Int) error

	// RevertEnygmaSupplyUpdateFunc mocks the RevertEnygmaSupplyUpdate method.
	RevertEnygmaSupplyUpdateFunc func(ctx context.Context, resourceId string, supplyUpdateEvents []service.EnygmaSupplyUpdate) error

	// RevertEnygmaTransferFunc mocks the RevertEnygmaTransfer method.
	RevertEnygmaTransferFunc func(parentCtx context.Context, resourceId string, txsByChainID map[string][]*types.EnygmaTransferBatchTx) error

	// calls tracks calls to the methods.
	calls struct {
		// RevertEnygmaDeposit holds details about calls to the RevertEnygmaDeposit method.
		RevertEnygmaDeposit []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ResourceId is the resourceId argument value.
			ResourceId string
			// ReferenceId is the referenceId argument value.
			ReferenceId [32]byte
			// From is the from argument value.
			From common.Address
			// Amount is the amount argument value.
			Amount *big.Int
		}
		// RevertEnygmaSupplyUpdate holds details about calls to the RevertEnygmaSupplyUpdate method.
		RevertEnygmaSupplyUpdate []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ResourceId is the resourceId argument value.
			ResourceId string
			// SupplyUpdateEvents is the supplyUpdateEvents argument value.
			SupplyUpdateEvents []service.EnygmaSupplyUpdate
		}
		// RevertEnygmaTransfer holds details about calls to the RevertEnygmaTransfer method.
		RevertEnygmaTransfer []struct {
			// ParentCtx is the parentCtx argument value.
			ParentCtx context.Context
			// ResourceId is the resourceId argument value.
			ResourceId string
			// TxsByChainID is the txsByChainID argument value.
			TxsByChainID map[string][]*types.EnygmaTransferBatchTx
		}
	}
	lockRevertEnygmaDeposit      sync.RWMutex
	lockRevertEnygmaSupplyUpdate sync.RWMutex
	lockRevertEnygmaTransfer     sync.RWMutex
}

// RevertEnygmaDeposit calls RevertEnygmaDepositFunc.
func (mock *EnygmaReverterMock) RevertEnygmaDeposit(ctx context.Context, resourceId string, referenceId [32]byte, from common.Address, amount *big.Int) error {
	if mock.RevertEnygmaDepositFunc == nil {
		panic("EnygmaReverterMock.RevertEnygmaDepositFunc: method is nil but EnygmaReverter.RevertEnygmaDeposit was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		ResourceId  string
		ReferenceId [32]byte
		From        common.Address
		Amount      *big.Int
	}{
		Ctx:         ctx,
		ResourceId:  resourceId,
		ReferenceId: referenceId,
		From:        from,
		Amount:      amount,
	}
	mock.lockRevertEnygmaDeposit.Lock()
	mock.calls.RevertEnygmaDeposit = append(mock.calls.RevertEnygmaDeposit, callInfo)
	mock.lockRevertEnygmaDeposit.Unlock()
	return mock.RevertEnygmaDepositFunc(ctx, resourceId, referenceId, from, amount)
}

// RevertEnygmaDepositCalls gets all the calls that were made to RevertEnygmaDeposit.
// Check the length with:
//
//	len(mockedEnygmaReverter.RevertEnygmaDepositCalls())
func (mock *EnygmaReverterMock) RevertEnygmaDepositCalls() []struct {
	Ctx         context.Context
	ResourceId  string
	ReferenceId [32]byte
	From        common.Address
	Amount      *big.Int
} {
	var calls []struct {
		Ctx         context.Context
		ResourceId  string
		ReferenceId [32]byte
		From        common.Address
		Amount      *big.Int
	}
	mock.lockRevertEnygmaDeposit.RLock()
	calls = mock.calls.RevertEnygmaDeposit
	mock.lockRevertEnygmaDeposit.RUnlock()
	return calls
}

// RevertEnygmaSupplyUpdate calls RevertEnygmaSupplyUpdateFunc.
func (mock *EnygmaReverterMock) RevertEnygmaSupplyUpdate(ctx context.Context, resourceId string, supplyUpdateEvents []service.EnygmaSupplyUpdate) error {
	if mock.RevertEnygmaSupplyUpdateFunc == nil {
		panic("EnygmaReverterMock.RevertEnygmaSupplyUpdateFunc: method is nil but EnygmaReverter.RevertEnygmaSupplyUpdate was just called")
	}
	callInfo := struct {
		Ctx                context.Context
		ResourceId         string
		SupplyUpdateEvents []service.EnygmaSupplyUpdate
	}{
		Ctx:                ctx,
		ResourceId:         resourceId,
		SupplyUpdateEvents: supplyUpdateEvents,
	}
	mock.lockRevertEnygmaSupplyUpdate.Lock()
	mock.calls.RevertEnygmaSupplyUpdate = append(mock.calls.RevertEnygmaSupplyUpdate, callInfo)
	mock.lockRevertEnygmaSupplyUpdate.Unlock()
	return mock.RevertEnygmaSupplyUpdateFunc(ctx, resourceId, supplyUpdateEvents)
}

// RevertEnygmaSupplyUpdateCalls gets all the calls that were made to RevertEnygmaSupplyUpdate.
// Check the length with:
//
//	len(mockedEnygmaReverter.RevertEnygmaSupplyUpdateCalls())
func (mock *EnygmaReverterMock) RevertEnygmaSupplyUpdateCalls() []struct {
	Ctx                context.Context
	ResourceId         string
	SupplyUpdateEvents []service.EnygmaSupplyUpdate
} {
	var calls []struct {
		Ctx                context.Context
		ResourceId         string
		SupplyUpdateEvents []service.EnygmaSupplyUpdate
	}
	mock.lockRevertEnygmaSupplyUpdate.RLock()
	calls = mock.calls.RevertEnygmaSupplyUpdate
	mock.lockRevertEnygmaSupplyUpdate.RUnlock()
	return calls
}

// RevertEnygmaTransfer calls RevertEnygmaTransferFunc.
func (mock *EnygmaReverterMock) RevertEnygmaTransfer(parentCtx context.Context, resourceId string, txsByChainID map[string][]*types.EnygmaTransferBatchTx) error {
	if mock.RevertEnygmaTransferFunc == nil {
		panic("EnygmaReverterMock.RevertEnygmaTransferFunc: method is nil but EnygmaReverter.RevertEnygmaTransfer was just called")
	}
	callInfo := struct {
		ParentCtx    context.Context
		ResourceId   string
		TxsByChainID map[string][]*types.EnygmaTransferBatchTx
	}{
		ParentCtx:    parentCtx,
		ResourceId:   resourceId,
		TxsByChainID: txsByChainID,
	}
	mock.lockRevertEnygmaTransfer.Lock()
	mock.calls.RevertEnygmaTransfer = append(mock.calls.RevertEnygmaTransfer, callInfo)
	mock.lockRevertEnygmaTransfer.Unlock()
	return mock.RevertEnygmaTransferFunc(parentCtx, resourceId, txsByChainID)
}

// RevertEnygmaTransferCalls gets all the calls that were made to RevertEnygmaTransfer.
// Check the length with:
//
//	len(mockedEnygmaReverter.RevertEnygmaTransferCalls())
func (mock *EnygmaReverterMock) RevertEnygmaTransferCalls() []struct {
	ParentCtx    context.Context
	ResourceId   string
	TxsByChainID map[string][]*types.EnygmaTransferBatchTx
} {
	var calls []struct {
		ParentCtx    context.Context
		ResourceId   string
		TxsByChainID map[string][]*types.EnygmaTransferBatchTx
	}
	mock.lockRevertEnygmaTransfer.RLock()
	calls = mock.calls.RevertEnygmaTransfer
	mock.lockRevertEnygmaTransfer.RUnlock()
	return calls
}

// Ensure, that EnygmaBlockWaiterServiceMock does implement service.EnygmaBlockWaiterService.
// If this is not the case, regenerate this file with moq.
var _ service.EnygmaBlockWaiterService = &EnygmaBlockWaiterServiceMock{}

// EnygmaBlockWaiterServiceMock is a mock implementation of service.EnygmaBlockWaiterService.
//
//	func TestSomethingThatUsesEnygmaBlockWaiterService(t *testing.T) {
//
//		// make and configure a mocked service.EnygmaBlockWaiterService
//		mockedEnygmaBlockWaiterService := &EnygmaBlockWaiterServiceMock{
//			WaitForBlockFunc: func(ctx context.Context, targetBlockNumber uint64) (uint64, error) {
//				panic("mock out the WaitForBlock method")
//			},
//		}
//
//		// use mockedEnygmaBlockWaiterService in code that requires service.EnygmaBlockWaiterService
//		// and then make assertions.
//
//	}
type EnygmaBlockWaiterServiceMock struct {
	// WaitForBlockFunc mocks the WaitForBlock method.
	WaitForBlockFunc func(ctx context.Context, targetBlockNumber uint64) (uint64, error)

	// calls tracks calls to the methods.
	calls struct {
		// WaitForBlock holds details about calls to the WaitForBlock method.
		WaitForBlock []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// TargetBlockNumber is the targetBlockNumber argument value.
			TargetBlockNumber uint64
		}
	}
	lockWaitForBlock sync.RWMutex
}

// WaitForBlock calls WaitForBlockFunc.
func (mock *EnygmaBlockWaiterServiceMock) WaitForBlock(ctx context.Context, targetBlockNumber uint64) (uint64, error) {
	if mock.WaitForBlockFunc == nil {
		panic("EnygmaBlockWaiterServiceMock.WaitForBlockFunc: method is nil but EnygmaBlockWaiterService.WaitForBlock was just called")
	}
	callInfo := struct {
		Ctx               context.Context
		TargetBlockNumber uint64
	}{
		Ctx:               ctx,
		TargetBlockNumber: targetBlockNumber,
	}
	mock.lockWaitForBlock.Lock()
	mock.calls.WaitForBlock = append(mock.calls.WaitForBlock, callInfo)
	mock.lockWaitForBlock.Unlock()
	return mock.WaitForBlockFunc(ctx, targetBlockNumber)
}

// WaitForBlockCalls gets all the calls that were made to WaitForBlock.
// Check the length with:
//
//	len(mockedEnygmaBlockWaiterService.WaitForBlockCalls())
func (mock *EnygmaBlockWaiterServiceMock) WaitForBlockCalls() []struct {
	Ctx               context.Context
	TargetBlockNumber uint64
} {
	var calls []struct {
		Ctx               context.Context
		TargetBlockNumber uint64
	}
	mock.lockWaitForBlock.RLock()
	calls = mock.calls.WaitForBlock
	mock.lockWaitForBlock.RUnlock()
	return calls
}

// Ensure, that EnygmaFinalizationServiceMock does implement service.EnygmaFinalizationService.
// If this is not the case, regenerate this file with moq.
var _ service.EnygmaFinalizationService = &EnygmaFinalizationServiceMock{}

// EnygmaFinalizationServiceMock is a mock implementation of service.EnygmaFinalizationService.
//
//	func TestSomethingThatUsesEnygmaFinalizationService(t *testing.T) {
//
//		// make and configure a mocked service.EnygmaFinalizationService
//		mockedEnygmaFinalizationService := &EnygmaFinalizationServiceMock{
//			ExecuteFinalizationFunc: func(ctx context.Context, id string, blockNumber uint64, resourceID string) error {
//				panic("mock out the ExecuteFinalization method")
//			},
//		}
//
//		// use mockedEnygmaFinalizationService in code that requires service.EnygmaFinalizationService
//		// and then make assertions.
//
//	}
type EnygmaFinalizationServiceMock struct {
	// ExecuteFinalizationFunc mocks the ExecuteFinalization method.
	ExecuteFinalizationFunc func(ctx context.Context, id string, blockNumber uint64, resourceID string) error

	// calls tracks calls to the methods.
	calls struct {
		// ExecuteFinalization holds details about calls to the ExecuteFinalization method.
		ExecuteFinalization []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID string
			// BlockNumber is the blockNumber argument value.
			BlockNumber uint64
			// ResourceID is the resourceID argument value.
			ResourceID string
		}
	}
	lockExecuteFinalization sync.RWMutex
}

// ExecuteFinalization calls ExecuteFinalizationFunc.
func (mock *EnygmaFinalizationServiceMock) ExecuteFinalization(ctx context.Context, id string, blockNumber uint64, resourceID string) error {
	if mock.ExecuteFinalizationFunc == nil {
		panic("EnygmaFinalizationServiceMock.ExecuteFinalizationFunc: method is nil but EnygmaFinalizationService.ExecuteFinalization was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		ID          string
		BlockNumber uint64
		ResourceID  string
	}{
		Ctx:         ctx,
		ID:          id,
		BlockNumber: blockNumber,
		ResourceID:  resourceID,
	}
	mock.lockExecuteFinalization.Lock()
	mock.calls.ExecuteFinalization = append(mock.calls.ExecuteFinalization, callInfo)
	mock.lockExecuteFinalization.Unlock()
	return mock.ExecuteFinalizationFunc(ctx, id, blockNumber, resourceID)
}

// ExecuteFinalizationCalls gets all the calls that were made to ExecuteFinalization.
// Check the length with:
//
//	len(mockedEnygmaFinalizationService.ExecuteFinalizationCalls())
func (mock *EnygmaFinalizationServiceMock) ExecuteFinalizationCalls() []struct {
	Ctx         context.Context
	ID          string
	BlockNumber uint64
	ResourceID  string
} {
	var calls []struct {
		Ctx         context.Context
		ID          string
		BlockNumber uint64
		ResourceID  string
	}
	mock.lockExecuteFinalization.RLock()
	calls = mock.calls.ExecuteFinalization
	mock.lockExecuteFinalization.RUnlock()
	return calls
}

// Ensure, that EnygmaBatcherMock does implement service.EnygmaBatcher.
// If this is not the case, regenerate this file with moq.
var _ service.EnygmaBatcher = &EnygmaBatcherMock{}

// EnygmaBatcherMock is a mock implementation of service.EnygmaBatcher.
//
//	func TestSomethingThatUsesEnygmaBatcher(t *testing.T) {
//
//		// make and configure a mocked service.EnygmaBatcher
//		mockedEnygmaBatcher := &EnygmaBatcherMock{
//			BatchTransfersFunc: func(ctx context.Context, txsByChainID map[string][]*types.EnygmaTransferBatchTx) ([]map[string][]*types.EnygmaTransferBatchTx, error) {
//				panic("mock out the BatchTransfers method")
//			},
//			GroupTransfersByChainIDFunc: func(events []service.EnygmaTransferTx) map[string][]*types.EnygmaTransferBatchTx {
//				panic("mock out the GroupTransfersByChainID method")
//			},
//		}
//
//		// use mockedEnygmaBatcher in code that requires service.EnygmaBatcher
//		// and then make assertions.
//
//	}
type EnygmaBatcherMock struct {
	// BatchTransfersFunc mocks the BatchTransfers method.
	BatchTransfersFunc func(ctx context.Context, txsByChainID map[string][]*types.EnygmaTransferBatchTx) ([]map[string][]*types.EnygmaTransferBatchTx, error)

	// GroupTransfersByChainIDFunc mocks the GroupTransfersByChainID method.
	GroupTransfersByChainIDFunc func(events []service.EnygmaTransferTx) map[string][]*types.EnygmaTransferBatchTx

	// calls tracks calls to the methods.
	calls struct {
		// BatchTransfers holds details about calls to the BatchTransfers method.
		BatchTransfers []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// TxsByChainID is the txsByChainID argument value.
			TxsByChainID map[string][]*types.EnygmaTransferBatchTx
		}
		// GroupTransfersByChainID holds details about calls to the GroupTransfersByChainID method.
		GroupTransfersByChainID []struct {
			// Events is the events argument value.
			Events []service.EnygmaTransferTx
		}
	}
	lockBatchTransfers          sync.RWMutex
	lockGroupTransfersByChainID sync.RWMutex
}

// BatchTransfers calls BatchTransfersFunc.
func (mock *EnygmaBatcherMock) BatchTransfers(ctx context.Context, txsByChainID map[string][]*types.EnygmaTransferBatchTx) ([]map[string][]*types.EnygmaTransferBatchTx, error) {
	if mock.BatchTransfersFunc == nil {
		panic("EnygmaBatcherMock.BatchTransfersFunc: method is nil but EnygmaBatcher.BatchTransfers was just called")
	}
	callInfo := struct {
		Ctx          context.Context
		TxsByChainID map[string][]*types.EnygmaTransferBatchTx
	}{
		Ctx:          ctx,
		TxsByChainID: txsByChainID,
	}
	mock.lockBatchTransfers.Lock()
	mock.calls.BatchTransfers = append(mock.calls.BatchTransfers, callInfo)
	mock.lockBatchTransfers.Unlock()
	return mock.BatchTransfersFunc(ctx, txsByChainID)
}

// BatchTransfersCalls gets all the calls that were made to BatchTransfers.
// Check the length with:
//
//	len(mockedEnygmaBatcher.BatchTransfersCalls())
func (mock *EnygmaBatcherMock) BatchTransfersCalls() []struct {
	Ctx          context.Context
	TxsByChainID map[string][]*types.EnygmaTransferBatchTx
} {
	var calls []struct {
		Ctx          context.Context
		TxsByChainID map[string][]*types.EnygmaTransferBatchTx
	}
	mock.lockBatchTransfers.RLock()
	calls = mock.calls.BatchTransfers
	mock.lockBatchTransfers.RUnlock()
	return calls
}

// GroupTransfersByChainID calls GroupTransfersByChainIDFunc.
func (mock *EnygmaBatcherMock) GroupTransfersByChainID(events []service.EnygmaTransferTx) map[string][]*types.EnygmaTransferBatchTx {
	if mock.GroupTransfersByChainIDFunc == nil {
		panic("EnygmaBatcherMock.GroupTransfersByChainIDFunc: method is nil but EnygmaBatcher.GroupTransfersByChainID was just called")
	}
	callInfo := struct {
		Events []service.EnygmaTransferTx
	}{
		Events: events,
	}
	mock.lockGroupTransfersByChainID.Lock()
	mock.calls.GroupTransfersByChainID = append(mock.calls.GroupTransfersByChainID, callInfo)
	mock.lockGroupTransfersByChainID.Unlock()
	return mock.GroupTransfersByChainIDFunc(events)
}

// GroupTransfersByChainIDCalls gets all the calls that were made to GroupTransfersByChainID.
// Check the length with:
//
//	len(mockedEnygmaBatcher.GroupTransfersByChainIDCalls())
func (mock *EnygmaBatcherMock) GroupTransfersByChainIDCalls() []struct {
	Events []service.EnygmaTransferTx
} {
	var calls []struct {
		Events []service.EnygmaTransferTx
	}
	mock.lockGroupTransfersByChainID.RLock()
	calls = mock.calls.GroupTransfersByChainID
	mock.lockGroupTransfersByChainID.RUnlock()
	return calls
}
