// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package handler_test

import (
	"context"
	"github.com/ethereum/go-ethereum/common"
	ethTypes "github.com/ethereum/go-ethereum/core/types"
	"github.com/raylsnetwork/rayls-privacy-relayer-api/contracts/PNTokenCoreV1"
	"github.com/raylsnetwork/rayls-privacy-relayer-api/contracts/PNTokenRegistryV1"
	"github.com/raylsnetwork/rayls-privacy-relayer-api/contracts/RNMessageDispatcherV1"
	"github.com/raylsnetwork/rayls-privacy-relayer-api/public-relayer/handler"
	"github.com/raylsnetwork/rayls-privacy-relayer-api/public-relayer/service"
	"sync"
)

// Ensure, that MessageDispatcherContractMock does implement handler.MessageDispatcherContract.
// If this is not the case, regenerate this file with moq.
var _ handler.MessageDispatcherContract = &MessageDispatcherContractMock{}

// MessageDispatcherContractMock is a mock implementation of handler.MessageDispatcherContract.
//
//	func TestSomethingThatUsesMessageDispatcherContract(t *testing.T) {
//
//		// make and configure a mocked handler.MessageDispatcherContract
//		mockedMessageDispatcherContract := &MessageDispatcherContractMock{
//			UnpackMessageDispatchedEventFunc: func(log *ethTypes.Log) (*RNMessageDispatcherV1.RNMessageDispatcherV1MessageDispatched, error) {
//				panic("mock out the UnpackMessageDispatchedEvent method")
//			},
//		}
//
//		// use mockedMessageDispatcherContract in code that requires handler.MessageDispatcherContract
//		// and then make assertions.
//
//	}
type MessageDispatcherContractMock struct {
	// UnpackMessageDispatchedEventFunc mocks the UnpackMessageDispatchedEvent method.
	UnpackMessageDispatchedEventFunc func(log *ethTypes.Log) (*RNMessageDispatcherV1.RNMessageDispatcherV1MessageDispatched, error)

	// calls tracks calls to the methods.
	calls struct {
		// UnpackMessageDispatchedEvent holds details about calls to the UnpackMessageDispatchedEvent method.
		UnpackMessageDispatchedEvent []struct {
			// Log is the log argument value.
			Log *ethTypes.Log
		}
	}
	lockUnpackMessageDispatchedEvent sync.RWMutex
}

// UnpackMessageDispatchedEvent calls UnpackMessageDispatchedEventFunc.
func (mock *MessageDispatcherContractMock) UnpackMessageDispatchedEvent(log *ethTypes.Log) (*RNMessageDispatcherV1.RNMessageDispatcherV1MessageDispatched, error) {
	if mock.UnpackMessageDispatchedEventFunc == nil {
		panic("MessageDispatcherContractMock.UnpackMessageDispatchedEventFunc: method is nil but MessageDispatcherContract.UnpackMessageDispatchedEvent was just called")
	}
	callInfo := struct {
		Log *ethTypes.Log
	}{
		Log: log,
	}
	mock.lockUnpackMessageDispatchedEvent.Lock()
	mock.calls.UnpackMessageDispatchedEvent = append(mock.calls.UnpackMessageDispatchedEvent, callInfo)
	mock.lockUnpackMessageDispatchedEvent.Unlock()
	return mock.UnpackMessageDispatchedEventFunc(log)
}

// UnpackMessageDispatchedEventCalls gets all the calls that were made to UnpackMessageDispatchedEvent.
// Check the length with:
//
//	len(mockedMessageDispatcherContract.UnpackMessageDispatchedEventCalls())
func (mock *MessageDispatcherContractMock) UnpackMessageDispatchedEventCalls() []struct {
	Log *ethTypes.Log
} {
	var calls []struct {
		Log *ethTypes.Log
	}
	mock.lockUnpackMessageDispatchedEvent.RLock()
	calls = mock.calls.UnpackMessageDispatchedEvent
	mock.lockUnpackMessageDispatchedEvent.RUnlock()
	return calls
}

// Ensure, that TokenCoreContractMock does implement handler.TokenCoreContract.
// If this is not the case, regenerate this file with moq.
var _ handler.TokenCoreContract = &TokenCoreContractMock{}

// TokenCoreContractMock is a mock implementation of handler.TokenCoreContract.
//
//	func TestSomethingThatUsesTokenCoreContract(t *testing.T) {
//
//		// make and configure a mocked handler.TokenCoreContract
//		mockedTokenCoreContract := &TokenCoreContractMock{
//			UnpackPublicChainStatusUpdatedEventFunc: func(log *ethTypes.Log) (*PNTokenCoreV1.PNTokenCoreV1PublicChainStatusUpdated, error) {
//				panic("mock out the UnpackPublicChainStatusUpdatedEvent method")
//			},
//		}
//
//		// use mockedTokenCoreContract in code that requires handler.TokenCoreContract
//		// and then make assertions.
//
//	}
type TokenCoreContractMock struct {
	// UnpackPublicChainStatusUpdatedEventFunc mocks the UnpackPublicChainStatusUpdatedEvent method.
	UnpackPublicChainStatusUpdatedEventFunc func(log *ethTypes.Log) (*PNTokenCoreV1.PNTokenCoreV1PublicChainStatusUpdated, error)

	// calls tracks calls to the methods.
	calls struct {
		// UnpackPublicChainStatusUpdatedEvent holds details about calls to the UnpackPublicChainStatusUpdatedEvent method.
		UnpackPublicChainStatusUpdatedEvent []struct {
			// Log is the log argument value.
			Log *ethTypes.Log
		}
	}
	lockUnpackPublicChainStatusUpdatedEvent sync.RWMutex
}

// UnpackPublicChainStatusUpdatedEvent calls UnpackPublicChainStatusUpdatedEventFunc.
func (mock *TokenCoreContractMock) UnpackPublicChainStatusUpdatedEvent(log *ethTypes.Log) (*PNTokenCoreV1.PNTokenCoreV1PublicChainStatusUpdated, error) {
	if mock.UnpackPublicChainStatusUpdatedEventFunc == nil {
		panic("TokenCoreContractMock.UnpackPublicChainStatusUpdatedEventFunc: method is nil but TokenCoreContract.UnpackPublicChainStatusUpdatedEvent was just called")
	}
	callInfo := struct {
		Log *ethTypes.Log
	}{
		Log: log,
	}
	mock.lockUnpackPublicChainStatusUpdatedEvent.Lock()
	mock.calls.UnpackPublicChainStatusUpdatedEvent = append(mock.calls.UnpackPublicChainStatusUpdatedEvent, callInfo)
	mock.lockUnpackPublicChainStatusUpdatedEvent.Unlock()
	return mock.UnpackPublicChainStatusUpdatedEventFunc(log)
}

// UnpackPublicChainStatusUpdatedEventCalls gets all the calls that were made to UnpackPublicChainStatusUpdatedEvent.
// Check the length with:
//
//	len(mockedTokenCoreContract.UnpackPublicChainStatusUpdatedEventCalls())
func (mock *TokenCoreContractMock) UnpackPublicChainStatusUpdatedEventCalls() []struct {
	Log *ethTypes.Log
} {
	var calls []struct {
		Log *ethTypes.Log
	}
	mock.lockUnpackPublicChainStatusUpdatedEvent.RLock()
	calls = mock.calls.UnpackPublicChainStatusUpdatedEvent
	mock.lockUnpackPublicChainStatusUpdatedEvent.RUnlock()
	return calls
}

// Ensure, that TokenRegistryReaderMock does implement handler.TokenRegistryReader.
// If this is not the case, regenerate this file with moq.
var _ handler.TokenRegistryReader = &TokenRegistryReaderMock{}

// TokenRegistryReaderMock is a mock implementation of handler.TokenRegistryReader.
//
//	func TestSomethingThatUsesTokenRegistryReader(t *testing.T) {
//
//		// make and configure a mocked handler.TokenRegistryReader
//		mockedTokenRegistryReader := &TokenRegistryReaderMock{
//			GetTokenByAddressFunc: func(ctx context.Context, tokenAddress common.Address) (PNTokenRegistryV1.TokenStructsToken, error) {
//				panic("mock out the GetTokenByAddress method")
//			},
//		}
//
//		// use mockedTokenRegistryReader in code that requires handler.TokenRegistryReader
//		// and then make assertions.
//
//	}
type TokenRegistryReaderMock struct {
	// GetTokenByAddressFunc mocks the GetTokenByAddress method.
	GetTokenByAddressFunc func(ctx context.Context, tokenAddress common.Address) (PNTokenRegistryV1.TokenStructsToken, error)

	// calls tracks calls to the methods.
	calls struct {
		// GetTokenByAddress holds details about calls to the GetTokenByAddress method.
		GetTokenByAddress []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// TokenAddress is the tokenAddress argument value.
			TokenAddress common.Address
		}
	}
	lockGetTokenByAddress sync.RWMutex
}

// GetTokenByAddress calls GetTokenByAddressFunc.
func (mock *TokenRegistryReaderMock) GetTokenByAddress(ctx context.Context, tokenAddress common.Address) (PNTokenRegistryV1.TokenStructsToken, error) {
	if mock.GetTokenByAddressFunc == nil {
		panic("TokenRegistryReaderMock.GetTokenByAddressFunc: method is nil but TokenRegistryReader.GetTokenByAddress was just called")
	}
	callInfo := struct {
		Ctx          context.Context
		TokenAddress common.Address
	}{
		Ctx:          ctx,
		TokenAddress: tokenAddress,
	}
	mock.lockGetTokenByAddress.Lock()
	mock.calls.GetTokenByAddress = append(mock.calls.GetTokenByAddress, callInfo)
	mock.lockGetTokenByAddress.Unlock()
	return mock.GetTokenByAddressFunc(ctx, tokenAddress)
}

// GetTokenByAddressCalls gets all the calls that were made to GetTokenByAddress.
// Check the length with:
//
//	len(mockedTokenRegistryReader.GetTokenByAddressCalls())
func (mock *TokenRegistryReaderMock) GetTokenByAddressCalls() []struct {
	Ctx          context.Context
	TokenAddress common.Address
} {
	var calls []struct {
		Ctx          context.Context
		TokenAddress common.Address
	}
	mock.lockGetTokenByAddress.RLock()
	calls = mock.calls.GetTokenByAddress
	mock.lockGetTokenByAddress.RUnlock()
	return calls
}

// Ensure, that MessagePublisherMock does implement handler.MessagePublisher.
// If this is not the case, regenerate this file with moq.
var _ handler.MessagePublisher = &MessagePublisherMock{}

// MessagePublisherMock is a mock implementation of handler.MessagePublisher.
//
//	func TestSomethingThatUsesMessagePublisher(t *testing.T) {
//
//		// make and configure a mocked handler.MessagePublisher
//		mockedMessagePublisher := &MessagePublisherMock{
//			PushFunc: func(contextMoqParam context.Context, message service.Message) error {
//				panic("mock out the Push method")
//			},
//		}
//
//		// use mockedMessagePublisher in code that requires handler.MessagePublisher
//		// and then make assertions.
//
//	}
type MessagePublisherMock struct {
	// PushFunc mocks the Push method.
	PushFunc func(contextMoqParam context.Context, message service.Message) error

	// calls tracks calls to the methods.
	calls struct {
		// Push holds details about calls to the Push method.
		Push []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// Message is the message argument value.
			Message service.Message
		}
	}
	lockPush sync.RWMutex
}

// Push calls PushFunc.
func (mock *MessagePublisherMock) Push(contextMoqParam context.Context, message service.Message) error {
	if mock.PushFunc == nil {
		panic("MessagePublisherMock.PushFunc: method is nil but MessagePublisher.Push was just called")
	}
	callInfo := struct {
		ContextMoqParam context.Context
		Message         service.Message
	}{
		ContextMoqParam: contextMoqParam,
		Message:         message,
	}
	mock.lockPush.Lock()
	mock.calls.Push = append(mock.calls.Push, callInfo)
	mock.lockPush.Unlock()
	return mock.PushFunc(contextMoqParam, message)
}

// PushCalls gets all the calls that were made to Push.
// Check the length with:
//
//	len(mockedMessagePublisher.PushCalls())
func (mock *MessagePublisherMock) PushCalls() []struct {
	ContextMoqParam context.Context
	Message         service.Message
} {
	var calls []struct {
		ContextMoqParam context.Context
		Message         service.Message
	}
	mock.lockPush.RLock()
	calls = mock.calls.Push
	mock.lockPush.RUnlock()
	return calls
}

// Ensure, that DeploymentPublisherMock does implement handler.DeploymentPublisher.
// If this is not the case, regenerate this file with moq.
var _ handler.DeploymentPublisher = &DeploymentPublisherMock{}

// DeploymentPublisherMock is a mock implementation of handler.DeploymentPublisher.
//
//	func TestSomethingThatUsesDeploymentPublisher(t *testing.T) {
//
//		// make and configure a mocked handler.DeploymentPublisher
//		mockedDeploymentPublisher := &DeploymentPublisherMock{
//			PushFunc: func(contextMoqParam context.Context, deployment service.Deployment) error {
//				panic("mock out the Push method")
//			},
//		}
//
//		// use mockedDeploymentPublisher in code that requires handler.DeploymentPublisher
//		// and then make assertions.
//
//	}
type DeploymentPublisherMock struct {
	// PushFunc mocks the Push method.
	PushFunc func(contextMoqParam context.Context, deployment service.Deployment) error

	// calls tracks calls to the methods.
	calls struct {
		// Push holds details about calls to the Push method.
		Push []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// Deployment is the deployment argument value.
			Deployment service.Deployment
		}
	}
	lockPush sync.RWMutex
}

// Push calls PushFunc.
func (mock *DeploymentPublisherMock) Push(contextMoqParam context.Context, deployment service.Deployment) error {
	if mock.PushFunc == nil {
		panic("DeploymentPublisherMock.PushFunc: method is nil but DeploymentPublisher.Push was just called")
	}
	callInfo := struct {
		ContextMoqParam context.Context
		Deployment      service.Deployment
	}{
		ContextMoqParam: contextMoqParam,
		Deployment:      deployment,
	}
	mock.lockPush.Lock()
	mock.calls.Push = append(mock.calls.Push, callInfo)
	mock.lockPush.Unlock()
	return mock.PushFunc(contextMoqParam, deployment)
}

// PushCalls gets all the calls that were made to Push.
// Check the length with:
//
//	len(mockedDeploymentPublisher.PushCalls())
func (mock *DeploymentPublisherMock) PushCalls() []struct {
	ContextMoqParam context.Context
	Deployment      service.Deployment
} {
	var calls []struct {
		ContextMoqParam context.Context
		Deployment      service.Deployment
	}
	mock.lockPush.RLock()
	calls = mock.calls.Push
	mock.lockPush.RUnlock()
	return calls
}
