// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package proof_test

import (
	"context"
	ethTypes "github.com/ethereum/go-ethereum/core/types"
	"github.com/raylsnetwork/rayls-sovereign-relayer/contractclient"
	"github.com/raylsnetwork/rayls-sovereign-relayer/contracts/Proofs"
	"github.com/raylsnetwork/rayls-sovereign-relayer/private-relayer/proof"
	"math/big"
	"sync"
)

// Ensure, that HeaderBlockchainClientMock does implement proof.HeaderBlockchainClient.
// If this is not the case, regenerate this file with moq.
var _ proof.HeaderBlockchainClient = &HeaderBlockchainClientMock{}

// HeaderBlockchainClientMock is a mock implementation of proof.HeaderBlockchainClient.
//
//	func TestSomethingThatUsesHeaderBlockchainClient(t *testing.T) {
//
//		// make and configure a mocked proof.HeaderBlockchainClient
//		mockedHeaderBlockchainClient := &HeaderBlockchainClientMock{
//			BlockNumberFunc: func(ctx context.Context) (uint64, error) {
//				panic("mock out the BlockNumber method")
//			},
//			HeaderByNumberFunc: func(ctx context.Context, number *big.Int) (*ethTypes.Header, error) {
//				panic("mock out the HeaderByNumber method")
//			},
//		}
//
//		// use mockedHeaderBlockchainClient in code that requires proof.HeaderBlockchainClient
//		// and then make assertions.
//
//	}
type HeaderBlockchainClientMock struct {
	// BlockNumberFunc mocks the BlockNumber method.
	BlockNumberFunc func(ctx context.Context) (uint64, error)

	// HeaderByNumberFunc mocks the HeaderByNumber method.
	HeaderByNumberFunc func(ctx context.Context, number *big.Int) (*ethTypes.Header, error)

	// calls tracks calls to the methods.
	calls struct {
		// BlockNumber holds details about calls to the BlockNumber method.
		BlockNumber []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// HeaderByNumber holds details about calls to the HeaderByNumber method.
		HeaderByNumber []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Number is the number argument value.
			Number *big.Int
		}
	}
	lockBlockNumber    sync.RWMutex
	lockHeaderByNumber sync.RWMutex
}

// BlockNumber calls BlockNumberFunc.
func (mock *HeaderBlockchainClientMock) BlockNumber(ctx context.Context) (uint64, error) {
	if mock.BlockNumberFunc == nil {
		panic("HeaderBlockchainClientMock.BlockNumberFunc: method is nil but HeaderBlockchainClient.BlockNumber was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockBlockNumber.Lock()
	mock.calls.BlockNumber = append(mock.calls.BlockNumber, callInfo)
	mock.lockBlockNumber.Unlock()
	return mock.BlockNumberFunc(ctx)
}

// BlockNumberCalls gets all the calls that were made to BlockNumber.
// Check the length with:
//
//	len(mockedHeaderBlockchainClient.BlockNumberCalls())
func (mock *HeaderBlockchainClientMock) BlockNumberCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockBlockNumber.RLock()
	calls = mock.calls.BlockNumber
	mock.lockBlockNumber.RUnlock()
	return calls
}

// HeaderByNumber calls HeaderByNumberFunc.
func (mock *HeaderBlockchainClientMock) HeaderByNumber(ctx context.Context, number *big.Int) (*ethTypes.Header, error) {
	if mock.HeaderByNumberFunc == nil {
		panic("HeaderBlockchainClientMock.HeaderByNumberFunc: method is nil but HeaderBlockchainClient.HeaderByNumber was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Number *big.Int
	}{
		Ctx:    ctx,
		Number: number,
	}
	mock.lockHeaderByNumber.Lock()
	mock.calls.HeaderByNumber = append(mock.calls.HeaderByNumber, callInfo)
	mock.lockHeaderByNumber.Unlock()
	return mock.HeaderByNumberFunc(ctx, number)
}

// HeaderByNumberCalls gets all the calls that were made to HeaderByNumber.
// Check the length with:
//
//	len(mockedHeaderBlockchainClient.HeaderByNumberCalls())
func (mock *HeaderBlockchainClientMock) HeaderByNumberCalls() []struct {
	Ctx    context.Context
	Number *big.Int
} {
	var calls []struct {
		Ctx    context.Context
		Number *big.Int
	}
	mock.lockHeaderByNumber.RLock()
	calls = mock.calls.HeaderByNumber
	mock.lockHeaderByNumber.RUnlock()
	return calls
}

// Ensure, that HeaderProofsSubmitterMock does implement proof.HeaderProofsSubmitter.
// If this is not the case, regenerate this file with moq.
var _ proof.HeaderProofsSubmitter = &HeaderProofsSubmitterMock{}

// HeaderProofsSubmitterMock is a mock implementation of proof.HeaderProofsSubmitter.
//
//	func TestSomethingThatUsesHeaderProofsSubmitter(t *testing.T) {
//
//		// make and configure a mocked proof.HeaderProofsSubmitter
//		mockedHeaderProofsSubmitter := &HeaderProofsSubmitterMock{
//			GetNextBlockNumberFunc: func(ctx context.Context, chainID *big.Int) (*big.Int, error) {
//				panic("mock out the GetNextBlockNumber method")
//			},
//			SubmitBatchHeadersFunc: func(ctx context.Context, chainID *big.Int, headers []Proofs.ProofsHeader) (*contractclient.SubmitResult, error) {
//				panic("mock out the SubmitBatchHeaders method")
//			},
//		}
//
//		// use mockedHeaderProofsSubmitter in code that requires proof.HeaderProofsSubmitter
//		// and then make assertions.
//
//	}
type HeaderProofsSubmitterMock struct {
	// GetNextBlockNumberFunc mocks the GetNextBlockNumber method.
	GetNextBlockNumberFunc func(ctx context.Context, chainID *big.Int) (*big.Int, error)

	// SubmitBatchHeadersFunc mocks the SubmitBatchHeaders method.
	SubmitBatchHeadersFunc func(ctx context.Context, chainID *big.Int, headers []Proofs.ProofsHeader) (*contractclient.SubmitResult, error)

	// calls tracks calls to the methods.
	calls struct {
		// GetNextBlockNumber holds details about calls to the GetNextBlockNumber method.
		GetNextBlockNumber []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ChainID is the chainID argument value.
			ChainID *big.Int
		}
		// SubmitBatchHeaders holds details about calls to the SubmitBatchHeaders method.
		SubmitBatchHeaders []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ChainID is the chainID argument value.
			ChainID *big.Int
			// Headers is the headers argument value.
			Headers []Proofs.ProofsHeader
		}
	}
	lockGetNextBlockNumber sync.RWMutex
	lockSubmitBatchHeaders sync.RWMutex
}

// GetNextBlockNumber calls GetNextBlockNumberFunc.
func (mock *HeaderProofsSubmitterMock) GetNextBlockNumber(ctx context.Context, chainID *big.Int) (*big.Int, error) {
	if mock.GetNextBlockNumberFunc == nil {
		panic("HeaderProofsSubmitterMock.GetNextBlockNumberFunc: method is nil but HeaderProofsSubmitter.GetNextBlockNumber was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		ChainID *big.Int
	}{
		Ctx:     ctx,
		ChainID: chainID,
	}
	mock.lockGetNextBlockNumber.Lock()
	mock.calls.GetNextBlockNumber = append(mock.calls.GetNextBlockNumber, callInfo)
	mock.lockGetNextBlockNumber.Unlock()
	return mock.GetNextBlockNumberFunc(ctx, chainID)
}

// GetNextBlockNumberCalls gets all the calls that were made to GetNextBlockNumber.
// Check the length with:
//
//	len(mockedHeaderProofsSubmitter.GetNextBlockNumberCalls())
func (mock *HeaderProofsSubmitterMock) GetNextBlockNumberCalls() []struct {
	Ctx     context.Context
	ChainID *big.Int
} {
	var calls []struct {
		Ctx     context.Context
		ChainID *big.Int
	}
	mock.lockGetNextBlockNumber.RLock()
	calls = mock.calls.GetNextBlockNumber
	mock.lockGetNextBlockNumber.RUnlock()
	return calls
}

// SubmitBatchHeaders calls SubmitBatchHeadersFunc.
func (mock *HeaderProofsSubmitterMock) SubmitBatchHeaders(ctx context.Context, chainID *big.Int, headers []Proofs.ProofsHeader) (*contractclient.SubmitResult, error) {
	if mock.SubmitBatchHeadersFunc == nil {
		panic("HeaderProofsSubmitterMock.SubmitBatchHeadersFunc: method is nil but HeaderProofsSubmitter.SubmitBatchHeaders was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		ChainID *big.Int
		Headers []Proofs.ProofsHeader
	}{
		Ctx:     ctx,
		ChainID: chainID,
		Headers: headers,
	}
	mock.lockSubmitBatchHeaders.Lock()
	mock.calls.SubmitBatchHeaders = append(mock.calls.SubmitBatchHeaders, callInfo)
	mock.lockSubmitBatchHeaders.Unlock()
	return mock.SubmitBatchHeadersFunc(ctx, chainID, headers)
}

// SubmitBatchHeadersCalls gets all the calls that were made to SubmitBatchHeaders.
// Check the length with:
//
//	len(mockedHeaderProofsSubmitter.SubmitBatchHeadersCalls())
func (mock *HeaderProofsSubmitterMock) SubmitBatchHeadersCalls() []struct {
	Ctx     context.Context
	ChainID *big.Int
	Headers []Proofs.ProofsHeader
} {
	var calls []struct {
		Ctx     context.Context
		ChainID *big.Int
		Headers []Proofs.ProofsHeader
	}
	mock.lockSubmitBatchHeaders.RLock()
	calls = mock.calls.SubmitBatchHeaders
	mock.lockSubmitBatchHeaders.RUnlock()
	return calls
}
