name: "PR Title Check"
on:
  pull_request_target:
    types:
      - assigned
      - unassigned
      - labeled
      - unlabeled
      - opened
      - reopened
      - edited
      - converted_to_draft
      - ready_for_review
      - review_requested
      - review_request_removed
      - locked
      - unlocked
      - synchronize

defaults:
  run:
    shell: bash

permissions:
  statuses: write
  pull-requests: read
  contents: read

jobs:
  title-check:
    name: Title Check
    runs-on: ubuntu-latest
    steps:
      - name: Check PR Title
        uses: amannn/action-semantic-pull-request@48f256284bd46cdaab1048c3721360e808335d50 # v6.1.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
