// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package healthcheck_test

import (
	"context"
	"github.com/raylsnetwork/rayls-sovereign-relayer/private-relayer/healthcheck"
	"sync"
)

// Ensure, that DatabaseClientMock does implement healthcheck.DatabaseClient.
// If this is not the case, regenerate this file with moq.
var _ healthcheck.DatabaseClient = &DatabaseClientMock{}

// DatabaseClientMock is a mock implementation of healthcheck.DatabaseClient.
//
//	func TestSomethingThatUsesDatabaseClient(t *testing.T) {
//
//		// make and configure a mocked healthcheck.DatabaseClient
//		mockedDatabaseClient := &DatabaseClientMock{
//			PingFunc: func(ctx context.Context) error {
//				panic("mock out the Ping method")
//			},
//		}
//
//		// use mockedDatabaseClient in code that requires healthcheck.DatabaseClient
//		// and then make assertions.
//
//	}
type DatabaseClientMock struct {
	// PingFunc mocks the Ping method.
	PingFunc func(ctx context.Context) error

	// calls tracks calls to the methods.
	calls struct {
		// Ping holds details about calls to the Ping method.
		Ping []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
	}
	lockPing sync.RWMutex
}

// Ping calls PingFunc.
func (mock *DatabaseClientMock) Ping(ctx context.Context) error {
	if mock.PingFunc == nil {
		panic("DatabaseClientMock.PingFunc: method is nil but DatabaseClient.Ping was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockPing.Lock()
	mock.calls.Ping = append(mock.calls.Ping, callInfo)
	mock.lockPing.Unlock()
	return mock.PingFunc(ctx)
}

// PingCalls gets all the calls that were made to Ping.
// Check the length with:
//
//	len(mockedDatabaseClient.PingCalls())
func (mock *DatabaseClientMock) PingCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockPing.RLock()
	calls = mock.calls.Ping
	mock.lockPing.RUnlock()
	return calls
}

// Ensure, that EthereumClientMock does implement healthcheck.EthereumClient.
// If this is not the case, regenerate this file with moq.
var _ healthcheck.EthereumClient = &EthereumClientMock{}

// EthereumClientMock is a mock implementation of healthcheck.EthereumClient.
//
//	func TestSomethingThatUsesEthereumClient(t *testing.T) {
//
//		// make and configure a mocked healthcheck.EthereumClient
//		mockedEthereumClient := &EthereumClientMock{
//			BlockNumberFunc: func(ctx context.Context) (uint64, error) {
//				panic("mock out the BlockNumber method")
//			},
//		}
//
//		// use mockedEthereumClient in code that requires healthcheck.EthereumClient
//		// and then make assertions.
//
//	}
type EthereumClientMock struct {
	// BlockNumberFunc mocks the BlockNumber method.
	BlockNumberFunc func(ctx context.Context) (uint64, error)

	// calls tracks calls to the methods.
	calls struct {
		// BlockNumber holds details about calls to the BlockNumber method.
		BlockNumber []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
	}
	lockBlockNumber sync.RWMutex
}

// BlockNumber calls BlockNumberFunc.
func (mock *EthereumClientMock) BlockNumber(ctx context.Context) (uint64, error) {
	if mock.BlockNumberFunc == nil {
		panic("EthereumClientMock.BlockNumberFunc: method is nil but EthereumClient.BlockNumber was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockBlockNumber.Lock()
	mock.calls.BlockNumber = append(mock.calls.BlockNumber, callInfo)
	mock.lockBlockNumber.Unlock()
	return mock.BlockNumberFunc(ctx)
}

// BlockNumberCalls gets all the calls that were made to BlockNumber.
// Check the length with:
//
//	len(mockedEthereumClient.BlockNumberCalls())
func (mock *EthereumClientMock) BlockNumberCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockBlockNumber.RLock()
	calls = mock.calls.BlockNumber
	mock.lockBlockNumber.RUnlock()
	return calls
}

// Ensure, that NATSClientMock does implement healthcheck.NATSClient.
// If this is not the case, regenerate this file with moq.
var _ healthcheck.NATSClient = &NATSClientMock{}

// NATSClientMock is a mock implementation of healthcheck.NATSClient.
//
//	func TestSomethingThatUsesNATSClient(t *testing.T) {
//
//		// make and configure a mocked healthcheck.NATSClient
//		mockedNATSClient := &NATSClientMock{
//			IsConnectedFunc: func() bool {
//				panic("mock out the IsConnected method")
//			},
//		}
//
//		// use mockedNATSClient in code that requires healthcheck.NATSClient
//		// and then make assertions.
//
//	}
type NATSClientMock struct {
	// IsConnectedFunc mocks the IsConnected method.
	IsConnectedFunc func() bool

	// calls tracks calls to the methods.
	calls struct {
		// IsConnected holds details about calls to the IsConnected method.
		IsConnected []struct {
		}
	}
	lockIsConnected sync.RWMutex
}

// IsConnected calls IsConnectedFunc.
func (mock *NATSClientMock) IsConnected() bool {
	if mock.IsConnectedFunc == nil {
		panic("NATSClientMock.IsConnectedFunc: method is nil but NATSClient.IsConnected was just called")
	}
	callInfo := struct {
	}{}
	mock.lockIsConnected.Lock()
	mock.calls.IsConnected = append(mock.calls.IsConnected, callInfo)
	mock.lockIsConnected.Unlock()
	return mock.IsConnectedFunc()
}

// IsConnectedCalls gets all the calls that were made to IsConnected.
// Check the length with:
//
//	len(mockedNATSClient.IsConnectedCalls())
func (mock *NATSClientMock) IsConnectedCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockIsConnected.RLock()
	calls = mock.calls.IsConnected
	mock.lockIsConnected.RUnlock()
	return calls
}
